### ISSUE TITLE
终于等到更新了，小黄鸟正版用户路过，大佬内测能否拉我一下？

### ISSUE THREAD

**Issue by user1121114685** [reqable/reqable-app#1]
很巧合，我也会flutter也用小黄鸟，大佬我邮件admin@shaoxia.xyz

**Comment by MegatronKing** [comment]
收到，感谢关注和支持！内测开始前我联系你🚀。

**Comment by nicolas-raoul** [comment]
I am also an Android developer, I would be happy to test the app if you need testers. 🙂

**Comment by MegatronKing** [comment]
> I am also an Android developer, I would be happy to test the app if you need testers. 🙂

Thanks, glad to here this.

**Comment by MrHanBaBa** [comment]
同希望内测，thor，网球，螃蟹，小黄鸟，fiddler everywhere都用过，想尝试一下reqable

**Comment by MegatronKing** [comment]
麻烦各位大佬填下这个单子：https://wj.qq.com/s2/11766634/74dd

**Comment by user1121114685** [comment]
填了大佬

**Comment by user1121114685** [comment]
大佬，我还没收到内测，现在发布了吗？

**Comment by MegatronKing** [comment]
> 大佬，我还没收到内测，现在发布了吗？

linux的没发，早期填了问卷的应该都发了，看下邮箱

**Comment by user1121114685** [comment]
大佬，邮箱里面没有收到，能再发一份吗？admin@shaoxia.xyz
