### ISSUE TITLE
[feature] 请求响应体显示格式问题

### ISSUE THREAD

**Issue by q954987161** [reqable/reqable-app#1003]
第一个链接选择格式为raw，能不能之后点的链接显示的格式都是raw啊，记忆一下。有时候不需要格式化的内容就需要都点一遍有点麻烦

**Comment by MegatronKing** [comment]
@q954987161 您好，感谢反馈。设计上是会记忆的，请更新到最新版本。如果还有问题，请提供下你那边的问题复现步骤。

**Comment by q954987161** [comment]
> @q954987161 您好，感谢反馈。设计上是会记忆的，请更新到最新版本。如果还有问题，请提供下你那边的问题复现步骤。


Uploading Video_2024-10-25_002118.mp4…

**Comment by q954987161** [comment]
> @q954987161 您好，感谢反馈。设计上是会记忆的，请更新到最新版本。如果还有问题，请提供下你那边的问题复现步骤。


https://github.com/user-attachments/assets/04e5ff41-7e98-41dd-8ec4-7d4706474188

**Comment by q954987161** [comment]
> @q954987161 您好，感谢反馈。设计上是会记忆的，请更新到最新版本。如果还有问题，请提供下你那边的问题复现步骤。


https://github.com/user-attachments/assets/04e5ff41-7e98-41dd-8ec4-7d4706474188

**Comment by q954987161** [comment]
https://github.com/user-attachments/assets/fc38b9ff-d146-4e4a-891c-6dec39876946

**Comment by MegatronKing** [comment]
啊抱歉，我的错，理解错issue了，确实有这个问题。

**Comment by MegatronKing** [comment]
请更新2.27.2版本，已优化。
