### ISSUE TITLE
[bug] 暂停抓包后websocket仍然在传输数据

### ISSUE THREAD

**Issue by xvhuan** [reqable/reqable-app#1009]
![recording](https://github.com/user-attachments/assets/5010e56a-2534-4f0c-9541-5c9f3cd63bd5)
暂停抓包后websocket仍然在传输数据
我不知道这是不是bug，还是说websocket的传输不能手动停止截取。

**Comment by MegatronKing** [comment]
您好，感谢反馈。停止抓包，不代表会中断请求，websocket仍然在传输数据是正常的。目前还没有提供中断connection的功能。
