### ISSUE TITLE
Clash和Reqable如何共存？如何设置二级代理

### ISSUE THREAD

**Issue by MarkLily** [reqable/reqable-app#1013]
目前的做法是，先关闭clash的系统代理，然后打开reqbale，才可以用；
如果设置二级代理，我要一一添加？有些麻烦，因为我的clash设置的是System Proxy 开启，TUN Mode关闭。
求大佬们，如何设置二级代理？

**Comment by MegatronKing** [comment]
crash的本地HTTP端口不是固定的吗，为什么要一一添加？

**Comment by MarkLily** [comment]
> crash的本地HTTP端口不是固定的吗，为什么要一一添加？

一一添加的是允许的域名，那个clash端口是固定的；允许模式和绕行模式 里面是不是就默认值*，会不会国内的流量都绕出去再回来？我想的是懒人法，优先国内的能打开就打开，打不开再借，不想浪费流量！感谢大佬回答

**Comment by MarkLily** [comment]
目前的做法，clash不变，打开reqable，设置二级代理，IP+端口后，在允许模式里面，分别一一添加外网网站即可共存。
是不是还有更好的方法？

**Comment by MarkLily** [comment]
> 那这个没办法。。。

感谢大佬的回答！
