### ISSUE TITLE
[bug] 重写功能，重定向与修改请求无法同时生效

### ISSUE THREAD

**Issue by zsh2517** [reqable/reqable-app#1014]
## 问题描述&复现步骤

添加重写规则

1. 修改请求：对于 `https://example.com/*` 新增参数 `a=b`
2. 重定向：`https://example.com/*` => `https://httpbin.org/*`
3. 修改请求：`https://httpbin.org/*` 新增参数 `c=d`

然后向 `https://example.com/anything` 发起 GET 请求

## 预期情况

根据文档“规则从上往下进行匹配，同一个请求可以匹配多个规则，越靠前越先执行。”，三条规则应该分别会将请求修改成

- `https://example.com/anything?a=b`
- `https://httpbin.org/anything?a=b`
- `https://httpbin.org/anything?a=b&c=d`

最终观测到的应该是

```json
"args": {
"a": "b",
"c": "d"
},
```

## 实际情况

```json
"args": {},
```

## 补充

1. 当直接请求 `https://httpbin.org/anything` 时，第三条规则是正常执行的，得到了 `c: d`
2. 请求 `https://example.com/anything?id=1` 时，参数保持不变，args 是  `id: 1`

## 信息

Mac m2, 14.5 (23F79)
Reqable: 2.27.2 (119)

**Comment by zsh2517** [comment]
我试了一下脚本功能，结果发现脚本似乎不支持 URL 重定向（CaptureHttpRequest 中没有 host 信息，且 protocol 只读）。最后用 [mitmproxy](https://mitmproxy.org/) 解决的

**Comment by MegatronKing** [comment]
@zsh2517 感谢反馈，问题能够复现。文档有点旧了，描述不太对，优先级是重定向 > 替换 > 修改，同一个请求最多只能有一个重定向规则生效，其他同类型规则下前面的优先级高。

**Comment by MegatronKing** [comment]
按照操作步骤，应该是2和3生效，实际上3没有生效，这个是bug，我们会在下个版本修复。

**Comment by zsh2517** [comment]
> @zsh2517 感谢反馈，问题能够复现。文档有点旧了，描述不太对，优先级是重定向 > 替换 > 修改，同一个请求最多只能有一个重定向规则生效，其他同类型规则下前面的优先级高。

有一个问题我一直想提，但是不确定是否算是个大众需求，而且同类产品好像也没有。

因为这类产品都提供了一系列功能，比如网关、重定向、脚本等修改请求、响应的能力，而且每个里面不止一条，整个流程串下来是有点黑盒的感觉。
希望能针对发起请求或者调试中的任意一条请求，提供一个完整的过程追踪。（从收到原始请求，经过了哪些阶段，每个阶段哪些规则生效了，生效前后是什么，有哪些变化）
我目前同时在用 proxyman 和 mitmproxy，比如拿重定向或者类似的功能来说，没记错的话，proxyman、mitmproxy 会在请求列表里面展示修改后的请求地址，而 reqable 会展示之前的。最理想的情况应该是能记录下来完整过程，或者可选原始请求/最终请求

上周有个关于正则的 feature request 也是我提的（#1004），想法来源是类似的——正则是一个公认的、完善的标准，即使 reqable 不提供相关调试，通过各种工具比如 regex101 可以调试、通过 GPT 可以辅助生成。
但是通配符就比较黑盒，比如有多个通配符会发生什么、替换后替换成了什么、能不能用到参数、路径（如 `https://exam*le.com` `https://example.com/path/aa*b/`）里面、get 参数的 ? 是否会按预期生效等等，除了文档里面特别明确的那个规则（/*）之外，其他每次使用都要测试一下

**Comment by zsh2517** [comment]
> @zsh2517 感谢反馈，问题能够复现。文档有点旧了，描述不太对，优先级是重定向 > 替换 > 修改，同一个请求最多只能有一个重定向规则生效，其他同类型规则下前面的优先级高。

另外文档建议找个地方补充一下，完整的优先级关系。以及“同一个请求最多只能有一个重定向规则生效”等类似的这种细节

--

另外，文档中 脚本、脚本 API 两节，尾部链接挂了（https://reqable.com/blog/2023/06/12/post）

**Comment by MegatronKing** [comment]
> 希望能针对发起请求或者调试中的任意一条请求，提供一个完整的过程追踪。（从收到原始请求，经过了哪些阶段，每个阶段哪些规则生效了，生效前后是什么，有哪些变化）

挺好的建议，你新建个issue吧

**Comment by luckywang1107** [comment]
我在验证重写功能时遇到了问题。

我需要本地进行调试，即将测试环境的所有请求转发到本地，除了请求 URL 替换，请求头、请求体等参数需要都带过来
1. 重定向 https://example.com/* => http://localhost:8080/*
2. 删除请求头中的 referer 参数

结果：
1. 抓包列表只看到了一条 CONNECT 的请求（未看到处理过之后的重定向请求）
2. 本地服务未收到转发过来的请求（偶现，有次本地服务收到了请求，但是请求头中的 referer 参数未删除）

Windows 10、Mac M1pro 均有该问题

**Comment by zsh2517** [comment]
感觉和我的情况有点像，但是不完全一样。

根据上面的描述，重定向+修改，第二个修改 需要看匹配的域名，如果是 example.com 则无效；如果是 localhost:8080 则理论上应该有效，但是因为 bug 也不会生效。不过本地服务未收到请求这个我没遇到过，如果确信代理配置正确等作者看看吧。

如果急用可以先试一下别的，mitmproxy 是个开源的代理工具，可以找 GPT 写脚本完成这个功能（类似于 reqable 的脚本功能），reqable 脚本我试过了，似乎实现不了重定向，无法修改 protocol 和 url (host)（有人提过 issue，暂时没有下文 #768 ）

**Comment by MegatronKing** [comment]
@zsh2517 @luckywang1107 

我优化了一个版本，修复了重定向和重写的一些问题，可以试试看：[reqable-app-macos-arm64.dmg](https://reqable-generic.pkg.coding.net/package/app/reqable-app-macos-arm64-redirect-fix.dmg?version=latest)

为了帮助大家自行排查问题，#1016 功能也做了，可以在`···`的`自定义选项卡`中开启`拦截器Tab`，里面会显示完整的流程。

<img width="1080" alt="截屏2024-11-01 17 33 45" src="https://github.com/user-attachments/assets/78a58be5-51e6-469a-9591-43b62f9559fa">

**Comment by luckywang1107** [comment]
可以了，好用！

**Comment by MegatronKing** [comment]
v2.28.0已修复。
