### ISSUE TITLE
[feature] 提供对请求和响应的全流程追踪能力

### ISSUE THREAD

**Issue by zsh2517** [reqable/reqable-app#1016]
## 背景描述

reqable 抓包时，提供了非常多的对请求、响应做出修改的能力。比如对请求的控制（网关）、修改目标服务器（镜像、重写-重定向、脚本）、修改请求响应（断点、脚本、重写-修改xx）等。不同的功能模块之间存在先后顺序（优先级），相同的功能由于具有一个列表，也是有一个从上到下的执行顺序。

而目前界面（调试）列表中，只会展现请求被捕获到时的信息。至于这个数据经过了哪些阶段、每一步经过了怎样的处理、处理前后有什么变化、最终是以什么数据形态发出去的，从用户的角度来看并不清楚。

当配置比较复杂或者组合多个规则时，比较容易遇到比如（下面都是我自己遇到过的问题）

- 为什么没有被修改？（匹配的 URL 有问题，比如拼写错误、通配符没开等）
- 修改不符合预期？（#1014 我在尝试构建一个复现案例时，有一个 example.com 的重定向规则没关而且我没注意到，差点写错 issue 描述，另外该 issue 提到的问题本身也是“修改不符合预期”）
- 通配符替换该怎么写？（#1004 正则就是因为通配符感觉比较黑盒才提出来的，当时我需要将 `https://example.com/api?arg=val` 这一个特定的 path 发到另一个服务器，通配符纠结了很久，最后还是直接 `example.com/*` 做了处理，然后手动在需要时打开，不需要时关闭）
- 发出去的是什么？（同 #1004，有的时候为了测试是否生效，需要拿 `httpbin.org` 进行测试，二级代理也许是我配置问题，上游接 proxyman 没有收到请求，这个话题暂时不讨论）

## 理想的解决方案：对一个请求的整个周期每一步进行记录

从请求进入 reqable 开始，每经过一条规则记录一下状态，形成一个例如下面这样的日志。
然后任意两个状态（例如收到请求与重写（# 5）处理前、重写（# 5）处理前与处理后等）可以进行对比
这样对于任意一条请求，可以明确知道它经历了什么，当遇到问题（无论是用户配置不当还是程序 bug）时，也更容易定位具体规则
另外，在每一步都可以提取出来进行“编辑”、重放，如复制为 curl 或直接新建一个 API 请求测试。

- 收到请求
- 重写（# 1）重定向：未命中
- 重写（# 2）重定向：命中
- 重写（# 3）修改请求体：未命中
- 重写（# 4）修改请求体：命中
- 重写（# 5）添加请求头：命中
- 重写（# 5）添加响应头：不涉及
- ……
- 脚本（# 1）未命中
- 脚本（# 2）命中
- ……
- 发送请求
- 收到响应
- ……继续逐步列出来
- ……
- 响应离开 reqable

## 附加能力（或单独作为次优方案）：修改前与修改后各保留一份记录

如果上面逐阶段实现比复杂，或许可以在记录修改前的请求和响应的同时，额外记录一份修改后的信息，然后在筛选、查看时提供选项（按照修改前展现/修改后展现）以及修改前后的对比（可以在请求点开之后，总览、原始、请求头……后面加一个修改前后对比）。

我目前使用过的类似产品有 Charles、Proxyman、MITMProxy，其他轻度使用的还有 Burpsuite。Charles 因为不喜欢 UI 没继续用。就说 Proxyman 和 MITMProxy 这两个，我记得这俩在抓包的记录页面，是按照修改后的请求记录的，而 reqable 是按照修改前的请求记录的，二者我觉得各有优劣，但仅从调试请求的角度来说，我认为记录修改后的请求可能会更好。

> 背景/原因：因为既然用户通过“重写”等功能修改了请求，那么表示用户是希望对原始请求进行修补（mock 或者增删改一些属性或字段），实际上更想要的是修改后的请求，而非仅仅查询原来的请求，此时显示修改后的数据更有意义。而不修改单纯抓包看数据无需讨论，前后是一样的。
我前后端都做过，开启修改请求/响应相关的选项时，通常是为了减轻操作的负担或者受到另一方/第三方限制（如直接重放避免在手机/网页重新点半天；抓包后编辑请求而无需找一个特定 case；做前端时不一定能让后端返回特定测试数据；做后端时不一定能让前端和客户端请求到我的服务器上或者携带实验标识（无法修改代码）；受到系统/宿主浏览器等影响会有跨域、同源、登录态、白名单、安全、内网等制约无法发起正确的请求）

## 可能存在的问题

下面这些是我想到的一些问题，不过通过白名单、选项（主动开启才记录多份）、适度的压缩策略（例如只有修改才记录、多份数据放到一起压缩等）等，应该不会有明显负担

- 体积膨胀：如果记录下来，那么意味着可能同一个请求的数据需要记录很多份。而记录请求 diff 可能比较难实现
- 性能：增加了额外的处理步骤，以及数据读写问题
- 长文本、二进制数据对比

**Comment by MegatronKing** [comment]
感谢，需求内容很详细，我今天在修复重定向问题的时候也想了下，两个问题。

1. UI显示是原始请求地址还是重定向的新地址。

这个有点难抉择，感觉各有优劣，每个人关注的点不一样，有人习惯关注原始请求，有人习惯关注新请求。要不要做个开关选项，还在纠结中。

2. 细节记录。
 
记录本身不难，但是问题确实就是记录的数据会太多了，一个数据会记录多份。存到内存简单，但是有性能问题，存到文件又大量占用用户空间，成本相比于功能本身而言太大了。如果不记录，最直接的就是用户又不好判断是否命中规则。

我倾向于不记录细节，而是简单记录触发了哪个规则，实现也简单。我打算新增一个Tab（拦截器），Tab下面显示这个请求触发了哪些规则，可以直接点击打开规则详情，如果没有显示则说明没有命中规则。

**Comment by MegatronKing** [comment]
基本做完了，下个版本上线。

https://github.com/user-attachments/assets/d4d94162-9859-4003-b83f-71e2a6fba57d

**Comment by MegatronKing** [comment]
v2.28.0已发布，再次感谢提供建议。
