### ISSUE TITLE
[bug] windows10系统，无法获取到使用node服务发起的后台接口请求

### ISSUE THREAD

**Issue by TTcom** [reqable/reqable-app#1020]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@TTcom 试试这个：https://reqable.com/zh-CN/docs/capture/proxy-terminal

**Comment by MegatronKing** [comment]
@TTcom 请问是否可以？

**Comment by TTcom** [comment]
> @TTcom 请问是否可以？

不行的，获取不到

**Comment by MegatronKing** [comment]
> > @TTcom 请问是否可以？
> 
> 不行的，获取不到

你用了代理终端吗？如果不行，麻烦提供下操作步骤、截图或者录屏。

**Comment by MegatronKing** [comment]
没有进一步的回复，这个Issue我先关闭了。
