### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by menmemdvtka** [reqable/reqable-app#1021]
https://github.com/user-attachments/assets/f5be05b5-b072-4909-b0ff-e4c54a868289

when i turn on check on iphone then data collection ok. but when i connect to transfer via computer then it is blocked. I have fully installed cretificate on computer and phone
![image](https://github.com/user-attachments/assets/993e0f18-ccd0-49f6-a771-faa6e0f184b8)

**Comment by menmemdvtka** [comment]
Hope ADM support

**Comment by MegatronKing** [comment]
SSL error means certificate issue, please see https://reqable.com/en-US/docs/faq/ssl/

**Comment by menmemdvtka** [comment]
> SSL error means certificate issue, please see https://reqable.com/en-US/docs/faq/ssl/

![image](https://github.com/user-attachments/assets/e137882b-9470-4c2c-a380-0fed9fa9388b)
![image](https://github.com/user-attachments/assets/f9b5df75-e414-4fc3-85b5-9c4f16767cec)
![image](https://github.com/user-attachments/assets/fbdd2ba8-7748-4cd5-8079-82740bbcf0a1)
on android i tried reinstalling the certificate many times but still error

**Comment by menmemdvtka** [comment]
https://github.com/user-attachments/assets/370e2886-0871-499f-ab40-87f97328363f

this is the process i installed the Certificate. i dont know what steps are missing and how to do it, hope to get help with videos from admin.

**Comment by MegatronKing** [comment]
Did you do this: https://reqable.com/en-US/docs/getting-started/installation/#user-certificate

**Comment by MegatronKing** [comment]
> bandicam.2024-11-02.14-13-34-201.mp4 
> this is the process i installed the Certificate. i dont know what steps are missing and how to do it, hope to get help with videos from admin.

Please complete your setup, are you missing 2.1 and 2.2?

**Comment by menmemdvtka** [comment]
> > bandicam.2024-11-02.14-13-34-201.mp4
> > this is the process i installed the Certificate. i dont know what steps are missing and how to do it, hope to get help with videos from admin.
> 
> Please complete your setup, are you missing 2.1 and 2.2?

admin do you have a video tutorial to install it. where do i make the file and put it?

**Comment by MegatronKing** [comment]
We have made it very clear in the documentation and application guides, if you choose to ignore or don't understand the steps, it's your own business.

**Comment by menmemdvtka** [comment]
> We have made it very clear in the documentation and application guides, if you choose to ignore or don't understand the steps, it's your own business.

If I understood, I wouldn't have asked the admin. The admin should make a video with instructions on how to install it. Then users will understand and follow it more easily.
