### ISSUE TITLE
[bug] 请求体格式化错误

### ISSUE THREAD

**Issue by picture-j** [reqable/reqable-app#1025]
![image](https://github.com/user-attachments/assets/bdf7d09f-6942-45cc-a3fb-59a77f0443af)

其中这个请求体是
{
    "idIndb": 7,
    "msgs": [
        {
            "content": "你好",
            "idInDb": 0,
            "isAtBySomeone": 0,
            "isAtGiftMsg": 0,
            "lastid": 0,
            "localuuid": "xxxx",
            "msgtype": "text",
            "skinid": "102",
            "sourceid": "xxx",
            "targetid": "cccc",
            "type": "1"
        }
    ],
    "action": "send",
    "signature": "d9039e9d57",
    "token": "xxcc",
    "type": "1",
    "userid": "ddd",
    "version": "09.0.2 (SEA-AL10 / 10)"
}

**Comment by MegatronKing** [comment]
要看content-encoding和transfer-encoding

**Comment by picture-j** [comment]
![image](https://github.com/user-attachments/assets/56e81890-d699-4108-80e3-229f7fa11811)

**Comment by MegatronKing** [comment]
content-encoding是gzip，你请求体gzip压缩了吗？

**Comment by picture-j** [comment]
是的

**Comment by MegatronKing** [comment]
> 是的

是的就不会出现这个错误，如果你确定是reqable的decode问题，请给出证明。

**Comment by picture-j** [comment]
我不是开发人员，我只能描述现象，请问还需要什么证明？同样的请求使用proxyman是可以正常展示请求体的
![image](https://github.com/user-attachments/assets/6d0aaf3d-298e-4668-bb63-5820cb5bf0c6)


header
![image](https://github.com/user-attachments/assets/ac6cab1e-cdcf-4e68-b487-2f7aa07495c3)

**Comment by MegatronKing** [comment]
@picture-j 请更新到2.30.1版本，这个问题已优化。
