### ISSUE TITLE
[feature] 希望能方便地跳转到当前打开的详情对应请求列表位置

### ISSUE THREAD

**Issue by xxr0ss** [reqable/reqable-app#1028]
**Is your feature request related to a problem? Please describe.**

我经常碰到这种使用场景：我需要按特定筛选条件找到某个请求并打开其详情页，然后查看这个请求附近的其他普通请求（不是我筛选的请求），然而删除筛选条件后，请求列表滚动位置并不位于我当前打开详情页的请求附近，我只能先记住这个请求的ID，然后手动滚动到这附近。

**Describe the solution you'd like**

希望添加快捷键可以直接滚动到**当前打开详情的请求**的请求列表附近，至少像mitmweb一样，当我用PgUp, PgDown的时候，会跳转到前后的请求并且左边列表也focus到对应位置。

**Comment by MegatronKing** [comment]
收到，感谢反馈，我们尽快优化。

**Comment by MegatronKing** [comment]
请更新到最新v2.29.1版本，可以使用`Control + ⬆️/⬇️`快捷键导航和定位之前浏览的请求。
