### ISSUE TITLE
在电脑端，开启python脚本，网速很卡？

### ISSUE THREAD

**Issue by Abner1995** [reqable/reqable-app#1029]
在电脑端，开启python脚本，浏览器浏览网页很卡，微信小程序加载也很慢。把脚本关闭就好很多了。什么原因呢

**Comment by MegatronKing** [comment]
@Abner1995 建议你配置规则的时候尽量精确匹配，开脚本确实会影响效率，每个请求都跑一遍脚本会感受到明显变慢。

**Comment by MegatronKing** [comment]
如果你对数据只读不改，请求数量较多的时候，建议使用[上报服务器](https://reqable.com/zh-CN/docs/capture/report-server/)功能，开个本地server接收数据，这个是异步的不会影响访问效率。

**Comment by Abner1995** [comment]
> 如果你对数据只读不改，请求数量较多的时候，建议使用[上报服务器](https://reqable.com/zh-CN/docs/capture/report-server/)功能，开个本地server接收数据，这个是异步的不会影响访问效率。

谢谢，我看看上报服务器
