### ISSUE TITLE
[feature] url中使用环境变量后的完整路径麻烦显示一下，能让我复制

### ISSUE THREAD

**Issue by davelet** [reqable/reqable-app#1035]
如题

**Comment by MegatronKing** [comment]
@davelet 您好，感谢反馈。

这个问题我们做过调研，同类的产品里面好像只有Insomnia有URL预览功能，但是我们不打算这么做，原因如下：

- UI元素会复杂化，对于参数非常多的URL显示完整很不友好（太长了，占用大量显示空间），编辑的时候很容易点到预览区域，发现又不能修改。
- 本身环境变量就有颜色标记（应用右上角），对不同的环境变量建议用差异化较大的颜色进行区分，看到颜色就知道环境变量的值是什么。
- 环境变量除了用户自建的，还有内置的动态变量，例如手机号、邮箱、时间戳等等，这个预览根本做不了，提交的时候随机生成的或者一直在变的。

关于复制环境变量内容，比如提取完环境变量之后完整的URL，这确实是个有必要做的功能。我们会在下个版本加上，任何地方选中包含环境变量的文本，都会出现一个`提取复制`的选项，复制提取完变量之后的内容到粘贴板。

补充一个点，我在掘金上看到你评论，除了这个问题，你说还有请求失败不知道什么原因的问题，能否再开个issue提供下详细的问题描述？

**Comment by MegatronKing** [comment]
v2.29.0版本已新增`提取复制`功能。

![image](https://github.com/user-attachments/assets/46d9c58c-fa8f-4fbd-af9e-9fccc08c480c)
