### ISSUE TITLE
[feature] Python 生成代码模板改进

### ISSUE THREAD

**Issue by xx299x** [reqable/reqable-app#1036]
![image](https://github.com/user-attachments/assets/372dfa1f-4207-494e-b5d3-ff7ab578c18b)
## 期望
这里的json.dumps去除, 放在这里, 以便于修改测试参数
response = requests.post(url, data=json.dumps(payload), headers=headers)

**Comment by MegatronKing** [comment]
您好，感谢建议。我改了一下，是要下面这样的效果吗：

![image](https://github.com/user-attachments/assets/e470ced4-2393-4237-aac6-b5657764cca8)

**Comment by xx299x** [comment]
> 您好，感谢建议。我改了一下，是要下面这样的效果吗：
> 
> ![image](https://private-user-images.githubusercontent.com/15059084/383833049-e470ced4-2393-4237-aac6-b5657764cca8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Njk1NjgsIm5iZiI6MTczMDk2OTI2OCwicGF0aCI6Ii8xNTA1OTA4NC8zODM4MzMwNDktZTQ3MGNlZDQtMjM5My00MjM3LWFhYzYtYjU2NTc3NjRjY2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA4NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMmQxMjVmZmI0ZGZkODI0M2EzM2IyZWRjYzQ2YTYzMTE1MTU3MTcwMWJmMGFkYWIwMTk5NzY3YWM2NzJiNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fvYzOs6rN1pMWsQ36ruzD-01z8AsuMbCsD2n0qIY3h8)

是需要这样的效果, 感谢, 另外还有 当 `content-type = 'application/x-www-form-urlencoded'` 时
![image](https://github.com/user-attachments/assets/af8b3ba8-b061-4c6d-ae6b-7d0ad8680955)

生成代码的效果是下面这样, 一样不利于修改调试
![image](https://github.com/user-attachments/assets/413a3fe8-105a-4216-a8b4-7c30dc9b90e1)
建议改为下面的样式
```python
import requests
import urllib.parse

url = "https://url"

payload_dict = {'time': "now"}

...

payload = urllib.parse.urlencode(payload_dict)
response = requests.post(url, data=payload, headers=headers)
print(response.text)
```

**Comment by MegatronKing** [comment]
@xx299x 我发现`requests`会自动urlencode，你试试这种行不行：

```python
import requests
import urllib.parse

url = "https://url"

payload = {'time': "now"}

...
response = requests.post(url, data=payload, headers=headers)
print(response.text)
```

**Comment by MegatronKing** [comment]
v2.29.0版本已优化，请更新版本。
