### ISSUE TITLE
[bug] 调试面板-搜索框-内容错乱

### ISSUE THREAD

**Issue by ITSiegeLion** [reqable/reqable-app#1037]
**Describe the bug**
调试面板-搜索框-输入内容有时候会自动把输入法预选框的字符输进去
![Snipaste_2024-11-07_11-39-42](https://github.com/user-attachments/assets/e49dd6a6-d9d2-4309-abdd-bd7f521d9e47)

**Information**
 - Platform: Windows
 - OS: [e.g. 12.1]
 - Arch: x64
 - App Version: 当前版本2.28.0(120)(x86_64)

**Comment by MegatronKing** [comment]
您好，感谢反馈，已复现，中文输入是有问题，尽快修复。

**Comment by Jingle-Pan** [comment]
发现同样的问题

**Comment by MegatronKing** [comment]
@ITSiegeLion @Jingle-Pan v2.29.0版本已修复，请更新版本。
