### ISSUE TITLE
[bug] Mac下经常CPU爆了，假死

### ISSUE THREAD

**Issue by Jesn** [reqable/reqable-app#1039]
![image](https://github.com/user-attachments/assets/cede5b50-3a99-42ae-904c-519338d08e81)

能关闭的都关了，CPU还占用3113%
![image](https://github.com/user-attachments/assets/6d296834-1d2c-4e62-9ed8-03fbd84e7753)

**Comment by MegatronKing** [comment]
@Jesn 您好，更新下版本看看？

**Comment by Jesn** [comment]
![image](https://github.com/user-attachments/assets/9d8738c4-7bf1-4ce1-b861-7db83f505a4e)
更新到最新版好了，好久没更新了

**Comment by MegatronKing** [comment]
好的，如果还有问题，排查下下面两个可能的点：
- 历史tab下面，把历史记录清掉。
- 用其他代理工具，比如clash等等，可能出现请求回路，一个请求来回代理循环无休无止，一般换个端口就可以了。
