### ISSUE TITLE
[feature] 列表的“时长”列的时间单位能否支持毫秒

### ISSUE THREAD

**Issue by ririliu** [reqable/reqable-app#1040]
**Is your feature request related to a problem? Please describe.**
无

**Describe the solution you'd like**
列表的“时长”列，单位能不能使用毫秒/ms，大部分开发调试场景，秒对于一个请求的耗时来说精度不太够，或者提供一个选项，让用户自己决定时长的单位

**Comment by MegatronKing** [comment]
单位是秒，精确到小数点后面2位，也就是精确到10毫秒，应该是够了，我看其他竞品好像也是这样

**Comment by ririliu** [comment]
🙏感谢回复，我之前用的是fiddler是精确到1ms，觉得比较合理，其他同类产品用的不多

![图片](https://github.com/user-attachments/assets/21c5140b-c4ab-4254-82c0-6abe73dfb5aa)

**Comment by MegatronKing** [comment]
那就小数点后面再多精确一位？

**Comment by ririliu** [comment]
> 那就小数点后面再多精确一位？

如果切换单位比较麻烦，这样精确到0.xxx也是不错的 👍

**Comment by MegatronKing** [comment]
v2.29.0版本已优化，请更新版本。
