### ISSUE TITLE
[bug] 搜索框无法正常输入中文

### ISSUE THREAD

**Issue by panyuan209** [reqable/reqable-app#1042]
**Describe the bug**
在搜索框用微信输入法和 mac 自带的输入法输入中文，无法正常输入，输完拼音后空格确认，会自动输入字母，没有输入汉字，升级最新版本之后出现的这个问题，之前版本使用没有这个问题

**Screenshots**

https://github.com/user-attachments/assets/e58c5da3-f532-4ea4-98a6-9e2c0814d848

**Comment by MegatronKing** [comment]
感谢反馈，同 #1037

**Comment by MegatronKing** [comment]
@panyuan209 v2.29.0版本已修复，请更新版本。
