### ISSUE TITLE
[bug] 上传文件自动将中文文件名进行了URL编码

### ISSUE THREAD

**Issue by SugarFatFree** [reqable/reqable-app#1043]
API调试功能，将请求体的“数据类型”改成“multipart”后，并将参数栏的“更多操作”选择“文件”，之后参数名为“file”，参数值选择一个中文文件，“发送”请求，后端接收到的文件名将会是一个URL编码后的文件名，如果我使用其他工具则不存在此现象，请不要将中文文件名自动进行URL编码，这样会阻碍我的功能测试。

 - Platform: windows
 - OS: 10
 - Arch: x86-64
 - App Version: 2.28.0

**Comment by MegatronKing** [comment]
HTTP RFC规范要求Header中必须是ASCII字符，其他的字符要用URI编码。其他工具则不存在此现象，应该是没有遵循RFC规范。

![image](https://github.com/user-attachments/assets/e061eec8-a427-4a02-bcf3-f434efbeefa8)

**Comment by MegatronKing** [comment]
后端收到文件时，文件名建议先调用URI解码下。

**Comment by SugarFatFree** [comment]
> 后端收到文件时，文件名建议先调用URI解码下。

这个“后端”并不一定可以由我进行控制，能否增加一个配置项进行控制是否进行URL编码呢？

**Comment by SugarFatFree** [comment]
> HTTP RFC规范要求Header中必须是ASCII字符，其他的字符要用URI编码。其他工具则不存在此现象，应该是没有遵循RFC规范。
> 
> ![image](https://private-user-images.githubusercontent.com/15059084/384213104-e061eec8-a427-4a02-bcf3-f434efbeefa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzY1NTMsIm5iZiI6MTczMTAzNjI1MywicGF0aCI6Ii8xNTA1OTA4NC8zODQyMTMxMDQtZTA2MWVlYzgtYTQyNy00YTAyLWJjZjMtZjQzNGVmYmVlZmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDAzMjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNTlmMDFjOTIzNmZkZjFjM2MzMzQzYWMxM2ZiZGM4M2I2NGY2Nzg3N2IzZWFmMGM5ZWJlNzM0ZTg5Y2UzM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sehWAvjwj-2e29db90wnHtOXXBzIcfllihNIjw1-Y14)

这个规范是只针对header吧，上传文件的文件名并不是存在header中的啊，我记得是放在body里面的吧

**Comment by MegatronKing** [comment]
> 这个规范是只针对header吧，上传文件的文件名并不是存在header中的啊，我记得是放在body里面的吧

文件名就在`Content-Disposition`里面，抓包看一下就知道了

**Comment by SugarFatFree** [comment]
> > 这个规范是只针对header吧，上传文件的文件名并不是存在header中的啊，我记得是放在body里面的吧
> 
> 文件名就在`Content-Disposition`里面，抓包看一下就知道了

下载文件的文件名才在header里面吧，上传文件是在body里面的，这个是我抓到的request header：
···
POST /agent/proxyApi/flames-docqa/doc/semantic-doc/document/files/upload HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 176596
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarylvLZdyIcqo4mqNyD
Host: 172.29.228.238:30880
Origin: http://172.29.228.238:30880
Pragma: no-cache
Referer: http://172.29.228.238:30880/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
X-Requested-With: XMLHttpRequest
···

**Comment by SugarFatFree** [comment]
> > 这个规范是只针对header吧，上传文件的文件名并不是存在header中的啊，我记得是放在body里面的吧
> 
> 文件名就在`Content-Disposition`里面，抓包看一下就知道了

包括你截图规范的部分，GPT回复是“响应头”而不是“请求头”，现在出现的场景是上传文件而不是下载文件

**Comment by MegatronKing** [comment]
额，抱歉，我忘了。`multipart/form-data`的`Content-Disposition`确实应该算是body部分。

**Comment by MegatronKing** [comment]
下个版本修复

**Comment by MegatronKing** [comment]
v2.29.0版本已修复，请更新版本。
