### ISSUE TITLE
[feature] 希望增加文档功能

### ISSUE THREAD

**Issue by baiweijie** [reqable/reqable-app#1044]
天下苦Api post久矣啊，越更新越卡。打开一次转半天,更了8与7不互通，还把7的下载从官网删了。但是他能把请求body的json提取出字段出来，能编辑字段备注。如果reqable有文档功能就能平替掉apipost了

**Comment by MegatronKing** [comment]
感谢建议，同 #525 ，需求有点多，这个功能一直还没时间做，可能需要等云服务和协作功能上线后才会处理。

**Comment by MegatronKing** [comment]
相同Issue先关闭了。
