### ISSUE TITLE
[bug] 导入集合Apipost 失败

### ISSUE THREAD

**Issue by Granttt** [reqable/reqable-app#1047]
![](http://qi.oss.buildyou.top/2024/11/08/131715QQ截图20241108131551.png)
导入失败：type'String'is not a subtype of type'List<dynamic>?'

apipost版本7.2.6
reqable版本2.28.0

**Comment by MegatronKing** [comment]
@Granttt 能提供下log吗，点击底部栏5下打开日志控制台，复制下log

**Comment by Granttt** [comment]
@MegatronKing 好的
[Uploading error.txt…]()

**Comment by Granttt** [comment]
@MegatronKing 好的
[reqable.log](https://github.com/user-attachments/files/17674095/reqable.log)

**Comment by Granttt** [comment]
@MegatronKing 好的
[reqable.log](https://github.com/user-attachments/files/17674114/reqable.log)

**Comment by MegatronKing** [comment]
收到，非常感谢

**Comment by MegatronKing** [comment]
@Granttt v2.29.0版本已经修复，请更新版本。
