### ISSUE TITLE
[question] apiPost 8.1.5版本的api接口无法导入

### ISSUE THREAD

**Issue by jasester** [reqable/reqable-app#1050]
**Describe the question**
apipost 版本8.1.5 导出的api无法导入
![QQ20241109-103334](https://github.com/user-attachments/assets/67ddb8e5-6092-4b82-b1ed-7906978d92e8)

**Comment by MegatronKing** [comment]
@jasester 感谢反馈，看样子他们数据结构改了，我下个版本支持下。

**Comment by MegatronKing** [comment]
@jasester 更新下2.29.0版本，我们支持ApiPost8数据导入了
