### ISSUE TITLE
[bug] 无法启用系统proxy

### ISSUE THREAD

**Issue by danny-su** [reqable/reqable-app#1054]
![PixPin_2024-11-11_11-26-38](https://github.com/user-attachments/assets/0473727e-1a87-4ca0-a9b2-6fb5832ff8db)

![image](https://github.com/user-attachments/assets/b38a11f0-5a4f-4ee5-bfdd-a242fd487a67)

**Comment by MegatronKing** [comment]
@danny-su 您好，检查下系统设置里面有没有开着VPN，需要关掉。

**Comment by danny-su** [comment]
@danny-su  嗯，是开了VPN，这个是和VPN有冲突的吗？

**Comment by MegatronKing** [comment]
> @danny-su 嗯，是开了VPN，这个是和VPN有冲突的吗？

VPN可能会导致代理配置检测不出来，算是bug吧，前几天有用户反馈过，还没来得及处理。

**Comment by MegatronKing** [comment]
Mac上面一旦开启了VPN，所有代理状态都是关闭状态，所以你看到无论怎么点击图标都没法变绿，这个是系统行为。其实也可以理解，VPN工作在网络层，代理工作在应用层，VPN的优先级更高，即使代理配置成功了也没法抓包。

**Comment by MegatronKing** [comment]
下个版本我们加个提示。

**Comment by danny-su** [comment]
@MegatronKing OK, Thanks.

**Comment by MegatronKing** [comment]
v2.29.1版本已优化，增加了关闭VPN的提示。
