### ISSUE TITLE
[bug] 导入cUrl后授权信息丢失

### ISSUE THREAD

**Issue by lakevilladom** [reqable/reqable-app#1056]
**Describe the bug**
如题，有如下curl:
```
curl -u aaa:bbb \
   -v -X POST  'https://urls.com' \
   -H 'Content-Type: application/json' \
   -d '
    {
    "envs": []
}'
```
导入后，"请求头"里面没有Authorization，"授权"里面用户名/密码

**Information**
 - Platform: [windows]
 - App Version: [2.29.0]

**Comment by MegatronKing** [comment]
有点问题，好像要加个`--basic`就可以了。下个版本修复掉。

**Comment by MegatronKing** [comment]
v2.29.1版本已修复。
