### ISSUE TITLE
[bug] Android端启用增强模式，Windows端的显示漏过了一些包

### ISSUE THREAD

**Issue by hwnng211** [reqable/reqable-app#1058]
**Describe the bug**
Android端启用增强模式并连接Windows端，显示漏过了一些http包。

**Screenshots**

**Information**
 - Platform: windows
 - OS: [e.g. 12.1]
 - Arch: x86-64
 - App Version: v2.28.0，v2.29.0

**Comment by hwnng211** [comment]
抓包时在Windows上同时打开wireshark抓包可以看到这些漏过显示的包

**Comment by MegatronKing** [comment]
> 抓包时在Windows上同时打开wireshark抓包可以看到这些漏过显示的包

 Reqable只会处理和显示HTTP协议，确定是漏了HTTP协议的包吗？

**Comment by hwnng211** [comment]
> > 抓包时在Windows上同时打开wireshark抓包可以看到这些漏过显示的包
> 
> Reqable只会处理和显示HTTP协议，确定是漏了HTTP协议的包吗？

是的

**Comment by MegatronKing** [comment]
理论上不太会漏HTTP，能否提供下更具体的细节，比如复现步骤？

**Comment by hw-d-s** [comment]
> 理论上不太会漏HTTP，能否提供下更具体的细节，比如复现步骤？
可能是查询字符串解析的问题。如下，如果删掉一个查询字符串就正常：
curl -X GET 'http://103.43.71.90:7080/user/addDevice?deviceDpi=2297%C3%971035&androidDeviceIds=%7B%22oaid%22:%220ED24160F2B99488019648D7E7FCC3267B44D3D0A8557C7B8E8F40F579726CF2%22,%22uuid%22:%225c33894b-d4ba-4588-8d5a-cc8f5885a1fb%22,%22androidId%22:%2282b303b2740847d6%22,%22ua%22:%22Mozilla%5C/5.0%20(Linux;%20Android%2011;%20IN2010%20Build%5C/RP1A.201005.001;%20wv)%20AppleWebKit%5C/537.36%20(KHTML,%20like%20Gecko)%20Version%5C/4.0%20Chrome%5C/87.0.4280.141%20Mobile%20Safari%5C/537.36%22%7D&deviceID=82b303b2740847d6&mac=00:00:00:00:00:00&osVersion=Android_11' -H 'User-Agent: Dalvik/2.1.0 (Linux; U; Android 11; IN2010 Build/RP1A.201005.001)' -H 'Connection: Keep-Alive' --http1.1

**Comment by hwnng211** [comment]
> 理论上不太会漏HTTP，能否提供下更具体的细节，比如复现步骤？

如下，如果删掉任意一个查询字符串就正常：
`curl -X GET 'http://ip:7080/user/addDevice?deviceDpi=2297%C3%971035&androidDeviceIds=%7B%22oaid%22:%220ED24160F2B99488019648D7E7FCC3267B44D3D0A8557C7B8E8F40F579726CF2%22,%22uuid%22:%225c33894b-d4ba-4588-8d5a-cc8f5885a1fb%22,%22androidId%22:%2282b303b2740847d6%22,%22ua%22:%22Mozilla%5C/5.0%20(Linux;%20Android%2011;%20IN2010%20Build%5C/RP1A.201005.001;%20wv)%20AppleWebKit%5C/537.36%20(KHTML,%20like%20Gecko)%20Version%5C/4.0%20Chrome%5C/87.0.4280.141%20Mobile%20Safari%5C/537.36%22%7D&deviceID=82b303b2740847d6&mac=00:00:00:00:00:00&osVersion=Android_11' -H 'User-Agent: Dalvik/2.1.0 (Linux; U; Android 11; IN2010 Build/RP1A.201005.001)' -H 'Connection: Keep-Alive' --http1.1`

**Comment by MegatronKing** [comment]
@hw-d-s 非常感谢，能否复现问题，我们今天版本会修复掉。

**Comment by MegatronKing** [comment]
v2.29.1版本已修复。
