### ISSUE TITLE
[bug] windows连接L2TP VPN后无法抓包

### ISSUE THREAD

**Issue by getDataTest** [reqable/reqable-app#1059]
电脑连上vpn后就无法抓包了
![image](https://github.com/user-attachments/assets/62395eb3-130e-408a-92ba-5756d535ebd6)
断开后就恢复正常了
![image](https://github.com/user-attachments/assets/67489213-fa66-4488-b2e8-696ea434cdef)

**Comment by MegatronKing** [comment]
您好，感谢反馈，我们没有测试过VPN这种模式，可能确实存在问题。

**Comment by MegatronKing** [comment]
VPN工作在网络层，代理工作在应用层，VPN的优先级更高，所以这个是正常行为。Reqable使用代理模式进行抓包，一旦开启VPN，网络访问会直接被VPN接管，没法走到代理。

**Comment by MegatronKing** [comment]
这个不是Reqable的问题，Issue我关闭了。
