### ISSUE TITLE
[question] 调试列表的自动滚动貌似不太稳定

### ISSUE THREAD

**Issue by ririliu** [reqable/reqable-app#1061]
**Describe the question**
有时候会滚动到最新的请求，有时候又不会，不管有没有选中某条请求记录，找不到什么规律，不清楚这个自动滚动的规则是怎么样的

**Comment by MegatronKing** [comment]
有新数据进来的时候，如果列表已经滑到最下面会自动滚动，否则不会。但是由于排序的因素，新进来的数据可能会插入到前面，可能导致选中的数据位置发生变更。

**Comment by ririliu** [comment]
我每次都手动滚动到最底端，然后不做任何操作，去抓包的android app里操作，自动滚动几条，然后就不滚动了，后续请求再多也不会滚动了，用fiddler的时候还真没碰到过这样的情况

**Comment by MegatronKing** [comment]
@ririliu 试试最新版本2.29.1，优化了下。
