### ISSUE TITLE
[feature] Adding a JSON Escaping Tool in Toolbox

### ISSUE THREAD

**Issue by sketchmind** [reqable/reqable-app#1063]
# Feature: Adding a JSON Escaping Tool in Toolbox

### Use Case
In many OpenAI API call scenarios, users need to send JSON data with multi-line text, especially when passing content within prompts. For instance, when sending a lengthy text containing newlines or double quotes as a prompt to OpenAI's API, the text must be JSON-compatible, meaning all special characters need to be correctly escaped.

### Example
Here’s an example of a prompt that a user might want to send:

```plaintext
# Multi-line prompt example
Once upon a time, a character said, "Magic is real!" 
Then they continued on their journey, and each step they took was more amazing than the last.
They were determined to prove that magic exists to all their friends.
```
This text needs to be in JSON format for the request body. Copying it directly would cause format errors, so all double quotes and newlines need to be manually escaped. The escaped JSON format would look like this:
```json
{
  "prompt": "Once upon a time, a character said, \"Magic is real!\" \nThen they continued on their journey, and each step they took was more amazing than the last.\nThey were determined to prove that magic exists to all their friends."
}
```
### Benefits of the Tool

By adding a JSON Escaping Tool in the toolbox, users could paste their original text into the tool and automatically generate a JSON-compatible string with proper escaping in just one click. This would eliminate the need for manual escaping, making it highly useful for writing prompts, debugging OpenAI requests, and quickly generating multi-line JSON strings.

### Summary of Use Cases

•	Quickly format complex prompts: Reduces time spent on manual escaping.
•	Reduces errors: Automated escaping minimizes the risk of mistakes.
•	Improves debugging efficiency: The formatted JSON is easier to read, helping users see the structure and content of the text more clearly.

**Comment by MegatronKing** [comment]
Thanks for the suggestion, this is a nice idea and we will add it to the toolbox as soon as possible.

**Comment by MegatronKing** [comment]
Done! Please update v2.30.1.
