### ISSUE TITLE
[bug]  导入apipost集合时报错：type 'int' is not a subtype of type 'String?'

### ISSUE THREAD

**Issue by Granttt** [reqable/reqable-app#1064]
[bug]  导入apipost集合报错：type 'int' is not a subtype of type 'String?'
，之前也提过一个类似 "Import failed: type 'String' is not a subtype of type 'List<dynamic>?'"
![QQ截图20241113110453](https://github.com/user-attachments/assets/af470640-5606-448c-ad35-df427332d3f7)
[reqable.log](https://github.com/user-attachments/files/17725556/reqable.log)

**Comment by MegatronKing** [comment]
感谢，今天稍后更新一个版本。

**Comment by MegatronKing** [comment]
@Granttt v2.29.1版本已修复。
