### ISSUE TITLE
[question] 我证书安装不了怎么回事

### ISSUE THREAD

**Issue by Nevoraa** [reqable/reqable-app#1066]
**Describe the question**
A clear and concise description of what the question is.
刷入模块已经成功了 /system/etc/security/cacerts/里面也可以看到证书 但是系统那里不显示 怎么办 之前还可以的 换了一个手机也是一样

**Comment by MegatronKing** [comment]
用电脑一键安装证书试试呢？

**Comment by Nevoraa** [comment]
> 用电脑一键安装证书试试呢？

可以了 嘿嘿谢谢
