### ISSUE TITLE
[bug] 文字乱码

### ISSUE THREAD

**Issue by Joehaivo** [reqable/reqable-app#1069]
**Describe the bug**
在mac夜间自动升级系统后, 自动重新打开app, 出现部分文字乱码

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/c5d45606-f8b6-41e8-8460-729dd41e7294)
![image](https://github.com/user-attachments/assets/43d5fe70-9dbf-4830-a527-66179cba80ad)

**Information**
 - Platform: macos 
 - OS: MacBook Pro（13 英寸，2020 年，四个雷雳 3 端口） macos15.1 
 - Arch:  x86-64
 - App Version: 2.29.0(121)

**Comment by Joehaivo** [comment]
重新打开应用后恢复了

**Comment by MegatronKing** [comment]
感谢反馈，这个bug有点神奇。

**Comment by Joehaivo** [comment]
> 感谢反馈，这个bug有点神奇。

似乎是 macos 系统更新后导致的的bug, 其他软件也出现了 
<img width="182" alt="image" src="https://github.com/user-attachments/assets/9ea7e27a-02c3-45ac-8a61-2c79f4f27ac1">
