### ISSUE TITLE
[bug] 升级页面点击打开文件夹卡死

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#1072]
![image](https://github.com/user-attachments/assets/d7b0a8e5-6ec2-4eaa-b1d1-7f8aaddf4197)
点击打开文件夹，百分百卡死，想手动安装都不行，找不到安装包位置

**Comment by MegatronKing** [comment]
@RonaldinhoL 当前卡死的版本是哪个版本？

**Comment by RonaldinhoL** [comment]
当前是 2.29.0 (121) (x86_64)，但是这个问题很早以前就发现存在了

**Comment by MegatronKing** [comment]
> 当前是 2.29.0 (121) (x86_64)，但是这个问题很早以前就发现存在了

2.29.1版本改了，你从github release下个2.29.1版本安装后再升级试试？

**Comment by RonaldinhoL** [comment]
2.29.1可以打开文件夹了，但是似乎进程检测有问题
![image](https://github.com/user-attachments/assets/874013fa-a342-4c65-92a3-577b75b68bb9)
手动杀到只剩一个进程，也无法安装，把这个进程也杀掉，安装界面也会消失
