### ISSUE TITLE
[feature] 已有的api上通过curl 导入的api请求不是替换已有的请求

### ISSUE THREAD

**Issue by PekingJam** [reqable/reqable-app#1076]
**Describe the bug**
在已有的api上通过curl 导入的api请求不是替换已有的请求，而是会提示新建一个api

**To Reproduce**
新建一个API集合，然后在该集合下新建一个api保存，打开此api，使用curl导入请求，然后点击保存。

**Expected behavior**
覆盖当前api而不是提示新建一个api

**Information**
 - Platform: windows
 - OS: 11
 - App Version: 2.29.2(123)

**Comment by MegatronKing** [comment]
@PekingJam 您好，感谢建议。这个在设计上就是这样，如果需要从cURL新建API，复制后右键点击`+`即可。

**Comment by PekingJam** [comment]
哦哦，好的
