### ISSUE TITLE
[feature] 系统代理的开启莫名其妙，严重干扰我开发

### ISSUE THREAD

**Issue by XiaoNaoWeiSuo** [reqable/reqable-app#1078]
reqable的系统代理会阻塞flutter的网络调试，我每次拿reqable调试好的api集合挂后台写前端的时候，reqable总有那么几下莫名其妙的自动打开了系统代理，导致我的flutter请求发不出去，我查半天还以为是跨域限制导致的，排查老半天，浪费了很多时间，reqable的系统代理能不能不要太过“自动”，把打开系统代理做的让我更可控一点，设计的太糟糕了这一点。

**Comment by MegatronKing** [comment]
@XiaoNaoWeiSuo 非常抱歉，`代理`菜单里面把`自动启用`关闭即可。
