### ISSUE TITLE
2.29.2版本导出HAR文件问题

### ISSUE THREAD

**Issue by Jingle-Pan** [reqable/reqable-app#1081]
导出的HAR文件中，解析出来headers的"host"变成了”:authority“，把":method": "POST", ":path":*** 及":scheme": "https",带入headers，与实际headers不符

**Comment by MegatronKing** [comment]
@Jingle-Pan 不是bug，这个是HTTP2协议的header，你用chrome导出HTTP2的请求也是这样。

**Comment by Jingle-Pan** [comment]
好的，了解
