### ISSUE TITLE
[bug] SSE流数据 处理的问题

### ISSUE THREAD

**Issue by 392004686** [reqable/reqable-app#1082]
content-type为text/event-stream，请求后无法获取实时流数据
SEE流为持续性，由服务器端于客户端建立连接后 不间断发送数据，在F12网页中可获取到流数据  

被动断开连接才会计算时长，当服务器端长时间保持不仅没获取到数据 且在软件停止后 时长无法计算，无法终止。

需要可截取流媒体数据，可主动关闭连接。
![微信截图_20241119170035](https://github.com/user-attachments/assets/b270dfc6-bfb2-4e30-81e2-7b104a2c4851)
![微信截图_20241119170055](https://github.com/user-attachments/assets/fc55596d-efd7-446f-b26c-386257ebfcf0)
![微信截图_20241119170121](https://github.com/user-attachments/assets/81fd9d2b-1bf4-4b5f-b77a-968468864cd8)
![微信截图_20241119170551](https://github.com/user-attachments/assets/9cc5538d-6935-4258-a0f8-600c19b55c43)

**Comment by MegatronKing** [comment]
同 #399

**Comment by MegatronKing** [comment]
这个需求会在下个版本实现，重复问题这里关闭了。
