### ISSUE TITLE
[bug] HttpHeaders 对象找不到 setitem 方法

### ISSUE THREAD

**Issue by mdcgqq** [reqable/reqable-app#1083]
**Describe the bug**
api 文档里面介绍 HttpHeaders 类有 setitem 方法，但实际使用中找不到该方法，会报下面的错误：
17:05:27.300     request.headers.setitem(key, value)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HttpHeaders' object has no attribute 'setitem'

**Comment by MegatronKing** [comment]
@mdcgqq 在python里面`__setitem__`的调用方式是 `headers[key] = value`

**Comment by MegatronKing** [comment]
后面把文档改一下，严谨一些

**Comment by mdcgqq** [comment]
嗯嗯，感谢
