### ISSUE TITLE
[feature] 能否在导入openapiV3时，创建二级目录，类似api分组管理

### ISSUE THREAD

**Issue by todohuai** [reqable/reqable-app#1087]
类似这样的形式
![image](https://github.com/user-attachments/assets/3d1ccdc8-afcc-44c5-9ef2-3eeba4f25337)

实际导入的这样
![image](https://github.com/user-attachments/assets/3959d0bd-4cfb-41fc-af49-b2d27715b206)

非常感谢

**Comment by MegatronKing** [comment]
您好，感谢建议。我看看openapiV3有没有目录结构。

**Comment by todohuai** [comment]
![image](https://github.com/user-attachments/assets/0764d5c2-6b39-464a-adad-6b3c198260e0)
可以参考这个Tags。 类似给接口打上标签，非常感谢

**Comment by MegatronKing** [comment]
@todohuai 请更新到最新2.30.1版本，这个问题已经优化。

**Comment by todohuai** [comment]
> @todohuai 请更新到最新2.30.1版本，这个问题已经优化。

已经测试了，导入没问题。非常感谢。
