### ISSUE TITLE
[question] 接口响应值不能通过属性名获取

### ISSUE THREAD

**Issue by valtenhyl** [reqable/reqable-app#1089]
登录接口的token和账号想放到全局环境变量里面，下面是Postman中的脚本
var responseData = JSON.parse(responseBody)
pm.globals.set("token", responseData.data.token)
pm.globals.set("account", responseData.data.currentUser.account)

在Reqable中引入json的依赖，使用json.load(response.body.data) 报错AttributeError: 'HttpBody' object has no attribute 'read'

**Comment by MegatronKing** [comment]
@valtenhyl 您好，不需要引入json依赖，直接使用下面的API：
```
response.body.jsonify()
value = response.body['key']
```
`response.body`会自动转换成字典。

**Comment by valtenhyl** [comment]
```
response.body.jsonify()
print('response.body ' + response.body) 
print('response.body ' + response.body['flag'])
```
![image](https://github.com/user-attachments/assets/76cc7ae3-147c-43c5-915c-085fc56fd6d6)
