### ISSUE TITLE
[bug] MacOS 打开软件立马闪退

### ISSUE THREAD

**Issue by deepinsideDrury** [reqable/reqable-app#1090]
**Describe the bug**
打开立马闪退

**To Reproduce**
打开软件

**Expected behavior**
软件正常打开

**Screenshots**
https://github.com/user-attachments/assets/d8aeaa9b-dd63-4a3a-aa63-b435ff77d8d6

**Information**
 - Platform: macos
 - OS: 15.1 (24B83)
 - Arch: arm
 - App Version: [v2.29.2](https://github.com/reqable/reqable-app/releases/tag/2.29.2)

**Comment by MegatronKing** [comment]
@deepinsideDrury 您好，感谢反馈，请问系统有Crash Report日志吗？

**Comment by deepinsideDrury** [comment]
> @deepinsideDrury您好，感谢反馈，请问系统有崩溃报告日志吗？

崩溃没有像其他软件一样出现崩溃弹窗而是直接没了, 我在控制台日志报告中搜到相关字样
[日志报告.txt](https://github.com/user-attachments/files/17866934/default.txt)

**Comment by MegatronKing** [comment]
> > @deepinsideDrury您好，感谢反馈，请问系统有崩溃报告日志吗？
> 
> 崩溃没有像其他软件一样出现崩溃弹窗而是直接没了, 我在控制台日志报告中搜到相关字样 [日志报告.txt](https://github.com/user-attachments/files/17866934/default.txt)

感谢，但是这个日志报告好像没有有用的信息，我们目前也没有收到这一类闪退问题。可以检查下这几项看看：

- 有没有可能安装错了cpu架构版本，比如m系列安装了x86_64的版本。
- 是否有其他常驻的后台服务影响了，比如输入法辅助工具，之前有用户反馈过这一类因素导致了闪退，可以排查下。
