### ISSUE TITLE
[bug] 导入apipost环境中服务没同步

### ISSUE THREAD

**Issue by lvhjean** [reqable/reqable-app#1091]
**Describe the bug**
apipost工具中存在环境配置；配置分服务或环境变量，导入到reqable中只将环境变量带来了，服务没有相应的处理方案；

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: windows
 - OS: 11
 - Arch: [e.g. arm, x86-64]
 - App Version: 2.29.2（123）

**Comment by MegatronKing** [comment]
@lvhjean 您好，感谢反馈。Reqable没有服务这个概念，你指的是不是数据导入Reqable的时候丢失了URL前缀？

**Comment by lvhjean** [comment]
@MegatronKing 服务是apipost的。我指的就是 apipost数据导入Reqable的时候丢失了URL前缀。

**Comment by MegatronKing** [comment]
@lvhjean 请更新到最新2.30.1版本，这个问题已经优化了。
