### ISSUE TITLE
[question] Unable to capture application traffic in pc

### ISSUE THREAD

**Issue by Abishek6789** [reqable/reqable-app#1092]
The application is running in the background but still it's not being shown in traffic list
>>Windows pc
![IMG_20241119_205648_028](https://github.com/user-attachments/assets/89e5bb92-dcc3-42ad-8247-ba88b50439b7)
The ice application mentioned is not showed in the list

**Comment by MegatronKing** [comment]
@Abishek6789 Hello, not all applications will access the reqable MITM proxy server, but you can use a third-party application such as Proxifier to force forwarding.
