### ISSUE TITLE
[feature] 请求方法筛选和自动选择原先安装的路径

### ISSUE THREAD

**Issue by pansy1110** [reqable/reqable-app#1095]
1.如标题所示，是否可以增加请求`方法`的筛选。理由：有时候只想看一个请求方法的，比如post。这样不会被其他请求方法干扰
![PixPin_2024-11-21_12-06-39](https://github.com/user-attachments/assets/40bd3233-8c52-4e57-bf54-57e10e0ddc5d)
2.还有一个不知道是不是bug，所以也写在功能请求里了。就是在点击更新后，不能`自动选择原先安装的路径`了，我记得以前版本可以`自动选择原先安装的路径`
![PixPin_2024-11-21_11-30-40](https://github.com/user-attachments/assets/ded70edd-527a-4f04-ad05-6c166b39721d)

**Comment by MegatronKing** [comment]
@PShiYou 您好，感谢反馈。

> 1. 如标题所示，是否可以增加请求方法的筛选。

Control + F 搜索里面有请求方法。

> 2. 点击更新后，不能自动选择原先安装的路径了，我记得以前版本可以自动选择原先安装的路径

确实是改了，之前默认是32位的安装路径，现在改成64位了，默认位置会变更，后续安装更新就会自动记住了。

**Comment by pansy1110** [comment]
@MegatronKing 
我尝试了，不能，可能是我没说清楚：抓包（调试）之后显示的这些接口是否可以根据`方法`的筛选
![PixPin_2024-11-21_14-38-44](https://github.com/user-attachments/assets/20649f15-4f9e-4151-9840-7c7dc4a076d6)

**Comment by MegatronKing** [comment]
不是这个吗？

![image](https://github.com/user-attachments/assets/9036f313-ca0e-4d19-b4c1-04b2d619b83c)
