### ISSUE TITLE
[question] 编辑栏字体优化

### ISSUE THREAD

**Issue by NightGlowww** [reqable/reqable-app#1099]
**Describe the question**
A clear and concise description of what the question is.
![image](https://github.com/user-attachments/assets/6a822b3c-cd7f-471d-bdb0-e954cc41d260)

![image](https://github.com/user-attachments/assets/019d5880-8f1a-426b-9efe-df59f8a41e78)
为什么在编辑请求这里的字体那么格格不入呀？是我Windows电脑问题吗？可以不可以自定义或者统一一下字体呢？

**Comment by MegatronKing** [comment]
@NightGlowww 您好，感谢反馈，我们将在下个版本修复。

**Comment by MegatronKing** [comment]
已解决，请更新到最新版本v2.30.1。
