### ISSUE TITLE
[bug] API测试时，修改部分参数后API标签不会实时变更为待保存状态

### ISSUE THREAD

**Issue by DemoJameson** [reqable/reqable-app#1100]
修改API的请求头或者脚本，API标签不会实时变更为待保存状态，另外光标在脚本中时无法按Ctrl+S保存。

**Information**
 - Platform: Windows
 - OS: Windows 11
 - App Version: 2.29.2

**Comment by MegatronKing** [comment]
@DemoJameson  您好，感谢反馈。

> API标签不会实时变更为待保存状态。

出于性能优化考虑，输入内容时不会实时刷新状态。完成输入后（丢失输入焦点），或者通过`Control + S`快捷键才会更新状态。

> 光标在脚本中时无法按Ctrl+S保存

这个bug在新版本2.30.1中已经修复了。

**Comment by DemoJameson** [comment]
> 出于性能优化考虑，输入内容时不会实时刷新状态。完成输入后（丢失输入焦点）

可以理解，不过据我测试“参数”中输入内容会实时刷新状态，是因为更新了 URL 吗

**Comment by MegatronKing** [comment]
对的，因为URL需要实时更新，太显眼了，不更新说不过去，没办法避免。

**Comment by DemoJameson** [comment]
明白了
