### ISSUE TITLE
[feature] 请问是否能增加RapidAPI，也就是曾经的Paw导出的接口文件格式

### ISSUE THREAD

**Issue by NavinChen** [reqable/reqable-app#1102]
使用平台是MacOS，日常使用的工具是Paw，随着接口数量越来越多，这个工具小问题不断，想要导出以后导入Reqable

但发现目前不支持，使用了Paw内置的插件导出为Postman格式，导入Reqable提示没有有效数据，发愁……

**Comment by MegatronKing** [comment]
感谢反馈，你说的是两个问题：

- 导入RapidAPI的接口。
- RapidAPI导出的Postman格式无法导入。

马上处理，下个版本解决应该没问题。

**Comment by NavinChen** [comment]
> 感谢反馈，你说的是两个问题：
> 
> * 导入RapidAPI的接口。
> * RapidAPI导出的Postman格式无法导入。
> 
> 马上处理，下个版本解决应该没问题。

非常感谢

**Comment by MegatronKing** [comment]
已支持Rapid API导出的Postman格式，需要更新到最新版本v2.30.1。
