### ISSUE TITLE
[bug] 抓包提示FormatException: Filter error, bad data

### ISSUE THREAD

**Issue by Cat-zaizai** [reqable/reqable-app#1104]
使用手机协同模式，在某些api获取的时候会出现FormatException: Filter error, bad data
![image](https://github.com/user-attachments/assets/680ad5ee-8b85-4ea4-9cb5-3fb9f02891be)

使用其他抓包软件可以正常获取到data数据
版本2.29.2

**Comment by MegatronKing** [comment]
您好，感谢反馈，下个版本修复。

**Comment by MegatronKing** [comment]
已解决，请更新到最新版本v2.30.1。
