### ISSUE TITLE
抓包获取不到证书错误的https

### ISSUE THREAD

**Issue by Mnoisec** [reqable/reqable-app#111]
![image](https://github.com/reqable/reqable-app/assets/28181883/c5ddea47-053b-4e7e-a492-6fd00c14047d)
对应Fiddler的忽略服务器证书错误功能
我访问部分证书错误的网站时获取不到抓包

**Comment by MegatronKing** [comment]
如果不开reqable，访问网站是不是也有问题，比如证书错误？

**Comment by MegatronKing** [comment]
Reqable默认是不检查服务器证书是否合法的，如果没有其他问题，这个issue我先关闭了。

**Comment by liesauer** [comment]
+1有这个需求，服务器的证书确实是有错的，想着本地绕过去。
