### ISSUE TITLE
[bug] 请求或响应数据单行文本过长且包含unicode会导致严重卡顿

### ISSUE THREAD

**Issue by Jingle-Pan** [reqable/reqable-app#1111]
遇到2M包，解析卡顿甚至导致软件崩溃，希望能优化

**Comment by MegatronKing** [comment]
@Jingle-Pan 您好，2M的数据不算大，理论上没问题。有一种情况，性能比较差，就是2M都在一行里面且显示用word wrap模式，你遇到的是这种情况吗？

**Comment by Jingle-Pan** [comment]
不知道是不是Word wrap模式，选择那条就卡死。用fiddle可以打开，响应内容解析是json，字典里有非常长list，实际包大小2.64M

**Comment by MegatronKing** [comment]
> 不知道是不是Word wrap模式，选择那条就卡死。用fiddle可以打开，响应内容解析是json，字典里有非常长list，实际包大小2.64M

应该不至于，你试试这个呢，3.5M的JSON，我这边测试没有问题：https://github.com/chinese-poetry/chinese-poetry/blob/master/%E5%85%A8%E5%94%90%E8%AF%97/authors.song.json

**Comment by Jingle-Pan** [comment]
> 应该不至于，你试试这个呢，3.5M的JSON，我这边测试没有问题：https://github.com/chinese-poetry/chinese-poetry/blob/master/%E5%85%A8%E5%94%90%E8%AF%97/authors.song.json

打开抓不到这个链接的json大包，变成浏览器下载。我说的情况跟你不一样，选中就卡着，如图
![image](https://github.com/user-attachments/assets/02da4a8d-bde3-4295-88cb-94abaf8d94d2)

![image](https://github.com/user-attachments/assets/cd85eb8a-8b6c-4435-8f82-b85bb3d515cb)

**Comment by Jingle-Pan** [comment]
从刚才回复，到现在大概10分钟，才把响应体打开，观察reqable程序内层占用消耗1.6Gb.（更新图片）
![image](https://github.com/user-attachments/assets/617ca793-35af-40b8-b81e-e2cfd33563ae)

**Comment by MegatronKing** [comment]
> 从刚才回复，到现在大概10分钟，才把响应体打开，观察reqable程序内层占用消耗1.6Gb.（更新图片） ![image](https://private-user-images.githubusercontent.com/75921710/389756906-617ca793-35af-40b8-b81e-e2cfd33563ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDM2NjQsIm5iZiI6MTczMjYwMzM2NCwicGF0aCI6Ii83NTkyMTcxMC8zODk3NTY5MDYtNjE3Y2E3OTMtMzVhZi00MGI4LWI4MWUtZTJjZmQzMzU2M2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA2NDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMzk5OGIxMTAzYzUwM2RmMGE4NDExZTM1NmE0ZGNjZTFjNWJkNTZlYjQwZWNjZGFmNWNjN2I0NmI3YWVjZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QHA6nUD8PwqdHpch4bx2CmXHrmg2E2QsJuOOKz5Y9aY)

这个太不正常了。

怀疑是不是和具体内容有关，能否提供下这个请求地址我这边测试下？如果不方便提供地址，可以提供下这个JSON内容（关键字段可以脱敏）？

**Comment by flon-chou** [comment]
<img width="510" alt="image" src="https://github.com/user-attachments/assets/0b6e6310-4853-494c-9638-f3c184ad1217">
<img width="697" alt="image" src="https://github.com/user-attachments/assets/0c1188d1-87b6-4b94-aaeb-8d46fd920b45">
我也遇到这个情况，我的响应体，压缩后还有1.7M，解压状态下时11M多，然后打开响应体就会卡死，CPU几乎被占满了。

**Comment by MegatronKing** [comment]
@flon-chou 请问能方便提供测试地址吗？如果不方便在这里公开，可以发送到我们邮箱 coding@reqable.com

**Comment by Jingle-Pan** [comment]
@MegatronKing 已发邮件

**Comment by MegatronKing** [comment]
感谢，已定位到问题原因。倒不是数据处理的问题，而是因为单行文本过长，Flutter框架的文字排版引擎skia文字处理性能奇差，直接卡死了。

**Comment by Jingle-Pan** [comment]
> 感谢，已定位到问题原因。倒不是数据处理的问题，而是因为单行文本过长，Flutter框架的文字排版引擎skia文字处理性能奇差，直接卡死了。

好的，定位到问题，找优化方案

**Comment by MegatronKing** [comment]
另一个原因好像是和里面包含Unicode有关，测试了3M的单行JSON不包含`\u`而是中文的情况下，也就是卡顿3s左右。skia引擎在处理unicode的时候在本来性能不高的情况下变得更差了，可能是踩到什么坑里面了。

**Comment by Jingle-Pan** [comment]
> 另一个原因好像是和里面包含Unicode有关，测试了3M的单行JSON不包含`\u`而是中文的情况下，也就是卡顿3s左右。skia引擎在处理unicode的时候在本来性能不高的情况下变得更差了，可能是踩到什么坑里面了。

能否先将unicode转换为utf-8，再用skia渲染

**Comment by MegatronKing** [comment]
@Jingle-Pan @flon-chou  您好，请更新2.30.2试试，卡顿已优化。

**Comment by Jingle-Pan** [comment]
> @Jingle-Pan @flon-chou  您好，请更新2.30.2试试，卡顿已优化。

测试OK，赞

**Comment by MegatronKing** [comment]
感谢测试。
