### ISSUE TITLE
客户端SSL握手失败

### ISSUE THREAD

**Issue by charley008** [reqable/reqable-app#1112]
家里更新app store总是会非常慢，想抓包看看啥情况，但是发现 抓不到包，总是提示客户端ssl握手失败，用的是ios 版reqable。
![image](https://github.com/user-attachments/assets/40351fc4-2955-45ca-b309-f26a41b49125)
![image](https://github.com/user-attachments/assets/27552b71-2993-41ce-9419-df63ea7eb917)

**Comment by MegatronKing** [comment]
apple所有相关的域名都是固定证书，无法抓包。
