### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by jinsc123** [reqable/reqable-app#1118]
**Describe the bug**
API测试中授权选择Bearer Token ，无法填写

**To Reproduce**
1、API测试 
2、授权  
3、选Bearer Token 后，无法填写token，没有任何地方可填写，也无法切换其他方式

**Expected behavior**
应该有地方可以填写token值

**Screenshots**
![image](https://github.com/user-attachments/assets/680c3bbf-d219-4b48-a59a-1eca84b7b524)

**Information**
 - Platform: windows
 - OS: win11专业版23H2
 - Arch:  x86-64
 - App Version: 2.30.0

**Comment by MegatronKing** [comment]
@jinsc123 您好，已解决，更新下版本v2.30.1看看。
