### ISSUE TITLE
请问是否支持FD中Free Http插件类似的功能

### ISSUE THREAD

**Issue by OwnerCM** [reqable/reqable-app#112]
请问是否支持FD中Free Http插件类似的功能，下载使用了一下，可能还不熟悉没找到类似功能

**Comment by MegatronKing** [comment]
可以参阅Reqable的文档：https://reqable.com/docs/capture/
如果你熟悉python，脚本可以实现绝大多数功能：https://reqable.com/blog/2023/06/12/post

**Comment by MegatronKing** [comment]
如果没有其他具体的问题，这个issue我先关闭了。
