### ISSUE TITLE
[bug] 中文字符导致崩溃

### ISSUE THREAD

**Issue by rxbit** [reqable/reqable-app#1120]
**Describe the bug**
API调试中误输入了全角：就崩了

**To Reproduce**
![image](https://github.com/user-attachments/assets/d958253b-f420-4129-9397-7dfe808bf926)

**Expected behavior**
不崩溃

**Information**
 - Platform: macos
 - OS: 15.1
 - Arch: arm
 - App Version: 2.30.1

**Comment by MegatronKing** [comment]
@rxbit 您好，感谢反馈，能够复现，下个版本修复。

**Comment by MegatronKing** [comment]
您好，请更新2.30.2，问题已修复。
