### ISSUE TITLE
[feature] 新版本的JSON树希望在添加一个小功能

### ISSUE THREAD

**Issue by xuxu777xu** [reqable/reqable-app#1121]
目前右键有复制键，复制值，在搜索的时候可以搜索关键词，真很棒！希望可以再加一个右键生成JSON Path到剪辑版或者显示出JSON Path。麻烦了，希望能够采纳！

**Comment by MegatronKing** [comment]
@xuxu777xu 您好，感谢建议。请问是需要 `/data/0/items/0/url` 这种还是 `$.data[0].items[0].url` 这种？

**Comment by xuxu777xu** [comment]
您好，感谢您听取我的建议，希望是/data/0/items/0/url这种。这样我就不用再借助其他工具获取JSON Path了。希望reqable越来越好！！！

**Comment by MegatronKing** [comment]
> 您好，感谢您听取我的建议，希望是/data/0/items/0/url这种。这样我就不用再借助其他工具获取JSON Path了。希望reqable越来越好！！！

问题不大，下个版本我顺手加上。

**Comment by xuxu777xu** [comment]
> > 您好，感谢您听取我的建议，希望是/data/0/items/0/url这种。这样我就不用再借助其他工具获取JSON Path了。希望reqable越来越好！！！
> 
> 问题不大，下个版本我顺手加上。

谢谢

**Comment by MegatronKing** [comment]
@xuxu777xu 您好，请更新2.30.2，已实现。

**Comment by xuxu777xu** [comment]
@MegatronKing  好的    已经更新  辛苦啦~
