### ISSUE TITLE
[bug] idea Sync gradle project总是失败

### ISSUE THREAD

**Issue by sagasm** [reqable/reqable-app#1122]
**Describe the bug**

**To Reproduce**
1. reqable 设置socket5代理, 端口8888
2. idea设置socket代理, 端口8888
3. 新建一个plugin示例工程.
4. 执行Sync gradle project失败, 不能下载文件.
**Expected behavior**
能够其他代理一样正常执行Sync gradle project

**Screenshots**
![image](https://github.com/user-attachments/assets/5c43cc29-2f02-4884-b8b2-8161df90d96a)

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: win10 x64 22h2
 - Reqable: 2.30.1

**Comment by MegatronKing** [comment]
@sagasm 您好，点开看看详情呢，显示什么错误？

**Comment by sagasm** [comment]
请问是id 840这条的详情么?  
![image](https://github.com/user-attachments/assets/a7371661-f499-44f4-8f2f-e49aed1aa002)

我猜测这条记录是查询镜像服务器, 但是不知道为什么没有返回数据. 但是用API调试功能是有返回数据的

**Comment by MegatronKing** [comment]
@sagasm 您好，能否提供下日志。

1. 打开电脑端Reqable设置，开启调试日志。
2. 复现下问题。
3. 点击Reqable底部栏5下，打开日志窗口，（复制）保存日志内容。
4. 日志内容脱敏（如果有必要的话）。
5. 关闭设置中调试日志开关，打开日志会影响调试性能。

**Comment by sagasm** [comment]
[reqable.log](https://github.com/user-attachments/files/17926801/reqable.log)

**Comment by sagasm** [comment]
我的本意:
Sync gradle project过程中有几个大文件特别难下, 我就想先用下载工具把难下的先下下来, 然后开启reqable的镜像功能, 把难下的文件从本地下载

**Comment by MegatronKing** [comment]
> 我的本意: Sync gradle project过程中有几个大文件特别难下, 我就想先用下载工具把难下的先下下来, 然后开启reqable的镜像功能, 把难下的文件从本地下载

看日志是因为ide发送的网络请求用的非系统的CA Store，证书没法信任。找到一个Fiddler相关的[文章](https://medium.com/@siddhartha.khare/how-to-capture-intellij-traffic-through-fiddler-8c69d1f6d080)，对Reqable也是适用的。

- 在Reqable的`证书` - `根证书管理` - `导出根公钥证书(.pem)`。
- 用`keytool`生成keystore。
- 配置keystore到ide中。

**Comment by sagasm** [comment]
谢谢, 按照这个思路, 再把证书导入java, 已经实现我的要求了.
