### ISSUE TITLE
[bug] SSE消息显示异常

### ISSUE THREAD

**Issue by sisi0318** [reqable/reqable-app#1126]
**Describe the bug**
SSE 消息无法正常解析

**To Reproduce**
自主请求流式消息
[正常的响应体.txt](https://github.com/user-attachments/files/17929768/default.txt)

**Expected behavior**
正常解析

**Screenshots**
![Snipaste_2024-11-27_13-54-17](https://github.com/user-attachments/assets/e8cb4e3d-1de4-4f58-9f61-ffef88df57cd)
![Snipaste_2024-11-27_13-57-29](https://github.com/user-attachments/assets/fae2c3d6-7f23-46ee-897d-e41ff5bfaa8f)
![Snipaste_2024-11-27_13-57-54](https://github.com/user-attachments/assets/25991a34-85ff-4bff-bc1d-a71031f68213)

**Information**
 - Platform: windows
 - OS: win11
 - Arch: x86-64
 - App Version: 2.30.1

**Comment by MegatronKing** [comment]
@sisi0318 了解，原来还有用非标准SSE结构的数据。

**Comment by sisi0318** [comment]
> @sisi0318 了解，原来还有用非标准SSE结构的数据。

非标准结构的还是挺多的哈哈

**Comment by MegatronKing** [comment]
已经处理，等下个版本发布。

**Comment by MegatronKing** [comment]
@sisi0318 您好，请更新2.30.2试试，问题已修复。
