### ISSUE TITLE
[bug] mac mini M1闪退

### ISSUE THREAD

**Issue by tjcfnerd** [reqable/reqable-app#113]
**Describe the bug**
mac mini M1闪退

**To Reproduce**
黄鸟图标呈现2-3秒后软件窗口消失，无任何提示

**Screenshots**
<a href="https://imgse.com/i/pC49kn0"><img src="https://s1.ax1x.com/2023/07/13/pC49kn0.png" alt="pC49kn0.png" border="0" /></a>

**Information**
 - Platform: [macos]
 - OS: [13.4.1 (22F82)]
 - Arch: [Apple M1]
 - App Version: [1.1.1]

**Comment by MegatronKing** [comment]
可以加您微信沟通下吗？或者加我微信king20091305035

**Comment by MegatronKing** [comment]
v1.1.3已正式修复。
