### ISSUE TITLE
[bug] 启用重定向 URL 后调式窗口内显示的 URL 缺少了部分内容

### ISSUE THREAD

**Issue by DemoJameson** [reqable/reqable-app#1132]
重定向规则为
URL: `https://hello.com/api/*`
重定向到: `http://localhost:8080/*`

调试窗口显示的 URL 变化
启用重定向前的请求: `https://hello.com/api/login`
启用后的请求: `https://hello.com/login`

**Information**
 - Platform: Windows
 - OS: Windows 11
 - App Version: 2.30.1

**Comment by MegatronKing** [comment]
@DemoJameson 您好，感谢反馈，已复现问题。

**Comment by MegatronKing** [comment]
您好，请更新2.30.2，问题已修复，现在会显示重定向后的域名。
