### ISSUE TITLE
[feature] 希望在集合的目录中加入公共参数

### ISSUE THREAD

**Issue by tyh97** [reqable/reqable-app#1135]
集合里目录下的请求一般都是同一类的，请求头这些很多都是一样的，在新增请求的时候，每次都需要重新设置请求头或者是授权。

希望在目录上可以统一设置当前目录下请求的请求头或授权等配置。而且支持继承父目录的配置，如果子目录/子请求配置了相同的配置，则覆盖父级的配置。

类似的功能在apiPost上有，感觉可以参考下，增加易用性

**Comment by MegatronKing** [comment]
同 #887
