### ISSUE TITLE
[bug] GetSystemMetricsForDpi

### ISSUE THREAD

**Issue by jihymood** [reqable/reqable-app#1136]
![image](https://github.com/user-attachments/assets/e31eaa75-fb7f-4667-8f5e-f91fcf7f58f9)
系统：win7
版本：2.30.1
启动win7桌面应用报错

**Comment by jihymood** [comment]
难道就没有替代品了吗，非得让我继续用apipost了，要不是apipost启动太慢也不会找新的调试工具

**Comment by MegatronKing** [comment]
@jihymood 试试这个版本：https://github.com/reqable/reqable-app/releases/tag/2.29.2

**Comment by MegatronKing** [comment]
@jihymood 您好，请更新2.30.2，问题已修复。
