### ISSUE TITLE
[feature] 增加自动生成 tesing 的功能

### ISSUE THREAD

**Issue by penn201500** [reqable/reqable-app#1138]
**Is your feature request related to a problem? Please describe.**
类似于 rapidapi 的 generate test 的功能：

![image](https://github.com/user-attachments/assets/f27fa3ef-e9b1-4bb8-a707-43775d11b4af)

![image](https://github.com/user-attachments/assets/9ebfa086-5da9-46cd-9c72-ef47fcc2669e)

修改数据或者重新发送请求，可以看到是否 PASS。效果类似于开发代码的时候 ‘单元测试'。 在切换功能分支，或者多人协作（或使用从其他那里导入的数据）的时候很有用

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
@penn201500 您好，感谢建议，同 #263
