### ISSUE TITLE
[feature] UI: 建议将选中项在侧边栏中高亮

### ISSUE THREAD

**Issue by penn201500** [reqable/reqable-app#1139]
**Is your feature request related to a problem? Please describe.**

Dark 模式下，建议将选中项在 F2 集合的侧边栏中高亮；当前选中效果无法分辨，如图所示，选中了 logout，侧边栏区分不出来
![image](https://github.com/user-attachments/assets/ef7fe869-6727-458f-9937-e81c96a780af)

这个是rapidapi的效果：

![image](https://github.com/user-attachments/assets/a56721c7-22c1-4207-9064-fc954a3376a4)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by penn201500** [comment]
补充：
F1， 工作台中选中项可以高亮：
![image](https://github.com/user-attachments/assets/64f3a6f8-6796-4409-917e-b202cc8d1977)

**Comment by MegatronKing** [comment]
同 #1127
