### ISSUE TITLE
[feature] 导入 swagger 格式的集合，<<host>> 只替换 ip:port 部分即可，不建议将 basePath 部分也一并替代

### ISSUE THREAD

**Issue by penn201500** [reqable/reqable-app#1140]
**Is your feature request related to a problem? Please describe.**
接
https://github.com/reqable/reqable-app/issues/625
导入 swagger 格式的合集：
![image](https://github.com/user-attachments/assets/b474253b-ca00-414c-a622-a1e4c09fe8f1)
将 `  "basePath": "/api",` 这部分也一并替换了

其对应的文档部分是：
{
  "swagger": "2.0",
  "info": {
    "title": "xxxxtestAPI.paw",
    "version": "v0.0.0"
  },
  "host": "127.0.0.1:8000",
  "schemes": [
    "http"
  ],
  "basePath": "/api",
  "paths": {
    "/token/refresh/": {
      "post": {
....

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
@penn201500 感谢建议，下个版本优化。

**Comment by MegatronKing** [comment]
您好，请更新2.30.2，问题已修复。
