### ISSUE TITLE
安卓最新版抓https失败，更换ssl证书不成功

### ISSUE THREAD

**Issue by dfjdlfjdlfjdl** [reqable/reqable-app#1141]
昨天那个问题描述错误，我重新修改下
我手机没有root，我就安装个vmos虚拟机，里面装了个root 安卓7，因为vmos虚拟机不支持vpn，所以我的reqable是安装在物理手机上的，导出的安卓证书，我就放到这个虚拟机的系统证书文件夹里面。截图可以看到ssl证书没有替换成reqable。
相同操作，用httpcanary就是可以的

**Comment by MegatronKing** [comment]
@dfjdlfjdlfjdl 您好，respond空空如也的界面截个图看看呢？

**Comment by dfjdlfjdlfjdl** [comment]
![5bd7d0c715cac7576398690f44b6143c](https://github.com/user-attachments/assets/51cffabf-ca6c-4a0a-bb06-244c90107f79)
![Screenshot_20241130_010530_com vmos pro](https://github.com/user-attachments/assets/d32fe97a-6420-4cea-b1c1-c3f2feaf39d6)
![Screenshot_20241130_010607_com reqable android](https://github.com/user-attachments/assets/107f02ac-4ca1-4abf-a5a9-e541a7b916eb)
![Screenshot_20241130_010614_com reqable android](https://github.com/user-attachments/assets/e3b79064-60bd-4fa5-83b2-65d967cd8a33)

**Comment by dfjdlfjdlfjdl** [comment]
> @dfjdlfjdlfjdl 您好，respond空空如也的界面截个图看看呢？

你好，我修改了问题，你有空看下，安装的是最新版reqable

**Comment by Mabciyptyl** [comment]
@dfjdlfjdlfjdl 请问这个问题后来解决了吗？我用最新版也遇到了这个问题。
