### ISSUE TITLE
[bug] 导入postman环境变量提示  未发现有效的数据

### ISSUE THREAD

**Issue by Ineffable919** [reqable/reqable-app#1144]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@Ineffable919 您好，请更新2.30.2，问题已修复。
