### ISSUE TITLE
响应体搜索出现扫描跳动

### ISSUE THREAD

**Issue by Jingle-Pan** [reqable/reqable-app#1153]
输入搜索关键词，连续点几下就会出现窗口内的文字无限循环扫描跳动

**Comment by MegatronKing** [comment]
@Jingle-Pan 您好，感谢反馈，请问能否提供个截图或者录屏？

**Comment by Jingle-Pan** [comment]
请查收附件






---- 回复的原邮件 ----
| 发件人 | Megatron ***@***.***> |
| 日期 | 2024年12月02日 17:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [reqable/reqable-app] 响应体搜索出现扫描跳动 (Issue #1153) |

@Jingle-Pan 您好，感谢反馈，请问能否提供个截图或者录屏？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

从 网易邮箱大师 发来的云附件
|
| |
| |
|
| |
| VID_20241201_141536.mp4 |
| |
| (15.5M,2024年12月17日 18:18 到期) |
| |
| 下载 |
| |
| |

**Comment by MegatronKing** [comment]
直接回复Github附件好像不行，能否发送到邮箱 coding@reqable.com

**Comment by Jingle-Pan** [comment]
***@***.***



---- 回复的原邮件 ----
| 发件人 | Megatron ***@***.***> |
| 日期 | 2024年12月02日 18:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [reqable/reqable-app] 响应体搜索出现扫描跳动 (Issue #1153) |

直接回复Github附件好像不行，能否发送到邮箱 ***@***.***

**Comment by MegatronKing** [comment]
感谢提供资料，问题已确认，尽快修复。

**Comment by MegatronKing** [comment]
v2.30.3版本已修复。
