### ISSUE TITLE
[bug] cannot delete collection data, environment

### ISSUE THREAD

**Issue by longzhihua** [reqable/reqable-app#1159]
**Describe the bug**
my device is mac book pro M1.  I import data from postman,  than , I cannot delete them.

**Information**
 - Platform: [e.g. macos ]
 - OS: [e.g. 13.2.1 (22D68)]
 - Arch: [e.g. arm]
 - App Version: [e.g. 13.2.1 (22D68)]

**Comment by MegatronKing** [comment]
@longzhihua Hello, have you tried right-click menu? There is a `Delete` option.
