### ISSUE TITLE
[feature] 请求测试功能中，增加参数启用禁用勾选项

### ISSUE THREAD

**Issue by NavinChen** [reqable/reqable-app#1164]
举例：RapidAPI的JSON请求方式中，支持指定的参数禁用
如同名参数，值不同
userId: 123
userId: 456
userId: 789
可以把其中部分字段禁用，否则每次只能弄最后一次请求的值，不够用

**Comment by MegatronKing** [comment]
@NavinChen 您好，感谢建议。JSON要做结构化编辑就太复杂了，建议试试环境变量。

```json
{
  "foo": "<<foo>>"
}
```

在不同的环境中配置不同的`foo`值，不需要更改数据，只需要切换环境变量了。
