### ISSUE TITLE
[bug] 导入postman集合 (type 'String' is not a subtype of type 'int' of 'index')

### ISSUE THREAD

**Issue by xiaohongxiedaima** [reqable/reqable-app#1167]
![image](https://github.com/user-attachments/assets/b65e2ed1-a95a-4729-9463-6dbf543d7424)![image](https://github.com/user-attachments/assets/f733c541-010a-40db-9cb8-4d41925491fd)

**Comment by MegatronKing** [comment]
@xiaohongxiedaima 您好，感谢反馈，能否提供下日志信息。

1. 复现下问题。
2. 点击底部栏5下，打开日志窗口，复制下报错日志。

**Comment by MegatronKing** [comment]
@xiaohongxiedaima 看起来像是不支持Postman v2格式，更新Reqable到v2.30.3版本试试，我们已经做了处理。
