### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by Jesn** [reqable/reqable-app#1170]
通过重发，点击请求是可以的，但是通过编辑点击请求就403，请问什么原因？

![image](https://github.com/user-attachments/assets/c8e4b2aa-b410-4a96-b273-139782d17217)

![image](https://github.com/user-attachments/assets/d21ebcc6-3e56-4757-8e66-101f2ec5569d)

**Comment by MegatronKing** [comment]
@Jesn 你用diff功能对比下：https://reqable.com/zh-CN/docs/capture/diff

**Comment by Jesn** [comment]
> @Jesn 你用diff功能对比下：https://reqable.com/zh-CN/docs/capture/diff

好的，找到问题了
