### ISSUE TITLE
[bug] 导入postman环境变量出错

### ISSUE THREAD

**Issue by cs12110** [reqable/reqable-app#1175]
**Describe the bug**

从postman导出环境变量json,导入reqable-app报错.

如果postman环境变量不使用下划线,而是使用`-`,例如环境变量名称为: 'a-b-c',而不是`a_b_c`.

**To Reproduce**

1. 从postman导出环境变量json,json里面的参数是`a-b-c`格式,而不是`a_b_c`
2. reqable-app会提示该变量参数非法.

**Expected behavior**

支持`a-b-c`格式,从postman导出,不需要进行修改就可以导入app使用.

**Screenshots**

<img width="538" alt="image" src="https://github.com/user-attachments/assets/0b57d5d3-4ad3-40be-a2c3-24524b6ecae8">

**Information**
 - Platform:  macos
 - OS: 12.2.1
 - Arch: intel
 - App Version:2.30.3

**Comment by MegatronKing** [comment]
@cs12110 您好，感谢反馈。变量名需要遵从常规的变量命名约定，我们后面会直接支持`env.foo_bar`这种调用而不需要`env['foo_bar']`这种写法，如果不遵从变量名称约定，这个无法实现。所以，这边建议你手动修改下。

**Comment by cs12110** [comment]
好的,谢谢. :"}

还有就是能支持批量导入没?
