### ISSUE TITLE
When will reqable Android version will come??

### ISSUE THREAD

**Issue by arpitdayma** [reqable/reqable-app#118]
Sir i am waiting for reqable Android version please make it as soon as possible and i want to know what features it will carry means it will have script editor, response redirect option in it???

**Comment by Natsume-C** [comment]
It will be established in September.

**Comment by MegatronKing** [comment]
I am still working on desktop platform now. About mobile platform, there is no definite development time yet.

**Comment by MegatronKing** [comment]
Please follow this issue: #71
