### ISSUE TITLE
[bug] 搜索功能无效

### ISSUE THREAD

**Issue by kwdiwt** [reqable/reqable-app#1183]
**Describe the bug**
搜索功能无效？

**To Reproduce**
看图，搜索后回车，啥也没有，但响应体里有文字

**Expected behavior**

**Screenshots**
<img width="1416" alt="image" src="https://github.com/user-attachments/assets/1831faa0-b2bc-42a5-8d42-909538b2e2fe">

**Information**
 - Platform: [macos]
 - OS: [14.4.1 (23E224)]
 - Arch: [arm]
 - App Version: [2.30.3 (127)]

**Comment by MegatronKing** [comment]
@kwdiwt 看看raw里面中文是不是unicode，如果是unicode启用下输入框后面深度搜索选项。

**Comment by kwdiwt** [comment]
> @kwdiwt 看看raw里面中文是不是unicode，如果是unicode启用下输入框后面深度搜索选项。

噢，了解了，原来预览界面的文字经过转码的。多谢
