### ISSUE TITLE
[feature] api接口和调试工具增加保存响应内容

### ISSUE THREAD

**Issue by jinshuqishi2019** [reqable/reqable-app#1188]
api接口可否增加保存响应内容。

调试工具也没有收藏响应内容的方法，只能导出保存，对于请求可以编辑然后保存在api集合中。

目的是为了方便比较不同时间响应内容和使用响应内容中的数据。

**Comment by hml044578** [comment]
支持改功能，类似软件apipost有这个功能，希望可以参考一下。

**Comment by MegatronKing** [comment]
您好，感谢建议，需求同 #924
