### ISSUE TITLE
[bug] 不能开启系统代理

### ISSUE THREAD

**Issue by 1021543442** [reqable/reqable-app#1198]
**Describe the bug**
系统代理一直不能开启，点击变绿之后几秒后又变成黄色的图标

**To Reproduce**

3. See error

**Expected behavior**

**Screenshots**
![bug](https://github.com/user-attachments/assets/ce0c681b-30d5-46a6-b70d-f80a032a8b25)
**Information**
 - Platform: macos，m4芯片
 - OS: 15
 - Arch: arm
 - App Version: 2.30.3（arm64）

**Comment by hehe1874** [comment]
可以安装代理辅助工具后，再试试开启代理
<img width="310" alt="image" src="https://github.com/user-attachments/assets/95738826-8825-47e9-89be-ca52ba03cf87" />
