### ISSUE TITLE
[feature] 能否能增加集合环境变量

### ISSUE THREAD

**Issue by hehe1874** [reqable/reqable-app#1200]
现在创建的环境变量实际还是属于全局环境变量，对于习惯使用集合来区分项目的人来说，多个项目可能会存在多个命名相同的环境变量。增加集合变量，这样使用起来会更方便。
Bruno 效果
<img width="275" alt="image" src="https://github.com/user-attachments/assets/1ea82213-228e-49c3-b408-602d2b8174ce" />

**Comment by MegatronKing** [comment]
@hehe1874 您好，感谢建议，需求合并到 #887
