### ISSUE TITLE
http 访问可以捕获请求吗，还有微信里的网页 也没捕获成功

### ISSUE THREAD

**Issue by zy5651768** [reqable/reqable-app#121]
请教捕获的原理是什么 为什么捕获不了 如图 我访问我自己的一个网址 变成微软的请求了
![1689835333347](https://github.com/reqable/reqable-app/assets/16420091/802663b3-0b9e-4dd0-9c5c-fd3f56d748a5)

**Comment by MegatronKing** [comment]
@zy5651768 看看系统设置 代理 里面是不是把localhost排除了？

**Comment by MegatronKing** [comment]
v1.1.3已支持捕获localhost请求

**Comment by MegatronKing** [comment]
如果没有这个问题，我先关闭了这个issue了。
