### ISSUE TITLE
[bug] 网络限制功能无法正常使用

### ISSUE THREAD

**Issue by LoveStudyJS** [reqable/reqable-app#1212]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@LoveStudyJS 您好，感谢反馈。请告知下你想实现什么功能，操作步骤是什么，预期是什么，实际是什么。

**Comment by MegatronKing** [comment]
@LoveStudyJS 由于没有进一步的信息补充，这个issue我关掉了，如果有补充信息请再打开。
