### ISSUE TITLE
[feature] 调用后建议能给出耗时统计的标签

### ISSUE THREAD

**Issue by magical1989** [reqable/reqable-app#1218]
可以给出一个耗时统计的概要，而不是一定要点击性能才能看到整体耗时的统计，这个操作能方便很多
<img width="637" alt="image" src="https://github.com/user-attachments/assets/5362c0ee-b8c0-4731-891a-1d6993d5763d" />

**Comment by MegatronKing** [comment]
@magical1989 您好，感谢建议。

这个问题其实考虑过，但是是否需要直接显示耗时信息仍然值得商榷。大部分用户都是关心数据不关注性能，所以性能是一个偏小众功能，直接显示出来对大部分用户来讲增加了信息冗余度失去了简洁性。另外，很多用户习惯于用左右布局，tab部分的显示空间更是有限，可能没有合适的地方加入。

**Comment by magical1989** [comment]
> @magical1989 您好，感谢建议。
> 
> 这个问题其实考虑过，但是是否需要直接显示耗时信息仍然值得商榷。大部分用户都是关心数据不关注性能，所以性能是一个偏小众功能，直接显示出来对大部分用户来讲增加了信息冗余度失去了简洁性。另外，很多用户习惯于用左右布局，tab部分的显示空间更是有限，可能没有合适的地方加入。

感谢您的回复，这个可能是个人习惯性问题了。
