### ISSUE TITLE
[bug] win7 旗舰版无法正常使用

### ISSUE THREAD

**Issue by yeluo1** [reqable/reqable-app#1219]
无法定位程序输入点 EventSetInformation 于动态链接库 ADVAPI32.dll 上。

系统版本：windows 7 旗舰版 Service Pack 1
程序版本：2.30.3

![屏幕截图 2024-12-16 145648](https://github.com/user-attachments/assets/a3284afe-51dd-405a-8976-1d6c95ba80c6)

**Comment by MegatronKing** [comment]
@yeluo1 您好，感谢反馈。

需要打个补丁：https://www.microsoft.com/zh-cn/download/details.aspx?id=48636

**Comment by yeluo1** [comment]
> @yeluo1 您好，感谢反馈。
> 
> 需要打个补丁：https://www.microsoft.com/zh-cn/download/details.aspx?id=48636

打完补丁可以正常使用了，感谢
