### ISSUE TITLE
[bug]  脚本编辑器 脚本控制台全选复制bug

### ISSUE THREAD

**Issue by lee003** [reqable/reqable-app#123]
脚本控制台，如果日志长度超过了当前屏幕了，出现滑动条的情况下  ctrl + A 只能复制到当前显示的日志。

**Comment by MegatronKing** [comment]
感谢反馈。这个问题是Flutter SelectionArea组件的已知bug，目前没有办法修复。有一个可行方案就是重做控制台的文本组件，但是工作量较大，难以安排，这个问题我只能先放一放了。

**Comment by MegatronKing** [comment]
@lee003 脚本控制台重做了，这个问题应该已经修复。
