### ISSUE TITLE
[feature] 黑暗模式下UI不明显,以及上边部分无法resize

### ISSUE THREAD

**Issue by Faserr** [reqable/reqable-app#124]
黑暗模式下很难区分窗口边界, 黑暗模式下的分界线应该是亮色的.
![image](https://github.com/reqable/reqable-app/assets/46740335/e0103edc-bbc7-44c5-8582-c3632606180d)

另外就是窗口上边缘部分无法重新调整窗口大小(这个截图不到), 我这边一打开应用就长度盖到任务栏了, 我没办法调整它. 只能全屏状态下使用才能体验到完整UI
![image](https://github.com/reqable/reqable-app/assets/46740335/956f06c3-6b1f-450a-bbed-dda62e7d72d1)

**Comment by MegatronKing** [comment]
您好，感谢反馈。

> 黑暗模式下很难区分窗口边界, 黑暗模式下的分界线应该是亮色的。

我在Win10下没有复现这个问题，不知道您的系统版本是？

> 窗口上边缘部分无法重新调整窗口大小(这个截图不到)

这是个已知问题，见这个issue #10 

> 我这边一打开应用就长度盖到任务栏了

刚打开应用的时候，窗体应该是屏幕居中的。你的意思是窗体的高度超过了屏幕的高度吗？

**Comment by Faserr** [comment]
> 我在Win10下没有复现这个问题，不知道您的系统版本是？
我使用的是WIN10-LTSC这个应该不是bug. 我的描述可能有些问题: 就是窗口都有个描边, 令窗口看起来更层次分明, 但是黑暗模式下由于描边是黑色的导致和背景的区分度很差, 感觉改成偏白的会更好.

> > 我这边一打开应用就长度盖到任务栏了
> 刚打开应用的时候，窗体应该是屏幕居中的。你的意思是窗体的高度超过了屏幕的高度吗？
是的, 不过这个应该是我之前用旧版拉伸导致的问题, Win记住了窗口大小导致的, 然后由于那个"窗口上边缘部分无法重新调整窗口大小"问题无法调整窗体height导致用起来比较难受.
