### ISSUE TITLE
[bug] 响应内容截断

### ISSUE THREAD

**Issue by An-Jhon** [reqable/reqable-app#1247]
**Describe the bug**
请求返回的响应内容被截断

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/ebc4cb27-5920-4c70-a381-2d6b46545427)

**Information**
 - Platform: [macos]
 - OS: [13]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@An-Jhon 您好，这个是设计如此，数据太长了渲染会卡UI，超过32k长度会自动截断用...替换，如果你需要看完整数据请保存后用文本查看软件处理。
