### ISSUE TITLE
[feature] 交互优化建议

### ISSUE THREAD

**Issue by Faserr** [reqable/reqable-app#125]
用了一段时间很好上手! 对于UI方面有一些小小的建议, 就是相比传统的开发貌似很多控件都是不太符合主流控件交互习惯的, 体验了一下目前感觉比较明显的类比如下:

## 菜单栏

_参考可见大多数拥有顶部菜单栏的原因, 如 Visual Code_

菜单栏当任意一个处于激活状态时, 鼠标移动到其他项时应将激活项改变为到光标所在项.

![image](https://github.com/reqable/reqable-app/assets/46740335/0c7d0472-4aae-471a-8568-4e71766062a7)

## 小工具处的编码解码

_以下以Base64为举例_

### 选项控件

单选按钮 应与 Lable共享点击事件, 单选按钮不好点, Lable浪费了交互空间. 并且感觉可以移动到中间 字符编码 的位置更顺手.

对于类似右下角的"执行"按钮, 使用文字作为按钮对于直觉有些不符, 加个边框/颜色/淡色都是不错的.

### 交互触发

编码解码对于短一些的文本其实直接自动解码比较好, 比如说可以512字符内自动解码, 或者说检测到粘贴动作引出的字符就自动执行,这 对性能的影响 和 多一步无用的交互 相比我想是比较值得的. 当然要是有开关对于大多数用户那肯定是更好的.

![image](https://github.com/reqable/reqable-app/assets/46740335/ae47c767-858b-4e8c-8f1c-98d5a4d736d6)

**Comment by MegatronKing** [comment]
您好，感谢建议和反馈。

1. 菜单栏的交互是已知问题，参考这个issue：#97
2. 单选按钮 应与Lable共享点击事件，这个马上优化。
3. 移动到中间 字符编码 的位置更顺手，这个我考虑下，位置可能有点仁者见仁智者见智。
4. 编码解码对于短一些的文本其实直接自动解码比较好，这个有道理，应该要自动解码的。

**Comment by Faserr** [comment]
辛苦!

> 3. 移动到中间 字符编码 的位置更顺手，这个我考虑下，位置可能有点仁者见仁智者见智。

确实是每个人的习惯不同, 这个建议是从一些操作习惯上综合看来中间是重合度比较高的位置.
_( 以下是"为什么要提出这条建议"的解释, 供予参考, 并非需求 XD )_
从鼠标轨迹: "编码"框起始 -> "结果"框结束.
从交互逻辑: 输入原始编码 -> 选择 操作模式 -> 复制结果


> 4. 编码解码对于短一些的文本其实直接自动解码比较好，这个有道理，应该要自动解码的。


个人感觉上 "或者说检测到粘贴动作引出的字符就自动执行" 在效率和可行性看来是比较现实的, 
因为感觉不会有人手动输入这些编码后的文本(当然除了用于"编码"动作). 像Md5这种没有解码的就可以不需要考虑动作问题了, 粘贴即编码.



> 用于补充解释, 不用回复 :)

**Comment by yareta2324** [comment]
软件字体大小调整功能缺失

**Comment by MegatronKing** [comment]
@yareta2324 字体大小功能见 #175

**Comment by MegatronKing** [comment]
这个Issue我将关掉了，大部分都已经实现。关于自动编解码的问题，后续请关注这里：#272
