### ISSUE TITLE
解析手机抓取的har文件失败

### ISSUE THREAD

**Issue by zdone** [reqable/reqable-app#126]
你好，我用手机抓取的包，导出格式为har。
但是在reqable中打开失败。
手机：ios

**Comment by MegatronKing** [comment]
@zdone 您好，感谢反馈。如果可以的话，把har文件发送到邮箱：coding@reqable.com

**Comment by MegatronKing** [comment]
@zdone 您好，是否能发下有问题的har文件。

**Comment by MegatronKing** [comment]
没有收到打不开的har文件，这个问题我先关闭了。
