### ISSUE TITLE
可以添加上游代理的设置选项。像charles中那样，有些网站需要挂梯子

### ISSUE THREAD

**Issue by sqw637** [reqable/reqable-app#127]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
Reqable最新版本已经支持`二级代理`，鼠标右键点击代理图标，在`二级代理`里面配置一个代理地址并选中即可。
