### ISSUE TITLE
[feature] raw模式不够raw(原始)

### ISSUE THREAD

**Issue by coolmian** [reqable/reqable-app#128]
![22e474f1e036ef5a85d84dc7033fda4](https://github.com/reqable/reqable-app/assets/36444522/0de4b2ec-087a-4c7f-bb1b-09e159a8ab6f)
multipart发送的请求体，这个raw格式不够原始，我刚开始都没找到右边还有个翻页按钮。
这个算是pretty format了吧

最好可以提供fiddler这种原始的信息
![4433d37f242c431ed81f2f6f8573d9c](https://github.com/reqable/reqable-app/assets/36444522/d71f27ed-6778-4cdc-9827-4e32324d4a84)
要是两种能区分开就好了，原始格式和美化格式

**Comment by qqqqddasdd** [comment]
我也遇到这个问题了，真火大

**Comment by MegatronKing** [comment]
原始请求的需求见这个issue #92，这个我当作重复issue先关闭了。
