### ISSUE TITLE
multipart请求体的键没有显示

### ISSUE THREAD

**Issue by qqqqddasdd** [reqable/reqable-app#131]
复制的curl能不能不要少东西，在少东西就不用你们的东西了，尤其是请求体的

**Comment by MegatronKing** [comment]
您好，抱歉，不好意思。能否描述下具体的问题方便我排查？

**Comment by qqqqddasdd** [comment]
[功能] raw模式不够raw（原始） #128和这个问题一样

**Comment by qqqqddasdd** [comment]
![20230726-133014](https://github.com/reqable/reqable-app/assets/140582246/77a33498-d8d0-4f63-bd51-429e6c5919ff)
比如这种，

**Comment by qqqqddasdd** [comment]
![20230726-133411](https://github.com/reqable/reqable-app/assets/140582246/6ed326c4-5a39-4f51-97c2-7515b602c5f1)
fiddler就没有你们这种情况

**Comment by MegatronKing** [comment]
感谢反馈。丢失name的问题已经修复了，下个版本会生效，预计明天部署新版本。

**Comment by qqqqddasdd** [comment]
保存的api为什么没有复制curl的功能，搞一个原始的curl保存到txt文件也行啊，curl少东西



---原始邮件---
发件人: "Megatron ***@***.***&gt;
发送时间: 2023年7月26日(周三) 中午1:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reqable/reqable-app] multipart请求体的键没有显示 (Issue #131)




 
感谢反馈。丢失name的问题已经修复了，下个版本会生效，预计明天部署新版本。

**Comment by MegatronKing** [comment]
curl少东西，请问这个有具体的case吗？

**Comment by qqqqddasdd** [comment]
就是fiddler有一个保存request保存到一个txt文件，reqable却把请求头，请求体，请求分开了，能不能做一个直接保存的



---原始邮件---
发件人: "Megatron ***@***.***&gt;
发送时间: 2023年7月26日(周三) 中午1:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reqable/reqable-app] multipart请求体的键没有显示 (Issue #131)




 
curl少东西，请问这个有具体的case吗？

**Comment by MegatronKing** [comment]
导出 -> 请求，保存的就是完整的请求txt
导出 -> 响应，保存的就是完整的响应txt
导出 -> HAR，保存的就是完整的请求 + 响应

**Comment by qqqqddasdd** [comment]
是我理解错了吗，我理解的是导出请求，请求体，请求头，才算一个request

---原始邮件---
发件人: "Megatron ***@***.***&gt;
发送时间: 2023年7月26日(周三) 中午1:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reqable/reqable-app] multipart请求体的键没有显示 (Issue #131)




 
导出 -&gt; 请求，保存的就是完整的请求txt
 导出 -&gt; 响应，保存的就是完整的响应txt
 导出 -&gt; HAR，保存的就是完整的请求 + 响应

**Comment by MegatronKing** [comment]
> 是我理解错了吗，我理解的是导出请求，请求体，请求头，才算一个request

没有错。Reqable是支持的，按照我上面的操作步骤试试。

**Comment by qqqqddasdd** [comment]
搞个导出完整的request和完整的response就行了，软件上现在并没有这个功能



---原始邮件---
发件人: "Megatron ***@***.***&gt;
发送时间: 2023年7月26日(周三) 下午2:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reqable/reqable-app] multipart请求体的键没有显示 (Issue #131)




  
是我理解错了吗，我理解的是导出请求，请求体，请求头，才算一个request
  
没有错。Reqable是支持的，按照我上面的操作步骤试试。

**Comment by MegatronKing** [comment]
<img width="1192" alt="截屏2023-07-26 14 19 10" src="https://github.com/reqable/reqable-app/assets/15059084/07fdcd82-7bdb-44a8-b99f-94dd3c355ed4">

**Comment by MegatronKing** [comment]
@qqqqddasdd 1.1.4版本已修复和优化multipart的几个问题

**Comment by qqqqddasdd** [comment]
带multipart的curl，导入到api还是没有name啊



---原始邮件---
发件人: "Megatron ***@***.***&gt;
发送时间: 2023年7月27日(周四) 晚上6:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reqable/reqable-app] multipart请求体的键没有显示 (Issue #131)




 
@qqqqddasdd 1.1.4版本已修复和优化multipart的几个问题

**Comment by qqqqddasdd** [comment]
做一个curl或者raw http转代码请求，难不难



---原始邮件---
发件人: "Megatron ***@***.***&gt;
发送时间: 2023年7月27日(周四) 晚上6:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reqable/reqable-app] multipart请求体的键没有显示 (Issue #131)




 
@qqqqddasdd 1.1.4版本已修复和优化multipart的几个问题

**Comment by MegatronKing** [comment]
@qqqqddasdd 代码生成功能见这个issue #75 
另外，关于multipart的curl导入到api的问题，更新1.1.5版本再试试，如果还有问题的话，可以发一个有问题的curl给我方便测试复现。

**Comment by qqqqddasdd** [comment]
能保密吗



---原始邮件---
发件人: "Megatron ***@***.***&gt;
发送时间: 2023年7月31日(周一) 下午5:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reqable/reqable-app] multipart请求体的键没有显示 (Issue #131)




 
@qqqqddasdd 代码生成功能见这个issue #75
 另外，关于multipart的curl导入到api的问题，更新1.1.5版本再试试，如果还有问题的话，可以发一个有问题的curl给我方便测试复现。

**Comment by qqqqddasdd** [comment]
我还是开通了会员的，年卡



---原始邮件---
发件人: "Megatron ***@***.***&gt;
发送时间: 2023年7月31日(周一) 下午5:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reqable/reqable-app] multipart请求体的键没有显示 (Issue #131)




 
@qqqqddasdd 代码生成功能见这个issue #75
 另外，关于multipart的curl导入到api的问题，更新1.1.5版本再试试，如果还有问题的话，可以发一个有问题的curl给我方便测试复现。

**Comment by MegatronKing** [comment]
如果没有其他问题，这个issue我先关闭了。

**Comment by qqqqddasdd** [comment]
能不能出个断言中断所有



---原始邮件---
发件人: "Megatron ***@***.***&gt;
发送时间: 2023年8月3日(周四) 晚上10:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reqable/reqable-app] multipart请求体的键没有显示 (Issue #131)




 
Closed #131 as completed.
