### ISSUE TITLE
[bug] 发送multipart/form-data的请求，file文件名为中文，无法发送请求

### ISSUE THREAD

**Issue by cry980285208** [reqable/reqable-app#133]
发送multipart/form-data的请求，file文件名为中文，无法发送请求，改成英文正常，希望可以支持中文

![Dingtalk_20230727142835](https://github.com/reqable/reqable-app/assets/46832863/511a6717-9f1a-459b-83f6-f28562bdace0)

**Comment by MegatronKing** [comment]
1.1.4版本已修复。

**Comment by MegatronKing** [comment]
如果没有其他问题，这个issue我先关闭了。
