### ISSUE TITLE
[feature] 

### ISSUE THREAD

**Issue by lijiaxiucai** [reqable/reqable-app#135]
# 1、当前使用的版本 当前版本1.1.3（27）

# 2、建议软件增加字体调节功能，目前软件的字体不能设置大小，至少在某些区域，对于大屏需要将字号整体调大一些。

# 3、目前设置菜单里只支持设置主题，功能相对少。

**Comment by MegatronKing** [comment]
您好，感谢反馈，字体调整目前尚不支持。关于功能相对少，请问除了字体外还有具体还需要支持的功能吗？

**Comment by MegatronKing** [comment]
字体调整的需求见这个issue #18，没有其他问题的话这个issue我先关闭了。
