### ISSUE TITLE
[bug] 网站部分链接点击出现“找不到页面”

### ISSUE THREAD

**Issue by coolmian** [reqable/reqable-app#136]
用这个链接进去（末尾没有斜杠）
https://reqable.com/zh-CN/docs/rest
然后拖到最下面，点击右边任意一个链接即可触发。
（如果是点左边的侧边栏不会触发这个问题）
![f149631623a2bc67b3eb5e8b48c2d32](https://github.com/reqable/reqable-app/assets/36444522/8a92c6c9-082b-49e6-88d1-e4fc2f6f09e3)

**Comment by MegatronKing** [comment]
非常感谢您的反馈！

**Comment by MegatronKing** [comment]
问题已修复上线，再次感谢反馈。
