### ISSUE TITLE
[feature] 其它linux发行版支持

### ISSUE THREAD

**Issue by biaji** [reqable/reqable-app#138]
**Is your feature request related to a problem? Please describe.**
目前只支持debian系产品的deb包。其它发行版无法使用

**Describe the solution you'd like**
增加RHEL系的RPM打包或者直接用appimage形式打包发布

**Describe alternatives you've considered**
直接发布二进制版本

**Additional context**

**Comment by MegatronKing** [comment]
根据Flutter官方的文档，对Debian/Ubuntu的支持是确认的。所以，我没有去测试其他的发行版。

<img width="701" alt="截屏2023-08-02 14 21 44" src="https://github.com/reqable/reqable-app/assets/15059084/cf1f20da-2ea9-48a2-8925-a498ea124426">

不知道RHEL系是否能正常运行Reqable？

**Comment by biaji** [comment]
> 根据Flutter官方的文档，对Debian/Ubuntu的支持是确认的。所以，我没有去测试其他的发行版。
> 
> <img alt="截屏2023-08-02 14 21 44" width="701" src="https://user-images.githubusercontent.com/15059084/257720312-cf1f20da-2ea9-48a2-8925-a498ea124426.png">
> 不知道RHEL系是否能正常运行Reqable？

linux发行版是二进制兼容的。 只要打包成对应的发行版支持包。  为了统一，可以考虑直接发布二进制，或者使用[appimage](https://appimage.org/) 来避免打包操作的复杂度。

**Comment by biaji** [comment]
@MegatronKing https://medium.com/@amin.bhst/a-complete-guide-to-building-rpm-packages-for-flutter-applications-c8cbbbab8548  也许可以试试这个？

我周末用源码打一个试试看

**Comment by biaji** [comment]
我错了。我还以为公开源码了。下了sourcecode发现不是能编译的东西

**Comment by MegatronKing** [comment]
@biaji 感谢建议，从v2.3.2版本开始提供AppImage格式。
