### ISSUE TITLE
[bug] 开启系统代理设置，mac浏览器就无法上网了 

### ISSUE THREAD

**Issue by huangwch** [reqable/reqable-app#139]
![image](https://github.com/reqable/reqable-app/assets/47070451/4032185c-8693-49c0-aea7-2cd4d02bc942)

![image](https://github.com/reqable/reqable-app/assets/47070451/bde8ca62-3c40-4f10-91c4-d7ff8fd202b8)
**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@huangwch 看上去像是dns缓存的问题，可以试试清除下系统dns缓存。
参考：https://www.freecodecamp.org/chinese/news/how-to-flush-dns-on-mac-macos-clear-dns-cache/

**Comment by huangwch** [comment]
@MegatronKing 试过了，没有解决问题

**Comment by MegatronKing** [comment]
或者试试切换代理协议（图标右键）。

<img width="1192" alt="截屏2023-08-02 20 25 07" src="https://github.com/reqable/reqable-app/assets/15059084/dc6d792e-6318-49e4-9d8e-a9a3b10065dd">

**Comment by MegatronKing** [comment]
无法复现这个问题，先挂起。

**Comment by yourbask** [comment]
我不知道这个问题是否归类于此但是我确实遇到了
win11 关闭系统代理，仍会收到来自127.0.0.1客户端的数据包
![image](https://github.com/reqable/reqable-app/assets/65041738/32b120d0-7304-4a55-bce0-ed793751965e)

**Comment by MegatronKing** [comment]
这个问题基本上是端口冲突，更换端口后就正常了。
