### ISSUE TITLE
[feature] api测试功能中，stream输出的api，希望能支持展示结果也同样stream输出

### ISSUE THREAD

**Issue by imyuxh** [reqable/reqable-app#140]
目前的结果展示，是等待拿到所有返回后，再一起展示出来，希望能像打字机效果一样流式输出战士。

**Comment by MegatronKing** [comment]
流式是一个非常好的效果，但我目前恐怕无法做到。因为这个涉及到传输压缩、数据解码等步骤，并不是所有的数据都能按照流式解压缩或者解码。非常抱歉！
