### ISSUE TITLE
调试安卓的时候，几乎所有应用都连不上网

### ISSUE THREAD

**Issue by liewstar** [reqable/reqable-app#141]
root和非root都试过，除了qq，其他应用都网络连接失败
![图片](https://github.com/reqable/reqable-app/assets/93535922/f51a9dea-03fc-44c2-9579-cb2327a23acf)
![图片](https://github.com/reqable/reqable-app/assets/93535922/c4944ed8-ef9b-4435-9d38-560d335a7e54)

**Comment by MegatronKing** [comment]
同 #142 ，证书未安装成功，非reqable问题。
