### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by jiqiu2022** [reqable/reqable-app#142]
![71691120621_ pic](https://github.com/reqable/reqable-app/assets/101506414/435307fe-4478-4089-b937-39949f493df3)
安卓12 内核5.10.66 xaga   （红米note11t pro） 加入系统证书后仍然无法解密ssl  已测试同种方式添加charles证书 正常解密
![61691120613_ pic](https://github.com/reqable/reqable-app/assets/101506414/24d86bc6-26fa-493d-a2af-4a44ece42144)
![71691120621_ pic](https://github.com/reqable/reqable-app/assets/101506414/6b93d4fe-6dee-4b46-aa37-5a5cfa6c0795)
cat /system/etc/security/cacerts/364618e0.0
xaga:/ # uname -a
Linux localhost 5.10.66-android12-9-gdc4677876dca #1 SMP PREEMPT Fri Nov 4 23:46:04 UTC 2022 aarch64

charles添加证书正常抓包的 reqable ssl握手失败
![121691121848_ pic](https://github.com/reqable/reqable-app/assets/101506414/abab8d3f-e118-4a65-9c25-7231de4149c1)

**Comment by MegatronKing** [comment]
已确认是证书未成功安装问题，非reqable的问题。

**Comment by RevealedSoulEven** [comment]
Then how to install the certificate properly??

**Comment by MegatronKing** [comment]
@RevealedSoulEven Different android phones may have different restrictions, which is especially troublesome for Chinese manufacturers. For Google native systems, take the simulator as an example:
```
emulator -avd Pixel_6_API_33 -writable-system

adb root
# Output: restarting adbd as root

adb shell avbctl disable-verification
# Output: Successfully disabled verification. Reboot the device for changes to take effect.

adb remount
# Output: Using overlayfs for /system
# Output: Using overlayfs for /vendor
# Output: Using overlayfs for /product
# Output: Using overlayfs for /system_ext
# Output: Now reboot your device for settings to take effect
# Output: remount succeeded

adb push reqable-ca.crt /system/etc/security/cacerts/364618e0.0
# Done!
```

**Comment by RevealedSoulEven** [comment]
Still the same. I know it used to work in httcanary till now but now there is no way left due to security. We can't use WiFi proxy, need to use android app
