### ISSUE TITLE
[bug] 二级代理无法设置

### ISSUE THREAD

**Issue by biaji** [reqable/reqable-app#145]
**Describe the bug**
无法添加二级代理

**To Reproduce**
1. 右键点击代理设置
2. 二级代理->新建配置
3. 输入"http://proxy.xxx.xxx"
4. 点击完成无反应

**Expected behavior**
正常保存或提示错误

**Screenshots**

**Information**
 - Platform: macos
 - OS: 13.4.1
 - Arch: x86
 - App Version: 1.1.5

**Comment by MegatronKing** [comment]
格式是 `ip:port` 不是链接哦

**Comment by RonaldinhoL** [comment]
> 格式是 `ip:port` 不是链接哦

这是合法的代理地址，当前的二级代理不支持认证
http://user:pass@host:port
http://host:port

**Comment by MegatronKing** [comment]
认证目前确实还不支持
