### ISSUE TITLE
希望能优化启用脚本时抓包接口加载速度

### ISSUE THREAD

**Issue by Peter-90** [reqable/reqable-app#146]
场景是写了一个脚本来获取某一些请求头及请求体里面的数据，然后通过脚本写入文件目录保存

目前URL栏填写的是 https://* 就是匹配所有的https请求，因为当前URL栏不支持写多个请求地址，而我需要用到多个不同地址的抓包请求，估计是这一原因导致了抓包很卡顿加载过慢，望团队能在后面的版本中优化这一问题，例如URL支持填多个或其他优化方案来处理该问题，感谢，该问题很影响使用脚本的抓包体验，把脚本里面指定的请求链接分成多个脚本又很麻烦

**Comment by MegatronKing** [comment]
不建议使用 `https://*` 匹配所有的https请求，必然会带来性能问题。虽然脚本性能确实可以进一步优化，但是对于捕获全部请求执行脚本并不能改变什么。

**Comment by MegatronKing** [comment]
脚本规则列表里面可以直接复制创建出新的规则的，配合wildcard匹配功能，应该不会造成麻烦这种问题。

**Comment by Peter-90** [comment]
感谢回复，也感谢你们做出这么好用的工具，但个人感觉使用脚本的卡顿是有点过于明显了，按照常理来说也就是所有https请求通过了一次脚本 脚本运行一次也不过就1秒不到，但是感觉很卡顿，希望还是能优化一下使用脚本的体验

**Comment by MegatronKing** [comment]
@Peter-90 UI卡顿应该不是脚本的问题，1.1.6版本有个性能问题导致的。但是执行了脚本的请求肯定会变慢，一个是python的效率，一个是Reqable的调度机制还没有优化。所以需要谨慎对请求挂脚本，类似对所有请求挂脚本这种方式应该是要避免的。

**Comment by Peter-90** [comment]
好的

**Comment by MegatronKing** [comment]
关于执行效率，可以关注这个issue：#151
