### ISSUE TITLE
证书自动安装功能以及安装之后不能抓到包

### ISSUE THREAD

**Issue by suixin521** [reqable/reqable-app#148]
尊敬的开发者你好，我使用reqable的过程中遇到了以下问题：
1.使用证书自动安装功能遇到错误提示，但是我这个目录下有证书。也尝试过用管理员身份运行，也是不行。手动安装证书时选择当前用户，提示成功实际也没导进去。最后我将证书安装到本地计算机才成功。
![1](https://github.com/reqable/reqable-app/assets/109323596/c3c5282a-b374-4058-97bb-1d006d3fe7e6)
![2](https://github.com/reqable/reqable-app/assets/109323596/84ad9f44-06e7-4886-a291-a7b08d369470)
![3](https://github.com/reqable/reqable-app/assets/109323596/1a23a1a8-0ae3-4645-9979-60e579bcebbf)
2.安装完了证书之后，我启动软件却抓取不到数据包，代理开关都尝试过了，全程没有反应。我不太清楚本软件的用法，还希望开发者可以抽空回复一下。十分感谢！
![4](https://github.com/reqable/reqable-app/assets/109323596/1234ebdc-b88a-47ea-b242-fd13bf1f4f08)

**Comment by MegatronKing** [comment]
> 我启动软件却抓取不到数据包，代理开关都尝试过了，全程没有反应。

使用浏览器测试过吗？

**Comment by suixin521** [comment]
测试过了，就是启动了抓包之后点啥都没有数据包

**Comment by suixin521** [comment]
测试过了，获取不到数据包

**Comment by MegatronKing** [comment]
加下我好友：https://reqable.com/zh-CN/assets/images/wechat_qrcode-e1215c7f8fc0b29146b37cfb7d3f624f.jpg

**Comment by MegatronKing** [comment]
没有进一步的信息，这个issue我先关闭了。
