### ISSUE TITLE
希望能新加功能

### ISSUE THREAD

**Issue by mowei1600** [reqable/reqable-app#149]
提两个新功能：
1、新增API集合导出支持APIfox、postman
2、可以对某个进程PID拦截

**Comment by MegatronKing** [comment]
您好，感谢建议！
1. 集合导出会做，但是Reqable和APIfox、postman是竞争关系，不会直接导出他们的格式。
2. Reqable是基于网络代理MITM原理，无法实现针对PID拦截。
