### ISSUE TITLE
[bug] 挂机一段时间后内存暴涨

### ISSUE THREAD

**Issue by wuewill** [reqable/reqable-app#150]
![image](https://github.com/reqable/reqable-app/assets/136971925/d3472451-30b4-4db9-854e-cde5148597bb)
这个是我挂软件什么都没启动的情况下挂机10小时内存暴涨
不知道是不是和我的运行环境有关系 还是内存泄漏

**Comment by MegatronKing** [comment]
同 #153 ，153信息更加充足，保留153，关闭这个issue。
