### ISSUE TITLE
[feature] 发布到 HomeBrew

### ISSUE THREAD

**Issue by Goooler** [reqable/reqable-app#156]
可以把 Mac 的安装包同步发布到 HomeBrew，还有 Windows 的话应该可以支持一下 [winget](https://learn.microsoft.com/en-us/windows/package-manager/winget/) 和 [Scoop](https://scoop.sh), deb 应该也可以考虑发布源？

**Comment by huaqi666** [comment]
+1

**Comment by MegatronKing** [comment]
@Goooler @huaqi666 已发布到homebrew-cask：https://github.com/Homebrew/homebrew-cask/pull/155446

```
brew install reqable
```

**Comment by Goooler** [comment]
可以更新一下 README

**Comment by MegatronKing** [comment]
@Goooler 感谢建议，已更新！
