### ISSUE TITLE
[bug] ubuntu安装后打开报错

### ISSUE THREAD

**Issue by Warren-W** [reqable/reqable-app#158]
Invalid argument(s): Failed to load dynamic library 'libreqable_netbare.so': /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/share/reqable/lib/libreqable_netbare.so)

**Comment by MegatronKing** [comment]
看起来是gcc相关库版本过低，可以尝试按照这个方式处理：
https://askubuntu.com/questions/1166292/version-glibcxx-3-4-26-not-found-even-though-libstdc-so-6-recent-enough

**Comment by MegatronKing** [comment]
v1.2.1已修复此问题，默认将static-libstdc++编译进制品。
