### ISSUE TITLE
可不可以单独对应用进行单独代理？

### ISSUE THREAD

**Issue by JiaLeDe** [reqable/reqable-app#160]
我启动了3个不同的浏览器，每个浏览器需要单独代理，这个可以实现吗？或者仅指定应用程序代理，可多选

- [x] 浏览器1
- [ ] 浏览器2
- [x] 植物大战僵尸
- [x] steam

**Comment by MegatronKing** [comment]
Reqable仅仅是配置系统代理，至于应用是否使用系统代理又或者哪些应用使用代理是无法控制的。虽然通过某些方式能够实现，但是这个容易引起法律问题，不在Reqable的考虑范围之内。
