### ISSUE TITLE
[feature] js注入

### ISSUE THREAD

**Issue by lsdlh** [reqable/reqable-app#161]
**Is your feature request related to a problem? Please describe.**
能不能增加对指定域名的html指定js文件注入，或者注入指定代码如
<script src="//cdn.bootcdn.net/ajax/libs/eruda/2.3.3/eruda.js"></script>
<script>eruda.init();</script>

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JiaLeDe** [comment]
使用Python脚本直接替换返回的html不就行了，或者替换返回的js文本

**Comment by MegatronKing** [comment]
重写、脚本、断点功能都可以实现
