### ISSUE TITLE
[feature] 优化历史记录占用空间大小

### ISSUE THREAD

**Issue by forchannot** [reqable/reqable-app#162]
这几天发现电脑C盘莫名其妙少了十几个G，逐一排查发现reqable的历史记录就占用了16个G，发现数据都是存在capture文件夹内明文存储，没有进行任何压缩，虽然可以删除历史记录，但是仍希望优化下内存占用大小

**Comment by MegatronKing** [comment]
压缩也只是治标不治本，可能会加个超过时间范围自动清理的选项。

**Comment by MegatronKing** [comment]
v1.2.2版本历史记录已支持保存时间和星标设置，未设置星标的历史记录过期后会自动删除。
