### ISSUE TITLE
[feature] 建议安卓root设备证书安装644权限提示

### ISSUE THREAD

**Issue by yourbask** [reqable/reqable-app#163]
安装证书指引忽略了证书传到指定目录后，需要给与 user: root group: root 644 权限，新手会容易忽略，造成https无法正常抓包。
建议增加提示 添加到 /system/etc/security/cacerts 目录。命令行 root用户 给予 "chmod 644 xxxxxxxx.0"权限的提示。
![image](https://github.com/reqable/reqable-app/assets/65041738/ccdba6ca-c78b-400e-a3b0-bdb751f3d255)

**Comment by MegatronKing** [comment]
我用模拟器测试并没有这种问题，不确定是否是国内定制ROM的问题？
模拟器的操作步骤如下：https://reqable.com/en-US/blog/2023/06/28/post#23-%E8%A7%A3%E9%94%81%E7%B3%BB%E7%BB%9F%E5%88%86%E5%8C%BA

**Comment by MegatronKing** [comment]
2.0.0版本已经新增文件权限提示。
