### ISSUE TITLE
[bug] 脚本问题

### ISSUE THREAD

**Issue by freeloop4032** [reqable/reqable-app#164]
1.web代理：访问web脚本能正常打印
2.app抓包：socks5代理，能正常抓包，但是脚本一直没有打印输出，抓app应该怎么设置？

**Comment by JiaLeDe** [comment]
抓app的配置和其他抓包软件一样吧，在手机安装证书就行，但大多数app应该是抓不到https的包的，需要一些魔法

**Comment by MegatronKing** [comment]
原理是一样的，web和手机只有安装证书的区别。
