### ISSUE TITLE
[bug] 脚本功能对来自已root的安卓设备不生效

### ISSUE THREAD

**Issue by lwc8699793** [reqable/reqable-app#166]
我使用windows10测试来自安卓的抓包。
我测试了抓包web的脚本功能，可以正常工作。
但是当我将抓包对象换成一台已root的安卓设备时，抓包ssl都可以正常工作，但是脚本功能却不生效。

**Comment by MegatronKing** [comment]
应该不会存在这种问题，android和web并没有本质的区别。如果能提供一些测试case或者录屏，可能对这个问题的分析有些帮助。

**Comment by MegatronKing** [comment]
没有进一步的信息，这个issue我关闭了。
