### ISSUE TITLE
[feature] 全局清除缓存功能

### ISSUE THREAD

**Issue by zhuliminl** [reqable/reqable-app#167]
![截屏2023-08-21 11 29 37](https://github.com/reqable/reqable-app/assets/20069490/061a9cdc-4dca-4439-9e36-018813b80e84)
里的文件太大的

**Comment by MegatronKing** [comment]
历史，删除无用的记录，或者全部清空

**Comment by zhuliminl** [comment]
功能不明显。建议弄个缓存清理

**Comment by MegatronKing** [comment]
1.2.0版本已实现全局缓存清理功能。
