### ISSUE TITLE
[feature] 希望点击SSL已启用按钮可以关闭SSL代理

### ISSUE THREAD

**Issue by Shinku-Chen** [reqable/reqable-app#169]
地址栏旁边的 SSL已启用按钮 希望点击是进行SSL代理开关切换 而不是弹出证书安装向导(可以右键弹出)
因为有时候调试需要频繁开关是否代理SSL,因此不太方便

**Comment by MegatronKing** [comment]
> 地址栏旁边的 SSL已启用按钮 希望点击是进行SSL代理开关切换 而不是弹出证书安装向导(可以右键弹出)

这个建议我觉得很有道理，左键点击确实应该让给其他更频繁的功能。顺便问一下，`频繁开关是否代理SSL`这是在什么场景下用得比较多？

**Comment by Shinku-Chen** [comment]
目前主要是尝试调整JA3字符串,因此需要通过https://tls.browserleaks.com/json返回
但如果开启代理,会直接重新修改JA3.

**Comment by yinsel** [comment]
> 地址栏旁边的 SSL已启用按钮 希望点击是进行SSL代理开关切换 而不是弹出证书安装向导(可以右键弹出) 因为有时候调试需要频繁开关是否代理SSL,因此不太方便

希望添加关闭SSL代理支持，但是我希望看到CONNECT，因为不需要关心其包的内容，只需关心目标，我是安全领域的，做流量调试，您的软件非常好用！

**Comment by yinsel** [comment]
> > 地址栏旁边的 SSL已启用按钮 希望点击是进行SSL代理开关切换 而不是弹出证书安装向导(可以右键弹出)
> 
> 这个建议我觉得很有道理，左键点击确实应该让给其他更频繁的功能。顺便问一下，`频繁开关是否代理SSL`这是在什么场景下用得比较多？

希望添加关闭SSL代理支持，但是我希望看到CONNECT，因为不需要关心其包的内容，只需关心目标，我是安全领域的，做流量调试，您的软件非常好用！

**Comment by MegatronKing** [comment]
v2.17.0已支持SSL代理配置，从`工具`菜单或者盾牌右键可以打开配置页面。
