### ISSUE TITLE
[feature] SSL Bypass支持列表静默功能

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#172]
![image](https://github.com/reqable/reqable-app/assets/1797392/0533ee72-8fd5-4e38-b780-2a52f11e694a)
![image](https://github.com/reqable/reqable-app/assets/1797392/c9d1e706-a4a1-4f12-8d1b-c081c08ce0a8)

**Comment by RonaldinhoL** [comment]
版本 1.20(33) windows

**Comment by MegatronKing** [comment]
@RonaldinhoL 提供的截图看起来并没有什么问题，ssl bypass是生效的。

**Comment by RonaldinhoL** [comment]
> @RonaldinhoL 提供的截图看起来并没有什么问题，ssl bypass是生效的。

也就是说，bypass的流量仍旧会显示在列表中是吗

**Comment by MegatronKing** [comment]
> > @RonaldinhoL 提供的截图看起来并没有什么问题，ssl bypass是生效的。
> 
> 也就是说，bypass的流量仍旧会显示在列表中是吗

是的，前面会有个锁的图标。如果列表显示控制，需要用网关功能。

**Comment by RonaldinhoL** [comment]
bypass的流量为啥不是默认静默的呢，网关配置的是url，不解密https如何能够进行url匹配

**Comment by RonaldinhoL** [comment]
你看我的截图，配置了`*.apple.com` 但是还是有显示 url 的，所以是不是没有bypass 😂

**Comment by MegatronKing** [comment]
v1.2.1已支持配置静默开关。

![ssl_03](https://github.com/reqable/reqable-app/assets/15059084/24b5ba8a-bb53-40b8-90c0-2318f4ddd619)
