### ISSUE TITLE
[feature] 希望能增加便携版本

### ISSUE THREAD

**Issue by idyllim** [reqable/reqable-app#173]
希望能增加便携版本

**Comment by MegatronKing** [comment]
请问`便携版本`是指什么？

**Comment by popokcn** [comment]
就是绿色版本，不需要安装，直接解压就能用。方便丢在U盘里，即插即用

**Comment by MegatronKing** [comment]
@popokcn 你可以直接将安装后的文件夹拷贝到U盘等存储介质上，肯定是可以运行的。之所以用setup安装，是因为需要做注册表关联，比如关联HAR文件格式，可以直接从HAR文件双击打开Reqable并进行查看。

**Comment by idyllim** [comment]
对的，便携版本就是上面仁兄说的，直接解压就可以运行的版本，这种版本，只在应用程序目录产生文件、信息，不会写注册表，以及系统的其他目录。如果需要关联注册表，可以执行相应的脚本即可

**Comment by MegatronKing** [comment]
v2.3.2版本开始已提供免安装版本。
