### ISSUE TITLE
[bug] 不能监听本地流量

### ISSUE THREAD

**Issue by klakekent** [reqable/reqable-app#177]
看了文档是对支持的"localhost"这样的本地流量做镜像支持，但是如果我本地开发通过hosts设置了域名，能监听到但是无法打开网站

比如hosts如下设置

127.0.0.1 local.mysite.com 

一旦通过reqable去调试请求，就没办法打开网站

**Comment by MegatronKing** [comment]
@klakekent 是mac吗？

**Comment by klakekent** [comment]
是Ubuntu

**Comment by MegatronKing** [comment]
@klakekent 我用Ubutun 20.04测试，未能复现这个问题。

![Screenshot from 2023-08-27 23-59-54](https://github.com/reqable/reqable-app/assets/15059084/a8589f36-4d20-4e5e-a2a1-1157b7735b10)

![Screenshot from 2023-08-27 23-58-52](https://github.com/reqable/reqable-app/assets/15059084/c74d3b07-d4f6-48f4-bd7f-f603df850fef)

**Comment by MegatronKing** [comment]
无法复现，没有更多信息，这个issue我先关闭了。
