### ISSUE TITLE
[bug] 调试列表上下键

### ISSUE THREAD

**Issue by wY1k** [reqable/reqable-app#182]
调试列表中按 ↑ 到了首行，按 ↓ 到了尾行。不能一行一行调试

**Comment by MegatronKing** [comment]
感谢反馈。按住Alt + 上下箭头可以快速定位到顶部和底部，单按上下箭头是一行行切换，目前没发现有问题。

**Comment by MegatronKing** [comment]
没有更多信息的话，这个issue我先关闭了。
