### ISSUE TITLE
[bug] 右键菜单失效

### ISSUE THREAD

**Issue by devotion-coding** [reqable/reqable-app#183]
**Describe the bug**
无法呼出右键菜单

**Information**
M1 macbook
<img width="233" alt="image" src="https://github.com/reqable/reqable-app/assets/52208967/224a6d93-1f2d-4703-80f1-68080d79ce45">

**Comment by MegatronKing** [comment]
@devotion-coding  是全部右键功能都失效了吗？能提供下系统版本信息吗？

**Comment by devotion-coding** [comment]
是的  似乎是对macbook 的键位没有做适配
<img width="311" alt="image" src="https://github.com/reqable/reqable-app/assets/52208967/a18474c6-d572-4280-b473-fbf921a4b5ce">

**Comment by MegatronKing** [comment]
@devotion-coding 刚刚测试了12.1，Macbook触摸板操作没有发现问题。请问你是触摸板还是鼠标？
<img width="1149" alt="Screen Shot 2023-08-28 at 12 11 18 PM" src="https://github.com/reqable/reqable-app/assets/15059084/2918600c-5444-41a5-9764-5cedfe919d51">

**Comment by MegatronKing** [comment]
无法复现此问题，如果没有更多信息，这个Issue我先关闭了。
