### ISSUE TITLE
[feature] JSON数据支持JSONPath模式

### ISSUE THREAD

**Issue by LarkinZero** [reqable/reqable-app#184]
**Is your feature request related to a problem? Please describe.**
在一个几千个字符的响应体中查找特定路径的字段用搜索功能太累了，往往要复制到第三方工具中才能用JSONPath表达式查找想要的内容
**Describe the solution you'd like**
在响应体或请体中，可以加入JSONPath表达式执行查找的功能。执行成功后直接显示成满足JSONPath表达式的结果，表达式输入框的清空按钮点击后还原原有的请求体或响应体

**Describe alternatives you've considered**
也可以加入一个按钮，点开后显示一个表达式执行文本框，旁边是执行按钮，以及清空按钮，下面是结果展示文本框。
执行完成后可以在结果展示文本框中显示结果，如果表达式出错，也可以在这个结果框中展示错误信息。
**Additional context**

**Comment by MegatronKing** [comment]
@LarkinZero 感谢反馈，这个是非常棒的建议。

**Comment by LarkinZero** [comment]
> @LarkinZero 感谢反馈，这个是非常棒的建议。
还可以有进一步的扩展，比如能否在抓包的时候加入返回字段的校验？这里就可以引入JSONPath表达式提取结果，进行简单的断言。
又或者在抓包的时候提供一个地方可以聚合展示某个接口某个字段的值，利用JSONPath从而直接一步到位的展示想要的结果。

**Comment by MegatronKing** [comment]
> > @LarkinZero 感谢反馈，这个是非常棒的建议。
> 
> 还可以有进一步的扩展，比如能否在抓包的时候加入返回字段的校验？这里就可以引入JSONPath表达式提取结果，进行简单的断言。 又或者在抓包的时候提供一个地方可以聚合展示某个接口某个字段的值，利用JSONPath从而直接一步到位的展示想要的结果。

可以同脚本实现：https://reqable.com/docs/capture/script

**Comment by MegatronKing** [comment]
JSON Path已支持，请更新到最新2.30.1版本。


https://github.com/user-attachments/assets/e4102ad7-3da1-4123-bac5-1ff72385fe7b
