### ISSUE TITLE
[feature] JSON数据支持Tree显示模式

### ISSUE THREAD

**Issue by MegatronKing** [reqable/reqable-app#185]
以树形结构显示JSON数据，支持对节点操作，例如复制、展开等。

**Comment by MegatronKing** [comment]
类似 #184 都是对JSON数据的优化项。

**Comment by punkisnotdead3** [comment]
这个特性 什么时候可以完成啊

**Comment by MegatronKing** [comment]
@punkisnotdead3 已完成，请更新到最新2.30.1版本。

https://github.com/user-attachments/assets/4894da2d-b369-4d97-b5a4-7d76be119b1c
