### ISSUE TITLE
[feature] IPTABLES 重定向过去的 HTTP/HTTPS 的流量无法被转发

### ISSUE THREAD

**Issue by lonkil** [reqable/reqable-app#186]
**Is your feature request related to a problem? Please describe.**
通过如下方式重定向的流量无法正常转发
```bash
iptables -t nat -A OUTPUT -p tcp ! -d 192.168.0.2 -m multiport --dports 80,443 -j DNAT --to-destination 192.168.0.2:9000
```

**Describe the solution you'd like**
Burp Suite 通过 `Support invisible proxying` 即可支持此项能力

**Comment by MegatronKing** [comment]
@lonkil 抱歉，我没有能够理解这种操作的场景。能否解释下这个操作在什么情况下会需要，是解决什么样的问题？希望您可以提供更多的信息，帮助我更好的理解这个问题，感谢。

**Comment by MegatronKing** [comment]
没有进一步的信息，这个issue我先关闭了。
