### ISSUE TITLE
[feature] 支持API调试设置请求次数

### ISSUE THREAD

**Issue by fuqiuluo** [reqable/reqable-app#188]
增加一下设置API请求次数，这样可以批量测试一下API。

![image](https://github.com/reqable/reqable-app/assets/61898844/39c1ea8f-2bd6-4c21-ba1f-1ac942553444)

比如说在这里加入这个功能。

**Comment by MegatronKing** [comment]
@fuqiuluo 
这个功能可以利用现有的重发机制实现。你点亮`跟随调试`图标，发送一个请求。然后在调试列表里面，右键重发，可以设置次数、间隔等参数。

API测试我还是想做得轻量级一点，保持简洁性，因为高频操作就是发请求看结果，但是压力测试并不属于这个功能范围内。更多的操作未来会放到侧边栏工作台中去实现，因为目前精力不在API测试这里，所以API测试的工作台功能还没有深度实现。

**Comment by hmlluy** [comment]
但是调试好像没法监听到本地的请求呢。我本地起一个服务，再用reqable调用本地接口，调试模式监听不到。同时我还想重发这个接口，应该怎么办呢
