### ISSUE TITLE
[bug] Reqable导致Datagrip无法访问数据库

### ISSUE THREAD

**Issue by cjnchk** [reqable/reqable-app#190]
1、开启reqable后datagrip无法访问数据库
2、关闭reqable后仍然无法访问
![image](https://github.com/reqable/reqable-app/assets/11740050/bebf833d-1b23-4853-a00e-a927a17a0b00)

**Comment by MegatronKing** [comment]
@cjnchk 有试过，取消socks代理选项吗？
<img width="1192" alt="截屏2023-09-05 12 04 49" src="https://github.com/reqable/reqable-app/assets/15059084/bbb11cc1-17a8-4390-a367-43e04cd96919">

**Comment by cjnchk** [comment]
试了，关闭socket代理可以，但是开启这个会影响软件使用感觉不太对，而且软件关闭后仍然起作用也不对

**Comment by MegatronKing** [comment]
@cjnchk 你好，我用datagrip能够复现这个问题。因为Reqable的Socks5的代理只处理了HTTP协议的数据包，可能需要做一些特定的过滤。请问你使用的数据库类型是什么，默认端口是多少，我加一下过滤逻辑。

**Comment by MegatronKing** [comment]
@cjnchk 我用mysql数据库测试能够复现这个问题，已经针对解决，但是不确定能够解决你的问题，还希望能够提供下上面的信息，谢谢。

**Comment by MegatronKing** [comment]
1.4.0已修复mysql数据库的连接问题。由于没有更多关于此issue的信息，我先关闭了。如果发现还有问题，可以提供有关此问题的更多信息，我再进行处理。
