### ISSUE TITLE
[feature] 希望增加Digest Auth 摘要认证

### ISSUE THREAD

**Issue by czwqyz** [reqable/reqable-app#192]

**Comment by MegatronKing** [comment]
感谢建议。Digest Auth稍微复杂了点，短期内可能无法支持，但后面肯定会支持的。

**Comment by MegatronKing** [comment]
@czwqyz 2.30.0版本开始已支持Digest Auth。

**Comment by czwqyz** [comment]
收到，谢谢啦



---- 回复的原邮件 ----
| 发件人 | Megatron ***@***.***> |
| 日期 | 2024年11月26日 16:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [reqable/reqable-app] [feature] 希望增加Digest Auth 摘要认证 (Issue #192) |

@czwqyz 2.30.0版本开始已支持Digest Auth。
