### ISSUE TITLE
[feature] 希望编辑请求时可以控制是否URL编码

### ISSUE THREAD

**Issue by chengcct** [reqable/reqable-app#196]
在调试列表中选择某条请求进行编辑时，部分参数会自动进行URL编码
例如：
<img width="431" alt="屏幕截图 2023-09-06 141643" src="https://github.com/reqable/reqable-app/assets/50371939/0b351bba-0edb-4922-b26c-ed3352596985">
点击编辑后变成了：
<img width="608" alt="屏幕截图 2023-09-06 142148" src="https://github.com/reqable/reqable-app/assets/50371939/75a40405-52c2-4481-adf7-341343aac3f8">

**Comment by MegatronKing** [comment]
感谢反馈，马上优化。

**Comment by MegatronKing** [comment]
1.3.1版本已经优化此问题。
