### ISSUE TITLE
[bug] 网关功能似乎无法起到作用

### ISSUE THREAD

**Issue by kkopmm** [reqable/reqable-app#197]
在网关功能中使用*.gif*匹配URL，用的静默模式，但有部分含有.gif的URL不能被屏蔽掉，还是会出现在调试窗口，例如xxx.gif?a=c&xxxx就无法屏蔽

**Comment by MegatronKing** [comment]
@kkopmm 感谢反馈，但是我没有复现这个问题。

配置规则：
```
https://reqable.com/*.gif*
```
成功静默的请求：
```
https://reqable.com/a.gif
https://reqable.com/a.gif?a=b
```
注意：这种配置下CONNECT代理请求（https://reqable.com）并不会被静默，如果需要静默代理请求，需要配置成这样：
```
https://reqable.com/*
```

**Comment by MegatronKing** [comment]
如果没有进一步的信息能够复现，这个issue我先关闭了。
