### ISSUE TITLE
[feature] Support PHP code snippet

### ISSUE THREAD

**Issue by wpf900** [reqable/reqable-app#199]
**生成导出请求代码没有php语言的希望能在后续中开发**
设置请求地址每次都得填写域名 希望能设置一个固定的几个域名 我可以来回切换 是线上域名还是测试域名 不用每次都填写

**Comment by MegatronKing** [comment]
> 设置请求地址每次都得填写域名 希望能设置一个固定的几个域名 我可以来回切换 是线上域名还是测试域名 不用每次都填写

这个会在变量功能中实现：#6

**Comment by MegatronKing** [comment]
@wpf900 我不了解PHP，问一下生成cURL和Guzzle两个框架的代码是否够用？

**Comment by MegatronKing** [comment]
1.4.0已支持。
