### ISSUE TITLE
[bug] reqable-app-windows-x86_64.tmp 被通报异常服务

### ISSUE THREAD

**Issue by lv123123long** [reqable/reqable-app#202]
certutil -verifystore root 一系列数字

这个操作指令和标题中文件是咋回事，，一直自动请求执行

被公司安全部警告了

**Comment by MegatronKing** [comment]
@lv123123long 非常抱歉，Reqable给您带来了麻烦，这是我的问题，在此表示歉意。

> certutil -verifystore root 一系列数字

`一系列数字`是Reqable的CA证书指纹（fingerprint），关于CA证书请阅读这篇文档：https://reqable.com/zh-CN/docs/getting-started/installation/

由于CA证书的状态会实时显示到盾牌图标上，Reqable会通过轮询的方式调用`certutil -verifystore root  fingerprint`检查证书安装状态。如果是安装成功状态，盾牌图标显示绿色；如果是未安装或失败状态，盾牌图标显示黄色。轮询的方式导致此命令调用次数过多，可能因此触发了安全警告，我会立即优化这个问题。

如果您有更多想要了解的问题，欢迎在此Issue下面回复。

对此问题，我再此表示歉意。

**Comment by MegatronKing** [comment]
@lv123123long  1.3.1版本已移除轮询机制，只有在启动调试的时候才会进行一次证书状态检测。

**Comment by MegatronKing** [comment]
这个Issue我先关闭了，如果问题再打开。
