### ISSUE TITLE
[feature] 请求和响应窗口的标签希望增加 cookie标签项

### ISSUE THREAD

**Issue by Unintendedz** [reqable/reqable-app#203]
如图：

![image](https://github.com/reqable/reqable-app/assets/64687143/311def15-18e2-49d6-90c4-d4a07d9de3b0)

**Comment by MegatronKing** [comment]
1.4.0版本已支持`原始报文`显示

**Comment by MegatronKing** [comment]
2.8.0版本已支持`Cookies`和`Set-Cookies`标签。

**Comment by LarkinZero** [comment]
调试的Cookies标签，点复制后。复制出来的Cookie值，不能直接用到发起请求时的cookie里，没有使用分隔符。
