### ISSUE TITLE
[bug] Not working ROOT Certificate installed in android

### ISSUE THREAD

**Issue by RevealedSoulEven** [reqable/reqable-app#209]
The apps aren't workiing after using manual proxy in wifi.
Even when I added the root certificate and gave permission 777 still it's not working. I can't capture requests

**Comment by MegatronKing** [comment]
@RevealedSoulEven Can you see `CONNECT` traffics? If you don’t see any `CONNECT`, it means that there is no traffic entering Reqable, and it is likely that the App is not connected to the Wifi Proxy.

**Comment by RevealedSoulEven** [comment]
![image](https://github.com/reqable/reqable-app/assets/49313374/8380e7e6-e398-40de-9559-482f8be80bd5)
YES

**Comment by RevealedSoulEven** [comment]
In httpcanary I could easily see traffics of apps even with SSL. But now that certificate is not working and even no methods to intercept traffic

**Comment by RevealedSoulEven** [comment]
The first thing is, as soon as I enable wifi proxy, the app stops making any connection, so how will it work
Not only a single app, but all with SSL

**Comment by MegatronKing** [comment]
It may be that the certificate is not trusted. There is a bug in the current version, no prompt for requests with certificate problems. This bug will be fixed in the next version.

**Comment by RevealedSoulEven** [comment]
What about httpcanary? Till reqable isn't launching android app. Can you provide trusted certificate for httpcanary?

**Comment by MegatronKing** [comment]
@RevealedSoulEven The CA certificates used by Reqable and HttpCanary are different. If you use Reqable for debugging, you need to install the Reqable CA certificate on your phone.

**Comment by RevealedSoulEven** [comment]
I know that,

**Comment by RevealedSoulEven** [comment]
@MegatronKing UPDATE

Now few of them started recording traffic, but still many of modern apps arern't working. Just due to they detect wifi proxy and they don't work on wifi proxy

**Comment by MegatronKing** [comment]
@RevealedSoulEven You can use [SocksDroid](https://github.com/PeterCxy/SocksDroid/releases/tag/1.0.1) as a VPN to forward traffic.

**Comment by RevealedSoulEven** [comment]
Waiiting a lot for the app, as httpcanary fixed all these issues

**Comment by RevealedSoulEven** [comment]
> @RevealedSoulEven You can use [SocksDroid](https://github.com/PeterCxy/SocksDroid/releases/tag/1.0.1) as a VPN to forward traffic. In the upcoming Android standalone app, I will integrate this feature.

That's not working too

**Comment by super0sd** [comment]
安装完证书也是ssl握手失败

**Comment by MegatronKing** [comment]
This is not a reqable issue, I will close this.
