### ISSUE TITLE
[feature]请问 为什么已root的安卓，下载好crt证书，改名成.0后，移动到系统证书，还是无法抓包？另外一台安卓7，个人用户已经安装好证书了，也同样无法抓包？

### ISSUE THREAD

**Issue by zyf1118** [reqable/reqable-app#214]
请问 为什么已root的安卓，下载好crt证书，改名成.0后，移动到系统证书，还是无法抓包？另外一台安卓7，个人用户已经安装好证书了，也同样无法抓包？charles和fiddler是没有问题的。难道和CPU是amd有关系？

**Comment by MegatronKing** [comment]
@zyf1118 之前收到过类似的反馈，最后表面都是证书没有安装成功，例如 #142

**Comment by RevealedSoulEven** [comment]
did you fixed it 0((
