### ISSUE TITLE
[bug] 导入来自谷歌浏览器的CURL提示:Could not find an option named "insecure"

### ISSUE THREAD

**Issue by lwc8699793** [reqable/reqable-app#215]
![image](https://github.com/reqable/reqable-app/assets/51874230/70d9ec9f-d114-4a83-b21a-bf1e94d5e347)

**Comment by MegatronKing** [comment]
@lwc8699793 看起来这是旧版本的问题，有更新到最新1.4.0吗？

**Comment by lwc8699793** [comment]
更到最新版本后问题不存在了。
