### ISSUE TITLE
希望增加一个抓包可以自动保存请求体和响应体到本地文件的功能

### ISSUE THREAD

**Issue by AX680** [reqable/reqable-app#218]
希望增加一个抓包可以自动保存请求体和响应体到本地文件的功能

**Comment by MegatronKing** [comment]
@AX680 这个功能我觉得你可以通过脚本来实现，这里有一个示例：https://reqable.com/zh-CN/docs/capture/addons#示例3

**Comment by AX680** [comment]
> @AX680 这个功能我觉得你可以通过脚本来实现，这里有一个示例：[https://reqable.com/zh-CN/docs/capture/addons#示例3](https://reqable.com/zh-CN/docs/capture/addons#%E7%A4%BA%E4%BE%8B3)

我是想在抓包的同时就保存并不是在调试的时候

**Comment by MegatronKing** [comment]
> > @AX680 这个功能我觉得你可以通过脚本来实现，这里有一个示例：[https://reqable.com/zh-CN/docs/capture/addons#示例3](https://reqable.com/zh-CN/docs/capture/addons#%E7%A4%BA%E4%BE%8B3)
> 
> 我是想在抓包的同时就保存并不是在调试的时候

非常抱歉，我没有能get到你的意思，不明白你所说`抓包`和`调试`具体场景上的区别。在Reqable的定义里面，API调试其实就是API抓包。

**Comment by MegatronKing** [comment]
没有进一步的信息，这个issue我先关闭了。
