### ISSUE TITLE
Exe http提交根本抓不到，Charles可以抓到你这个不行，还没有过滤或隐藏功能

### ISSUE THREAD

**Issue by 365DRM** [reqable/reqable-app#219]
Exe http提交根本抓不到，Charles可以抓到你这个不行，还没有过滤或隐藏功能

**Comment by MegatronKing** [comment]
> Exe http提交根本抓不到，Charles可以抓到你这个不行

这个是否可以提供一个能复现的案例？

> 还没有过滤或隐藏功能

过滤：https://reqable.com/zh-CN/docs/capture/search
隐藏：https://reqable.com/zh-CN/docs/capture/gateway#静默

**Comment by 365DRM** [comment]
你试试这个客户端能不能抓到 https://www.ieway.cn/evplayer.html  ，自己的不行，再看看人家charles能不能抓到。

**Comment by MegatronKing** [comment]
> 你试试这个客户端能不能抓到 https://www.ieway.cn/evplayer.html ，自己的不行，再看看人家charles能不能抓到。

Reqable和Charles都是采用相同的MITM代理方案，我用evplayer测试也未发现两者有差异。更可能的情况是，系统或者软件的代理设置不同等原因导致出现不同的结果。

**Comment by MegatronKing** [comment]
如果没有其他进一步的证据，这个issue我先关闭了。
