### ISSUE TITLE
[bug] 在Python安装目录包含中文的情况下脚本功能貌似无法识别到python

### ISSUE THREAD

**Issue by 2659170494** [reqable/reqable-app#22]
**Describe the bug**
脚本功能中目录包含中文无法识别到python

**To Reproduce**
只需在python目录包含中文就行

**Screenshots**
![image](https://user-images.githubusercontent.com/45305838/223750423-69d7b715-9ad7-4fb8-9104-7e06dd370947.png)

**Information**
 - Platform: windows
 - OS: 10
 - Arch: x86-64
 - App Version: 0.0.2

**Comment by 2659170494** [comment]
#19

**Comment by MegatronKing** [comment]
v0.0.3已修复。
