### ISSUE TITLE
[feature] 我是否可以脱离reqable的脚本编辑器使用reqable与python结合？

### ISSUE THREAD

**Issue by programday** [reqable/reqable-app#220]
我想把我的python框架结合reqable，但是我发现我并没有办法引入reqable这个库，自然也就没有办法使用相关的api了

![Snipaste_2023-09-21_18-36-05](https://github.com/reqable/reqable-app/assets/62821993/fd2432c3-28d5-49ac-98fa-cbe8f241714f)

而在reqable的脚本编辑器里面写一个框架感觉不现实

**Comment by MegatronKing** [comment]
@programday 你好，由于Reqable编辑器没有实现代码提示，编写确实有点麻烦。我会尽快开放python的reqable库，参见这个issue：#28

**Comment by MegatronKing** [comment]
目前的情况，你可以在VSCode或者其他IDE上参考Reqable官网的API文档编写：https://reqable.com/zh-CN/docs/capture/addons

**Comment by programday** [comment]
> @programday 你好，由于Reqable编辑器没有实现代码提示，编写确实有点麻烦。我会尽快开放python的reqable库，参见这个issue：#28

希望能尽早实现，有意愿为其付费

**Comment by MegatronKing** [comment]
@programday python api源码已开放，详见这个仓库：https://github.com/reqable/python-scripting-api。最新版本1.6.0，支持从Reqable的编辑器中也可以直接启动VS Code进行开发。
