### ISSUE TITLE
[bug] win端升级覆盖安装时下载完成后点击“安装”无响应

### ISSUE THREAD

**Issue by lwc8699793** [reqable/reqable-app#221]
![image](https://github.com/reqable/reqable-app/assets/51874230/b16ed0ea-3453-424f-8fde-0cdf46d9a1bb)

**Comment by lwc8699793** [comment]
我的系统信息：
![image](https://github.com/reqable/reqable-app/assets/51874230/959bdb97-b707-4235-bb60-eea3d6f20aea)

**Comment by MegatronKing** [comment]
最近的版本已经修复了。
