### ISSUE TITLE
[bug] 通过“reqable”模拟发送的请求在对比池中的“应用程序”显示为“未知”

### ISSUE THREAD

**Issue by lwc8699793** [reqable/reqable-app#222]
![image](https://github.com/reqable/reqable-app/assets/51874230/8415cdf4-4e66-4ddd-83fb-b3f59e6be864)

**Comment by MegatronKing** [comment]
@lwc8699793 原先列表中也是未知应用吗？还是仅仅是对比列表？

**Comment by lwc8699793** [comment]
> @lwc8699793 原先列表中也是未知应用吗？还是仅仅是对比列表？

都会显示“未知应用”
![image](https://github.com/reqable/reqable-app/assets/51874230/c567ef75-02a4-408c-9178-1bceacb08da3)

**Comment by MegatronKing** [comment]
@lwc8699793 v1.5.1已经修复此问题。
