### ISSUE TITLE
[feature] "保存Api"弹窗自动填写名称、通过键盘操作保存

### ISSUE THREAD

**Issue by moeakwak** [reqable/reqable-app#223]
保存Api是常用的功能。目前，保存一个Api需要手动输入名称，选择集合并点击保存。这就至少需要一次键盘输入和两次鼠标点击。希望能够完全通过键盘完成操作，并且简化这一保存流程：

1. 提供默认的Api名称。这可以从 url 中提取。例如，对于 `https://example.com/example/api`，名称默认为 `example/api`。
2. 允许通过按下 **Tab** 键从填写 title 跳转到选择集合区域，并且通过 **上下键** 选择集合。这里也可以考虑自动选择上一次使用的Api集合。
3. 在选择好集合的情况下，按下 **Enter** 即可保存。

<img src="https://github.com/reqable/reqable-app/assets/80299225/2af5ff54-3172-474c-90fb-bfbb5c5c8dfc" width="400" />

**Comment by MegatronKing** [comment]
@moeakwak 感谢建议，尽快安排！

**Comment by MegatronKing** [comment]
这个问题我拆分成了三个issue，由于下个月将开启移动端的millstone，考虑到开发周期，下个版本会暂时实现一部分。

**Comment by MegatronKing** [comment]
这个issue先关闭，具体跟踪详见子issue。
