### ISSUE TITLE
[bug] 重写不能转发本地 nodejs 服务的反向代理

### ISSUE THREAD

**Issue by kybetter** [reqable/reqable-app#224]
**Describe the bug**
重写不能转发本地 nodejs 服务的反向代理

我本来想从 proxyman 切到 reqable，配置重写后，发现访问页面不正常，头一个问题就是我本地 nodejs 的反向代理重写后不好使。
没办法，还是继续用 proxyman。

就是很简单的配置，proxyman 好使，reqable 就不好使：
https://www.abc.com/test/*  映射到本地服务：http://localhost:3000/test/*

**Comment by MegatronKing** [comment]
@kybetter 由于HTTP2依赖ALPN的问题，重写-重定向功能要求原始服务器是可响应的，也就是说`www.abc.com`这个域名能够连接。不知道你这边遇到的情况是否是原始服务器无法连接？

**Comment by MegatronKing** [comment]
下面是我测试的结果：
<img width="912" alt="截屏2023-09-23 13 57 32" src="https://github.com/reqable/reqable-app/assets/15059084/b437afc2-a36b-49a6-9a78-52e78a9b118c">
映射本地服务正常：
<img width="1192" alt="截屏2023-09-23 13 55 56" src="https://github.com/reqable/reqable-app/assets/15059084/a7af0c4c-30ff-4a9b-8db7-42367c876533">

**Comment by kybetter** [comment]
应该不是我这 node 服务的问题，因为我在用 proxyman 时，无论是访问页面还是请求接口都好使。
但是换到 reqable 后，访问页面正常，请请求接口就不好使了。

我的配置跟你上面发的完全一样。

你们可以尝试一下使用 nuxtjs v2 起一个服务，在里面配置一个接口的反向代理就能复现了。

我也再研究研究不同的配置看看是否真的是配置问题。

另外，proxyman 可以配 host，但我在 reqable 里似乎没找到。因为有这样的需求，把 nuxt 反向代理的接口域名指定到某个 host 上。

**Comment by MegatronKing** [comment]
@kybetter  丢失query的问题已修复，方便的话希望能帮忙确认下你的问题是否还存在。

**Comment by chenjiangui** [comment]
我也有这个问题 proxyman 支持 vite 的反向代理， 换成req后客户端看着能显示返回结果，node网页打开就xhr network error

**Comment by chenjiangui** [comment]
> @kybetter 丢失query的问题1.6.2版本已修复，方便的话希望能帮忙确认下你的问题是否还存在。

windows也是这个问题, req软件已经拿到response了, 但是nodejs进程拿到的是一个空的response

**Comment by MegatronKing** [comment]
@kybetter @chenjiangui Reqable已经更新到2.24.0版本，有空可以试试新版本。这个Issue我先关闭，如果有问题再打开。
