### ISSUE TITLE
[bug] API请求压缩json只影响显示

### ISSUE THREAD

**Issue by Haocen2004** [reqable/reqable-app#225]
**Describe the bug**
使用API发送请求json post请求时，点击编辑栏的压缩json，只会压缩显示的内容，而不会压缩最终发送的内容 除非再次编辑  
我知道未处理好空行是服务器的锅，但（

**To Reproduce**
```json
[
  {
    "id": 764,
    "song_name": "フィクサー",
    "level": "13",
    "level_index": 3,
    "achievements": 100.4086,
    "fc": null,
    "fs": null,
    "dx_score": 2026,
    "dx_rating": 290.62265184,
    "rate": "sss",
    "type": "standard"
  }
]
```
创建api时在请求体中填入带有换行的json
点击压缩
点击发送
同时转发到调试页面查看hex发现内容未变化
此时api页面切换json或text也会恢复空行

**Expected behavior**
删除空行且不再恢复

**Screenshots**
![QQ截图20230922235057](https://github.com/reqable/reqable-app/assets/25221696/9ff8ba89-092b-4524-bde9-c4c5bca883cb)

**Information**
 - Platform: windows
 - OS: 11
 - Arch: x86_64
 - App Version: 1.5.0(44)

**Comment by MegatronKing** [comment]
@Haocen2004 感谢反馈，已复现，将在下周一的版本修复。

**Comment by MegatronKing** [comment]
同样的，对于`美化`功能也有相同的问题，会一起修复了。

**Comment by MegatronKing** [comment]
@Haocen2004 v1.5.1已经修复。
