### ISSUE TITLE
[bug] 调试页面，系统代理图标显示错误

### ISSUE THREAD

**Issue by callng** [reqable/reqable-app#23]
Describe the bug

![R8IQRHJM2MF$G7K0K_Y3TY9](https://user-images.githubusercontent.com/64207250/223751241-f381b046-ebb0-40f1-9bed-e89dca4bc3ea.png)

软件启动的时候这个按钮就是开启状态，实际上系统的代理设置并没有打开，而且点击关闭 等2秒它又自己开了

Information

    Platform: windows
    OS: 11
    Version: 0.0.2

**Comment by MegatronKing** [comment]
@callng 方便的话，帮我跑个Powershell命令，看看结果和系统的代理设置是否一致：
```
Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings" | findstr ProxyServer
```

**Comment by callng** [comment]
@MegatronKing 
![图片](https://user-images.githubusercontent.com/64207250/224016940-fda82dc5-5153-4cae-830f-cc1620566f50.png)
结果一致。

**Comment by MegatronKing** [comment]
感谢支持，已复现，下个版本修复。

**Comment by MegatronKing** [comment]
v0.0.3已修复。
