### ISSUE TITLE
[feature] 主窗口试图添加过滤选项，比如我只想关注有setCookie的链接

### ISSUE THREAD

**Issue by sqw637** [reqable/reqable-app#230]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
@sqw637 这个试过吗？
![image](https://github.com/reqable/reqable-app/assets/15059084/b096a4ed-12b0-4f0e-a910-a3d20499817e)

**Comment by MegatronKing** [comment]
如果没有其他问题，这个issue我关闭了。
