### ISSUE TITLE
reqable-win10退出后钉钉不能联网

### ISSUE THREAD

**Issue by zhqianlong** [reqable/reqable-app#232]
reqable退出后钉钉登录加载验证码的时候提示网络错误，无法加载二维码
微信浏览器打开网页提示网络错误

**Comment by MegatronKing** [comment]
@zhqianlong 可能是未正常退出Reqable导致，系统网络代理没有关闭，你可以检查下系统网络代理是否还开着。另外，如果未退出Reqable的时候直接关机再开机后会出现此问题，因为Reqable只有在手动退出的时候才会关闭系统网络代理，这种情况是个bug，我会尽快解决这个问题。

**Comment by zhqianlong** [comment]
我是正常退出的  网络代理也没关，这应该是个bug，你也看看吧

**Comment by MegatronKing** [comment]
@zhqianlong 你是通过哪种方式退出的？

**Comment by zhqianlong** [comment]
我是windows系统，是系统右下角托盘图标 -> 退出

**Comment by MegatronKing** [comment]
@zhqianlong 代理图标是不是没法点绿？点绿一小会儿了又跳没了？
![image](https://github.com/reqable/reqable-app/assets/15059084/6545a41b-6769-4b17-bea3-fa3f821a41a7)

**Comment by zhqianlong** [comment]
之前没注意，现在好像又好了，就是退出后 系统代理就关了

**Comment by MegatronKing** [comment]
@zhqianlong 1.5.1小小优化了下关闭系统代理的逻辑，可能是生效了。如果没有问题这个issue我先关闭了，有问题再打开。
