### ISSUE TITLE
[bug] 生成python-requests代码中有错误

### ISSUE THREAD

**Issue by programday** [reqable/reqable-app#234]
生成的headers，cookie不可用，
例：
headers = {
  'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
  'pragma': "no-cache",
  'accept-language': "zh-CN,zh;q=0.9",
  'cookie': "visid_incap_2445686=MkMJmFxwQvGaC",
  'cookie': "incap_ses_894_2445686=IEfAVAZTKTJw5behN",
}
这个字典中有多个相同 键名，cookie，会导致最后一个cookie的值将之前的覆盖，导致我后续请求，cookie丢失很多
建议独立生成cookie

比如：
headers = {
  'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
  'pragma': "no-cache",
  'accept-language': "zh-CN,zh;q=0.9",
  }
cookies = {
    "visid_incap_2445686": "MkMJmFxwQvGaCc",
    "incap_ses_894_2445686": "IEfAVAZTKTJw5behN",
}

response = requests.get(url, headers=headers, cookies=cookies)

print(response.text)

**Comment by MegatronKing** [comment]
@programday 我在1.5.1版本将多个cookie的值合并了，仍然是放在headers中，没有独立出来。你可以更新后试试，如果还有问题，可以反馈给我，谢谢。

**Comment by MegatronKing** [comment]
如果没有问题，这个issue我先关闭了
