### ISSUE TITLE
[feature] 关于一些功能上的小建议

### ISSUE THREAD

**Issue by CoCoSuYa** [reqable/reqable-app#237]
**Is your feature request related to a problem? Please describe.**
从Charles转过来的，刚开始用软件根本记不住快捷键

**Describe the solution you'd like**
侧边栏那么空不如把一些快捷键功能放在旁边，尤其是调试里的清空功能等常用功能

**Comment by MegatronKing** [comment]
@CoCoSuYa 感谢建议。目前软件右下角有快捷键文档快速入口：
![image](https://github.com/reqable/reqable-app/assets/15059084/dfa1a354-a501-4b9e-930f-54c58d9473ca)
