### ISSUE TITLE
[feature] Change the arrangement of fields arbitrarily 想要自定义排序抓包列表的表头字段

### ISSUE THREAD

**Issue by wyf1463630616** [reqable/reqable-app#238]
**conditions**
url can only show behind name ,sometimes too long 
usually need to get other info  of apis instead of whole urls,so i want to customise sorts of  headers in session
大多数时候只需要看名称而不是完整的路径,希望在打开url显示的时候能自定义表头顺序
ex 
id method name code time url ...
希望可以把url放到最后,有需要的时候看详细路径

**Comment by MegatronKing** [comment]
@wyf1463630616 This is your want: https://reqable.com/docs/capture/list

**Comment by MegatronKing** [comment]
如果没有问题，这个issue我就关闭了。
