### ISSUE TITLE
[bug] 接口，无法对端口为6666的url进行访问

### ISSUE THREAD

**Issue by callng** [reqable/reqable-app#24]
![图片](https://user-images.githubusercontent.com/64207250/223752379-2f08867d-70b8-4885-8cc6-cfae42bbdb8a.png)

未知异常：net::ERR_UNSAFE_PORT
6666端口为默认的非安全端口，包含此端口的url无法从浏览器中访问，但Reqable不需要此限制。

Information

Platform: windows
OS: 11
Version: 0.0.2

**Comment by MegatronKing** [comment]
v0.0.3已修复
