### ISSUE TITLE
[bug] 为什么我重写请求或者启用脚本都会请求失败？

### ISSUE THREAD

**Issue by Afish-Cattle** [reqable/reqable-app#240]
![image](https://github.com/reqable/reqable-app/assets/52074348/d5975044-69aa-4999-ba12-272c84b7ae31)
![image](https://github.com/reqable/reqable-app/assets/52074348/7b143744-571e-433a-93ef-eaf573655941)
我启用脚本或者重写来修改请求时，都会请求失败，但重写来修改响应体是正常的

**Comment by MegatronKing** [comment]
@Afish-Cattle 检查一下下面几项：
1. 请求是否有签名，如果有签名是否有重签？
2. 如果没有签名，请求还是失败了，是哪一种失败？400，404还是什么？
3. 如果失败是没有任何响应反馈，可以提供一个能复现问题的case，方便我进行排查。

**Comment by Afish-Cattle** [comment]
> @Afish-Cattle 检查一下下面几项：
> 
> 1. 请求是否有签名，如果有签名是否有重签？
> 2. 如果没有签名，请求还是失败了，是哪一种失败？400，404还是什么？
> 3. 如果失败是没有任何响应反馈，可以提供一个能复现问题的case，方便我进行排查。

没有任何响应反馈，一直在CONNECT，请求头也没有新增脚本里的字段，想问下有什么办法导出日志给您排查吗？

**Comment by MegatronKing** [comment]
@Afish-Cattle 应用设置里面开启下调试日志开关，然后复现下问题后找到日志文件，如果不方便发这里，可以发送到我邮箱：coding@reqable.com

日志所在目录：
C:\Users\xxx\AppData\Roaming\Reqable\log

**Comment by wayswei** [comment]
这个应该是跟我之前遇到的问题是一样的 #207

**Comment by MegatronKing** [comment]
@wayswei 是的，确定挺像的，我也不知道是什么原因，也没法复现。看 @Afish-Cattle 什么时候方便，能够提供下相关日志。

**Comment by wayswei** [comment]
@MegatronKing 我现在不开二级代理依然也是有问题的，时好时坏。

**Comment by MegatronKing** [comment]
> @MegatronKing 我现在不开二级代理依然也是有问题的，时好时坏。

log is welcome

**Comment by wayswei** [comment]
@MegatronKing 阻塞住的时好像 没有相关 
`
windows "Windows 10 Home China" 10.0 (Build 22621) 1.6.0(46) x86_64 cpu(20)
09-28 17:10:40.1123 [I][Dart]: App logger is ready now.
09-28 17:10:40.1123 [V][Dart]: Pre-initing app...
09-28 17:10:40.1123 [V][Dart]: App pre-init done.
09-28 17:10:40.1123 [V][Dart]: Post-initing app...
09-28 17:10:40.1162 [V][Dart]: Initing netbare engine...
09-28 17:10:40.1172 [V][Dart]: Loading CA certificate...
09-28 17:10:40.1172 [V][Dart]: CA certificate is found from cache.
09-28 17:10:40.1192 [V][Dart]: App post-init done.
09-28 17:10:40.1341 [V][Dart]: Starting netbare engine on port 8351
09-28 17:10:40.1381 [I][Dart]: Netbare engine is ready!
09-28 17:10:40.2272 [I][Dart]: Capture redundancy file clean done!
09-28 17:10:40.4134 [V][Dart]: Event: app_start
09-28 17:10:40.4364 [V][Dart]: Detecting python env version: python3.exe
09-28 17:10:40.5508 [V][Dart]: Local IP detected: 10.110.3.245
09-28 17:10:40.5508 [V][Dart]: Local IP detected: 10.108.180.199
09-28 17:10:40.5508 [V][Dart]: Local IP detected: 192.168.31.132
09-28 17:10:40.5508 [V][Dart]: Local IP detected: 172.23.144.1
09-28 17:10:40.5508 [I][Dart]: Use local IP: 10.110.3.245
09-28 17:10:40.6057 [I][Dart]: Python env detect output: Python 3.10.11

09-28 17:10:40.7321 [I][Dart]: Check update ok, has update: false
09-28 17:10:44.9208 [V][Dart]: Event: menu_help_check_update
09-28 17:10:45.1223 [I][Dart]: Check update ok, has update: false
09-28 17:10:47.2486 [V][Dart]: Event: capture_engine_start
09-28 17:11:16.0741 [W][Dart]: Failed to detect process info for 56989
09-28 17:11:22.0854 [V][Dart]: Showing window capture_script_list
09-28 17:11:22.0854 [V][Dart]: Popuping window capture_script_list
09-28 17:11:22.0854 [V][Dart]: Event: window_popup_capture_script_list
09-28 17:11:25.1006 [V][Dart]: Popuping window capture_script_editor
09-28 17:11:25.1006 [V][Dart]: Event: window_popup_capture_script_editor
09-28 17:11:25.1640 [V][Dart]: Event: window_popup_capture_script_editor

`

**Comment by MegatronKing** [comment]
@wayswei 设置里面调试日志是不是没打开？

**Comment by wayswei** [comment]
@MegatronKing  https://api.xxxxxxx.com/settings 是POST请求 
[xxx_log.txt](https://github.com/reqable/reqable-app/files/12747997/xxx_log.txt)

**Comment by MegatronKing** [comment]
@wayswei 感谢提供，就是序号21的请求对吧，看起来确实是没有获取到响应，连接就断开了。我猜测可能是请求的协议出错了，导致服务器主动断开了连接，可以提供下https://api.xxxxxxx.com/settings的请求头吗，是不是有什么的编码或者压缩？

**Comment by MegatronKing** [comment]
很尴尬，我还是无法复现此问题。

**Comment by Afish-Cattle** [comment]
[20231013034101-db13cf60-699b-11ee-b313-9dedb3855efb.log](https://github.com/reqable/reqable-app/files/12890916/20231013034101-db13cf60-699b-11ee-b313-9dedb3855efb.log)

**Comment by MegatronKing** [comment]
@Afish-Cattle 感谢。我看了下没有报错，猜测可能是编码之类的问题，可以提供一个有问题请求的curl吗，我测试下。

**Comment by Afish-Cattle** [comment]
> @Afish-Cattle 感谢。我看了下没有报错，猜测可能是编码之类的问题，可以提供一个有问题请求的curl吗，我测试下。
有问题的请求无法复制curl，我只能复制出关闭重写后的curl
![image](https://github.com/reqable/reqable-app/assets/52074348/b699b5af-3230-4d0a-8bbf-5de85d085b13)

关闭重写后的curl：
curl -X POST 'https://api.zajiebao.com/api/common/user/get-member-base-info.do?sid=11013B5A30EEAEC53E31B5115F969A3336885D97F32F8ECF5AFAA211F823E48EFDDE250C290D3794' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'Content-Type: application/json' -H 'sec-ch-ua: "Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"' -H 'sid: 11013B5A30EEAEC53E31B5115F969A3336885D97F32F8ECF5AFAA211F823E48EFDDE250C290D3794' -H 'sec-ch-ua-mobile: ?0' -H 'sequenceId: 20231013163850821_2052924_1911860900_0622' -H 'App: advertisement' -H 'sec-ch-ua-platform: "Windows"' -H 'Origin: https://zajiebao.com' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Dest: empty' -H 'Referer: https://zajiebao.com/' -H 'Accept-Language: zh-CN,zh;q=0.9' -d '{"memberId":"1911860900"}'

**Comment by MegatronKing** [comment]
@Afish-Cattle 同样的请求，无法复现问题。话说你上面截图的图标怎么都挂了？
![image](https://github.com/reqable/reqable-app/assets/15059084/74b9b0db-7f13-4bf0-8a0a-5f5b091369e8)

**Comment by MegatronKing** [comment]
尝试使用Postman和curl命令发送请求，然后使用Reqable拦截重写也没有复现问题。换了windows设备，也没有复现。😂有点奇怪，不知道是哪里测试条件没有对齐。

**Comment by MegatronKing** [comment]
@Afish-Cattle Reqable已经更新到2.24.0版本，有空可以试试新版本。这个Issue我先关闭，如果有问题再打开。
