### ISSUE TITLE
脚本失效问题

### ISSUE THREAD

**Issue by kkopmm** [reqable/reqable-app#245]
使用SocksDroid对某个APP进行代理时，脚本会失效，使用WiFi代理时，脚本可以正常工作

**Comment by kkopmm** [comment]
这是失效的脚本，请求score的值也没被修改
![WW{]`B)Q%D}E~@E7SV1MBAN.png](https://github.com/reqable/reqable-app/assets/130914655/74e0cf80-d9fd-4994-a809-d5d267325aff)

![6APW0DRV8P097_(EOM5H2JX.png](https://github.com/reqable/reqable-app/assets/130914655/d6e9bfa1-bd85-4250-992e-ff4be629ee39)

**Comment by MegatronKing** [comment]
@kkopmm 感谢反馈，同 #251 ，1.6.1版本已修复。
