### ISSUE TITLE
[feature] 能否增加自动导出（符合特定规则的）包元数据

### ISSUE THREAD

**Issue by an-Underpriviliged-ZJUer** [reqable/reqable-app#248]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
@an-Underpriviliged-ZJUer 可以使用脚本功能，这里是一个自动保存图片的例子：
https://reqable.com/zh-CN/docs/capture/addons#%E7%A4%BA%E4%BE%8B3

**Comment by MegatronKing** [comment]
如果没有其他问题，这个issue我先关闭了。
