### ISSUE TITLE
[bug] 断点功能部分失效（请求断点失效      响应断点正常）

### ISSUE THREAD

**Issue by sunbin1028** [reqable/reqable-app#251]
**Describe the bug**
断点功能失效（请求断点失效      响应断点正常）

**Information**
 - Platform: [e.g. windows, macos, linux]
 - Windows: [e.g. 11]
 - Arch: [e.g.x86-64]
 - App Version: [e.g. 1.6.0]

**Comment by MegatronKing** [comment]
感谢反馈，1.6.1版本已修复。
