### ISSUE TITLE
[bug] POST请求，响应体为0，但响应体显示窗口，却不显示响应体0

### ISSUE THREAD

**Issue by RobustBody** [reqable/reqable-app#254]
POST请求，响应体只有一个字符 0 的时候，但响应体显示窗口，却不显示响应体0；
在重写功能模块，去替换或替换响应，都无法显示响应体；
在断点功能也一样。

我原本是要把响应体的0替换为其他数值，但发现无法替换。
软件版本是最新的，exe文件版本为：1.6.1.47
补充截图
![image](https://github.com/reqable/reqable-app/assets/68662195/cf2062a0-e7dd-40fb-809f-c51a6ba7a122)
![image](https://github.com/reqable/reqable-app/assets/68662195/9f864989-29f8-46f6-a35d-d13e19eb4590)

**Comment by MegatronKing** [comment]
@RobustBody 感谢反馈。我这边测试响应体只有一个字符的时候没有发现问题。不知道是否能提供具体的case方便进行测试对齐？
![image](https://github.com/reqable/reqable-app/assets/15059084/16957d96-44ac-4eac-8035-6a08cd258253)

**Comment by MegatronKing** [comment]
看到截图了，0是chunked编码，只有0的时候表示空请求或者空响应体，没有问题。

**Comment by RobustBody** [comment]
已用其他工具发包，确实就没有响应体，建议增加Content-Length: 0；
![image](https://github.com/reqable/reqable-app/assets/68662195/cf59f438-8d1a-44bb-a894-8f40945da724)

**Comment by MegatronKing** [comment]
> 建议增加Content-Length: 0

按照rfc规范，当使用chunked编码的时候，不能存在`Content-Length`头部；反之如果使用了`Content-Length`头部，就不能使用chunked编码；这两者是冲突的。至于是否选择使用chunked编码，是由服务器决定的。
