### ISSUE TITLE
[bug] 集合中保存的api发送，调试中无法显示

### ISSUE THREAD

**Issue by yd-coder** [reqable/reqable-app#257]
系统win10，reqable版本是最新版
之前都还正常，今天发送集合中保存的请求，在调试面板中无法抓到显示，已尝试重启软件，电脑。

**Comment by MegatronKing** [comment]
@yd-coder 跟随调试开关开启了吗？URL输入框最后面的信号图标点亮。

**Comment by yd-coder** [comment]
感谢！跟随调试开关开启后恢复正常，不小心关闭了
