### ISSUE TITLE
[feature] 开放Reqable脚本功能的Python库

### ISSUE THREAD

**Issue by 2659170494** [reqable/reqable-app#26]
**Is your feature request related to a problem? Please describe.**
pip不兼容嵌入版python，而没有源代码又不知道是否要编译代码或者该仓库需要什么关联库

**Describe the solution you'd like**
开放Reqable的Python库代码，方便自定义更改以及上传新功能

**Describe alternatives you've considered**
或许可以将内嵌库文件在软件的方式改成只用压缩包打包库文件？

**Comment by MegatronKing** [comment]
已完成：https://github.com/reqable/python-scripting-api
