### ISSUE TITLE
[feature] 新加一个脚本执行结果显示框

### ISSUE THREAD

**Issue by zzzzzshou** [reqable/reqable-app#262]
![image](https://github.com/reqable/reqable-app/assets/143604659/514a88ae-a555-400b-8647-5a42b424bee1)
建议在这个响应体旁边加一个框，能够显示一些脚本处理后的结果，例如这个发，返回值为加密结果，我已经知道了算法，可以写一个脚本来进行解密进而帮助分析接口情况。目前的脚本功能只提供了修改打印功能，如果只是打印的话，在日志中匹配很长一段的加密参数有些麻烦，可以把脚本执行结果对应的值放到新加的框里面，这样既不影响原始的返回值，也能够通过脚本结果框来看到明文帮助分析。感谢

**Comment by MegatronKing** [comment]
同 #261
