### ISSUE TITLE
Reqable for Android Devices

### ISSUE THREAD

**Issue by TechnoIndian** [reqable/reqable-app#266]
Sir,
      Can u provide Reqable for Android Devices Like Httpacanry

**Comment by MegatronKing** [comment]
@TechnoIndian We will open beta testing of the mobile app of Reqable as soon as the end of this month.

**Comment by TechnoIndian** [comment]
Thankyou So Much Sir

**Comment by MegatronKing** [comment]
See #71

**Comment by IamLoot** [comment]
> @TechnoIndian We will open beta testing of the mobile app of Reqable as soon as the end of this month.

May I know how to apply for beta? I want to become a beta tester.
