### ISSUE TITLE
[feature] 优化重写重定向功能

### ISSUE THREAD

**Issue by sunyuu** [reqable/reqable-app#267]
![image](https://github.com/reqable/reqable-app/assets/16495064/967b0630-f9ef-488d-8728-c56a88de925b)
这块功能有计划屏蔽掉原请求吗，只发送重写的请求，像其它常用的代理工具一样

**Comment by MegatronKing** [comment]
@sunyuu 这其实是两个问题，目前逻辑比较粗糙，后面会优化的。
1. 是否与原始服务器连接。由于Reqable支持HTTP2，HTTP2要求与原始服务器使用ALPN进行版本协商，可以理解成是一次握手。如果不与原始服务器通信就意味着要舍弃HTTP2的支持。但是Reqable的设计原则是尽量还原原始的请求信息，包括协议版本，如果仅仅给重写重定向功能设计一套新的逻辑机制，这个就复杂了，目前不会考虑。
2. 是否不向原始服务器发送请求。这个是可以的，后面会优化。
Reqable还提供了镜像的机制，将远程主机域名直接映射到localhost，不存在上面的问题，如果你的场景合适，可以试试镜像。当然，镜像目前不支持映射https域名到localhost，这个后面也会完善。

**Comment by sunyuu** [comment]
好的，希望2的后面可以实现，因为我们目前用这个来代理测试环境，需要根据路径匹配部分的代理到不同的环境，所以重写-重定向是最合适的功能

**Comment by mystery4f** [comment]
> @sunyuu 这其实是两个问题，目前逻辑比较粗糙，后面会优化的。
> 
> 1. 是否与原始服务器连接。由于Reqable支持HTTP2，HTTP2要求与原始服务器使用ALPN进行版本协商，可以理解成是一次握手。如果不与原始服务器通信就意味着要舍弃HTTP2的支持。但是Reqable的设计原则是尽量还原原始的请求信息，包括协议版本，如果仅仅给重写重定向功能设计一套新的逻辑机制，这个就复杂了，目前不会考虑。
> 2. 是否不向原始服务器发送请求。这个是可以的，后面会优化。
> 
> Reqable还提供了镜像的机制，将远程主机域名直接映射到localhost，不存在上面的问题，如果你的场景合适，可以试试镜像。当然，镜像目前不支持映射https域名到localhost，这个后面也会完善。

希望第（2）项可以实现，我需要它！

**Comment by ItosEO** [comment]
Android端重写功能预计多久可以上线 @MegatronKing

**Comment by MegatronKing** [comment]
v2.24.0已优化，重定向时不再向原始服务器发送请求。

**Comment by ItosEO** [comment]
> Android端重写功能预计多久可以上线

Android端重写功能预计多久可以上线
