### ISSUE TITLE
[bug] 启动时卡着了是什么情况？

### ISSUE THREAD

**Issue by Eikochan007** [reqable/reqable-app#268]
在先前的两个月的使用中没有任何问题
但昨天突然出现了这种情况
![bae0967621f0073369eba81901140c79](https://github.com/reqable/reqable-app/assets/41229998/1d6fc2d7-3b07-4b79-bf60-8ce6c615f7d6)
我尝试过重启、重装reqable
但似乎都没有办法解决这个问题...是啥冲突了吗

**Comment by MegatronKing** [comment]
@Eikochan007 您好，可能是出现bug了。希望可以提供个最新的日志给我排查下，目录见这里：https://reqable.com/docs/faq

**Comment by MegatronKing** [comment]
在这里上传日志后，可以尝试删除整个缓存目录再启动看看。

**Comment by Eikochan007** [comment]
@MegatronKing 好的，这是最新的log
[20231016095537-af2560c0-6c2b-11ee-8e98-a382fade203e.log](https://github.com/reqable/reqable-app/files/12917531/20231016095537-af2560c0-6c2b-11ee-8e98-a382fade203e.log)

**Comment by Eikochan007** [comment]
已解决，感谢
