### ISSUE TITLE
[bug] mac 启用代理后请求连不上

### ISSUE THREAD

**Issue by nsyujian** [reqable/reqable-app#269]
**Screenshots**
![Xnip2023-10-17_18-07-05](https://github.com/reqable/reqable-app/assets/8776592/2e6d1d7d-343c-4cab-9dc2-766ecb9bc3fd)

**Information**
 - Platform: [macos]
 - OS: [14.0]
 - Arch: [arm]
 - App Version: [1.6.2（48）]

**Comment by nsyujian** [comment]
> @nsyujian 大概率是端口冲突了，试试换个端口看看。Reqable会自动检测端口是否占用然后更换端口，但是有些时候检测不出来，就会出现类似的情况。

换过8888报一样的错

**Comment by MegatronKing** [comment]
@nsyujian 试试socks5协议：
```
curl -x socks5://localhost:9000 http://reqable.com -v
```

**Comment by nsyujian** [comment]
还是端口冲突了，改了个不常用的好了
