### ISSUE TITLE
[bug] 还原客户端URL编码规范

### ISSUE THREAD

**Issue by MegatronKing** [reqable/reqable-app#271]
重写、脚本、断点等修改操作需要保持原始客户端URL编码规范，比如`*`号是否需要编码，如果和服务器解码规范对应不上可能导致请求失败。

**Comment by blueidea2500** [comment]
比如分辨率的参数 result = 640*768 ，但由于转码，在服务端检测就过不了，请求就失败了。

**Comment by MegatronKing** [comment]
另一个case：空格是编码成`+`还是`%20`?

**Comment by MegatronKing** [comment]
v2.18.0已经优化。
