### ISSUE TITLE
[feature] 根据应用程序、方法类型等筛选抓取的请求

### ISSUE THREAD

**Issue by tiam-bloom** [reqable/reqable-app#274]
**Is your feature request related to a problem? Please describe.**
当抓取到很多请求时， 我需要只关心某一个应用程序或者其他的请求， 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
@tiam-bloom 参考文档：https://reqable.com/zh-CN/docs/capture/search

**Comment by tiam-bloom** [comment]
你好, 貌似并没有根据应用程序筛选的功能, 不过有其他类型的我看到了


***@***.***
 
发件人： Megatron King
发送时间： 2023-10-18 17:06
收件人： reqable/reqable-app
抄送： Tiam; Mention
主题： Re: [reqable/reqable-app] [feature] 根据应用程序、方法类型等筛选抓取的请求 (Issue #274)
@tiam-bloom 参考文档：https://reqable.com/zh-CN/docs/capture/search

**Comment by MegatronKing** [comment]
最新版本有应用程序筛选，看这个视频：https://reqable.com/zh-CN/assets/medias/arts_zh-4f53ff715486c4e06df6485ed454c012.mp4

**Comment by z0z0r4** [comment]
> reqable.com/zh-CN/assets/medias/arts_zh-4f53ff715486c4e06df6485ed454c012.mp4

this video not found
