### ISSUE TITLE
[bug]Mac版本(m1芯片)的reqable在使用过程中经常出现无法抓包，抓包数据不显示

### ISSUE THREAD

**Issue by changxingang** [reqable/reqable-app#277]
官网下载的最新版本：
bug1：关闭监控端口关闭代理后再次开启，无法抓包
操作步骤
1、正常启动后使用一段时间，点击停止，关闭系统代理。
2、等待几分钟后开启系统代理，点击启动监控端口9000.
3、手机再次请求接口，手机无网络，必须重启reqable才行(必现)

bug2：正常使用过程中偶现无法抓包
1、正常启动后使用一段时间，偶现无法抓包，手机网络不通，必须重启

bug3：启动系统代理后，在启用监控9000端口，其他浏览器不能正常使用(这个很重要，下载的当天是正常的，后来就不行了，官网没有找到相关问题)

**Comment by MegatronKing** [comment]
@changxingang 感谢反馈。

### bug1和bug2：

从问题的描述来看无法确定问题所在。建议在`手机网络不通，必须重启`问题发生后，打开Reqable左下角设置页面勾选打开`调试日志`功能，手机上再测试一下，然后把最新的日志（~/Library/Caches/Reqable/log目录下面）发我看看。

如果上面操作嫌麻烦，可以在问题发生后，用下面的curl命令测试一下Reqable是否能连通。

```
curl -x localhost:9000 http://reqable.com -v
```

另外，调试远程设备是不需要开启系统代理的。

### bug3:

看起来像是系统代理没有生效，可以检查下Mac系统设置里面网络代理是否配置成功了。

**Comment by changxingang** [comment]
![img_v2_d96da004-b277-4034-8116-4b1fbf51a84g](https://github.com/reqable/reqable-app/assets/42930095/060e7cd7-8db3-4e87-8381-5c767cbf3aec)
出现后的截图如上，是bug2的

**Comment by MegatronKing** [comment]
@changxingang 感觉是9000端口被别的软件占用了，换个端口试试？

**Comment by MegatronKing** [comment]
@changxingang 请问问题是否还存在？

**Comment by changxingang** [comment]
> @changxingang 请问问题是否还存在？

还存在，能经常遇到，并且可以确认端口没有被占用。

**Comment by ByteSecurity** [comment]
ios 下有 SSL Pending ，正确安装证书也解不开他； 
只有越狱环境下开启 [SSL Kill Switch2](https://github.com/nabla-c0d3/ssl-kill-switch2) 才行

@MegatronKing 这个问题不用深究

**Comment by changxingang** [comment]
> ios 下有 SSL Pending ，正确安装证书也解不开他； 只有越狱环境下开启 [SSL Kill Switch2](https://github.com/nabla-c0d3/ssl-kill-switch2) 才行
> 
> @MegatronKing 这个问题不用深究

为什么一开始正常，使用一段时候就不正常？有时候一天也不会遇到一次，有时候一个小时遇到好几次？
另外还有其他问题，
1、正常抓包时，会出现某个接口不显示，实际上发起请求了(通过安卓的日志发现接口请求了），但是reqable没有显示，也没有转发，导致数据错误，重启之后就正常
2、正常使用时，会突然出现所有接口都不显示，

**Comment by MegatronKing** [comment]
@changxingang 我需要日志才能进一步分析。可以在Reqable设置里面打开`调试日志`开关，复现下问题后，将日志发我（coding@reqable.com），日志目录在：~/Library/Caches/Reqable/log

**Comment by changxingang** [comment]
> @changxingang 我需要日志才能进一步分析。可以在Reqable设置里面打开`调试日志`开关，复现下问题后，将日志发我（[coding@reqable.com](mailto:coding@reqable.com)），日志目录在：~/Library/Caches/Reqable/log

你好，我再次出现问题后，到你提供的 目录下没有查找到Reqable文件，我是看到你的回复就开启了调试，
![uZxUhQZvsX](https://github.com/reqable/reqable-app/assets/42930095/3d99c3c9-da52-49db-bc48-b35c11e7d691)
在12号左右，今天有遇到问题了，发现没有这个文件
![mdJfOg4dcF](https://github.com/reqable/reqable-app/assets/42930095/45e3d52a-5b2f-48bd-945b-6c350256ec89)
，然后我开始测试这个调试功能，我再勾选这个调试后，刷新/Library/Caches，也没有Reqable文件，包括重启APP，在次勾选，勾选后重启APP，都没有这个文件。
<img width="682" alt="image" src="https://github.com/reqable/reqable-app/assets/42930095/ad09a4c8-6dea-46c2-aa5f-44c110c97f49">

**Comment by changxingang** [comment]
那个自动调试我也够选了，测试重启，等场景，也没有日志文件目录。

**Comment by MegatronKing** [comment]
@changxingang 在用户目录下， 是～/Library 不是 /Library

**Comment by MegatronKing** [comment]
@changxingang 请问问题是否还存在？

**Comment by changxingang** [comment]
> @changxingang 请问问题是否还存在？

问题还存在，在遇到我把日志发出来

**Comment by MegatronKing** [comment]
@changxingang 已发布2.3.0版本，可以试试。如果还有问题，麻烦把日志发我看看。

**Comment by MegatronKing** [comment]
@changxingang 如果没有问题，这个issue我先关闭了。
