### ISSUE TITLE
[bug] 界面字体适配问题

### ISSUE THREAD

**Issue by StLeoX** [reqable/reqable-app#279]
**Describe the bug**
界面字体适配存在问题。

**To Reproduce**
界面字体过小，影响使用体验。
无法拖动窗口边界以扩大窗口。

**Expected behavior**
提供调节字体的选项。

**Information**
 - Platform: linux
 - OS: Linux Mint 21
 - Arch: x86-64
 - App Version: 1.0.4

**Comment by MegatronKing** [comment]
@StLeoX 按理说会自动适配系统设置的比例缩放的，能给个截个图我看看吗？

**Comment by MegatronKing** [comment]
字体功能见这个：#175

**Comment by StLeoX** [comment]
![2023-10-25_11-43-24](https://github.com/reqable/reqable-app/assets/59193798/0cdccea0-1f27-494f-b3cb-a68c92f349e7)

软件字体明显较小。

**Comment by MegatronKing** [comment]
@StLeoX 因人而异，这个确实只能通过调整字体大小来解决，字体调整这个功能已经在做了。参见 #175 ，重复问题我先关闭了。
