### ISSUE TITLE
[bug] [Windows] 托盘图标右键菜单栏会有机率失效

### ISSUE THREAD

**Issue by 2659170494** [reqable/reqable-app#28]
**Describe the bug**
右击托盘图标弹出菜单栏无论点击哪个按钮都无反应，包括退出和显示窗口。单击图标可以正常显示窗口，在0.0.2也出现过这个问题。

**To Reproduce**
在程序后台挂机，有一定机率会出现这个bug

**Information**
 - Platform: windows
 - OS: 10
 - Arch: x86-64
 - App Version: 0.0.3

**Comment by MegatronKing** [comment]
@2659170494 0.0.5版本又出现吗

**Comment by 2659170494** [comment]
> @2659170494 0.0.5版本又出现吗

目前使用中没有遇到🤔
