### ISSUE TITLE
[feature] 请求列表选择交互优化

### ISSUE THREAD

**Issue by devcxm** [reqable/reqable-app#280]
现状【macOS版本】：
1、双击某个请求展示请求详情界面，再双击该请求关闭界面；
2、在展开请求详情界面情况双击列表空白处没任何反应。

建议：
在原有交互上，已经展开请求详情界面情况下，双击列表空白处，关闭展开的请求详情界面。

**Comment by MegatronKing** [comment]
@devcxm 很好的建议，非常感谢！

**Comment by MegatronKing** [comment]
@devcxm 实现了，可以试试2.0.0-preview5版本：https://github.com/reqable/reqable-app/releases/tag/2.0.0-preview5
