### ISSUE TITLE
Android app ? [feature] 

### ISSUE THREAD

**Issue by albhost** [reqable/reqable-app#281]
What's dates coming android app ? Thanks

**Comment by MegatronKing** [comment]
@albhost The mobile version is still under development and it will take about 1-2 weeks to release the first beta test version.

**Comment by IamLoot** [comment]
> @albhost The mobile version is still under development and it will take about 1-2 weeks to release the first beta test version.

May I know how to apply for beta? Or how will i get beta app when it's available. I want to test your beta app before it released.

**Comment by MegatronKing** [comment]
> May I know how to apply for beta? Or how will i get beta app when it's available. I want to test your beta app before it released.

Thanks for following Reqable mobile app. Beta testing requires logging in with an annual license, after completing the testing preparations, I will deploy the APK to the official website and `Github Releases`, and notify all the annual subscription users by email.

**Comment by MegatronKing** [comment]
https://github.com/reqable/reqable-app/releases/tag/2.0.0-preview1
