### ISSUE TITLE
[bug] 无法启动抓包

### ISSUE THREAD

**Issue by zxerqw** [reqable/reqable-app#282]
**Describe the bug**
今天打开就是这样了，什么也没做
![image](https://github.com/reqable/reqable-app/assets/16666177/ea297b0d-7e85-4b24-9909-b810529fe8e3)

**Information**
 - Platform: windows x64
 - App Version:1.6.2

**Comment by MegatronKing** [comment]
@zxerqw 更换下端口试试？

**Comment by zxerqw** [comment]
换了一个其他端口可以了，不知道为啥这个8888没被占用也一直提示被占用

**Comment by changxingang** [comment]
![image](https://github.com/reqable/reqable-app/assets/42930095/688f8bc1-ce5b-4e33-adf6-d27a313722f3)
你看看这个提示啥，我这边是同时连接两个网络，一个网线，一个wifi(这2个网一个是移动，一个是电信)也会出现网络不通，不在一个局域网。

**Comment by MegatronKing** [comment]
> ![image](https://user-images.githubusercontent.com/42930095/279591896-688f8bc1-ce5b-4e33-adf6-d27a313722f3.png) 你看看这个提示啥，我这边是同时连接两个网络，一个网线，一个wifi(这2个网一个是移动，一个是电信)也会出现网络不通，不在一个局域网。

这个感叹号只是表示检测到了多个IP。如果在手机上通过局域网连接调试，选择正确的局域网IP配置代理即可，电脑单机使用没影响可以不用管。

**Comment by zxerqw** [comment]
感叹号倒是没啥，换ip的，不过换个端口问题就修复了，感谢
