### ISSUE TITLE
[feature] 重放功能建议增加并发数设置

### ISSUE THREAD

**Issue by popokcn** [reqable/reqable-app#284]
刚刚用重发功能抢优惠券，总次数设置9999，另外都是0。58秒的时候点开始，直接卡住了，然后过了10几秒，拉起255个并发线程开始重发了。而且根本找不到在哪里停止的按钮，只能结束整个APP进程。

建议增加一个并发数选项，像charles一样
![image](https://github.com/reqable/reqable-app/assets/17810922/a224a8d6-48c0-46ad-90c6-b1cad4401e0c)
比如并发我只要5，然后间隔延时都是0，总次数设置高一些，这样就能一直发了。而且发送过程中，建议重放的对话框不隐藏，上面有停止按钮。

**Comment by MegatronKing** [comment]
这个功能不是给你抢券用的。

**Comment by popokcn** [comment]
我只是说了其中一个使用场景而已，就算是纯粹测试用，没有并发数量选项也是不科学，不灵活的。同类工具，基本都是有线程数可以选择的。
