### ISSUE TITLE
[feature] 增加自动设置代理的设置项

### ISSUE THREAD

**Issue by MUKAPP** [reqable/reqable-app#285]
**Describe the solution you'd like**
发现每次打开reqable都会自动设置系统代理，但是我一般是使用手机模拟器进行抓包，用不到系统代理，反而会把梯子的代理顶掉
我觉得可以增加一个自动设置代理的设置项，默认开启，有需求再关闭就可以了

**Comment by RonaldinhoL** [comment]
右键地球图标，有一个选项关闭自动开启系统代理

**Comment by MUKAPP** [comment]
> 右键地球图标，有一个选项关闭自动开启系统代理

好家伙，藏挺好（）
