### ISSUE TITLE
[feature] 增加一个快捷按钮快速定位到当前选择的行

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#286]
当搜索指定的请求以后，当前选中的行会改变，这时我们按 esc，并希望观察上下文的其他包，但是列表会变成从头开始，希望此时会自动滚动到当前选择的行，或者增加一个按钮可以快速定位到当前选中的列表行

**Comment by MegatronKing** [comment]
@RonaldinhoL 

试试这个版本：https://github.com/reqable/reqable-app/releases/tag/2.0.0-preview5
快捷键：Control + L

**Comment by MegatronKing** [comment]
2.0.0没有问题的话，issue先关闭了。
