### ISSUE TITLE
[feature] 增加一个专门的 cookie 选项卡

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#287]
![image](https://github.com/reqable/reqable-app/assets/1797392/aee2ca61-c7d3-4d98-8e18-43f57c663085)

如图，有时候会特别关注 cookie 的情况，当前需要去headers里面找 Cookies 或者 SetCookie ，像花瓶一样有一个专门的 cookie 页就会特别方便

**Comment by MegatronKing** [comment]
@RonaldinhoL 这个有计划，后续会出自定义Tab管理，顺便会把这个做了。

**Comment by MegatronKing** [comment]
同 #203
