### ISSUE TITLE
[bug] [Windows] 软件退出后进程没有被终止

### ISSUE THREAD

**Issue by ShiFangJuMie** [reqable/reqable-app#29]
**Describe the bug**
如标题所述

**To Reproduce**
1. 启动软件
2. 在调试页面点开始
3. 在调试页面点停止
4. 右上角X掉软件
5. 右下角菜单栏右键，选择退出

**Expected behavior**

**Screenshots**
![屏幕截图 2023-03-16 212324](https://user-images.githubusercontent.com/9131886/225631718-80b197b6-4e48-405f-ad86-2bd5d292b0b9.png)

**Information**
 - Platform: Windows
 - OS: 10 企业版 22H2
 - Arch: [e.g. arm, x86-64]
 - App Version: 0.0.3+3

**Comment by MegatronKing** [comment]
@ShiFangJuMie 可以试试0.0.5版本，应该已经修复了

**Comment by MegatronKing** [comment]
同 #30 #28
