### ISSUE TITLE
兄弟忽略了一个最大的使用人群

### ISSUE THREAD

**Issue by midasjx** [reqable/reqable-app#292]
一，兄弟忽略了一个最大的使用人群
易语言最多人用来测试的
竟然没有支持易语言生成的代码，你可以根据精易模块的生成代码
二，双击 抓包到的数据，弹出的总览信息窗口的大小总是固定，没有记录上次调整过的尺寸。很不方便

三，抓包到的数据的第一列，应该设置一个，双击就会变成小红星的快捷标记，不然老是要右键，再选择颜色，很浪费时间

四。对比的功能做得太好。 对比应该是对比各个参数，无论是POST还是GET ，有的少了一个参数也没有发现

五，编辑重发的时候，有的删除了一些头部参数，或增加了一些参数后，，竟然没有复制修改后的功能

六，抓包到的数据的图标列，颜色都是一样的，不能不够醒目的识别

七，数据列太短时，URL又太长时，看不到URL全部  鼠标移到这一行时，没有显示全部内容，很不方便，

八，数据列不能调整排序，有的希望 URL 前列是其它内容，很难调整

九，可能的话，，希望给个免费的帐号测试一下，过虑功能等

希望reqable 越来越好，做到行业NO1

**Comment by midasjx** [comment]
易语言是国内某小众群体，没错，但可是写外挂，测试网站等的使用量，易语言说第一没有人敢说第二。增加不增加这个生成代码，随你喜好了。只不过是错过一大群潜在客户。做买卖也是要有客户精准定位，往往抓住一小众客户，都够生存和发展了。

五，编辑重发的时候，有的删除了一些头部参数，或增加了一些参数后，，竟然没有复制修改后的功能

****是说修改了数据后，修改的数据无法保存，也没有办法复制 **** 

十,  个人觉得 HttpAnalyzer  这个老牌应用做得还行，可以多参考参考
     每次开机，启动 HttpAnalyzer，打开 Microsoft Edge，后马上就可以抓包到数据出来。
     而 reqable 则是启动无法抓出数据出来，要替换了一下应用，等一会才有数据出来

**Comment by midasjx** [comment]
十  一  ，  保存和导入 过虑规则的  功能是不是没有？

十二， 像这样的 https://reqable.com/zh-CN/assets/js/935f2afb.423639c9.js    
            .js 网址，响应体，竟然是空! 明明是有数据

**Comment by MegatronKing** [comment]
> 易语言是国内某小众群体，没错，但可是写外挂，测试网站等的使用量，易语言说第一没有人敢说第二。

你说对了，这就是为什么没有做易语言的原因。Reqable是正规的API生产测试工具，所以烦请那些最大的使用人群有多远请走多远。

**Comment by hegu365** [comment]
抓个包非得用这玩意么，虽然我也用易语言，但是没做过灰产，但是这语气很多很nice

**Comment by hegu365** [comment]
没眼看
