### ISSUE TITLE
[bug] 代理无法启动，启动了不到几秒钟就会自动关闭，贴出了日志

### ISSUE THREAD

**Issue by xiaolan66** [reqable/reqable-app#294]
macos 版本13.6（版号22G120） 1.6.2(48) x86_64 cpu(6)
11-14 14:47:06.5308 [I][Dart]: App logger is ready now.
11-14 14:47:06.5308 [V][Dart]: Pre-initing app...
11-14 14:47:06.5309 [V][Dart]: App pre-init done.
11-14 14:47:06.5314 [V][Dart]: Post-initing app...
11-14 14:47:06.5374 [V][Dart]: Initing netbare engine...
11-14 14:47:06.5415 [V][Dart]: Loading CA certificate...
11-14 14:47:06.5418 [V][Dart]: CA certificate is found from cache.
11-14 14:47:06.5432 [V][Dart]: App post-init done.
11-14 14:47:06.5532 [V][Dart]: Starting netbare engine on port 8000
11-14 14:47:06.5536 [I][Dart]: Netbare engine is ready!
11-14 14:47:06.8334 [V][Dart]: Event: app_start
11-14 14:47:06.8578 [V][Dart]: Detecting python env version: python3
11-14 14:47:06.9117 [V][Dart]: Local IP detected: 192.168.2.3
11-14 14:47:06.9118 [I][Dart]: Use local IP: 192.168.2.3
11-14 14:47:07.0335 [I][Dart]: Check update ok, has update: false
11-14 14:47:07.1062 [E][Dart]: Failed to enable proxy Assertion failed: ""
11-14 14:47:20.1567 [V][Dart]: Event: capture_proxy_on

11-14 14:47:20.3688 [E][Dart]: Failed to enable proxy Assertion failed: ""
11-14 14:47:21.3065 [V][Dart]: Event: capture_engine_start

**Comment by MegatronKing** [comment]
@xiaolan66 感谢反馈，我看看。

**Comment by MegatronKing** [comment]
@xiaolan66 试试这个命令行，看看打印什么：
```
networksetup -listallnetworkservices
```

**Comment by xiaolan66** [comment]
An asterisk (*) denotes that a network service is disabled.
MT65xx Preloader
*Ethernet
Ethernet 2.2
*iPhone USB

我是开启了固定ip

**Comment by MegatronKing** [comment]
@xiaolan66 感谢，再试试这个命令能不能生效：
```
networksetup -setsecurewebproxy 'MT65xx Preloader' 127.0.0.1 9000 && networksetup -setwebproxy 'MT65xx Preloader' 127.0.0.1 9000 && networksetup -setautoproxystate 'MT65xx Preloader' off && networksetup -setsecurewebproxy 'Ethernet 2.2' 127.0.0.1 9000 && networksetup -setwebproxy 'Ethernet 2.2' 127.0.0.1 9000 && networksetup -setautoproxystate 'Ethernet 2.2' off
```

**Comment by xiaolan66** [comment]
这样没问题，代理是正常工作，的但是软件上面的  代理地球图标还是一样的，点亮了几秒钟就熄灭了
还有我发现了，如果我是dhcp模式的话，软件就是正常工作的，我如果用固定ip 就会出现我说的问题

**Comment by xiaolan66** [comment]
估计就是启用代理的操作，其实并没有对固定ip的网卡生效，因为我看了里面确实没有相关的代理信息

**Comment by MegatronKing** [comment]
> 估计就是启用代理的操作，其实并没有对固定ip的网卡生效，因为我看了里面确实没有相关的代理信息

请问仅仅跑上面的命令，不在软件里面操作也不用管软件代理图标的状态。从系统设置里面看，固定IP的网卡代理是不是设置成功了？

**Comment by xiaolan66** [comment]
是的

**Comment by MegatronKing** [comment]
ok，我知道问题所在了，下个版本应该就修复了。非常感谢配合！

**Comment by MegatronKing** [comment]
@xiaolan66 是否可以试试2.0.0-preview5版本，应该已经修复了这个问题：https://github.com/reqable/reqable-app/releases/tag/2.0.0-preview5

**Comment by zrqbug** [comment]
我的1.6.2版本还是存在这个问题

**Comment by MegatronKing** [comment]
@zrqbug 1.6.2是有问题的，楼上那个2.0.0-preview5版本你试了吗？

**Comment by MegatronKing** [comment]
最新2.0.0版本理论上已经修复了这个bug，问题先关闭。
