### ISSUE TITLE
[feature] Reqable for Andoid device

### ISSUE THREAD

**Issue by TechnoIndian** [reqable/reqable-app#297]
Sir, when are you releasing the Android version? You said in October last.

Or you can update 'Httpcnary' only.

**Comment by MegatronKing** [comment]
@TechnoIndian Here：https://github.com/reqable/reqable-app/releases/tag/2.0.0-preview1

**Comment by TechnoIndian** [comment]
**HttpCanary Batter Then Reqable because HttpCanary Free Apk**
