### ISSUE TITLE
[feature] 调试过滤器支持暂时禁用某个搜索项

### ISSUE THREAD

**Issue by Zrincet** [reqable/reqable-app#298]
目前可以增加或者减少某个搜索项，但是不能做到临时禁用某个搜索项。
场景：可以在不同搜索项之间快速切换，提高不同场景接口的查找能力

**Comment by MegatronKing** [comment]
有道理，感谢建议。

**Comment by MegatronKing** [comment]
#329 需求更为完整，请跟进那个issue，这个先关闭。

**Comment by MegatronKing** [comment]
@Zrincet v2.4.0已支持。
