### ISSUE TITLE
[question] Will the Android version be paid?

### ISSUE THREAD

**Issue by whyakari** [reqable/reqable-app#299]
Hello, I downloaded the application and it asks for a license. How can I acquire it?

**Comment by MrIkso** [comment]
@MegatronKing Hi, possible open source for old project http canary?

**Comment by MegatronKing** [comment]
@MrIkso No such plan.

**Comment by MrIkso** [comment]
> @MrIkso No such plan.

Why? What are the reasons for this. Do not create new competitors or plans to use the code in commercial projects?
