### ISSUE TITLE
[bug] 右下角托盘已经操作退出后，并不能完全退出

### ISSUE THREAD

**Issue by abinnz** [reqable/reqable-app#30]
**Describe the bug**
右下角托盘已经操作退出后，并不能完全退出

**To Reproduce**
1. 右下角托盘操作退出
2. 重新双击打开应用后提示应用正常运行

**Expected behavior**
应用完全退出

**Screenshots**
![image](https://user-images.githubusercontent.com/13955662/226116093-dbbe5d48-ad50-4c7c-9c57-a84eeb22ca79.png)

**Information**
 - Platform: windows
 - OS: 10
 - Arch: x86-64
 - App Version:  0.0.4

**Comment by MegatronKing** [comment]
@abinnz 可以试下0.0.5版本，应该修复了

**Comment by abinnz** [comment]
@MegatronKing 0.0.5版本没出现这个问题了
