### ISSUE TITLE
体验建议

### ISSUE THREAD

**Issue by superen7527** [reqable/reqable-app#305]
1.可以多选列表保存记录，我找了一下午发现有一些重要的链接多选出来后只能改颜色，而不能批量保存导出，看了一个多小时文档也没找到相关信息。以前httpcanary就可以保存。重新打开只有历史记录还要重新筛选 不利于继续分析，只有发起http请求调试才能保存。

2.选中文本方式有点问题，双击文本以后，只能往右，往左会丢失。而window正常体验是左右都不会丢失最开始选中文本。

3.工具里面，有一些可以多窗口打开，有一些不行.比如jwt同时只能打开一个 不好对比。

4.http的post请求有点问题，测试发不出去参数 同样的设置在别的http测试工具没问题。

5.选中文本右键建议增加直接使某个工具或者智能或者根据频率或者自己设置右键菜单快速解析，比如选中base64可以直接解码，选中时间可以时间戳，等等

6.选中文本建议可以直接右键搜索，或者在其他记录里找哪个包含了该文本，快速定位上下文。

5和6是我最近最想要的 因为一堆数据来来回回复制粘贴进工具箱和搜索 剪切板记录乱而且还不能多窗口都是截图记录。一次次来来回回也好麻烦，降低了效率。

**Comment by MegatronKing** [comment]
@superen7527 感谢建议，很中肯，这几个点我先简要回答下。
1. 多选记录可以右键保存HAR文件，不然碎片文件太多了。后面可能会开放保存到新建目录。
2. 确实不能往左，后面可以优化，问题不大。
3. 有的确实限制了打开一个，我担心开太多关起来麻烦，这点还需要考虑。
4. 希望能给个例子，能够让我复现这个问题，不然不好解决。
5. 这个功能是有的，可能你没有发现。
6. 右键菜单确实没有搜索，选中后可以用快捷键Control + F，效果是一样的。

**Comment by MegatronKing** [comment]
> 建议可以像保存api调试一样，直接保存到文件夹里，不需要额外导出。毕竟导出还是没有界面直观。

我感觉你需求的是收藏功能，不知道我理解得对不对。

> 这个例子不太好给。

确实需要一个具体例子，因为我没法复现你说的问题。

> 可以说一下如何使用吗？

选中后右键不是有编码和解码选项吗？

**Comment by MegatronKing** [comment]
@superen7527 

> 2.选中文本方式有点问题，双击文本以后，只能往右，往左会丢失。而window正常体验是左右都不会丢失最开始选中文本。

试试这个版本：

https://github.com/reqable/reqable-app/releases/tag/2.0.0-preview4

**Comment by MegatronKing** [comment]
> 选择表单模式软件会自动优化变成{1:2}写法，但是右上角修改变成文本模式却不能改回1=2&这种写法，手动写文本提交后也会自动变回:模式(在字符串后面加上了冒号)。
我觉得文本模式应该是最原始的模式，格式化以后方便修改的模式可以用你的优化版本，这样比较好，你觉得呢？

key:value 这种批量编辑的写法是业内常用的方式，比如postman也是这样。
