### ISSUE TITLE
如何抓局域网的包

### ISSUE THREAD

**Issue by superen7527** [reqable/reqable-app#306]
有考虑抓其他地址吗？看了一下交换机抓包好麻烦。有时候我在虚拟机跑东西，数据在另一个网段，本机抓不到。以后会不会支持？

**Comment by MegatronKing** [comment]
@superen7527 只要在同一个局域网内，都可以代理到reqable的地址和端口。本机使用地址是127.0.0.1，局域网内其他设备需要使用局域网地址，比如192.168.1.3。

**Comment by MegatronKing** [comment]
> 你好，我测试过，虚拟机桥接到局域网地址，没有发现该局域网地址，也不能自定义地址只能自定义端口

本机IP地址是路由器自动分配的，当然你可以在网络设置里固定，但是对你的这个问题根本没有帮助。。

**Comment by MegatronKing** [comment]
对的，在桌面端调试Android也是类似的原理，这个问题我先关闭了。
