### ISSUE TITLE
[feature] 可否加入Charles的Map Remote

### ISSUE THREAD

**Issue by WuMe-sicx** [reqable/reqable-app#308]
建议添加一个远程映射功能
方便后期管理源站的静态js和css重定向到其他服务器上的静态文件
如有其它操作方式,请留言说明一下 感谢！！！

**Comment by MegatronKing** [comment]
@WuMe-sicx 看下这两个：
镜像：https://reqable.com/zh-CN/docs/capture/mirror
重写重定向：https://reqable.com/zh-CN/docs/capture/rewrite#redirect
