### ISSUE TITLE
抓包某款app时 响应信息没有了

### ISSUE THREAD

**Issue by heckerstone** [reqable/reqable-app#309]
在抓包某款app时可能存在中间人检测导致连接中断没有响应

**Comment by heckerstone** [comment]
![image](https://github.com/reqable/reqable-app/assets/12561095/772ca0a4-757d-47c0-923c-08175c9d9108)

**Comment by MegatronKing** [comment]
@heckerstone 如果你觉得是reqable的bug请提供详细的信息。

**Comment by heckerstone** [comment]
样本如下：
[Uploading wy32.apk.zip…]()
