### ISSUE TITLE
[feature] 重写功能不支持ws协议, 镜像功能中域名与镜像域名是默认同协议, 没有修改的地方

### ISSUE THREAD

**Issue by itmier** [reqable/reqable-app#310]
重写和镜像现在的功能不太灵活, 希望可以优化一下

使用场景: 微信绑定|微信登录的本地调试, 需要实现将 `https://www.baidu.com重定向到 http://localhost:8000` , 但是本地项目是 `dev`  环境, 热更新时会有 `ws`  链接, 使用重写功能访问时, 会导致一直`ws`  连接失败,一直刷新, 镜像功能使用时必须同一协议, 无法实现 `https`  到 `http` , 所以这个比较常见的需求`reqable`  无法满足, 希望可以优化一下

**Comment by MegatronKing** [comment]
@itmier 有这个优化计划，看看这个 #267 是不是差不多？

**Comment by itmier** [comment]
刚看到,
是差不多, 看到这个:
> Reqable还提供了镜像的机制，将远程主机域名直接映射到localhost，不存在上面的问题，如果你的场景合适，可以试试镜像。当然，镜像目前不支持映射https域名到localhost，这个后面也会完善。

镜像可以算映射的快捷实现, 但还是希望重定向上也能实现, 并且重定向的条件希望可以多一些条件选择, 如并, 且, 或者直接正则,
希望早日实现~ @MegatronKing
