### ISSUE TITLE
[feature] 代理的方式不支持

### ISSUE THREAD

**Issue by hpp0hpp** [reqable/reqable-app#312]
**Is your feature request related to a problem? Please describe.**

如微信反馈，此代理方式目前不支持，会导致连接中断

相关wireshark记录
[wireshark.zip](https://github.com/reqable/reqable-app/files/13458706/wireshark.zip)

**Describe the solution you'd like**
希望能添加支持

**Comment by MegatronKing** [comment]
2.0.0-preview5版本确认已经修复。
