### ISSUE TITLE
[bug] System Certificate installation issue

### ISSUE THREAD

**Issue by RamuSriram** [reqable/reqable-app#321]
**Describe the bug**
Encountering difficulty installing the System Certificate using Magisk Modules like Cert Mover and AdGuard Cert. While attempts to directly copy the CA Certificate to the /system/etc/security/cacerts directory result in a "Remount RW failed" error, the User Certificate works fine though. How can the System Certificate be made to work?

**To Reproduce**
1. Utilize Magisk Modules such as Cert Mover or AdGuard Cert.
2. Try copying the CA Certificate to /system/etc/security/cacerts.
3. Face "Remount RW failed" error.
4. Even with Magisk Modules, the certificate doesn't appear in System Certificates (in Settings), and Reqable fails to detect it despite the certificate is in /system/etc/security/cacerts directory.

**Screenshots**
![IMG_20231204_080232](https://github.com/reqable/reqable-app/assets/71754546/19507fa7-243d-4b0a-b8fb-463b2dda699f)
![IMG_20231204_080116](https://github.com/reqable/reqable-app/assets/71754546/6013b992-4598-4fb3-9b97-8a9a155deb09)

**Information**
 - Platform: Android
 - OS: Oxygen OS 14, Android 14
 - Architecture: ARM 64
 - App Version: 2.0.0-preview4

**Comment by MegatronKing** [comment]
@RamuSriram Sorry, my knowledge on this part is extremely limited. Android 14 has made some changes to the certificate mechanism. 

https://www.reddit.com/r/ReverseEngineering/comments/16aontf/android_14_blocks_all_modification_of_system/
