### ISSUE TITLE
[feature] Add floating window 

### ISSUE THREAD

**Issue by RamuSriram** [reqable/reqable-app#322]
**Is your feature request related to a problem? Please describe.**
Currently, there's a need to consistently return to the app to monitor the captured traffic.

**Describe the solution you'd like**
Integrate Picture-in-Picture (PIP) or Floating Window functionality, similar to what was available in HttpCanary previously.

**Comment by MegatronKing** [comment]
PiP mode is available starting from v2.3.2 version now.
