### ISSUE TITLE
[bug] connect 链接一直提示握手失败

### ISSUE THREAD

**Issue by 382960875** [reqable/reqable-app#323]
![image](https://github.com/reqable/reqable-app/assets/65341944/ee4591f9-2429-4cad-a66d-9d1a6088049a)

**Comment by MegatronKing** [comment]
@382960875 感谢反馈，请问有复现步骤吗？

**Comment by 382960875** [comment]
开了二级代理, 转发到clash 然后就这样了

**Comment by MegatronKing** [comment]
> 开了二级代理, 转发到clash 然后就这样了 @MegatronKing

换句话说，是不是不开二级代理就没问题

**Comment by 382960875** [comment]
是的  @MegatronKing

**Comment by iszhangsc** [comment]
IOS 代理也是一样

**Comment by MegatronKing** [comment]
@382960875 @iszhangsc 试试最新版本v2.2.0是否仍然存在此问题。如果仍然存在，可以打开设置 - 调试日志开关，复现后，提供下日志。日志目录在 `C:\Users\xxx\AppData\Roaming\Reqable\log`下面。

**Comment by MegatronKing** [comment]
没法复现，没有进一步的信息，这issue我先关闭了。
