### ISSUE TITLE
[feature] 几个新功能建议

### ISSUE THREAD

**Issue by jjustwin** [reqable/reqable-app#325]
1.环境变量，参考如postman，集合中就可以参数化，
2.结果提取器，类似于postman的Test，配合环境变量的写入和读取，可以做到自动化执行，
3.网络限制，如带宽限制、丢包率限制、延迟限制，这个功能可以完全在付费功能里，
4.数据同步，登录账号后同步数据。

以上是鄙人日常工作中会用到的功能，作者大人可以看看

**Comment by MegatronKing** [comment]
> 1.环境变量，参考如postman，集合中就可以参数化，

同 #6

2.结果提取器，类似于postman的Test，配合环境变量的写入和读取，可以做到自动化执行，

同 #263 

3.网络限制，如带宽限制、丢包率限制、延迟限制，这个功能可以完全在付费功能里，

同 #14 

4.数据同步，登录账号后同步数据。

同 #205

**Comment by MegatronKing** [comment]
感谢反馈，如果没有特别的需求，这个issue我将作为重复问题关闭了。
