### ISSUE TITLE
[feature] 是否考虑支持透明代理模式

### ISSUE THREAD

**Issue by yinsel** [reqable/reqable-app#326]
如题。

**Comment by MegatronKing** [comment]
@yinsel 目前还不支持，请问你们透明代理模式的应用场景是什么？

**Comment by yinsel** [comment]
> @yinsel 目前还不支持，请问你们透明代理模式的应用场景是什么？

透明代理抓包分析，针对客户端App部分包抓不到的情况

**Comment by MegatronKing** [comment]
@yinsel 我不了解透明代理的操作，你可以试试最新版本2.0.0-preview5，看看有什么具体问题

**Comment by MegatronKing** [comment]
没有进一步的信息，这个问题先关闭了。
