### ISSUE TITLE
[bug] 安卓14如何导入证书？

### ISSUE THREAD

**Issue by lllAlex2333** [reqable/reqable-app#327]
官方文档中的adb方法对于安卓14无效，作者有其他方式移动证书到系统吗？

**Comment by MegatronKing** [comment]
@lllAlex2333 Android 14更新了证书机制，你按照文档操作遇到的问题是什么？

**Comment by lllAlex2333** [comment]
你好，我后来发现不是证书的问题，我换了一台电脑就正常了，能抓到包。
当时出现的问题是，电脑上的reqable抓不到任何来自手机的包，换了一台手机也还是不行。电脑是win11系统，能抓电脑自己的包，就是抓不到安卓上的。然后安卓手机的表现为上不去网，浏览器访问网页提示 err_time_out

**Comment by lsdlh** [comment]
能否增加证书magisk模块

**Comment by MegatronKing** [comment]
> 你好，我后来发现不是证书的问题，我换了一台电脑就正常了，能抓到包。 当时出现的问题是，电脑上的reqable抓不到任何来自手机的包，换了一台手机也还是不行。电脑是win11系统，能抓电脑自己的包，就是抓不到安卓上的。然后安卓手机的表现为上不去网，浏览器访问网页提示 err_time_out

wifi代理，还是用的协同模式？

**Comment by MegatronKing** [comment]
> 能否增加证书magisk模块

我对magisk并不懂，但是也不想在这方面花时间，所以很抱歉答案是不能。

**Comment by lllAlex2333** [comment]
> > 你好，我后来发现不是证书的问题，我换了一台电脑就正常了，能抓到包。 当时出现的问题是，电脑上的reqable抓不到任何来自手机的包，换了一台手机也还是不行。电脑是win11系统，能抓电脑自己的包，就是抓不到安卓上的。然后安卓手机的表现为上不去网，浏览器访问网页提示 err_time_out
> 
> wifi代理，还是用的协同模式？

wifi代理

**Comment by MegatronKing** [comment]
@lllAlex2333 看你这个现象，感觉像是电脑防火墙禁止访问reqable的代理端口了。

**Comment by MegatronKing** [comment]
没有进一步的信息，这个问题先关闭了。
