### ISSUE TITLE
[feature] 清除列表时不清除工作台勾选记录

### ISSUE THREAD

**Issue by ByteSecurity** [reqable/reqable-app#328]
**功能：**

1. 清理历史记录的时候，能不能不要把工作台域名勾选记录给清掉了

> 每次清理后，重新抓，需要在一堆域名里找刚才fork的域名，好麻烦

3. 只勾选目标域名，其他域名能不能不解https，甚至不抓包(charles, fiddler 都可以做到)

> 举个例子，在ios下，开着reqable后，只跟踪目标域名，这时候 appstore下载 和 有些谷歌服务没法用(SSL双层绑定的)

4. 脚本适配到指定url的时候，能不能在 包详情栏里单独一个 lab 显示

>  直接用python脚本写解密脚本，不在控制台输出，而是在详情独立的lab输出 方便查看解密后的发送和回复的明文,fiddler已有

**bug：**

1. mac下 reqable 脚本功能有问题：**无法在自带编辑器里保存**，无法唤起vscode

> mac下装了vscode，并且安装了启动命令， 使用 code +路径能打开文件

**Comment by MegatronKing** [comment]
@ByteSecurity 感谢反馈。关于这几个问题，我回答下。

> 1. 清理历史记录的时候，能不能不要把工作台域名勾选记录给清掉了

确实有这个问题，我尽快修复。

> 3. 只勾选目标域名，其他域名能不能不解https，甚至不抓包(charles, fiddler 都可以做到)

有SSL Bypass（SSL旁路）功能，把不需要的域名加进去；只处理某个域名或者URL你可以使用PC上Reqable的网关功能。

> 脚本适配到指定url的时候，能不能在 包详情栏里单独一个 lab 显示

后面会做，同 #261

> mac下 reqable 脚本功能有问题：无法在自带编辑器里保存，无法唤起vscode

应该会自动保存的，当然也可以试试 Command + S 快捷键手动保存。无法唤起vscode，这个我目前没有复现，如果方便的话提供下日志：~/Library/Caches/Reqable/log

**Comment by MegatronKing** [comment]
@ByteSecurity 新建的脚本保存确实有问题，我发现了，下个版本修复。无法唤起vscode，无法复现。

**Comment by ByteSecurity** [comment]
感谢回复 ~
3： “把不需要的域名加进去”  代理一旦开启，域名增量是无可预估的，如果专注域名模式不太好设计， 现在也能用 哈哈

脚本无法保存的日志：
`macos Mac13 版本12.5.1（版号21G83） 2.0.05(53) arm64 cpu(10)
12-12 13:34:28.6193 [I][Dart]: App logger is ready now.
12-12 13:34:28.6194 [V][Dart]: Pre-initing app...
12-12 13:34:28.6195 [V][Dart]: App pre-init done.
12-12 13:34:28.6216 [V][Dart]: Post-initing app...
12-12 13:34:28.6284 [V][Dart]: Initing netbare engine...
12-12 13:34:28.6318 [V][Dart]: Loading CA certificate...
12-12 13:34:28.6323 [V][Dart]: CA certificate is found from cache.
12-12 13:34:28.6375 [V][Dart]: App post-init done.
12-12 13:34:28.6391 [V][Dart]: Starting netbare engine on port 9000
12-12 13:34:28.6393 [I][Dart]: Netbare engine is ready!
12-12 13:34:28.6402 [I][Dart]: Capture SSL enabled: true
12-12 13:34:28.9166 [I][Dart]: Capture redundancy file clean done!
12-12 13:34:28.9231 [V][Dart]: Event: app_start
12-12 13:34:28.9833 [V][Dart]: Detecting python env version: /Users/username/.pyenv/shims/python3
12-12 13:34:28.9835 [I][Dart]: [Collabrotive] Server is running on port 12312
12-12 13:34:28.9983 [V][Dart]: Local IP detected: 10.0.0.13
12-12 13:34:28.9983 [I][Dart]: Use local IP: 10.0.0.13
12-12 13:34:29.0385 [I][Dart]: Python env detect output: Python 3.10.4

12-12 13:34:29.0980 [I][Dart]: Check update ok, has update: false
12-12 13:34:41.6380 [V][Dart]: Showing window capture_script_list
12-12 13:34:41.6381 [V][Dart]: Popuping window capture_script_list
12-12 13:34:41.6381 [V][Dart]: Event: window_popup_capture_script_list
12-12 13:34:46.8732 [E][Dart]: PathNotFoundException: Deletion failed, path = '/Users/username/Library/Caches/Reqable/scripts/12dada60-6ce4-11ee-a00b-67e06b593053' (OS Error: No such file or directory, errno = 2)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 80389, tid: 6134919168, name io.flutter.ui
os: macos arch: arm64 comp: no sim: no
isolate_dso_base: 118000000, vm_dso_base: 118000000
isolate_instructions: 118007dc0, vm_instructions: 118002300
    #00 abs 000000011882c30b _kDartIsolateSnapshotInstructions+0x82454b
    #01 abs 000000011841b92f _kDartIsolateSnapshotInstructions+0x413b6f
    #02 abs 000000011841b887 _kDartIsolateSnapshotInstructions+0x413ac7
    #03 abs 0000000118157d5f _kDartIsolateSnapshotInstructions+0x14ff9f
    #04 abs 000000011815af3f _kDartIsolateSnapshotInstructions+0x15317f
    #05 abs 000000011815aa6b _kDartIsolateSnapshotInstructions+0x152cab
    #06 abs 0000000118010243 _kDartIsolateSnapshotInstructions+0x8483
    #07 abs 000000011841b7e7 _kDartIsolateSnapshotInstructions+0x413a27
    #08 abs 000000011841b6ff _kDartIsolateSnapshotInstructions+0x41393f
    #09 abs 0000000118502b8b _kDartIsolateSnapshotInstructions+0x4fadcb
    #10 abs 000000011826d03f _kDartIsolateSnapshotInstructions+0x26527f
    #11 abs 000000011826ce0b _kDartIsolateSnapshotInstructions+0x26504b
    #12 abs 00000001189e6fd3 _kDartIsolateSnapshotInstructions+0x9df213
    #13 abs 00000001185b49e3 _kDartIsolateSnapshotInstructions+0x5acc23
    #14 abs 0000000118564d77 _kDartIsolateSnapshotInstructions+0x55cfb7
    #15 abs 00000001185a8f67 _kDartIsolateSnapshotInstructions+0x5a11a7
    #16 abs 000000011822d82b _kDartIsolateSnapshotInstructions+0x225a6b
    #17 abs 000000011822d5a7 _kDartIsolateSnapshotInstructions+0x2257e7
    #18 abs 00000001189bc897 _kDartIsolateSnapshotInstructions+0x9b4ad7
    #19 abs 000000011804334b _kDartIsolateSnapshotInstructions+0x3b58b
    #20 abs 000000011885ddc3 _kDartIsolateSnapshotInstructions+0x856003
    #21 abs 00000001180432c7 _kDartIsolateSnapshotInstructions+0x3b507
    #22 abs 000000011804323f _kDartIsolateSnapshotInstructions+0x3b47f
    #23 abs 0000000118160d67 _kDartIsolateSnapshotInstructions+0x158fa7
    #24 abs 00000001189bc7eb _kDartIsolateSnapshotInstructions+0x9b4a2b
    #25 abs 0000000118043157 _kDartIsolateSnapshotInstructions+0x3b397
    #26 abs 00000001180430af _kDartIsolateSnapshotInstructions+0x3b2ef
    #27 abs 0000000118042bab _kDartIsolateSnapshotInstructions+0x3adeb
    #28 abs 00000001189c294b _kDartIsolateSnapshotInstructions+0x9bab8b
    #29 abs 000000011805899b _kDartIsolateSnapshotInstructions+0x50bdb
    #30 abs 0000000118032077 _kDartIsolateSnapshotInstructions+0x2a2b7
    #31 abs 0000000118031fb7 _kDartIsolateSnapshotInstructions+0x2a1f7
    #32 abs 0000000118031f43 _kDartIsolateSnapshotInstructions+0x2a183

12-12 13:34:50.0359 [V][Dart]: Event: capture_script_on
12-12 13:34:50.0378 [V][Dart]: Event: capture_script_on
12-12 13:34:54.2699 [E][Dart]: PathNotFoundException: Deletion failed, path = '/Users/username/Library/Caches/Reqable/scripts/12dada60-6ce4-11ee-a00b-67e06b593053' (OS Error: No such file or directory, errno = 2)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 80389, tid: 6134919168, name io.flutter.ui
os: macos arch: arm64 comp: no sim: no
isolate_dso_base: 118000000, vm_dso_base: 118000000
isolate_instructions: 118007dc0, vm_instructions: 118002300
    #00 abs 000000011882c30b _kDartIsolateSnapshotInstructions+0x82454b
    #01 abs 000000011841b92f _kDartIsolateSnapshotInstructions+0x413b6f
    #02 abs 000000011841b887 _kDartIsolateSnapshotInstructions+0x413ac7
    #03 abs 0000000118157d5f _kDartIsolateSnapshotInstructions+0x14ff9f
    #04 abs 000000011815af3f _kDartIsolateSnapshotInstructions+0x15317f
    #05 abs 000000011815aa6b _kDartIsolateSnapshotInstructions+0x152cab
    #06 abs 0000000118010243 _kDartIsolateSnapshotInstructions+0x8483
    #07 abs 000000011841b7e7 _kDartIsolateSnapshotInstructions+0x413a27
    #08 abs 000000011841b6ff _kDartIsolateSnapshotInstructions+0x41393f
    #09 abs 0000000118502b8b _kDartIsolateSnapshotInstructions+0x4fadcb
    #10 abs 000000011826d03f _kDartIsolateSnapshotInstructions+0x26527f
    #11 abs 000000011826ce0b _kDartIsolateSnapshotInstructions+0x26504b
    #12 abs 00000001189e6fd3 _kDartIsolateSnapshotInstructions+0x9df213
    #13 abs 00000001185b49e3 _kDartIsolateSnapshotInstructions+0x5acc23
    #14 abs 0000000118564d77 _kDartIsolateSnapshotInstructions+0x55cfb7
    #15 abs 00000001185a8f67 _kDartIsolateSnapshotInstructions+0x5a11a7
    #16 abs 000000011822d82b _kDartIsolateSnapshotInstructions+0x225a6b
    #17 abs 000000011822d5a7 _kDartIsolateSnapshotInstructions+0x2257e7
    #18 abs 00000001189bc897 _kDartIsolateSnapshotInstructions+0x9b4ad7
    #19 abs 000000011804334b _kDartIsolateSnapshotInstructions+0x3b58b
    #20 abs 000000011885ddc3 _kDartIsolateSnapshotInstructions+0x856003
    #21 abs 00000001180432c7 _kDartIsolateSnapshotInstructions+0x3b507
    #22 abs 000000011804323f _kDartIsolateSnapshotInstructions+0x3b47f
    #23 abs 0000000118160d67 _kDartIsolateSnapshotInstructions+0x158fa7
    #24 abs 00000001189bc7eb _kDartIsolateSnapshotInstructions+0x9b4a2b
    #25 abs 0000000118043157 _kDartIsolateSnapshotInstructions+0x3b397
    #26 abs 00000001180430af _kDartIsolateSnapshotInstructions+0x3b2ef
    #27 abs 0000000118042bab _kDartIsolateSnapshotInstructions+0x3adeb
    #28 abs 00000001189c294b _kDartIsolateSnapshotInstructions+0x9bab8b
    #29 abs 000000011805899b _kDartIsolateSnapshotInstructions+0x50bdb
    #30 abs 0000000118032077 _kDartIsolateSnapshotInstructions+0x2a2b7
    #31 abs 0000000118031fb7 _kDartIsolateSnapshotInstructions+0x2a1f7
    #32 abs 0000000118031f43 _kDartIsolateSnapshotInstructions+0x2a183

12-12 13:34:58.7211 [V][Dart]: Popuping window capture_script_editor
12-12 13:34:58.7213 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:34:58.7365 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:35:08.6723 [V][Dart]: Popuping window capture_script_editor
12-12 13:35:08.6724 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:35:08.6868 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:36:21.5737 [V][Dart]: Popuping window capture_script_editor
12-12 13:36:21.5738 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:36:21.5903 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:37:55.2259 [V][Dart]: Event: capture_engine_start
12-12 13:38:13.2755 [V][Dart]: Event: sidebar_open_by_tab
12-12 13:39:30.2647 [V][Dart]: Popuping window capture_script_editor
12-12 13:39:30.2647 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:39:30.2790 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:39:31.8762 [E][Dart]: Assertion failed: "/bin/sh: code: command not found\n"
12-12 13:39:38.4432 [E][Dart]: Assertion failed: "/bin/sh: code: command not found\n"
12-12 13:42:27.9520 [E][Dart]: Assertion failed: "/bin/sh: code: command not found\n"
12-12 13:42:28.9794 [E][Dart]: Assertion failed: "/bin/sh: code: command not found\n"
12-12 13:42:29.2234 [E][Dart]: Assertion failed: "/bin/sh: code: command not found\n"
12-12 13:42:29.4620 [E][Dart]: Assertion failed: "/bin/sh: code: command not found\n"
12-12 13:42:29.8136 [E][Dart]: Assertion failed: "/bin/sh: code: command not found\n"
12-12 13:42:31.4818 [E][Dart]: Assertion failed: "/bin/sh: code: command not found\n"
12-12 13:42:41.7618 [E][Dart]: Assertion failed: "/bin/sh: code: command not found\n"
12-12 13:42:48.3195 [V][Dart]: Popuping window capture_script_editor
12-12 13:42:48.3195 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:42:48.3295 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:43:14.7019 [V][Dart]: Popuping window capture_script_editor
12-12 13:43:14.7019 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:43:14.7083 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:43:19.9368 [V][Dart]: Popuping window capture_script_editor
12-12 13:43:19.9370 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:43:19.9486 [V][Dart]: Event: window_popup_capture_script_editor
12-12 13:50:43.0748 [V][Dart]: Event: menu_app_check_update
12-12 13:50:43.1941 [I][Dart]: Check update ok, has update: false
12-12 13:52:04.8115 [V][Dart]: Event: capture_engine_stop
12-12 13:55:54.0997 [V][Dart]: Event: capture_detail_on
12-12 13:55:56.4809 [V][Dart]: Event: capture_detail_off
12-12 13:55:57.3827 [V][Dart]: Event: capture_detail_on
12-12 15:04:01.6895 [V][Dart]: Event: work_show_menu_at_index_0
12-12 15:04:02.3673 [V][Dart]: Event: capture_list_clear
12-12 15:04:11.8513 [V][Dart]: Event: capture_engine_start
12-12 15:20:17.8879 [V][Dart]: Event: work_show_menu_at_index_0
12-12 15:20:18.5149 [V][Dart]: Event: capture_list_clear
12-12 15:20:35.6888 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:20:35.6905 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:20:40.5685 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:20:40.5686 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:20:49.2366 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:20:49.2367 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:20:51.3687 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:20:51.3688 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:20:53.9492 [V][Dart]: Event: capture_list_record_copy_url
12-12 15:23:17.5053 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:23:17.5055 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:23:25.3024 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:23:25.3025 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:40:08.2898 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:40:08.2899 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:40:11.7234 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:40:11.7235 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:40:26.9053 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:40:26.9054 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:40:36.5551 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:40:36.5551 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:40:40.3727 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:40:40.3728 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:40:43.4554 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:40:43.4555 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:40:45.6396 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:40:45.6397 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 15:40:51.9058 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 15:40:51.9059 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:32:12.6148 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 16:32:12.6149 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:32:25.7988 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 16:32:25.7989 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:32:31.3709 [V][Dart]: Event: capture_list_records_repeat
12-12 16:32:32.2485 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 16:32:32.2485 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:35:07.9834 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 16:35:07.9835 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:35:10.6686 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 16:35:10.6687 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:37:42.0120 [V][Dart]: Event: capture_list_records_repeat
12-12 16:37:44.8818 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 16:37:44.8819 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:37:45.4829 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 16:37:45.4830 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:37:46.6501 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 16:37:46.6502 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:37:49.4583 [V][Dart]: Event: capture_list_records_repeat
12-12 16:37:54.2170 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 16:37:54.2171 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:37:54.7494 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 16:37:54.7495 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 16:53:36.7759 [E][Dart]: FormatException: Filter error, bad data
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 80389, tid: 6126366720, name io.flutter.ui
os: macos arch: arm64 comp: no sim: no
isolate_dso_base: 118000000, vm_dso_base: 118000000
isolate_instructions: 118007dc0, vm_instructions: 118002300
    #00 abs 00000001189d60e7 _kDartIsolateSnapshotInstructions+0x9ce327
    #01 abs 0000000118a51b47 _kDartIsolateSnapshotInstructions+0xa49d87
    #02 abs 00000001180bb727 _kDartIsolateSnapshotInstructions+0xb3967
    #03 abs 00000001180bd1af _kDartIsolateSnapshotInstructions+0xb53ef
    #04 abs 0000000118a6508b _kDartIsolateSnapshotInstructions+0xa5d2cb
    #05 abs 00000001188263af _kDartIsolateSnapshotInstructions+0x81e5ef
    #06 abs 00000001189b8a97 _kDartIsolateSnapshotInstructions+0x9b0cd7
    #07 abs 0000000118816e6b _kDartIsolateSnapshotInstructions+0x80f0ab
    #08 abs 00000001186edacf _kDartIsolateSnapshotInstructions+0x6e5d0f
    #09 abs 00000001186ed9df _kDartIsolateSnapshotInstructions+0x6e5c1f
    #10 abs 00000001180b6a23 _kDartIsolateSnapshotInstructions+0xaec63
    #11 abs 000000011884233b _kDartIsolateSnapshotInstructions+0x83a57b
    #12 abs 000000011801745b _kDartIsolateSnapshotInstructions+0xf69b
    #13 abs 000000011801767b _kDartIsolateSnapshotInstructions+0xf8bb
    #14 abs 00000001189b5197 _kDartIsolateSnapshotInstructions+0x9ad3d7
    #15 abs 0000000118016c6b _kDartIsolateSnapshotInstructions+0xeeab
    #16 abs 0000000118017a17 _kDartIsolateSnapshotInstructions+0xfc57
    #17 abs 000000011802e3b3 _kDartIsolateSnapshotInstructions+0x265f3
    #18 abs 00000001180148ff _kDartIsolateSnapshotInstructions+0xcb3f
    #19 abs 00000001189b43e3 _kDartIsolateSnapshotInstructions+0x9ac623
    #20 abs 0000000118014877 _kDartIsolateSnapshotInstructions+0xcab7

12-12 16:53:36.7820 [E][Dart]: FormatException: Filter error, bad data
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 80389, tid: 6126366720, name io.flutter.ui
os: macos arch: arm64 comp: no sim: no
isolate_dso_base: 118000000, vm_dso_base: 118000000
isolate_instructions: 118007dc0, vm_instructions: 118002300
    #00 abs 00000001189d60e7 _kDartIsolateSnapshotInstructions+0x9ce327
    #01 abs 0000000118a51b47 _kDartIsolateSnapshotInstructions+0xa49d87
    #02 abs 00000001180bb727 _kDartIsolateSnapshotInstructions+0xb3967
    #03 abs 00000001180bd1af _kDartIsolateSnapshotInstructions+0xb53ef
    #04 abs 0000000118a6508b _kDartIsolateSnapshotInstructions+0xa5d2cb
    #05 abs 00000001188263af _kDartIsolateSnapshotInstructions+0x81e5ef
    #06 abs 00000001189b8a97 _kDartIsolateSnapshotInstructions+0x9b0cd7
    #07 abs 0000000118816e6b _kDartIsolateSnapshotInstructions+0x80f0ab
    #08 abs 00000001186edacf _kDartIsolateSnapshotInstructions+0x6e5d0f
    #09 abs 00000001186ed9df _kDartIsolateSnapshotInstructions+0x6e5c1f
    #10 abs 00000001180b6a23 _kDartIsolateSnapshotInstructions+0xaec63
    #11 abs 000000011884233b _kDartIsolateSnapshotInstructions+0x83a57b
    #12 abs 000000011801745b _kDartIsolateSnapshotInstructions+0xf69b
    #13 abs 000000011801767b _kDartIsolateSnapshotInstructions+0xf8bb
    #14 abs 00000001189b5197 _kDartIsolateSnapshotInstructions+0x9ad3d7
    #15 abs 0000000118016c6b _kDartIsolateSnapshotInstructions+0xeeab
    #16 abs 0000000118017a17 _kDartIsolateSnapshotInstructions+0xfc57
    #17 abs 000000011802e3b3 _kDartIsolateSnapshotInstructions+0x265f3
    #18 abs 00000001180148ff _kDartIsolateSnapshotInstructions+0xcb3f
    #19 abs 00000001189b43e3 _kDartIsolateSnapshotInstructions+0x9ac623
    #20 abs 0000000118014877 _kDartIsolateSnapshotInstructions+0xcab7

12-12 17:12:12.5904 [V][Dart]: Event: capture_list_record_copy_url
12-12 17:13:03.8588 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 17:13:03.8590 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 17:14:01.1274 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 17:14:01.1276 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 17:14:02.6629 [V][Dart]: Event: capture_list_record_copy_url
12-12 17:16:26.2101 [W][Dart]: Failed to prettify with HttpBodyType.json
12-12 17:16:26.2102 [W][Dart]: Failed to prettify with HttpBodyType.xml
12-12 17:31:11.8239 [V][Dart]: Event: capture_detail_on
12-12 17:55:56.9843 [V][Dart]: Event: capture_search_on
12-12 17:56:36.2159 [V][Dart]: Event: capture_list_highlight_record_red
12-12 19:19:24.3758 [V][Dart]: Event: work_select_at_index_1
12-12 19:19:26.7601 [V][Dart]: Event: work_select_at_index_0
12-12 19:19:27.2769 [V][Dart]: Event: capture_search_on
12-12 19:23:54.5834 [V][Dart]: Event: work_show_menu_at_index_0
12-12 19:23:55.2987 [V][Dart]: Event: capture_list_clear
12-12 19:25:53.4151 [V][Dart]: Event: work_show_menu_at_index_0
12-12 19:25:53.9827 [V][Dart]: Event: capture_list_clear
12-12 19:31:50.0435 [V][Dart]: Event: capture_search_on
12-12 20:04:31.1671 [V][Dart]: Event: capture_list_record_compose
12-12 20:04:31.1703 [V][Dart]: Event: work_new_api_from_capture
12-12 20:04:41.7347 [V][Dart]: Event: rest_set_body_type_text
12-12 20:04:45.0982 [V][Dart]: Event: rest_set_body_type_none
12-12 20:04:51.4537 [V][Dart]: Event: work_close_tab_at_index_7
12-12 20:04:54.5148 [V][Dart]: Event: work_select_at_index_1
12-12 20:04:57.0707 [V][Dart]: Event: work_select_at_index_0
12-12 20:05:02.7845 [V][Dart]: Event: capture_list_record_compose
12-12 20:05:02.7869 [V][Dart]: Event: work_new_api_from_capture
12-12 20:05:33.1661 [V][Dart]: Event: rest_request_send
12-12 20:05:42.8210 [V][Dart]: Event: work_select_at_index_0
12-12 20:05:50.5535 [V][Dart]: Event: capture_list_highlight_record_red
`

**Comment by MegatronKing** [comment]
2.0.0正式版已修复脚本无法保存的bug。

**Comment by MegatronKing** [comment]
@ByteSecurity 2.1.1版本已支持固定应用程序和域名操作，固定后不会跟随列表变化，列表清空后勾选仍然会保留。
