### ISSUE TITLE
[feature] 调试列表搜索支持`或`逻辑关系

### ISSUE THREAD

**Issue by leegohi** [reqable/reqable-app#329]
1、建议搜索条件如果在多个的情况下增加类似proxyman的“或”功能，现在默认多个搜索条件都是“与”
2、搜索条件支持勾选取消以及默认，而不是直接删除，不然每次都要重新增加搜索条件

<img width="1298" alt="image" src="https://github.com/reqable/reqable-app/assets/10923930/c550cf01-c53d-4875-b053-e3a5a710e49a">

**Comment by MegatronKing** [comment]
@leegohi 感谢反馈，部分类似 #298

**Comment by MegatronKing** [comment]
@leegohi 

> 2、搜索条件支持勾选取消以及默认，而不是直接删除，不然每次都要重新增加搜索条件

v2.4.0已支持。

> 1、建议搜索条件如果在多个的情况下增加类似proxyman的“或”功能，现在默认多个搜索条件都是“与”

逻辑关系会在后面的版本实现。

**Comment by MegatronKing** [comment]
v2.20.2已支持或逻辑关系。
