### ISSUE TITLE
[feature] 调试功能里没办法修改监听的ip

### ISSUE THREAD

**Issue by xry1029** [reqable/reqable-app#33]
如题 我的电脑有三个网络接口 reqable自动代理了vmware的子网并且无法修改 而我需要调试的手机在wifi下...
希望添加一个ip选择功能

我的设备: windows11
ip: 192.168.1.132 192.168.4.1(被调试功能选中) 192.168.5.2
version: 0.0.5(5)

**Comment by MegatronKing** [comment]
0.1.2版本已实现。
