### ISSUE TITLE
搜索文本只能筛选出部分

### ISSUE THREAD

**Issue by leegohi** [reqable/reqable-app#331]
问题：
在分析某网站接口的时候，有多个请求的req body和response body 都有某个关键字，但是根据关键字搜索只筛选出来了部分

复现：
1、搜索关键字为:pla.c
2、未在搜索关键字里输入关键字的时候，这个截图是包含 pla.c的请求body:
<img width="1154" alt="image" src="https://github.com/reqable/reqable-app/assets/10923930/7e3d4206-0227-498e-ac14-e53c65946604">
3、当我在搜索框里输入关键字pla.c的时候,只筛选出一个请求的response body：
<img width="1153" alt="image" src="https://github.com/reqable/reqable-app/assets/10923930/c707e156-a262-4f3c-b3d0-716104cda797">

**Comment by leegohi** [comment]
补充一下：我重启后打开历史记录，就能搜索到了，但是在之前的调试tab是打死都搜索不到

**Comment by MegatronKing** [comment]
@leegohi 感谢反馈，reqable版本号是？

**Comment by leegohi** [comment]
> @leegohi 感谢反馈，reqable版本号是？

1.6.2

**Comment by MegatronKing** [comment]
历史记录打开能搜索到，这倒是个挺奇怪的问题

**Comment by leegohi** [comment]
> 历史记录打开能搜索到，这倒是个挺奇怪的问题。能copy下这个请求的curl给我测试下吗？

涉及到要登录后的敏感信息，不好发，而且单个请求也没法模拟之前5000多个请求item环境。我感觉是不是之前调试tab里请求太多的缘故。

**Comment by MegatronKing** [comment]
@leegohi 好的，注意下是否应用了其他筛选条件。如果能找到复现bug的规律，欢迎告诉我。

**Comment by MegatronKing** [comment]
@leegohi 您好，请问是否可以更新到最新版本2.25.1，测试下是否还存在这个问题？

**Comment by MegatronKing** [comment]
由于没有进一步的信息，这个issue我先关闭了。
