### ISSUE TITLE
[feature] 自动调试功能建议

### ISSUE THREAD

**Issue by vay1314** [reqable/reqable-app#332]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
可否在自动调试开关里添加系统代理的开关。在设置里打开自动调试，打开软件就自动进入调试，并设置系统代理了。想只开启调试但不设置系统代理
**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
系统代理的开关在代理菜单里面。

**Comment by vay1314** [comment]
> 系统代理的开关在代理菜单里面。

知道这个开关，就是想问下能设置打开软件进入自动调试后，不让系统代理打开吗。

**Comment by MegatronKing** [comment]
> > 系统代理的开关在代理菜单里面。
> 
> 知道这个开关，就是想问下能设置打开软件进入自动调试后，不让系统代理打开吗。

代理菜单里面关掉代理自动启用

**Comment by vay1314** [comment]
> > > 系统代理的开关在代理菜单里面。
> > 
> > 
> > 知道这个开关，就是想问下能设置打开软件进入自动调试后，不让系统代理打开吗。
> 
> 代理菜单里面关掉代理自动启用

刚看到，谢谢
