### ISSUE TITLE
[feature] 移动端 - 关于动画速度与辅助服务的优化建议

### ISSUE THREAD

**Issue by Faserr** [reqable/reqable-app#340]
### 关于菜单栏
- [ ] **右上角菜单**以及**点进去的抓包详情**动画速度太慢了, 感觉还有点掉帧, 希望能够**加快动画速度**获取加个**取消动画选项**.

### 关于辅助服务
- [x] 辅助服务并没有什么主动触发的功能, 在桌面上占用了一个用处不大的图标. 感觉可以**不注册入口启动器**, 在**主app中启动**即可.

**Comment by MegatronKing** [comment]
@Faserr 感谢反馈和建议。

> 右上角菜单以及点进去的抓包详情动画速度太慢了, 感觉还有点掉帧, 希望能够加快动画速度获取加个取消动画选项.
确实有点慢，我优化下。

> 辅助服务并没有什么主动触发的功能, 在桌面上占用了一个用处不大的图标. 感觉可以不注册入口启动器, 在主app中启动即可.
这个估计不行，辅助服务后面要上应用市场，没有启动入口肯定没法上架。

**Comment by MegatronKing** [comment]
@Faserr 
1. 右上角菜单动画速度没有办法调整，动画时间是300ms，flutter框架组件里面写死的。我观察和Android原生的菜单相比，速度应该是差不多的，但是动画没有原生流畅是肯定的。如果有明显掉帧的话，可以录个视频我看看。
2. 点进去的抓包详情动画速度太慢了，这个自定义动画最新v2.2.0版本已经去掉，麻烦再看看。

**Comment by Faserr** [comment]
> 1. 右上角菜单动画速度没有办法调整，动画时间是300ms，flutter框架组件里面写死的。我观察和Android原生的菜单相比，速度应该是差不多的，但是动画没有原生流畅是肯定的。

右上角菜单我看了下原生确实差不多, 我看Chrome的实现是以更快的速度先弹出框架, 然后再逐行显示动画, 我都没注意到速度其实也很慢, 属于是感觉上慢了.不过右上角菜单使用频率也不高, 影响不大.

>如果有明显掉帧的话，可以录个视频我看看。

这个掉帧是只有"点进去的抓包详情"这里, 不过新版没有动画后就没感觉到了.

> 2. 点进去的抓包详情动画速度太慢了，这个自定义动画最新v2.2.0版本已经去掉，麻烦再看看。

现在流畅很多, 辛苦了!
