### ISSUE TITLE
[feature]  Capture by Targetting  App

### ISSUE THREAD

**Issue by tas33n** [reqable/reqable-app#343]
At present, Reqable captures API requests and responses globally, posing challenges when trying to focus on the APIs of a specific application. While there is a Host filtering feature, it becomes complicated for applications with multiple hosts or unknown hosts that may not be easily identified.

Currently, I use HttpCanary on Android, which offers a "Target App" feature. This feature proves to be very handy as it allows users to work exclusively with the APIs of a single app.

I hope Reqable will add this feature in future..

**Comment by MegatronKing** [comment]
@tas33n
Thanks for submitting the issue. It seems that reqable supports the feature you mentioned.
If you are using the desktop app of Reqable, you can filter applications in the sidebar.
if you are using the mobile app of Reqable, you can select the target application in Action Menu -> Application.

**Comment by tas33n** [comment]
Oops my bad. I  searched on wrong place.. thanks for telling..
