### ISSUE TITLE
[feature] There is a Magisk module for install custom CA certificate to the system store support Android 14

### ISSUE THREAD

**Issue by WindSpiritSR** [reqable/reqable-app#344]
There is a Magisk module for install custom CA certificate to the system store.

[WindSpiritSR/CustomCACert](https://github.com/WindSpiritSR/CustomCACert)

Is there any willingness to add it to the Reqable Android APP documentation to help more users install a system certificate?

**Comment by MegatronKing** [comment]
Sorry, there's nothing we can do as we don't have any experience with magisk.

**Comment by WindSpiritSR** [comment]
There are many users using Android 14 devices have encountered the problem of being **unable to install system certificates** or **unable to access the network through VPN mode** in issues.

And you can just put the repo url into the document, and there is no need to do any development based on magisk.

This is the only secure, user-controlled way to add system certificates in Android 14.

**Comment by MegatronKing** [comment]
@WindSpiritSR Sorry, I misunderstood you. Regarding the CustomCACert you provided, can you write a brief operation step? I will put it on the website documentation. Of course, I can give you a Reqable license as a gift.

**Comment by WindSpiritSR** [comment]
1. `git clone https://github.com/WindSpiritSR/CustomCACert.git` or directly download the repository's ZIP file.
2. Place the certificate generated by Reqable for Android devices (named as `hash.0`), into the `system/etc/security/cacerts` directory.
3. Compress all files within the `CustomCACert` directory into a ZIP file. Please ensure select all files directly, not the `CustomCACert` folder itself.
4. Proceed to install the packaged ZIP file using Magisk.

1. `git clone https://github.com/WindSpiritSR/CustomCACert.git` 或直接下载仓库 zip
2. 将 Reqable 生成的用于 Android 设备的证书（以 `hash.0` 命名）放进 `system/etc/security/cacerts` 目录
3. 将 `CustomCACert` 目录中的所有文件打包，注意，请直接打包所有文件而不是打包 `CustomCACert` 目录
4. 使用 Magisk 安装打包好的 zip

**Comment by MegatronKing** [comment]
@WindSpiritSR 感谢，我有空整理下。麻烦联系下 coding@reqable.com ，送您个许可证礼品卡。

**Comment by WindSpiritSR** [comment]
好的，非常感谢，很高兴能为正在使用的产品做出一些微不足道的贡献

后续有任何相关问题也可以通过issue或邮件等方式联系我，我很愿意提供相关技术的支持:)

**Comment by yjgame-mark** [comment]
原来这样就可以获得礼品卡，哈哈，即使我已经订阅支付了个人版。虽然Move Certificates早就停更，并且在某些环境或者系统下不再起作用。不知道你说的这个模块是否好用。

**Comment by iccfish** [comment]
自定义证书只要设备有root权限可以直接自己装的，用adb shell。

**Comment by qilinxinan** [comment]
> ## CN
> 1. `git clone https://github.com/WindSpiritSR/CustomCACert.git`或者直接下载存储库的 ZIP 文件。
> 2. 将 Reqable 为 Android 设备生成的证书（名为`hash.0`）放入该`system/etc/security/cacerts`目录中。
> 3. 将目录中的所有文件压缩`CustomCACert`为 ZIP 文件。请确保直接选择所有文件，而不是`CustomCACert`文件夹本身。
> 4. 继续使用 Magisk 安装打包的 ZIP 文件。
> 
> ## ZHCN
> 1. `git clone https://github.com/WindSpiritSR/CustomCACert.git`或直接下载仓库zip
> 2. 将 Reqable 生成的用于 Android 设备的证书（以`hash.0`命名）`system/etc/security/cacerts`按钮目录
> 3. 将`CustomCACert`目录中的所有文件，注意，请直接压缩所有文件而不是压缩`CustomCACert`目录
> 4. 使用 Magisk 安装压缩包

I used the same method to import the certificate, but the installed certificate is not displayed in the certificate, I am also using Android 14

**Comment by MegatronKing** [comment]
感谢支持，模块已内置到Reqble Android App中。
