### ISSUE TITLE
[bug] 总是莫名其妙的崩溃

### ISSUE THREAD

**Issue by layxyer** [reqable/reqable-app#345]
**Describe the bug**
软件打开后,无论用不用,过一会儿就可能崩溃,当开启代理崩溃后网络访问有问题,需要手动取消代理或重新打开软件

**To Reproduce**
打开软件常住后台,过一会儿就崩溃

**Expected behavior**
正常使用

**Screenshots**
<img width="1036" alt="iShot_2023-12-28_09 16 40" src="https://github.com/reqable/reqable-app/assets/17535968/c79da895-9ba9-4425-a611-8424fe544e3b">

**Information**
 - Platform: macos
 - OS: 12.7.1 
 - Arch: arm
 - App Version: 2.1.1

**Comment by MegatronKing** [comment]
@layxyer 感谢反馈，能否将这个弹窗里面的崩溃日志提供下？

**Comment by MegatronKing** [comment]
@layxyer 目前没有办法复现这个问题，还是需要日志分析，可否提供下日志呢？

**Comment by layxyer** [comment]
使用第一天很容易复现,今天再打开试了下目前还没有复现,当初只截图没有保留完整的文本日志,等后面复现了我再提吧

**Comment by MegatronKing** [comment]
@layxyer 请问你Mac有使用`KeyboardHolder`这个辅助应用程序吗？

**Comment by MegatronKing** [comment]
理论上问题已经修复，issue关闭。
