### ISSUE TITLE
允许手动调整总览里url栏的高度[feature] 

### ISSUE THREAD

**Issue by Sucaiking** [reqable/reqable-app#349]
**Is your feature request related to a problem? Please describe.**
确实存在这样一些场合，我在调试窗口抓到的请求里，总有些真的超长了的url。我希望能完整地看到整个url。这里用edge浏览器的一则请求举例：
<img width="628" alt="ima" src="https://github.com/reqable/reqable-app/assets/48800800/ddc4bc19-5553-4c16-b29c-cbecc05e1c7b">

**Describe the solution you'd like**
我希望能通过手动操作，完整展示超过2行的url。

**Describe alternatives you've considered**
比如说对于超过2行显示省略号的url，提供一个展开按钮，或者用户双击此栏时，在合理的范围内再次调大栏高；比如说在超高的场合，提供一个滚动条等。

**Additional context**
祝软件越来越好

**Comment by MegatronKing** [comment]
@Sucaiking 总览确实有url显示不全这个问题，你可以临时用快捷键Contrl + U，或者右键 - 查看 - URL，这两个方式查看URL全文。

**Comment by MegatronKing** [comment]
@Sucaiking 2.3.0版本可以点击查看URL全文。

**Comment by Sucaiking** [comment]
试用感觉不错，我觉得我的建议已经得到实现。感谢！
