### ISSUE TITLE
[bug][windows] 进程不会自动退出, 且系统代理不会自动取消

### ISSUE THREAD

**Issue by Sunquymans** [reqable/reqable-app#35]
我使用的是 Windows 版本 , 发现当我单击 "关闭" 按钮后 , 进程不会自动退出 , 并且系统代理不会自动取消

**Comment by MegatronKing** [comment]
@Sunquymans 麻烦更新到最新的v0.1.2版本，并在设置中关闭”后台模式“。如果还有问题，请反馈给我。

**Comment by MegatronKing** [comment]
如果没有问题的话， 这个issue我先关闭了。
