### ISSUE TITLE
[feature] 桌面端在协同模式下显示应用ID

### ISSUE THREAD

**Issue by SebaSs007** [reqable/reqable-app#350]
**Is your feature request related to a problem? Please describe.**

Hi！你好，我在一些APP分析取证的事务中需要提供给客户文档信息，一些客户会希望在文档里直观体现APP和抓包站点直接的关联
手机端抓包时会显示APP图标、名称、包名、URL等信息，这很不错！但是由于手机显示面积、剪切板限制等问题，需要在目标APP和request 之间来回切换，当需要便携更详细的APP分析文档时 就更加糟糕了。

电脑端抓包工具方便查看流量信息，但是由于不包含APP图标、名称、包名等信息无法用于报告文档中。

**Describe the solution you'd like**

我想能否给手机端和电脑端添加联动功能，强化APP抓包功能？
1、通过手机端+PC端 能否把手机APP抓包信息同步给PC端，让PC端可以看到APP和流量之间的关系

2、PC端如果要抓手机流量需要使用WiFi代理，但是一些APP检测到WiFi代理就会停止运行，或者让流量不走WiFi代理。
手机端通过VPN抓包获取流量更全、适用性更高，那么能否把这部分流量发送给PC端？增加PC端抓手机流量的覆盖效果（droni/drony + fiddler 设置好证书后是可以实现的2，但是不支持1）

**Describe alternatives you've considered**

droni/drony + fiddler 设置好证书 可以实现抓包流量更高的覆盖，但是不包含APP信息，截图时依旧需要手机上抓包并不停切换APP
**Additional context**

**Comment by MegatronKing** [comment]
@SebaSs007 手机上启用辅助服务，然后描述电脑端二维码进入协同模式，可以在电脑上看到应用的信息，例如图标和名称。
![image](https://github.com/reqable/reqable-app/assets/15059084/5226b8ac-4a14-4603-b7ce-9d0fed322ef9)

**Comment by SebaSs007** [comment]
> @SebaSs007手机上启用辅助服务，然后描述电脑端二维码进入良好模式，可以在电脑上看到应用的信息，例如图标和名称。 ![图像](https://private-user-images.githubusercontent.com/15059084/293500846-5226b8ac-4a14-4603-b7ce-9d0fed322ef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMjAwMDQsIm5iZiI6MTcwNDAxOTcwNCwicGF0aCI6Ii8xNTA1OTA4NC8yOTM1MDA4NDYtNTIyNmI4YWMtNGExNC00NjAzLWI3Y2UtOWQwZmVkMzIyZWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDEwNDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZWY3M2M1ODZjM2NiYWZhZjYyYmM0YzdmZTVlNjJiYTQxYWFmNjFhZjE0NGFhYzk3ODlkN2I5ZjViODdkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QI8WX74g8QZbN2O0-smtC3cNDvhFcV2afCfigp_-Yo8)

感谢感谢！我用的版本太老了，没看到这个功能，更新后可以正常使用满足需求！

有几点建议：1、添加包名信息，有一些涉诈等APP 会出现很多名称一致但是包名不同的情况、甚至使用图标作为APP名称，添加包名列显示可以更好的区分。  //强烈希望后续添加
2、添加一种批量选择方式，目前request PC端我只看到了手动多选、划动多选 以及全选，希望可以添加按照条件批量选择。

fiddler 右键---select---Matching Values  可以根据【所选列】的【内容】匹配选择
比如host列为www.baidu.com的
或者URL列为/h5/login.php的     
或者Content-Type列里的 PNG 
方便提升效率，有时手机APP流量非常多，按照条件筛选可以快速从数量众多的url信息中更快捷筛选数据
//如果采纳该建议，希望把host和url路径拆分，方便筛选。

**Comment by SebaSs007** [comment]
> @SebaSs007 手机上启用辅助服务，然后描述电脑端二维码进入协同模式，可以在电脑上看到应用的信息，例如图标和名称。 ![image](https://private-user-images.githubusercontent.com/15059084/293500846-5226b8ac-4a14-4603-b7ce-9d0fed322ef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMzQyOTAsIm5iZiI6MTcwNDAzMzk5MCwicGF0aCI6Ii8xNTA1OTA4NC8yOTM1MDA4NDYtNTIyNmI4YWMtNGExNC00NjAzLWI3Y2UtOWQwZmVkMzIyZWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDE0NDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMzY2NzIxYTA1NWViYjkxMjYwOGFjYmViNjk0MTAzYzJiM2I5ZTAxZDcwMjJkZWI5MzU5N2I4MGY3MmQyNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n9UMVedYN13ikD6qN9XLuyLBhaTN8IoeFU0PZpfhE4w)

能否增加一列用以显示包名？有的涉诈APP包名不同但是名称都一样，这样编写分析文档时不好关联到分析的样本。
有一些还是使用了emoji 作为名称的APP，在不同平台显示也不一致，这样不方便区分。
希望可以采纳

**Comment by MegatronKing** [comment]
> 能否增加一列用以显示包名？有的涉诈APP包名不同但是名称都一样，这样编写分析文档时不好关联到分析的样本。

好的，全力支持分析涉诈APP，这个功能我会在下个版本上线。

**Comment by MegatronKing** [comment]
Android应用显示package name，Mac应用bundle id。iOS平台无法获取应用信息，Windows和Linux没有应用ID的概念，均不显示。

**Comment by MegatronKing** [comment]
@SebaSs007 试试最新版本v2.3.0，已经支持显示应用ID，需要手动定义列选项显示应用ID。
