### ISSUE TITLE
[bug] 移动端APP使用WIFI可以抓包，使用移动数据无法抓包

### ISSUE THREAD

**Issue by zangwill** [reqable/reqable-app#351]
**Describe the bug**
非root手机，只在移动端APP使用，发现使用WIFI可以抓包，使用移动数据无法抓包。

**Information**
 - Platform: Android
 - OS: 14
 - Arch: arm
 - App Version: 2.2.0

**Comment by zangwill** [comment]
在使用reqable用来获取浙里办某个小程序的请求时发现这个问题，一开始wifi下时灵时不灵，应用权限给足后可以抓取了，就是抓取时请求很慢，但是移动数据下一直无法抓取

**Comment by MegatronKing** [comment]
@zangwill 抱歉，提供的这些信息没有办法确定是Reqable的问题。如果你确定是Reqable的bug，请提供详细的信息，例如报错信息、Reqable的日志等。
