### ISSUE TITLE
[feature] Android支持配置应用黑名单

### ISSUE THREAD

**Issue by SebaSs007** [reqable/reqable-app#353]
**Is your feature request related to a problem? Please describe.**

目前手机在抓包过程中会产生很多流量底噪，主要是一些系统服务，比如厂商服务组件、Google play组件。
流量产生时虽然可以通过【工作台】【应用程序】 设置显示和隐藏，但是这个操作并不会影响【域名】，比如仅仅Google play商店和服务就在【域名】里产生了20+的站点 并且会持续输出流量删除也没用，这些信息对我没有任何帮助反而污染列表 降低效率。

**Describe the solution you'd like**

添加屏蔽规则可以按照应用程序、URL等规则，彻底隐藏流量信息，消除手机流量底噪带来的无效信息污染，最终提升效率。

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
@SebaSs007 感谢建议，目前支持两种方式处理这个问题。
- SSL旁路规则
入口：证书菜单 - SSL旁路 - 管理规则，或者右键盾牌图标打开。SSL旁路配置域名规则并启用静默模式，所有相关域名的SSL流量都不会解密，并且不会出现在列表中。

- 网关静默
入口：右键网关图标 - 管理规则，或者快捷键 Alt + G，或者选中请求右键。配置一个URL规则并选择静默，匹配上的URL都不会出现在列表中。

**Comment by SebaSs007** [comment]
> @SebaSs007 感谢建议，目前支持两种方式处理这个问题。
> 
> * SSL旁路规则
>   入口：证书菜单 - SSL旁路 - 管理规则，或者右键盾牌图标打开。SSL旁路配置域名规则并启用静默模式，所有相关域名的SSL流量都不会解密，并且不会出现在列表中。
> * 网关静默
>   入口：右键网关图标 - 管理规则，或者快捷键 Alt + G，或者选中请求右键。配置一个URL规则并选择静默，匹配上的URL都不会出现在列表中。
> 
> 另外，在手机上可以选中指定的应用程序：标题右侧更多菜单 - 应用程序 - 添加

感谢回复，您反馈的这两种方式我都有尝试，并不能完全解决问题。

1. SSL旁路规则，主要针对域名，而手机流量底噪会包含很多IP信息，此外会存在误伤情况，比如APP使用了Google、阿里、腾讯、华为的服务、或者用于获取云端站点作为主控，静默这些流量域名会导致APP分析不完整。

2. 网关静默，可以针对域名、IP静默，但存在时效问题。此前使用fiddler时屏蔽过一批，但是经过一段时间还会产生新的域名、IP，需要持续屏蔽也会存在误伤情况，reqable应该也需要持续添加新的规则来消除底噪
3. 手机选中指定的应用程序可以只获取APP流量从源头解决底噪问题，效果很好。
    但是需要增加很多额外操作：关闭抓包---点击右上角选择应用程序----找到需要抓包APP----选中并退出----开启抓包  ，当需要处置很多APP（20+---60+ 极限100+/每天）时严重影响效率。
    手机端能否添加黑名单？除了列表内的APP流量不抓取其余都抓取。
4.感谢！

**Comment by MegatronKing** [comment]
看起来能做的就是手机端添加应用黑名单。

**Comment by MegatronKing** [comment]
v2.25.1已支持配置Android应用黑名单。
