### ISSUE TITLE
[bug] APP抓包流量获取不完整

### ISSUE THREAD

**Issue by SebaSs007** [reqable/reqable-app#354]
**Describe the bug**

对一类APP流量获取有些问题，该类APP首次运行时会使用域名获取IP信息，目前在每天的涉诈样本中占比较高。
比如：jia.gz.duli53aitu.com:11053 解析IP  183.192.65.101
使用reqable 手机端+PC端协同  首次启动只能抓到解析后的IP 183.192.65.101
![image](https://github.com/reqable/reqable-app/assets/71699483/2db698e5-4846-4acd-aab3-2d9a21d0bf77)

而更换Droni/Drony 作为手机客户端+reqable 可以抓到解析前的域名 jia.gz.duli53aitu.com:11053
![image](https://github.com/reqable/reqable-app/assets/71699483/a1ff837e-0837-43cf-a085-9996cc53db48)
![image](https://github.com/reqable/reqable-app/assets/71699483/1b8e43ff-cbf1-4df2-be21-e1dbbf61a564)

**To Reproduce**

分别使用reqable和 Droni/Drony 作为手机客户端 搭配PC端抓包
如果需要具体APP，请提供邮箱。

**Expected behavior**

解析前的域名比较固定，解析后的IP多变，更希望可以抓到域名

**Comment by MegatronKing** [comment]
@SebaSs007 感谢反馈。我测试了下确实是有这个问题，之前处理过类似的但没彻底解决，这个case下个版本应该可以解决。

**Comment by SebaSs007** [comment]
> @SebaSs007 感谢反馈。我测试了下确实是有这个问题，之前处理过类似的但没彻底解决，这个case下个版本应该可以解决。

这个问题解决对我来说就可以完全当主力来用了，已经购买了专业版支持一下。

**Comment by MegatronKing** [comment]
> 这个问题解决对我来说就可以完全当主力来用了，已经购买了专业版支持一下。

好的，非常感谢支持。你们是国内做安全的公司吗，不知道有没有机会更加深入合作下，欢迎致信 market@reqable.com 取得进一步的联系！

对于这个问题，我简单研究了下。域名是从HTTPS请求的SNI里面获取的，Reqable是先连接IP地址，连接成功了才会去解析SNI，如果连接失败就直接返回了不会去获取SNI。可能需要修改下这个策略，我先研究怎么处理。

**Comment by MegatronKing** [comment]
@SebaSs007 试试最新版本v2.3.0，这个问题理论已修复。

**Comment by SebaSs007** [comment]
> @SebaSs007 试试最新版本v2.3.0，这个问题理论已修复。

我把PC端、安卓端都更新至最新版。
经过测试并未解决该问题。
APP代码内嵌域名为 ayix.gz.gmhgfdsfghjk373.com  解析IP为 81.71.4.169
![image](https://github.com/reqable/reqable-app/assets/71699483/46966a20-e02d-4d32-9aaf-a71e2b4c01ab)
APP启动后可以看到 reqable 手机端+PC端 抓包只获取到IP地址，而非域名
![image](https://github.com/reqable/reqable-app/assets/71699483/338ca699-15fb-4694-b1db-3f3812fb7a4c)
更换手机端为：droni/drony 后 可以获取到域名部分
![image](https://github.com/reqable/reqable-app/assets/71699483/faa97af6-1106-4ddd-87e4-ea989eed43d2)
![image](https://github.com/reqable/reqable-app/assets/71699483/9921b9ad-1fe7-4112-9aca-a4bb1fc89910)
该类型APP不实际使用域名访问，仅用于获取解析IP。

我把APP打包后分享给你，你有时间可以实际测试一下。
下载:https://wwkt.lanzoul.com/iuNK51khor0f 密码:3vir

**Comment by SebaSs007** [comment]
@MegatronKing 你好，有关注到么？没有的话我开个新帖？

**Comment by MegatronKing** [comment]
> @MegatronKing 你好，有关注到么？没有的话我开个新帖？

我没测试机，用模拟器安装简单看了下也进不去。要不你在Reqable设置里面启用下“调试日志”开关，测试复现问题后，点击Reqable底部栏5下，把日志导出来贴到这里，我分析下。

**Comment by SebaSs007** [comment]
[reqable.log](https://github.com/reqable/reqable-app/files/13898380/reqable.log)
[app_har.zip](https://github.com/reqable/reqable-app/files/13898409/app_har.zip)

2024-01-11 14:47  开启抓包
reqable PC端+手机端  
2024-01-11 14:48:34 切换为
reqable PC端 + droni/drony   重装APP 抓包

**Comment by MegatronKing** [comment]
@SebaSs007 感谢提供案例。我分析了下，像`81.71.4.169`这个IP没有识别出来是HTTPS协议，确实是有点问题，我先排查下原因。

**Comment by MegatronKing** [comment]
@SebaSs007 你发我的样本无法测试，注册和登录都进不去。大概定位到什么原因，但是没有能复现的数据不好调试。2.4.0版本我加了些日志，您要是方便再帮我测试下。或者更加直接地用Wireshark抓到`81.71.4.169`这个ip的数据包也行。

**Comment by SebaSs007** [comment]
[PCAPdroid_15_1月_14_10_27.zip](https://github.com/reqable/reqable-app/files/13935463/PCAPdroid_15_1._14_10_27.zip)
手机上用PCAPdroid APP 抓了一个pcap包。
里面有81.71.4.169 这个IP数据。

**Comment by MegatronKing** [comment]
@SebaSs007 感谢，我已经知道问题所在了。Reqable只处理HTTP和HTTPS（SSL/TLS）协议，这些都属于TCP传输协议，`81.71.4.169`这个IP的域名并没有在TCP传输协议中出现，所以Reqable无法获取其域名信息。 droni/drony能获取到，是因为他们处理了UDP传输协议，而DNS解析用的就是UDP，他们读取了DNS的解析结果，所以能够知道`81.71.4.169`这个IP的域名。

![image](https://github.com/reqable/reqable-app/assets/15059084/a20b96c3-2bd9-4b6e-9320-dd19af892e0e)

解决这个问题的思路就是处理UDP协议并读取DNS的解析结果，将IP还原成域名。

**Comment by SebaSs007** [comment]
@MegatronKing 感谢，期待后续软件更新覆盖。

**Comment by MegatronKing** [comment]
所以这个问题目前来看不是bug，我新建了一个需求issue #394，后续动态在那个issue里面讨论，这个问题我先关闭了。
