### ISSUE TITLE
[bug] 对请求对gzip不进行解密

### ISSUE THREAD

**Issue by yanyuheng2008** [reqable/reqable-app#355]
当请求content-encoding是gzip，content-type是application/json时，请求体被识别为二进制，新建重发时以默认二进制模式发送，content-encoding 被锁定为application/octet-stream

**Information**
 - Platform: iOS

**Comment by MegatronKing** [comment]
@yanyuheng2008 您好，感谢反馈。但是非常抱歉，这个问题的描述我没能理解。能否提供下操作步骤？或者截图？或者录屏？

**Comment by yanyuheng2008** [comment]
这是抓到的请求头
![7FA670AF-A292-4776-8D01-4A2928D65897](https://github.com/reqable/reqable-app/assets/73336881/6f8b74f4-f686-4263-abff-7671adbedf6b)
数据经过了gzip压缩，查看请求体时如下（gzip并没有被识别并解压，但导出后用gzip -d命令可以正常解压）
![ACA95E7D-136E-4B57-BB3E-9D8E93AE9501](https://github.com/reqable/reqable-app/assets/73336881/aa11cf2c-c580-438e-b01c-058e8e2d4ae4)
当选择编辑重放时，自动填写参数如下，并锁定，无法修改
![3874A31E-5EFF-4B85-AED9-FD8C8483F72B](https://github.com/reqable/reqable-app/assets/73336881/1cdc7fcb-a5e2-4048-8653-4482b2af3ead)
导致服务器返回错误
![F6A8C764-72A1-4611-BA4E-8E60F0A6F445](https://github.com/reqable/reqable-app/assets/73336881/e495c528-4989-4255-a995-b9e8274adb79)
这可能不是一个符合标准的数据包。但确实，它无法被正确重放。

还希望可以添加gzip的自动解压与回压缩，让编辑数据重放更加容易。

**Comment by yanyuheng2008** [comment]
在这之后发现了一种重放它的方式。把gzip数据用文本编辑器打开，并把混乱的字符复制进去以json模式请求
显然非常麻烦

**Comment by MegatronKing** [comment]
@yanyuheng2008 感谢提供case，好像是大写GZIP没识别出来，这个问题下个版本修复。

**Comment by MegatronKing** [comment]
@yanyuheng2008 试试最新版本v2.3.0，这个问题理论已修复。

**Comment by yanyuheng2008** [comment]
> @yanyuheng2008 试试最新版本v2.3.0，这个问题理论已修复。

好的，我正在等待ios推送

**Comment by yanyuheng2008** [comment]
测试了一下，新版本已解决

**Comment by yanyuheng2008** [comment]
2.3.0已修复

**Comment by anylayer** [comment]
> 2.3.0已修复
android上面也有这种情况
![image](https://github.com/user-attachments/assets/98f09fff-a38d-45db-823e-c684cee03204)
