### ISSUE TITLE
调试unity中socket的包抓不到，http/https正常，没有看到ws

### ISSUE THREAD

**Issue by yzjjdcf** [reqable/reqable-app#356]
Describe the bug

调试unity中socket的包抓不到，http/https正常，没有看到ws
另外用wireshark 是抓到正常socket的包的

To Reproduce

这是我哪里没配置对么，还是有什么需要注意的

Expected behavior

**Comment by yzjjdcf** [comment]
就是websocket

**Comment by yzjjdcf** [comment]
![image](https://github.com/reqable/reqable-app/assets/13599694/26f4eb63-5840-422c-90aa-efaf311ee327)

**Comment by MegatronKing** [comment]
@yzjjdcf 你这个图不是传输层协议包吗？websocket是应用层协议。

**Comment by yzjjdcf** [comment]
我是应用层没抓到 我才用的wireshark抓的 。。。。。传输层是必然能抓到的

**Comment by MegatronKing** [comment]
> 我是应用层没抓到 我才用的wireshark抓的 。。。。。传输层是必然能抓到的

Reqable工作在应用层，在传输层下面，所以没法获取传输层的数据包。

**Comment by yzjjdcf** [comment]
明白了 sokect  websocket 不是一个东西
