### ISSUE TITLE
纯IP形式的URL无记录

### ISSUE THREAD

**Issue by liuchenger** [reqable/reqable-app#357]
URL貌似只有是域名的才会记录，ip地址类型的URL都没有记录，比如×××.×××.×××.×××/index.html

**Comment by MegatronKing** [comment]
@liuchenger 都会记录的。在显示上，如果host是IP，则会优先使用SNI、请求头里面的host等作为显示。

**Comment by liuchenger** [comment]
![1](https://github.com/reqable/reqable-app/assets/77476436/5d547f4e-28c2-4e03-bc05-3c60ee1ef517)
![2](https://github.com/reqable/reqable-app/assets/77476436/e080d251-afa6-41af-b2e8-b983e705270d)

**Comment by liuchenger** [comment]
> @liuchenger 都会记录的。在显示上，如果host是IP，则会优先使用SNI、请求头里面的host等作为显示。如果您觉得有问题，可以提供一个case让我测试。

我录了两个动画，由于是内网，所以没法发你地址，第一次直接访问ip10.255.21.185，没看到有记录，第二次我把aaa.com解析到10.255.21.185，可以看到，访问aaa.com是有记录的

**Comment by MegatronKing** [comment]
@liuchenger 感谢提供信息。

看你的截屏，纯URL请求成功了但是Reqable没有记录，说明请求没有走系统代理，有没有可能系统代理里面配置了ip bypass？
1. 可以打开系统设置 - 网络 - 代理服务器检查下。
2. Reqable代理菜单 - 配置回环 开关打开，再试试能不能记录？

**Comment by liuchenger** [comment]
> @liuchenger 感谢提供信息。
> 
> 看你的截屏，纯URL请求成功了但是Reqable没有记录，说明请求没有走系统代理，有没有可能系统代理里面配置了ip bypass？
> 
>     1. 可以打开系统设置 - 网络 - 代理服务器检查下。
> 
>     2. Reqable代理菜单 - 配置回环 开关打开，再试试能不能记录？

打开配置回环可以了
