### ISSUE TITLE
[bug] 不能通过 Reqable 的代理访问网络

### ISSUE THREAD

**Issue by HouCoder** [reqable/reqable-app#358]
似乎开启代理后并没有起作用

**To Reproduce**
1. 使用 Reqable 抓包，开启 SSL，不使用 Reqable 作为系统代理，已安装 Proxy Helper Tool
2. Reqable 监听本机 IP 的 9000 端口
3. 将浏览器代理指这个 9000 端口后浏览器不能访问任何网站
4. 用 curl 测试代理端口也报错
	```
	 $ curl -x "http://192.168.21.109:9000" "http://qq.com/"
     curl: (28) Failed to connect to 192.168.21.109 port 9000: Connection timed out
	````
**Screenshots**

![image](https://github.com/reqable/reqable-app/assets/5292143/2e7e5fe1-3837-4b8d-8524-63e2510995b6)

**Information**
 - Platform: macOS
 - OS: 14.2.1 (23C71)
 - Arch: Apple Silicon
 - App Version: 2.2.0 (60)

**Comment by MegatronKing** [comment]
@HouCoder 看起来是端口冲突的问题，试试最新版本v2.3.0，加了检测冲突并自动更换端口的功能。

**Comment by HouCoder** [comment]
更新后测试发现可以正常工作了，谢谢
