### ISSUE TITLE
[bug] 对未启用的重写规则进行修改，无法点击完成按钮

### ISSUE THREAD

**Issue by abinnz** [reqable/reqable-app#36]
**Describe the bug**
 对未启用的重写规则进行修改，无法点击完成按钮

**To Reproduce**
1. 点击管理规则
2. 修改规则
3. 无法点击完成按钮，灰色禁止点击状态

**Expected behavior**
修改后应可以点击完成按钮

**Screenshots**
![image](https://user-images.githubusercontent.com/13955662/231810848-832a56c5-f42c-433d-b203-0684c68c3085.png)

**Information**
 - Platform: windows
 - OS: 11
 - Arch: arm
 - App Version: 0.0.5

**Comment by MegatronKing** [comment]
v0.1.1版本已优化
