### ISSUE TITLE
[bug]后台抓包出现假死状态

### ISSUE THREAD

**Issue by 2379780711** [reqable/reqable-app#362]
**Describe the bug**
开启抓包以后，将reqable放置后台，返回其他应用时无法正常捕获请求，会出现一直请求中的情况，直至我再次返回reqable，请求才会正常进行，包也会正常出现，reqable似乎只有在前台才可以正常运行

**To Reproduce**
1. 开始抓包
2. 置于后台
3. 前台进行的请求会被拦截，无法得到响应
4. 返回reqable，请求恢复，得到响应

**Expected behavior**
not

**Screenshots**
not

**Information**
 - Platform: [iOS]
 - OS: [16.7.2]
 - App Version: 2.3.0]

**Comment by MegatronKing** [comment]
@2379780711 感谢反馈，看起来是苹果系统禁止了后台活动。

**Comment by MegatronKing** [comment]
@2379780711 v2.4.0已解决。
