### ISSUE TITLE
[feature] 自定义快捷筛选栏条件

### ISSUE THREAD

**Issue by yjgame-mark** [reqable/reqable-app#363]
![image](https://github.com/reqable/reqable-app/assets/82769170/132558a1-6a6e-4269-a644-1b1e2fe0cf67)

譬如这个网站需要的数据有200 302 html  json。同类html和json就无法多选，筛选判读数据会累一点。

![image](https://github.com/reqable/reqable-app/assets/82769170/343d6cbe-5786-478d-9d1e-2ba425cbf746)

还有就是能否增加响应体的json内容单独复制某个结构的key或者value，charles上有这个功能，很方便。

**Comment by MegatronKing** [comment]
@yjgame-mark 感谢反馈。

1. 筛选栏目前是`与`的逻辑关系，如果同类能多选就会变成同类`或` + 分类`与`，这个逻辑就复杂了，对于用户来讲更加不好理解。解决方案是支持自定义筛选栏，有需求的自己编辑条件。
2. 这个功能在这个需求里面： #185

**Comment by MegatronKing** [comment]
功能已实现。
