### ISSUE TITLE
[feature] pop-up in android

### ISSUE THREAD

**Issue by Sansekai** [reqable/reqable-app#365]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when opening and closing apps

**Describe the solution you'd like**
Please add a pop-up for reqable apps so you don't have to open and close the app.

Thanks

**Comment by MegatronKing** [comment]
@Sansekai Does your proposal refer to the Picture-in-Picture  mode?

**Comment by Sansekai** [comment]
Ya
