### ISSUE TITLE
[bug] Android版非root设备如何抓包？

### ISSUE THREAD

**Issue by Marblog** [reqable/reqable-app#367]
和PC端通过socksdroid 转发流量也没办法抓包
证书已经安装到了用户
- OS: Android12

**Comment by Marblog** [comment]
项目中添加网络安全配置文件（非Root设备、Android 7.0+）这个指的是，在哪里写？

**Comment by MegatronKing** [comment]
> 项目中添加网络安全配置文件（非Root设备、Android 7.0+）这个指的是，在哪里写？

你的Android项目里面。

**Comment by Marblog** [comment]
> > 项目中添加网络安全配置文件（非Root设备、Android 7.0+）这个指的是，在哪里写？
> 
> 你的Android项目里面。

第五步如果没有配置，就抓不掉数据了吗？

**Comment by MegatronKing** [comment]
> > > 项目中添加网络安全配置文件（非Root设备、Android 7.0+）这个指的是，在哪里写？
> > 
> > 
> > 你的Android项目里面。
> 
> 第五步如果没有配置，就抓不掉数据了吗？

可以，但是https请求会握手失败。另外，不建议使用socksdroid，Reqable有手机版本，可以协同PC版本进行流量转发。

**Comment by Marblog** [comment]
![微信截图_20240108145410](https://github.com/reqable/reqable-app/assets/22953256/c37a577a-4669-44ab-b4c7-2b3074eda502)
![微信图片_20240108145432](https://github.com/reqable/reqable-app/assets/22953256/be0a0848-9173-4f30-8b87-3e2c60208a5c)
![微信图片_20240108145436](https://github.com/reqable/reqable-app/assets/22953256/98ab5d12-1918-4c14-bd5f-141bc174ce4e)

**Comment by MegatronKing** [comment]
@Marblog  非root设备，如果要处理HTTPS请求，请在你的Android项目里面配置`网络安全配置文件`。

**Comment by Marblog** [comment]
> @Marblog 非root设备，如果要处理HTTPS请求，请在你的Android项目里面配置`网络安全配置文件`。

我只是想抓部分APP的数据包，比如说美团，云闪付，微信小程序数据，这些没有本地项目，没有root就无法解决呀？

**Comment by MegatronKing** [comment]
> > @Marblog 非root设备，如果要处理HTTPS请求，请在你的Android项目里面配置`网络安全配置文件`。
> 
> 我只是想抓部分APP的数据包，比如说美团，云闪付，微信小程序数据，这些没有本地项目，没有root就无法解决呀？

建议你换其他工具。Reqable是API开发工具，仅支持用户自己的项目，不支持未授权的其他应用。
