### ISSUE TITLE
[feature] ReWrite Mobile App 

### ISSUE THREAD

**Issue by phatal** [reqable/reqable-app#368]
**Is your feature request related to a problem? Please describe.**
Do I understand correctly that Android app will not have the main killer feature that turned httpcanary into something more than just another SSL traffic sniffer?  if the feature is not directly available, are there any other workflows that can achieve the same result?

p.s. ssory if I repeated already asked question, but I don't found same.

**Comment by MegatronKing** [comment]
@phatal No rewrite, no breakpoint, and no script. In the past, HttpCanary's data injection feature caused me a lot of trouble, so I decided to correct this mistake and not provide any related functionality on mobile apps. 

If you have such a need, you can use the desktop app, scan the QR code with your mobile app to connect to the desktop. Forwarding the traffic to the desktop, and then reprocess it on the desktop.

**Comment by MegatronKing** [comment]
Same as #568
