### ISSUE TITLE
[bug] curl生成未合并Cookie

### ISSUE THREAD

**Issue by tiam-bloom** [reqable/reqable-app#370]
**Describe the bug**
当我使用reqable抓取网页中的接口时, 复制其中的抓取的接口curl, 并导入postman中再次调用测试, 无法成功调用;
但是我使用浏览器自带的开发者工具中复制curl导入到postman, 便可成功调用

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux] windows
 - OS: [e.g. 12.1] 11
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@tiam-bloom 感谢反馈，但是你得告诉我你这个有问题的case。

**Comment by tiam-bloom** [comment]
https://m.damai.cn/shows/item.html?itemId=747189662387网页中的https://mtop.damai.cn/h5/mtop.alibaba.damai.detail.getdetail/1.2/接口, 
reqable免费版限制了两个标签页, 不太方便

**Comment by MegatronKing** [comment]
> [https://m.damai.cn/shows/item.html?itemId=747189662387网页中的https://mtop.damai.cn/h5/mtop.alibaba.damai.detail.getdetail/1.2/接口](https://m.damai.cn/shows/item.html?itemId=747189662387%E7%BD%91%E9%A1%B5%E4%B8%AD%E7%9A%84https://mtop.damai.cn/h5/mtop.alibaba.damai.detail.getdetail/1.2/%E6%8E%A5%E5%8F%A3), reqable免费版限制了两个标签页, 不太方便

看起来是URL的query没编码导致Postman导入没正确处理的，在Reqable中导入同一个cURL是完全没问题的。要说是Reqable的问题也行，但更多还是Postman这个解析curl逻辑太垃了。所以，最好的方案还是建议买个许可证，抛弃掉Postman，直接在Reqable里面一站式处理。

**Comment by tiam-bloom** [comment]
可是我从浏览器开发工具中复制的curl可以正常工作

**Comment by MegatronKing** [comment]
> 可是我从浏览器开发工具中复制的curl可以正常工作

浏览器复制的curl在Reqable里面导入也行啊。

**Comment by MegatronKing** [comment]
看起来也可能是Cookie没有合并导致的。

**Comment by MegatronKing** [comment]
v2.4.0已解决。
