### ISSUE TITLE
[feature] Api测试栏支持滚轮操作

### ISSUE THREAD

**Issue by Faserr** [reqable/reqable-app#371]
这里的操作不是很方便, 能否使用鼠标滚轮滑动
![image](https://github.com/reqable/reqable-app/assets/46740335/957943d7-617c-4a8a-ba6c-ba77612d0f7b)

**Comment by MegatronKing** [comment]
@Faserr 感谢反馈，我测试确实能复现。看起来像是Flutter框架的默认设计，需要按住`Shift`按键并滚动滚轮，参考issue #https://github.com/flutter/flutter/issues/105095
下个版本我会优化这个行为，直接通过滚轮来滚动。

**Comment by MegatronKing** [comment]
@Faserr v2.4.0已解决。
