### ISSUE TITLE
[bug] mac m1 抓不了包

### ISSUE THREAD

**Issue by zoushucai** [reqable/reqable-app#373]
反正经常抓不了包,偶尔有些时候有可以, 很奇怪

还有在无痕浏览器下面可以抓包, 但是在正常的浏览器下面访问网页,就抓不了包

**Comment by MegatronKing** [comment]
@zoushucai  因为你浏览器有本地缓存。

**Comment by MegatronKing** [comment]
不是Reqable的问题，所以这个issue我关闭了。
