### ISSUE TITLE
[bug] iOS模拟器，无论是手动导入证书还是自动安装证书，都没办法握手抓包，显示客户端SSL握手失败

### ISSUE THREAD

**Issue by xujiali08** [reqable/reqable-app#375]
![image](https://github.com/reqable/reqable-app/assets/18440881/aa97b750-a94e-4f9b-bbd8-40e4da828d5a)

**Comment by MegatronKing** [comment]
@xujiali08 抓模拟器，证书当然要安装到模拟器里面啦

**Comment by SebaSs007** [comment]
> ![image](https://private-user-images.githubusercontent.com/18440881/295473522-aa97b750-a94e-4f9b-bbd8-40e4da828d5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzEzODksIm5iZiI6MTcwNDg3MTA4OSwicGF0aCI6Ii8xODQ0MDg4MS8yOTU0NzM1MjItYWE5N2I3NTAtYTk0ZS00ZjliLWJiZDgtNDBlNGRhODI4ZDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA3MTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNWRjMTlmNjk2YWQ0MGRkNzg2NzE0ODZkNzYxMTM1MzRhNThjYzcwMTMzZWU1Y2M3M2NmOWU2YTE3ZWJlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p1r_4NedJkl1RAgpouiTDlsd3cQLkj9AjGnulfSzGLk)

iOS模拟器用的哪一款？

**Comment by xujiali08** [comment]
@SebaSs007 我开了很多个模拟器都不可以抓包，并且需要把reqable上的系统代理设置关掉才能使用模拟器，否则也没有网络

**Comment by xujiali08** [comment]
@MegatronKing 对，我也是这样想的，但是一开始模拟器始终打不开http://reqable.proxy/ssl这个网址，现在可以了，非常感谢

**Comment by SebaSs007** [comment]
@xujiali08 哪一个IOS模拟器抓包好用能推荐下么？

**Comment by xujiali08** [comment]
@SebaSs007 用过charles 和 proxyman 都不错，这个reqable 也挺好用的

**Comment by SebaSs007** [comment]
> @SebaSs007 用过charles 和 proxyman 都不错，这个reqable 也挺好用的

谢谢您回复，我是想请教一下IOS模拟器您用的哪款？而不是抓包工具，以前没接触过ios模拟器 资料也不多，想了解下。
谢谢

**Comment by xujiali08** [comment]
> > @SebaSs007 用过charles 和 proxyman 都不错，这个reqable 也挺好用的
> 
> 谢谢您回复，我是想请教一下IOS模拟器您用的哪款？而不是抓包工具，以前没接触过ios模拟器 资料也不多，想了解下。 谢谢

你好，我目前下载了两个系统，截图如下
<img width="381" alt="image" src="https://github.com/reqable/reqable-app/assets/18440881/c07daf17-2b42-45ef-bc78-5ca00ee1c0cd">

**Comment by SebaSs007** [comment]
@xujiali08  感谢！

**Comment by encyclist** [comment]
同样的问题，安卓，已安装证书为系统级证书
