### ISSUE TITLE
[feature] 原始数据，希望用一个cookie字段存放多个cookie值

### ISSUE THREAD

**Issue by LorHua** [reqable/reqable-app#376]
**Is your feature request related to a problem? Please describe.**
cookie分成了多行，不方便复制到其他软件进行测试

**Describe the solution you'd like**
希望多个cookie值放在一个cookie字段（同一行）

**Additional context**
![image](https://github.com/reqable/reqable-app/assets/40552703/07cde192-2a36-4844-89e1-1ed13198a378)

**Comment by MegatronKing** [comment]
重复问题，我先关闭了。
