### ISSUE TITLE
Cannot resolve mmtls request of WeChat since 2024/1/11

### ISSUE THREAD

**Issue by monica9999** [reqable/reqable-app#377]
![image](https://github.com/reqable/reqable-app/assets/31276019/f85af408-c7ff-4638-a343-8219cc4ed877)

**Comment by MegatronKing** [comment]
微信自己实现了一套加密协议，我没看出来有什么问题，你不至于认为reqable能解密吧😅。

**Comment by monica9999** [comment]
> 微信自己实现了一套加密协议，我没看出来有什么问题，你不至于认为reqable能解密吧😅。

哈哈，我还真以为reqable能解密呢，因为我前几天用它拦截微信小程序请求能看到具体信息，但是同样的请求今天开始就看不了了

**Comment by MegatronKing** [comment]
> > 微信自己实现了一套加密协议，我没看出来有什么问题，你不至于认为reqable能解密吧😅。
> 
> 哈哈，我还真以为reqable能解密呢，因为我前几天用它拦截微信小程序请求能看到具体信息，但是同样的请求今天开始就看不了了

你想多了，微信让我们看的，我们才能看到。Reqable只是开发工具，不会针对任何特定的应用程序去做攻防。
