### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by CAI5201314** [reqable/reqable-app#378]
1.好多APP抓包无网，切换到report后目标APP才开始请求响应
2.无法抓取魔法网站，配置成功也没用，更没有IOS端的说明文档
3.代理模式下抓不到包，也没有说明文档
4.只有VPN模式能抓包，但是默认9000端口抓包无网，需要换个端口，鬼知道有没有占用

 - 平台： [ios］
 - 操作系统： [17.2.1］
 - 系统架构：[arm］
 - 应用程序版本： [2.3.2］

**Comment by MegatronKing** [comment]
@CAI5201314 感谢反馈。

> 1.好多APP抓包无网，切换到report后目标APP才开始请求响应

这个问题，请更新到2.4.0版本试试，应该解决了。

> 2.无法抓取魔法网站，配置成功也没用，更没有IOS端的说明文档

可能需要配置二级代理，可以参考PC端的二级代理文档，原理是一样的。

> 3. 代理模式下抓不到包，也没有说明文档

还是文档问题，我新建了个issue #379 ，后面会补上但目前事情太多我一个人忙不过来，非常抱歉。

> 4.只有VPN模式能抓包，但是默认9000端口抓包无网，需要换个端口，鬼知道有没有占用

可能是bug，2.4.0版本修复了一些问题，请更新到2.4.0版本试试。

非常抱歉，带来这么多问题，我会持续优化的。

**Comment by MegatronKing** [comment]
@CAI5201314 这个issue我先关闭了。如果有新的问题，欢迎新开issue反馈。
