### ISSUE TITLE
Forward proxy 

### ISSUE THREAD

**Issue by moolakarapaiyan** [reqable/reqable-app#380]
I am receiving a traffic in reqable but i want to forward the traffic to the burpsuite (another proxy) which is running on same machine?
i think its not possible in reqable, is there any workaround for this

**Comment by MegatronKing** [comment]
@moolakarapaiyan Try `Secondary Proxy` https://reqable.com/en-US/docs/capture/proxy#secondary , config the proxy host and port of burpsuite.
