### ISSUE TITLE
Humble Request to add some features to Reqable

### ISSUE THREAD

**Issue by TechnoIndian** [reqable/reqable-app#382]
Humble Request to add some features to Reqable

( This feature can make Reqable more interesting & attractive. )

1. Add Apk click in "+" ➕ Icon 
![IMG_20240112_105027](https://github.com/reqable/reqable-app/assets/133761719/e6f7cede-747e-4fd6-bdf9-4ff00f9c9bf3)

2. Status Line/Response Code (200,202) Convert in Green Colour
& Error Responce Code Show in Red Colour 
![IMG_20240112_104747](https://github.com/reqable/reqable-app/assets/133761719/c6c54dc9-9f63-4ee3-b9b3-07ea1c78a8c7)

3. Add 🖊 Rewrite Plugins  & Export Plugin Feature :- Request & Response Data Edit & Send Plugin 
![IMG_20240112_104601](https://github.com/reqable/reqable-app/assets/133761719/bea338b8-1f6d-42a9-8e75-72a51850aeeb)
![IMG_20240112_105105](https://github.com/reqable/reqable-app/assets/133761719/62038cf1-edf8-4706-baae-cad909d415da)
![IMG_20240112_104653](https://github.com/reqable/reqable-app/assets/133761719/8ba987b8-905a-47b4-9bd1-72e1e60b2ba3)
![IMG_20240112_104152](https://github.com/reqable/reqable-app/assets/133761719/f3b18cf7-9d5b-40dd-8a29-3baeb933573c)

4. Add JavaScript To Sniff Apk Features :- This Feature can be useful to bypass VPN & PROXY Detect/FLUTTER Detect/Virtual & App Detect /SSL Detect/Api Detect/Frida Detect etc through JavaScript (Frida) 
![IMG_20240112_111935](https://github.com/reqable/reqable-app/assets/133761719/1581c52f-86dc-4a39-85aa-391414df6f46)
![IMG_20240112_112036](https://github.com/reqable/reqable-app/assets/133761719/639e42bd-c4bf-4ad6-911e-b9f123d319c0)

5. Add AES Encryption Key Finder Feature :- As you know that nowadays the data of all apps is encrypted and AES Keys are required to decrypt them, so this feature can prove useful. 
![IMG_20240112_115950](https://github.com/reqable/reqable-app/assets/133761719/07b49f99-95c6-43f5-a66d-61e5162914ed)
![Screenshot_2024-01-12-11-51-45-29_9fe0c6f17021c60d4106a8d843efa668](https://github.com/reqable/reqable-app/assets/133761719/8a0c9425-0631-4c8c-b616-c865e3141bda)

6. Text/Data Decrypt Features :- Make this feature in such a way that once the key & IV is applied, wherever there is data encrypted with that key & IV in the entire App, it gets automatically decrypted, that is, there is no need to decrypt it again and again.

(This feature is exactly the same as when 'SSLKEYLOGFILE' is applied in Wireshark, all the encrypted data captured is automatically decrypted.) 
![IMG_20240112_115512](https://github.com/reqable/reqable-app/assets/133761719/85ab9f34-bb19-489f-8027-7c4037c75556)
![IMG_20240112_115734](https://github.com/reqable/reqable-app/assets/133761719/df2925c5-aadc-40af-9e5b-32ea73467df8)

7.  For Non-root users, uploading an SSL bypass/all detection bypassed app cloner will be the icing on the cake as the data on adding apps can be captured.
![IMG_20240112_104832](https://github.com/reqable/reqable-app/assets/133761719/6677c736-5512-4c81-b189-90015b44acae)

**Comment by ShadyAp** [comment]
nice

**Comment by ShadyAp** [comment]
can i dm u @TechnoIndian ?

**Comment by TechnoIndian** [comment]
This is my ID, you can tell me

**Comment by MegatronKing** [comment]
Thanks for the suggestion, I split the requirements into the followings, and I will close this issue as dunplicated.
#372 #387 #388 #368

**Comment by TechnoIndian** [comment]
But why, I have explained completely

**Comment by TechnoIndian** [comment]
https://github.com/reqable/reqable-app/issues/382

Please Look it 🙏
