### ISSUE TITLE
关于安卓上记录模式

### ISSUE THREAD

**Issue by Arcticlyc** [reqable/reqable-app#384]
没太懂安卓上记录模式（代理和vpn）的区别。

打开vpn时可以捕获流量，代理模式则没有效果；协作时代理模式则可以成功在协作设备上查看。

代理模式是将本机流量代理到协作设备上吗？如果要本机捕获并查看是不是必须用vpn模式？

**Comment by Arcticlyc** [comment]
> @Arcticlyc 抱歉移动端还没有文档。
> 
> 1. VPN模式，主要就是捕获本机流量。
> 2. 代理模式，也可以捕获本机流量，比如你可以把端口设置到wifi的代理选项里面，一般没必要这么用。另一种场景，就是其他设备（比如PC、嵌入式等设备）配置手机的IP地址和代理端口，可以将流量转发到手机上，在手机上调试，不过这个场景也不多。

感谢您的回复。我之前的问题描述有误，我在测试时代理模式确实是协作端设置的，本机使用的是vpn模式。我似乎理解您的意思了：

代理模式主要是用于协作（即将另一设备的流量代理到协作端），当然我也可以设置手机wifi代理来捕获本机流量（我刚刚测试过了，将代理设置为127.0.0.1:9000，成功捕获到了流量），请问是我这样理解的吗？

**Comment by MegatronKing** [comment]
@Arcticlyc 可以这么理解。Reqable在桌面端和移动端都开启了代理服务器，同一个局域网段内的设备都可以将流量转发到这个代理服务器。只是移动端额外有个VPN模式，可以通过VPN将流量自动转发代理服务器（本机或者其他设备都可以），当然你也可以将VPN关闭，关闭就是所谓的`代理模式`，准确地讲应该是`仅代理模式`。
