### ISSUE TITLE
[feature] [android] Support entering the address of the remote device during initialization

### ISSUE THREAD

**Issue by yurijserrano** [reqable/reqable-app#385]
Good Afternoon 

Happy New Year 

I noticed that it is possible to forward the traffic from the mobile app to the Desktop app, scanning the QR code.

Is this possible with Genymotion?

If not, just setting the proxy on the emulator is the only way?

**Comment by MegatronKing** [comment]
@yurijserrano Please try this: Remote Devices -> Click `+` -> Input Address

**Comment by yurijserrano** [comment]
@MegatronKing I followed this procedure, but it did not work.

The request is not being forwarded for the Desktop App.

![image](https://github.com/reqable/reqable-app/assets/14169134/0645b263-17d5-4509-9d22-cd1ea4a5a1c1)

![image](https://github.com/reqable/reqable-app/assets/14169134/ca11e4a8-974d-4868-bd24-7304ec367548)

The Record Mode is VPN.

**Comment by MegatronKing** [comment]
@yurijserrano You should keep the page in remote device tab. And the feature is completed in 2.6.2 version.
