### ISSUE TITLE
[feature] app安卓上能不能加重写功能，就跟小黄鸟一样

### ISSUE THREAD

**Issue by nanzhinet** [reqable/reqable-app#386]
能不能把重写功能加一下呢，开发的时候也能测试验证

**Comment by MegatronKing** [comment]
抱歉，目前没有计划，见#368 。我现在不觉得真有人在手机上有使用重写功能进行开发测试，不过是想搞事罢了，真有开发和测试需求，桌面端的功能已经足够了。
