### ISSUE TITLE
[bug] 首页tab标题显示不完整

### ISSUE THREAD

**Issue by CAI5201314** [reqable/reqable-app#390]
win10电脑端历史数据标签业，有些看不到时间，不知道是不是正常现象
![QQ截图20240113225417](https://github.com/reqable/reqable-app/assets/155355247/82c95541-7061-4dfa-b411-f325c8ac13f7)
侧边栏可以正常显示
![QQ截图20240113225356](https://github.com/reqable/reqable-app/assets/155355247/cede50b1-5962-4eaf-ae7b-747d57c87ba9)
打开到标签页有的显示，有的不显示

**Comment by MegatronKing** [comment]
@CAI5201314 感谢反馈，是bug。将在下个版本修复。

**Comment by MegatronKing** [comment]
@CAI5201314 v2.4.1版本已修复。
