### ISSUE TITLE
[bug] 退出后，电脑无网络

### ISSUE THREAD

**Issue by Hsy-z** [reqable/reqable-app#393]
退出后，电脑无网络，浏览器提示：未连接到互联网，代理服务器出现问题，或者地址有误。

**Comment by MegatronKing** [comment]
@Hsy-z 请问设备系统是什么？是否有安装使用过其他代理相关软件？

**Comment by MegatronKing** [comment]
如果方便的话，可以提供下日志帮助我定位问题，谢谢。

日志目录：
```
C:\Users\xxx\AppData\Roaming\Reqable\log
```

**Comment by MegatronKing** [comment]
未能获取到可以定位问题的信息加上无法复现，这个issue先关闭了。
