### ISSUE TITLE
[feature] [android] 解析DNS结果还原IP域名

### ISSUE THREAD

**Issue by MegatronKing** [reqable/reqable-app#394]
通过VPN转发的TCP流量中可能不包含域名信息，需要通过解析UDP的DNS结果获取，案例见 #354 。

**Comment by SebaSs007** [comment]
@MegatronKing 该功能还未上线么？目前最新版本还是显示IP信息 而非还原为域名。

**Comment by MegatronKing** [comment]
> @MegatronKing 该功能还未上线么？目前最新版本还是显示IP信息 而非还原为域名。

没有，这个功能比较复杂

**Comment by yinsel** [comment]
> @MegatronKing 该功能还未上线么？目前最新版本还是显示IP信息 而非还原为域名。

师傅是在研究涉炸App吗，近些年来这种app确实蛮多

**Comment by SebaSs007** [comment]
> > @MegatronKing 该功能还未上线么？目前最新版本还是显示IP信息 而非还原为域名。
> 
> 师傅是在研究涉炸App吗，近些年来这种app确实蛮多

是的，这一类挺常见的。所以这个功能点就成了刚需，不然就要来再单独用别的工具搞了。

**Comment by yinsel** [comment]
> > > @MegatronKing 该功能还未上线么？目前最新版本还是显示IP信息 而非还原为域名。
> > 
> > 
> > 师傅是在研究涉炸App吗，近些年来这种app确实蛮多
> 
> 是的，这一类挺常见的。所以这个功能点就成了刚需，不然就要来再单独用别的工具搞了。

师傅有遇到过一些涉炸App中通信非HTTP的TCP流量吗，像一些业务如登录，注册都采用的TCP，不知有何办法？

**Comment by SebaSs007** [comment]
@MegatronKing 各位研发大佬加把劲
Reqable 高效又直观，目前就这一类处理不了，还得再切换别的工具实在太难受了。

**Comment by MegatronKing** [comment]
@MegatronKing 莫催，其实这个项目就我一个人在做。虽然我很想立刻马上实现这个功能，但是这个需求太小众了，研发roi太低。我现在主要精力都做大众化的功能，希望将产品营收提一提，毕竟只能靠这个项目来养活自己了，望见谅。

**Comment by SebaSs007** [comment]
> @SebaSs007 莫催，其实这个项目就我一个人在做。虽然我很想立刻马上实现这个功能，但是这个需求太小众了，研发roi太低。我现在主要精力都做大众化的功能，希望将产品营收提一提，毕竟只能靠这个项目来养活自己了，望见谅。

@MegatronKing 辛苦，我以为有一个项目团队，只有1个人做那确实精力不足，不着急慢慢来吧。
祝大佬产品大卖。

**Comment by MegatronKing** [comment]
@SebaSs007 有空试试最新版本v2.19.1，理论上这个问题应该是优化掉了。

**Comment by SebaSs007** [comment]
@MegatronKing 测试了这类样本，这个问题确实解决了，目前可以正确显示域名信息 而不只是IP了。

**Comment by MegatronKing** [comment]
感谢测试和反馈，这个issue我关闭了。
