### ISSUE TITLE
[bug] cookie生成代码有2个

### ISSUE THREAD

**Issue by 363137946** [reqable/reqable-app#397]
安卓2.4.0版本，生成代码，如果有请求头有cookie，会生成2份重复的
比如原来是cookie: xxx
现在生成的是cookie: xxx, xxx
重复了

**Comment by MegatronKing** [comment]
@363137946 感谢反馈，能复现，将在下个版本修复。

**Comment by MegatronKing** [comment]
@363137946 v2.4.1版本已修复。
