### ISSUE TITLE
Genymotion - Certification Installation

### ISSUE THREAD

**Issue by yurijserrano** [reqable/reqable-app#398]
Good Morning

I have installed the reqable app, but in order to install the certification it requires:

![image](https://github.com/reqable/reqable-app/assets/14169134/032d3013-acd9-431a-a949-5b62bdbad609)

However, I am using Genymotion and I did not find a way to initiate in writable system.

Is there a way to overcome this?

**Comment by MegatronKing** [comment]
@yurijserrano Sorry, I'm afraid I can't help you because I'm not familiar with Genymotion.

**Comment by yurijserrano** [comment]
@MegatronKing  Genymotion is an Android Simulator which allows to install several emulators with several capabilities and versions:

Link: https://www.genymotion.com/

Many people use it, so I think it would be good to provide support, if not now, at least in the near future.

**Comment by yurijserrano** [comment]
I was able to include the certification in the folder, but it's still appearing that it was not installed, as can be observed below:

![image](https://github.com/reqable/reqable-app/assets/14169134/04c8a468-1c30-455e-8d9c-0806d51aef69)

![image](https://github.com/reqable/reqable-app/assets/14169134/8d891841-53c6-487a-b0f3-c778b1c3af40)

![image](https://github.com/reqable/reqable-app/assets/14169134/e0b89eeb-f0ae-4090-bcdb-fd14e567070f)

**Comment by MegatronKing** [comment]
> I was able to include the certification in the folder, but it's still appearing that it was not installed, as can be observed below:
> 
> ![image](https://private-user-images.githubusercontent.com/14169134/297524186-04c8a468-1c30-455e-8d9c-0806d51aef69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDM0MzEsIm5iZiI6MTcwNTY0MzEzMSwicGF0aCI6Ii8xNDE2OTEzNC8yOTc1MjQxODYtMDRjOGE0NjgtMWMzMC00NTVlLThkOWMtMDgwNmQ1MWFlZjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMWE2YTg2MDgzOTc0YTU5YzJlMmRjMGEwODdjMTA3NGExNTNhZjJhMWExMzFlYTQ5YzZjNjQ2ODZhNGI2NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QNscvKRZ71rltHFictPv250cV6cK5mQGJOEl1d5wOMk)
> 
> ![image](https://private-user-images.githubusercontent.com/14169134/297524302-8d891841-53c6-487a-b0f3-c778b1c3af40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDM0MzEsIm5iZiI6MTcwNTY0MzEzMSwicGF0aCI6Ii8xNDE2OTEzNC8yOTc1MjQzMDItOGQ4OTE4NDEtNTNjNi00ODdhLWIwZjMtYzc3OGIxYzNhZjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNjQ1NDEyOGJmMTNlNjhhZjM2Y2FkMzY2MjZhYjllM2NmOWRiZDcxZjAwMjAxNzIyMjJiZmM4NWQ5MWFhODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gm3naM7XI97GneEXVeapDtlDtJjRSuNTp-B5FIJMOac)
> 
> ![image](https://private-user-images.githubusercontent.com/14169134/297524997-e0b89eeb-f0ae-4090-bcdb-fd14e567070f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDM0MzEsIm5iZiI6MTcwNTY0MzEzMSwicGF0aCI6Ii8xNDE2OTEzNC8yOTc1MjQ5OTctZTBiODllZWItZjBhZS00MDkwLWJjZGItZmQxNGU1NjcwNzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YTkyM2Y4NjFkMjRkYTc1YjRjNGEyNWUyMWRhNmQ1MDZhOWM2NmFmODY5ZDQ2NDk3NGY4MDgzNWYyMTRjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xYo-exoovNNmFHviYw0AUexqZ3xIAqDlxCxraqB1vuY)

Have you checked the certificate file permissions? Try keeping file permissions consistent with other certificates.

**Comment by yurijserrano** [comment]
@MegatronKing Thanks for the tip now I was able to install the certificate properly, if you need it, I could write a guide for Genymotion users to use your application as well.

**Comment by MegatronKing** [comment]
> @MegatronKing Thanks for the tip now I was able to install the certificate properly, if you need it, I could write a guide for Genymotion users to use your application as well.

👀 Great, very welcome.

**Comment by baserker2** [comment]
> [@MegatronKing](https://github.com/MegatronKing) Thanks for the tip now I was able to install the certificate properly, if you need it, I could write a guide for Genymotion users to use your application as well.感谢您的提示，现在我能够正确安装证书，如果您需要，我可以为 Genymotion 用户编写一份指南来使用您的应用程序。

I really need this, would you have a plan to do this?
