### ISSUE TITLE
参与内测人员信息填写单

### ISSUE THREAD

**Issue by MegatronKing** [reqable/reqable-app#4]
戳👉：https://wj.qq.com/s2/11766634/74dd

**Comment by VwEl** [comment]
来晚了

**Comment by MegatronKing** [comment]
内测报名已结束，感谢关注！

**Comment by csyjyy** [comment]
求一个内测码！1192031943@qq.com

**Comment by i11m20n** [comment]
求一个内测码，谢谢！honkerunionofchina@foxmail.com
@MegatronKing

**Comment by MegatronKing** [comment]
各位，感谢关注！由于Reqable内测即将结束，已停止发放新的邀请码。过几天就正式发布了，届时可以大家可以直接去官网下载正式公开版本。

**Comment by MegatronKing** [comment]
Reqable已正式发布：https://reqable.com/
