### ISSUE TITLE
[feature] 脚本功能建议增加自定义模板功能

### ISSUE THREAD

**Issue by MoLeft** [reqable/reqable-app#400]
希望可以添加自定义脚本模板功, 因为有的场景下可能涉及到数据的加密和解密,以及json格式化,通过自定义脚本模板,可以快速编写脚本
目前我在调试同一个接口时,都需要将以前写的代码复制过来.
![image](https://github.com/reqable/reqable-app/assets/41848811/ffbcefb0-af8a-4a45-8c6a-c6df1ef16899)
同时希望可以自定义脚本储存的路径

**Comment by MegatronKing** [comment]
@MoLeft 巧了，我刚刚恰好正在思考这个问题。脚本模板这个功能会进一步深化去做，包括会提供一些常用的公用模板，比如阿里云oss签名。

**Comment by MegatronKing** [comment]
@MoLeft v2.5.0版本已支持。
