### ISSUE TITLE
[bug] 在系统安装有三方中文字体的情况下，界面部分控件显示字体会怪异

### ISSUE THREAD

**Issue by iccfish** [reqable/reqable-app#401]
**Describe the bug**
Windows系统，系统安装有三方中文字体，这时reqable的界面中部分UI界面会显示出非系统默认字体（微软雅黑等）。这个问题其实在Chrome/Edge浏览器中也有。我尝试过卸载看到的中文字体，但卸载一个后界面又会显示成别个中文字体，就没法搞了。

建议统一所有控件的字体设定哈。

**Expected behavior**
整个界面字体一致。

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/1091653/c141b21e-b7d2-4c85-b7a0-2175e8401ff2)

**Information**
 - Platform: Windows
 - OS: Windows 11

**Comment by MegatronKing** [comment]
@iccfish 挺奇怪，看起来像是flutter框架的问题，我先研究下。

**Comment by MegatronKing** [comment]
@iccfish 你好，我们在最新版本2.12.1修复了这个问题，可以验证下。
