### ISSUE TITLE
[bug] 二级代理可能会进入莫比乌斯环

### ISSUE THREAD

**Issue by Asura88** [reqable/reqable-app#402]
刚刚升级到最新版本，卡顿不行，只能重启

**Comment by Asura88** [comment]
![image](https://github.com/reqable/reqable-app/assets/25000885/afdbb9a8-b432-4784-833a-b1e0ff57218c)

**Comment by MegatronKing** [comment]
@Asura88 感谢反馈，我在了解下详细的情况。

1. 是因为这个数据多了卡顿吗？还是说没有数据的时候也卡顿？
2. 升级之前的版本号是多少？

**Comment by Asura88** [comment]
1.没有数据不卡顿，只要有数据就卡，数据很多，一次性出现
2.应该是2.4.0
3.配置没问题，上一个版本很流畅，16g运行内存，i7

**Comment by Asura88** [comment]
重新安装了旧版本，居然也卡了，很奇怪，都是Connect包

**Comment by MegatronKing** [comment]
> 1.没有数据不卡顿，只要有数据就卡，数据很多，一次性出现 2.应该是2.4.0 3.配置没问题，上一个版本很流畅，16g运行内存，i7

感谢提供信息。方便的话，能否提供下日志呢？
1. 进入Reqable设置页面，打开`调试日志`开关。
2. 复现下数据很多，一次性出现的问题。
3. 找到日志文件：C:\Users\xxx\AppData\Roaming\Reqable\log

为了能更好解决问题，如果方便的话可以加下我微信。

![](https://reqable.com/zh-CN/assets/images/wechat_qrcode-e1215c7f8fc0b29146b37cfb7d3f624f.jpg)

**Comment by MegatronKing** [comment]
v2.5.0已添加循环请求检测。
