### ISSUE TITLE
[feature] 列表显示增加排除的能力

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#405]
首先我知道网关可以排除掉部分流量，但是个人比较少用网关，一个原因是怕配错导致漏掉重要的请求，另一个是比如是已知的流量才能配到网关里排除。

但是实际使用过程中经常会有临时的需求，比如排除 aaa 域名的流量，排除所有 css 请求等，感觉需要一个更灵活的方案。

**Comment by MegatronKing** [comment]
@RonaldinhoL 我目前没想到合适的方法，也许搜索需要支持下取反逻辑？

**Comment by MegatronKing** [comment]
v2.21.0已支持搜索取反匹配。
