### ISSUE TITLE
[bug] Webstock content. There is a partial missing and Extremely long loading times, even 50 seconds

### ISSUE THREAD

**Issue by MNDIA** [reqable/reqable-app#406]
**Describe the bug**
![Screenshot_20240122-000839_Reqable](https://github.com/reqable/reqable-app/assets/74826767/d0543780-ff10-4d58-9bff-4e3a768a3686)
1- Webstock内容加载时间极长（不限于首次加载），50秒，有结果甚至看不到结果。同设备环境对比，httpcanary查看Webstock立刻出结果。

2- 对比内容，发现内容缺失。
httpcanary显示前部分发送内容（两条绿色），在requable中没有显示（整个requable工具也没有其他入口可以看Webstock）
![{7D21AEC0-1B09-49a4-B085-FFD5FBF9A7E0}](https://github.com/reqable/reqable-app/assets/74826767/51cec4d1-5021-4766-b057-61c789821cd9)

**Information**
 同设备环境多次反复对比测试requable和httpcanary
 同有系统证书
 同vpn实现
com.reqable.android为2.4.1版本
com.reqable.android.helper为1.0.0版本

**Comment by MNDIA** [comment]
然后我尝试了windows端协同工作分析。webstocket存一样的问题
1加载耗时1分钟以上（即使是同一webstocket包，已经打开查看过，再次打开还会很久加载）
![image](https://github.com/reqable/reqable-app/assets/74826767/f0df8311-ad44-4d5b-bd3c-5f90363769c6)
2内容缺失
![image](https://github.com/reqable/reqable-app/assets/74826767/5618abf2-62d6-4716-9e77-c51ef8d62608)

**Comment by MegatronKing** [comment]
@MNDIA 感谢反馈，已确认问题，会尽快修复。

**Comment by MegatronKing** [comment]
@MNDIA v2.5.0已修复此问题。
