### ISSUE TITLE
[bug] [Android] Mobile App not working on Android emulators

### ISSUE THREAD

**Issue by r00tee** [reqable/reqable-app#407]
I tried using the app on memu play emulator
But unfortunately it does not work, I get an error message "Reqable keeps stopping"

![2024-01-22_060510](https://github.com/reqable/reqable-app/assets/32619657/0153ec01-314b-49d3-996b-6636fd54640d)

**Comment by MegatronKing** [comment]
@r00tee Reqable Android only supports arm arch now.

**Comment by MegatronKing** [comment]
Same as #410
