### ISSUE TITLE
[feature] 导出HAR文件时记录高亮信息

### ISSUE THREAD

**Issue by freeloop4032** [reqable/reqable-app#408]
数据包高亮，保存本地后，增加打开后依旧高亮状态，因为有的时候包数据包多且乱，二次分析不方便

**Comment by MegatronKing** [comment]
@freeloop4032 感谢建议。这个功能比较简单，下个版本加上。

**Comment by freeloop4032** [comment]
> @freeloop4032 感谢建议。这个功能比较简单，下个版本加上。

同一个痛点的小需求：抓完大量数据后，添加一个自定义字段隐藏相关无用数据包的功能（只是隐藏非删除），提高分析排除效率，目前处理无用数据包，貌似只有手动删除、搜索字段全选删除（经常遇到右键删除灰色状态不能删除）、根据请求方式提交数据类型这几种方式，效率不是很高

**Comment by MegatronKing** [comment]
@freeloop4032 HAR记录高亮信息v2.5.0版本已实现。

> 添加一个自定义字段隐藏相关无用数据包的功能

你看看是不是和 #405 是一个意思？

> 经常遇到右键删除灰色状态不能删除

从历史记录和HAR文件打开是只读的，无法删除，也许做个假删除？

**Comment by MegatronKing** [comment]
这个issue的功能已经实现了，先关闭。如果有新的建议或者问题，请新开issue。
