### ISSUE TITLE
程序未退出[bug] 

### ISSUE THREAD

**Issue by lsdlh** [reqable/reqable-app#409]
已经在图标那里点了退出，图标消失了，进程但还在，导致无法从桌面图标再次启动
![image](https://github.com/reqable/reqable-app/assets/45959509/39bffaaa-43e8-4c58-9887-71fa7239ae8a)

**Comment by MegatronKing** [comment]
@lsdlh 这个是最新版本吗？能提供下当时的log文件吗？log在下面这个目录
```
C:\Users\xxx\AppData\Roaming\Reqable\log
```

**Comment by lsdlh** [comment]
> @lsdlh 这个是最新版本吗？能提供下当时的log文件吗？log在下面这个目录
> 
> ```
> C:\Users\xxx\AppData\Roaming\Reqable\log
> ```
[20240119041800-427b10b0-b6a3-11ee-af75-ed85e080a4b4.log](https://github.com/reqable/reqable-app/files/14017862/20240119041800-427b10b0-b6a3-11ee-af75-ed85e080a4b4.log)


是最新版，

**Comment by MegatronKing** [comment]
@lsdlh 2.8.0版本已经修复！
