### ISSUE TITLE
[bug] 证书不被信任

### ISSUE THREAD

**Issue by Acytoo** [reqable/reqable-app#411]
**Describe the bug**
Arch Linux Desktop, Firefox Browser，最新 reqable
安装了证书，火狐显示使用了 Reqable 的证书，但是 依旧不被信任，有些网站可以强制访问，但是有一些不可以，例如 Google 的网站，使用 Google Firebase 登录的网站也不可以。

![image](https://github.com/reqable/reqable-app/assets/18031762/adc73462-a70b-4879-9c91-462f885e1ad9)

![image](https://github.com/reqable/reqable-app/assets/18031762/0b2da6a1-0c95-4edb-829b-3a6d6054045b)

**Comment by MegatronKing** [comment]
@Acytoo 是不是没有把证书导入火狐浏览器？证书安装里面应该是有这一步提示的。

**Comment by Acytoo** [comment]
哦哦，原来在系统里安装证书后还要在 firefox 里安装。

有没有添加 socks5 二级代理的想法？目前 http 不稳定，有时候无法用，似乎是 DNS 请求不能通过？界面里看到连接超时，没有 destination ip。

**Comment by MegatronKing** [comment]
> 哦哦，原来在系统里安装证书后还要在 firefox 里安装。
> 
> 有没有添加 socks5 二级代理的想法？目前 http 不稳定，有时候无法用，似乎是 DNS 请求不能通过？界面里看到连接超时，没有 destination ip。

1. socks5 二级代理我感觉没必要，一般代理软件都会开HTTP代理端口的。
2. SOCKS代理的DNS解析时在本机，如果希望DNS解析不走本机，就把SOCKS关掉，只保留HTTP/HTTPS代理。
