### ISSUE TITLE
[feature] App流量分析

### ISSUE THREAD

**Issue by yinsel** [reqable/reqable-app#412]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

当我想关闭SSL代理时，发现没有关闭按钮，于是我卸载证书重启，SSL代理关闭了（图标变黄），希望添加SSL代理一键关闭功能，因为需要App有时候证书校验较为严格，可以选择不查看HTTPS流量内容而捕获域名。

另外，有一个问题：SSL代理关闭后，PC端浏览器走代理正常访问，但App通过一些VPN代理软件如VProxy、Proxifier走PC的reqable的代理时，打开浏览器显示证书不可信。

**Comment by MegatronKing** [comment]
@yinsel 建议配置SSL旁路：https://reqable.com/zh-CN/docs/capture/ssl

**Comment by yinsel** [comment]
> @yinsel 建议配置SSL旁路：https://reqable.com/zh-CN/docs/capture/ssl

但是我不知道对方域名，甚至可能是IP，能否直接配置SSL旁落匹配所有？

**Comment by MegatronKing** [comment]
> > @yinsel 建议配置SSL旁路：https://reqable.com/zh-CN/docs/capture/ssl
> 
> 但是我不知道对方域名，甚至可能是IP，能否直接配置SSL旁落匹配所有？

可以，配置一个 * 就行

**Comment by MegatronKing** [comment]
如果没有问题，这个issue先关闭了。
