### ISSUE TITLE
[feature] 接口的发送按钮 颜色能不能调亮点

### ISSUE THREAD

**Issue by vigor1453** [reqable/reqable-app#414]
![image](https://github.com/reqable/reqable-app/assets/49779962/748332a3-abc0-422c-8730-ab56381c7f8a)
上面的启动按钮颜色太明显,想点发送很容易会误按到启动

**Comment by MegatronKing** [comment]
@vigor1453 下个版本会提供禅模式，顶部的操作栏可以隐藏，可以避免在API测试模式时误点调试开关按钮。

**Comment by MegatronKing** [comment]
@vigor1453 v2.5.0已发布，双击tab可以进入禅模式。
