### ISSUE TITLE
[bug] 系统代理一直是未设置

### ISSUE THREAD

**Issue by Acheng97** [reqable/reqable-app#418]
版本：2.4.1 (66) (arm64)
系统：Mac m2
打开app后，系统代理一直是未设置，手动点击系统代理，过一会自己又回到未设置状态，无法抓包
<img width="455" alt="image" src="https://github.com/reqable/reqable-app/assets/65265814/2447b8a5-7930-4dab-bd74-c5c7013fb4d9">

**Comment by MegatronKing** [comment]
@Acheng97 代理辅助工具安装了吗？

**Comment by Acheng97** [comment]
没有安装，在哪里下载

**Comment by MegatronKing** [comment]
> 没有安装，在哪里下载

代理菜单，或者右键代理图标

**Comment by Acheng97** [comment]
已安装，现在可以了，谢谢
