### ISSUE TITLE
[feature] 留意reqable响应处理

### ISSUE THREAD

**Issue by feijihong** [reqable/reqable-app#42]
水平很低，但是我把我遇到的问题说一下
最近在使用httpcanary时
发现，在响应的抓包，含有中文的话
在高流量高并发时，可能会出现中文乱码
是突然有1个中文乱码，不是所有中文乱码
这种乱码我之前在用nodejs的http模块做请求时遇到过
感觉是在chunk，拼接数据流的时候出问题
那时，改成request就解决了

希望可以留意一下

**Comment by MegatronKing** [comment]
reqable采用和httpcanary完全不一样的技术实现，应该不会存在issue所说的并发问题。不管怎样，还是感谢您的建议，如果使用reqable的过程中有遇到类似问题，欢迎反馈给我们，谢谢。
