### ISSUE TITLE
[feature] 脚本支持获取应用信息

### ISSUE THREAD

**Issue by darkqiank** [reqable/reqable-app#420]
**Is your feature request related to a problem? Please describe.**
每条请求的来源应用只在界面上展示，可以通过接口或者脚本来分析、筛选吗

**Comment by MegatronKing** [comment]
@darkqiank 您好，感谢提供建议。请问能提供个具体的场景吗？或者举一个例子，方便我们对齐需求。

**Comment by mystery4f** [comment]
> @darkqiank 您好，感谢提供建议。请问能提供个具体的场景吗？或者举一个例子，方便我们对齐需求。

后端模拟第三方接口响应。

**Comment by MegatronKing** [comment]
v2.14.0已支持通过脚本获取应用信息。
