### ISSUE TITLE
[feature] 这...实属有点大啊

### ISSUE THREAD

**Issue by fafa889** [reqable/reqable-app#421]
![85ff44492f61c68910f2f2a0155b985](https://github.com/reqable/reqable-app/assets/36075503/c6b82350-5e49-4be0-9f13-1226d869a507)

**Comment by MegatronKing** [comment]
@fafa889 额，检查下这里是不是改成永久了？
![image](https://github.com/reqable/reqable-app/assets/15059084/0fe3f01c-a1da-4663-8e7e-719a20198051)

**Comment by fafa889** [comment]
设置的7天，已经解决了。写了个bat定时清理

**Comment by MegatronKing** [comment]
@fafa889 好的，请问你这7天内有使用很频繁吗？逻辑上超过7天的历史记录会自动清理掉的。

**Comment by MegatronKing** [comment]
这个问题我先关闭了，如果有发现超出设定的缓存时间的历史数据未清理的话再重新打开。
PS. 如果不希望缓存数据，可以开启无痕模式。
