### ISSUE TITLE
[feature] 后续导出功能否增加更多选项

### ISSUE THREAD

**Issue by SebaSs007** [reqable/reqable-app#425]
目前批量导出 仅支持导出HAR，不包含应用信息等内容，能否增加一份更完整的导出信息用以补充？
同时导出har+完整流量，适用场景为 抓包留证 。
谢谢，望采纳

**Comment by MegatronKing** [comment]
@SebaSs007 2.5.0应该是包含应用信息内容的。

**Comment by SebaSs007** [comment]
@SebaSs007 之前导出时没有，刚才试了试现在版本有了，谢谢。
