### ISSUE TITLE
授权方式可以从三台不同设备改为2台同样的设备吗？

### ISSUE THREAD

**Issue by xdkhan** [reqable/reqable-app#427]
现在个人版授权是：1 Mac + 1 Windows + 1 Linux 设备
但是常见的场景是公司Mac长时间使用，下班时间在家中Mac使用。
两种场景使用时间不会重复，有没有可能把授权改为两台Mac，或者限制同一种授权设备不能同时使用。

**Comment by MegatronKing** [comment]
@xdkhan 年后专业版会新增一个拓展设备位，也就是在已有的设备平台下再新增一个通用设备位，即5台不同设备 + 1台任意平台设备。这个功能上线后，已购买的用户会直接赠送，新购的用户可以选择加购或者不加购。

**Comment by MegatronKing** [comment]
这个功能其实是在计划之内，但是年前肯定来不及上线了，大概是年后上线。

**Comment by MegatronKing** [comment]
相关功能请大家参考 #436 ，这个问题先关闭。
