### ISSUE TITLE
[feature] 扫码连接电脑，自动配置代理

### ISSUE THREAD

**Issue by wao3** [reqable/reqable-app#428]
想用PC端对手机抓包，必须手动配置代理

既然同时有PC端和手机端，应该可以做到PC端生成二维码，让手机端扫码获取PC代理配置，通过自动配置手机VPN的方式连接到PC端代理，然后在PC端对手机抓包吧？

ps：看到现在有一个手机协同配置的功能，但是用了以下看起来是用手机控制PC代理开关的，和我说的功能不太一样

**Comment by MegatronKing** [comment]
@wao3 不需要手动设置代理，协同模式就是使用VPN进行转发的。参考我这篇文章：https://juejin.cn/post/7325255455289753634

**Comment by wao3** [comment]
@MegatronKing 试用了一下确实可以，但是似乎有bug？总是开启的一段时间能用，之后大概30秒后就用不了了，表现就是手机没网了，PC上没有抓到新的包。还有就是看了系统设置页面确实开了VPN，但是手机状态栏上没有VPN标识？
app都是最新版的
手机是iPhone13，iOS 17.0.3

**Comment by wao3** [comment]
看到有一样的反馈bug的了
#404

**Comment by wao3** [comment]
另外，看上一个issue说的是macos的bug，我这也是macos，但是应该只是手机端app有问题，因为我手动配置代理的话，就不会有这个问题

**Comment by MegatronKing** [comment]
> @MegatronKing 试用了一下确实可以，但是似乎有bug？总是开启的一段时间能用，之后大概30秒后就用不了了，表现就是手机没网了，PC上没有抓到新的包。还有就是看了系统设置页面确实开了VPN，但是手机状态栏上没有VPN标识？ app都是最新版的 手机是iPhone13，iOS 17.0.3

是有这个问题的，v2.6.0版本已经修复提交，等审核通过后你再试试？
