### ISSUE TITLE
[windows][bug] Proxifier无法转发到reqable代理服务器

### ISSUE THREAD

**Issue by huang95-Q** [reqable/reqable-app#43]
**Describe the bug**
使用Proxifier挂载全局代理时无法设置HTTPS代理

**To Reproduce**
1.在Proxifier添加好对应代理地址和端口并设置HTTPS协议；
2.配置好相关代理规则；
3.测试代理服务一直没法通过
**Expected behavior**
希望大佬有时间能够解决一下，谢谢

**Screenshots**

![image](https://user-images.githubusercontent.com/58483002/235290120-e21ef041-95e0-41f9-985c-cb3f2a7449b5.png)

**Information**
 - Platform: windows
 - OS: 11
 - Arch: x86-64
 - App Version: 0.1.4（10）

**Notes**
经过我测试发现fiddler和Charles没问题，由于fiddler只支持https协议，所以只测试了http和https，经测试没问题，可以正常加载通过，Charles支持htpp和socks，所以两项都测试了，也都没问题。

**Comment by MegatronKing** [comment]
@huang95-Q 麻烦看一下0.1.6版本，是不是还有这个问题。

**Comment by huang95-Q** [comment]
> @huang95-Q 麻烦看一下0.1.6版本，是不是还有这个问题。

谢谢大佬啦，已经解决了
