### ISSUE TITLE
[feature] Add `Comment` column in traffic list.

### ISSUE THREAD

**Issue by lol-1-afk** [reqable/reqable-app#432]
Firstly, thanks for the software, it is awesome

Bookmars is nice feature, but can you plase add "Comment" Column? Like in fiddler, it is very usefull
![image](https://github.com/reqable/reqable-app/assets/58441229/b3e5f473-6604-46b7-ad23-206f9c284629)

~Also, please add feature to filter requests and hide them. Like i don't want to see analytics requests or requests from FireFox~
Found -> Gateway - Silently

Speakig about requests from different processes, it will be great if you create feature to select process to sniff (popup list of running processes, click to select)
![image](https://github.com/reqable/reqable-app/assets/58441229/9e21bf71-451d-4149-99cf-5eb2e20025b3)
![image](https://github.com/reqable/reqable-app/assets/58441229/99107acd-c8ad-448e-bd03-62cdafacd2d7)
![image](https://github.com/reqable/reqable-app/assets/58441229/174d09a1-10c6-42b2-817a-f8b91d166f57)

Again thanks for reqable!!

**Comment by MegatronKing** [comment]
@lol-1-afk Thanks for your feedback.

> Speakig about requests from different processes, it will be great if you create feature to select process to sniff (popup list of running processes, click to select)

You can filter apps from the `Explore` tab.

**Comment by lol-1-afk** [comment]
sorry, haven't found it . What about comments?

**Comment by MegatronKing** [comment]
> sorry, haven't found it . What about comments?

This is a new feature, not available yet.

**Comment by MegatronKing** [comment]
2.8.0 is available now. `Comment` is not enabled by default, but you can enable it by yourself.
