### ISSUE TITLE
reqable脚本编辑器修改意见

### ISSUE THREAD

**Issue by zbx911** [reqable/reqable-app#433]
1.指定脚本路径;
2.输出窗口不用每次都输出 时间和 运行环境;
08:03:19.383 Running script with python 3.10.9
3.tcp的支持

**Comment by MegatronKing** [comment]
@zbx911 感谢建议。

> 1.指定脚本路径;

抱歉，没能理解你的意思，可否详细说下呢？

> 2.输出窗口不用每次都输出 时间和 运行环境;

v2.6.0版本已经去除运行环境日志。另外，时间是否显示可以通过下方按钮控制的。

> 3.tcp的支持。

抱歉，不在支持范围内。目前仅以HTTP协议和衍生协议为主要业务方向。

**Comment by MegatronKing** [comment]
@zbx911 这个issue我先关闭了，如果有新的建议或者问题请新开issue，谢谢。
