### ISSUE TITLE
[bug] API模式启用脚本之后，URL参数的?会被转义

### ISSUE THREAD

**Issue by rxbit** [reqable/reqable-app#435]
**Describe the bug**
API模式启用脚本之后，URL参数的?会被转义

**To Reproduce**

API模式打开脚本，请求带参数的URL，如`https://httpbin.org/post?param=abc`

**Expected behavior**

不转义

**Screenshots**

正常请求

![image](https://github.com/reqable/reqable-app/assets/1555218/db3dc943-0a2e-4046-ac08-b3aaf178c1dc)

启用脚本后

![image](https://github.com/reqable/reqable-app/assets/1555218/f4bf4e0a-d9c5-474b-84e4-54a380937d11)

开启跟踪可以看到"?"被转义成了%3F

![image](https://github.com/reqable/reqable-app/assets/1555218/06093280-5e10-4c5b-b7fd-714d6a07ea8f)

**Information**
 - Platform: macos
 - OS: 14.2.1
 - Arch: arm64
 - App Version: 2.6.1

**Comment by MegatronKing** [comment]
@rxbit 感谢反馈，问题已确认。
