### ISSUE TITLE
[活动] `专业版`许可证可免费升级至`专业版Plus`许可证预告

### ISSUE THREAD

**Issue by MegatronKing** [reqable/reqable-app#436]
Reqable将在春节之后推出`专业版Plus`许可证。

目前的`专业版`许可证可以同时授权5台不同平台的设备，即 1 Windows + 1 Mac + 1 Linux + 1 Android + 1 iOS，而`专业版Plus`许可证将额外增加一个通用平台设备位，即 1 Windows + 1 Mac + 1 Linux + 1 Android + 1 iOS + 1 Any，通用平台设备指目前5大平台中的任意一个，也就是可以同时授权2台Windows设备或者2台Mac设备等等。

`专业版Plus`许可证计划上线时间为2024-02-19日，届时大家可以自主选择是否将已有的`专业版`许可证**免费升级**至`专业版Plus`许可证。

感谢大家对Reqable的支持，提前祝大家春节快乐！

**Comment by rouxianmantou** [comment]
为啥要把平台加到权益里面呢，不能X pc devices / Y mobile devices这种吗？我和我对象总共3台mac，还要订阅两个。。

**Comment by MegatronKing** [comment]
> 为啥要把平台加到权益里面呢，不能X pc devices / Y mobile devices这种吗？我和我对象总共3台mac，还要订阅两个。。

销售模式其实是参考的竞品，例如Charles、Proxyman等，他们的模式都是一个许可证激活一台设备，Reqable是一个许可证多台设备，打低价路线。那为什么不能X pc devices / Y mobile devices这种呢，SKU太多我维护不过来，如果用户需要添加或者删减设备，组合太多，这个处理就会很麻烦。另外，三台相同设备可以考虑直接买企业版，按照席位分配。

**Comment by MegatronKing** [comment]
已上线。
