### ISSUE TITLE
[feature] reqable脚本编辑器修改意见 

### ISSUE THREAD

**Issue by zbx911** [reqable/reqable-app#438]
1.对指定的url的设置指定的脚本，并设置脚本保存加载路径
2.或者设置统一脚本，用脚本控制url处理方式
3.脚本的log输出，可以单独成一个大的界面，添加filter操作框，处理筛选后的信息，可以参考charls的url过滤功能

**Comment by MegatronKing** [comment]
@zbx911 感谢建议。

> 1. 对指定的url的设置指定的脚本，并设置脚本保存加载路径

这个功能是有的，建议看下文档。

> 2.或者设置统一脚本，用脚本控制url处理方式

没太明白您的意思，可否详细说下呢？

> 3.脚本的log输出，可以单独成一个大的界面，添加filter操作框，处理筛选后的信息，可以参考charls的url过滤功能

新版本有控制台Tab，可以进行搜索

**Comment by MegatronKing** [comment]
@zbx911 你好，如果没有进一步的信息，这个issue我就关闭了。
