### ISSUE TITLE
Android app 

### ISSUE THREAD

**Issue by Bahaa-dev** [reqable/reqable-app#44]
Hello Megatron King Is There is any news about the android app ? i want to make a donation to speed the process of build this app cuz i am a user of httpcanary and it's a great app 
Is there is any email i can text you please let me know .

**Comment by MegatronKing** [comment]
Thanks for the support. There is no plan for a mobile platform at this stage, at least we need to wait for the official release of the desktop.

**Comment by MegatronKing** [comment]
Hello，


We have released desktop version, but the mobile version is still in planning and has not yet started development. You can visite our website for more information about desktop version.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reqable/reqable-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月1日(星期一) 下午5:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[reqable/reqable-app] Android app  (Issue #44)





 
Hello Megatron King Is There is any news about the android app ? i want to make a donation to speed the process of build this app cuz i am a user of httpcanary and it's a great app
 Is there is any email i can text you please let me know .
