### ISSUE TITLE
[bug] glibc 更新到 2.39 后无法使用

### ISSUE THREAD

**Issue by Acytoo** [reqable/reqable-app#440]
Hey Bro, 今天 Arch Linux 更新了glibc，从 2.38. 到 2.39，后，reqable 无法启动，报错

```
g_application_set_application_id: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed [1] 9000 segmentation fault (core dumped) 
```

似乎跟新版本声明 Application 的方式变了有关，回滚 glibc 到上一个版本后正常使用， 请问有没有更新依赖的计划呢？

![Screenshot from 2024-02-04 12-35-28](https://github.com/reqable/reqable-app/assets/18031762/a575033d-581e-4c27-b899-14946c2ce024)
![Screenshot from 2024-02-04 12-35-08](https://github.com/reqable/reqable-app/assets/18031762/db659a78-418a-4f75-b451-286f7f94cbbb)

**Information**
 - Platform: linux
 - Arch:  x86-64
 - App Version: latest

**Comment by MegatronKing** [comment]
@Acytoo 感谢反馈，看起来像现有application id格式不支持的问题，下个版本试试修复。

**Comment by MegatronKing** [comment]
@Acytoo 试试最新版本2.6.3，已发布。

**Comment by Acytoo** [comment]
在 glibc 2.39 下依旧不能用，这次是 segmentation fault

![image](https://github.com/reqable/reqable-app/assets/18031762/a6a263aa-a560-45d0-8fae-827c636f34b9)

新版本在 glibc 2.38 下依旧可以使用，我是用缓存的 2.38 安装的，更换了下面两个包
![image](https://github.com/reqable/reqable-app/assets/18031762/ce9e21a6-da97-4f4c-86f6-c8deb5f66da6)

**Comment by MegatronKing** [comment]
@Acytoo @WzLYVg387U 麻烦试试这个版本：
deb文件：https://reqable-generic.pkg.coding.net/package/app/reqable-app-linux-x86_64.deb?version=test
appImage文件：https://reqable-generic.pkg.coding.net/package/app/reqable-app-linux-x86_64.AppImage?version=test

**Comment by Acytoo** [comment]
只测试了appimage 文件，无论什么版本的 glibc，都可以打开，但是软件打开后没有内容，黑屏，terminal 没有任何输出

**Comment by MegatronKing** [comment]
@WzLYVg387U @Acytoo 更新2.8.1版本试试，已经验证修复。
