### ISSUE TITLE
重写规则能不能忽略http和https，一个规则同时支持两种协议

### ISSUE THREAD

**Issue by gwhcn** [reqable/reqable-app#441]

**Comment by MegatronKing** [comment]
@gwhcn 定义规则的时候使用通配符匹配，例如`*://reqable.com`就可以匹配两种。

**Comment by gwhcn** [comment]
> @gwhcn 定义规则的时候使用通配符匹配，例如`*://reqable.com`就可以匹配两种。

刚试了下，不行。这么写两种都抓不到了

**Comment by MegatronKing** [comment]
> > @gwhcn 定义规则的时候使用通配符匹配，例如`*://reqable.com`就可以匹配两种。
> 
> 刚试了下，不行。这么写两种都抓不到了

右边通配符开关没打开吧

**Comment by gwhcn** [comment]
> > > @gwhcn 定义规则的时候使用通配符匹配，例如`*://reqable.com`就可以匹配两种。
> > 
> > 
> > 刚试了下，不行。这么写两种都抓不到了
> 
> 右边通配符开关没打开吧

开了，好像是bug，通配符写左边不生效，如：*/app/getDetails；通配符在右边可以，如：http://reqable.com/app*；只写一个通配符也不行，如：*

**Comment by MegatronKing** [comment]
@gwhcn 感谢反馈。确实是bug，最新2.7.0版本已经修复。
