### ISSUE TITLE
Linux下无法启动程序

### ISSUE THREAD

**Issue by WzLYVg387U** [reqable/reqable-app#442]
`(process:3881): GLib-GIO-CRITICAL **: 01:35:10.876: g_application_set_application_id: assertion 'application_id == NULL || g_application_id_is_valid (application_id)' failed

(reqable:3881): Gdk-CRITICAL **: 01:35:10.932: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed`

环境：Arch Linux KDE plasma 5.27

**Comment by MegatronKing** [comment]
@WzLYVg387U 试试最新版本2.6.3，已发布。
