### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by Adhambec** [reqable/reqable-app#444]
<img width="1264" alt="Screenshot 2024-02-07 at 15 36 57" src="https://github.com/reqable/reqable-app/assets/76445038/b23fb15d-e74c-43b1-82f8-58a26c7ed1ac">

**Comment by MegatronKing** [comment]
@Adhambec 🙏 Thanks very much! I will fix this.

**Comment by MegatronKing** [comment]
Done!
