### ISSUE TITLE
[bug] 协同调试时 PUT 请求的重写和断点不生效

### ISSUE THREAD

**Issue by JiunnTarn** [reqable/reqable-app#445]
**Describe the bug**
在手机和电脑协同调试时，由手机发起的 PUT 请求不会被重写规则影响，断点也不生效

**Screenshots**
<img width="938" alt="Snipaste_2024-02-09_00-31-19" src="https://github.com/reqable/reqable-app/assets/45126705/68c3898d-fa82-42fe-8810-88025022b492">

例如这个例子
- 手机发送的 PUT 请求符合我的重写规则，URL 应当被替换为黄色框中的内容，但是并没有被替换；
- 在发送请求时断点也没有生效；
- 在收到响应时断点生效，而且重写响应的重写器也是正常工作的。

另外，这个问题似乎只存在于协同调试中，当我直接用 Reqable 发送请求并打开跟随调试时就不会有这个问题，断点和重写都能生效。

以下是我的配置

重写

<img width="451" alt="Snipaste_2024-02-09_00-44-40" src="https://github.com/reqable/reqable-app/assets/45126705/46632063-4e0d-4b29-bc6c-bca2275a7f53">

<img width="601" alt="Snipaste_2024-02-09_00-45-18" src="https://github.com/reqable/reqable-app/assets/45126705/b3bfe998-5b29-47e7-9f91-f84b0f13f095">

断点

<img width="529" alt="Snipaste_2024-02-09_00-45-34" src="https://github.com/reqable/reqable-app/assets/45126705/692818d7-b6b1-4af4-b854-80c1f2414e8c">

调试列表

<img width="902" alt="Snipaste_2024-02-09_00-53-02" src="https://github.com/reqable/reqable-app/assets/45126705/5da149a7-9c60-4a75-ac4f-984e700bb630">

**Information**
 - Platform: Windows, Android
 - OS: Windows11 23H2, Android13
 - Arch: x86_64
 - App Version: Windows: 2.6.2 (70), Android: 2.6.2

**Comment by JiunnTarn** [comment]
感谢您的回复，也祝您春节快乐！如我截图所示，我认为我的规则设置应该没有问题：通配符开关已经打开，重写和断点开关均已打开，并且规则之间没有重叠。换个角度，既然我使用 Reqable 发送的请求能够正确地被重写和断点，那说明我的规则应该是正确的。如果您的手机里有得物 APP，您可以测试一下修改头像的请求：PUT http://dewu-image.oss-cn-shanghai.aliyuncs.com/app/...

**Comment by MrXhh** [comment]
协同调试时，配置了请求重定向。
经过排查日志，请求既发送给了原始接口，也发送给了重定向的那个接口。导致1个请求2个服务器都收到了

**Comment by JiunnTarn** [comment]
> 协同调试时，配置了请求重定向。
> 经过排查日志，请求既发送给了原始接口，也发送给了重定向的那个接口。导致1个请求2个服务器都收到了
> 
> @JiunnTarn 

感谢回复，你说的情况我明白，但是我使用的是替换请求功能，而非重定向功能。理想情况是当手机发送请求，请求内容被 Reqable 替换后发送给服务器，但是现在直接发送给了服务器，内容没有被替换。

**Comment by MrXhh** [comment]
> > 协同调试时，配置了请求重定向。
> > 经过排查日志，请求既发送给了原始接口，也发送给了重定向的那个接口。导致1个请求2个服务器都收到了
> > @JiunnTarn
> 
> 感谢回复，你说的情况我明白，但是我使用的是替换请求功能，而非重定向功能。理想情况是当手机发送请求，请求内容被 Reqable 替换后发送给服务器，但是现在直接发送给了服务器，内容没有被替换。

@错了抱歉  我是想完善下【协同调试】这种场景也有问题

**Comment by JiunnTarn** [comment]
@MrXhh  你说的是一个已知问题，这点在文档中有说明。如果你想要反馈，可以另开一个 issue 来反馈。
![图片](https://github.com/reqable/reqable-app/assets/45126705/955550ee-53b5-41a7-b20a-a0a9f985b320)

**Comment by MegatronKing** [comment]
@JiunnTarn 写了个android demo，使用okhttp发送put请求，仍然无法复现你的问题。

**Comment by JiunnTarn** [comment]
@MegatronKing 我好像找到原因了：https 正常，http 无法重写请求，请求断点也不生效

**Comment by MegatronKing** [comment]
@JiunnTarn 已更新2.7.0版本，规则匹配可能存在一些问题。试试新版本，如果还有问题，希望能提供一个可复现的例子。

**Comment by JiunnTarn** [comment]
> @JiunnTarn 已更新 2.7.0 版本，规则匹配可能存在一些问题。试试新版本，如果还有问题，希望能提供一个可复现的例子。

这是一个可复现的例子：https://github.com/JiunnTarn/reqable-test

这是我的录屏：https://raw.githubusercontent.com/JiunnTarn/reqable-test/main/record.mp4

**Comment by MegatronKing** [comment]
不可思议，我确实复现不了，你看我这个录屏（最新2.7.0版本）：


https://github.com/reqable/reqable-app/assets/15059084/b93d2da6-ecc7-4273-8cb5-c3a579acd007
