### ISSUE TITLE
[suggestion] Uppercase for the API acronym

### ISSUE THREAD

**Issue by rickysullivan-gallagher** [reqable/reqable-app#447]
![image](https://github.com/reqable/reqable-app/assets/74567052/3732f158-954f-4216-a84a-d668ecd59f39)

Perhaps it should be "API".

**Comment by MegatronKing** [comment]
@rickysullivan-gallagher Thanks, I will fix this in the next version.

**Comment by MegatronKing** [comment]
Fixed!
