### ISSUE TITLE
[feature] API调试功能中，URL历史提供删除选项

### ISSUE THREAD

**Issue by Become-ILLUSORY** [reqable/reqable-app#448]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by Become-ILLUSORY** [comment]
[](url)
<img width="707" alt="屏幕截图 2024-02-16 194739" src="https://github.com/reqable/reqable-app/assets/79624137/03143a3f-19bd-4761-b1bb-51fecfbac757">
或者我没找到如何删除 o_O

**Comment by Become-ILLUSORY** [comment]
> <img alt="屏幕截图 2024-02-16 194739" width="707" src="https://private-user-images.githubusercontent.com/79624137/305404461-03143a3f-19bd-4761-b1bb-51fecfbac757.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODQ1ODMsIm5iZiI6MTcwODA4NDI4MywicGF0aCI6Ii83OTYyNDEzNy8zMDU0MDQ0NjEtMDMxNDNhM2YtMTliZC00NzYxLWIxYmItNTFmZWNmYmFjNzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDExNTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZDU3ODRlMjQ0Yzg2NWY0MjJlYTQxMDI2OGZiZTU2MzE1YjZkOTdjZDdlZWU4ZmJlNWFlYzQzYTdmMGQ0MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bIGi91SzOujqbFW9gc-bR7A8_Sd9M1ZlgJr-hdz_crI"> 或者我没找到如何删除 o_O

可以在URL后加个“X”来删除不

**Comment by MegatronKing** [comment]
@Become-ILLUSORY 感谢反馈。这个是autocomplete的提示，确实没有提供删除选项，一般也不会有人想着删除，不知道你是什么考虑，能否讲讲呢？

**Comment by Become-ILLUSORY** [comment]
> @Become-ILLUSORY 感谢反馈。这个是autocomplete的提示，确实没有提供删除选项，一般也不会有人想着删除，不知道你是什么考虑，能否讲讲呢？

强迫症这个理由可以吗💩

**Comment by MegatronKing** [comment]
> 历史记录可以手动保存起来，但是新开的调试窗口包含以往的url记录是否略显杂乱

**Comment by Become-ILLUSORY** [comment]
> > 强迫症这个理由可以吗💩
> 
> 🐶同是强迫症患者，你这个理由说服了我，下个版本就加上。

好的很💩💩

**Comment by MegatronKing** [comment]
v2.7.0已支持。
