### ISSUE TITLE
[bug] 手机连接电脑抓包，电脑上的域名可能错误

### ISSUE THREAD

**Issue by MUKAPP** [reqable/reqable-app#449]
**Describe the bug**
手机连接电脑抓包，电脑上的域名可能错误

**To Reproduce**
一级域名相同（均为abc.top），二级域名不同的三个域名

**Expected behavior**
8、9均正确，10应该为`pan.abc.top`，11应该为`htool.abc.top`，但是不知道为什么传到电脑上就变成`lanzou.abc.top`了（单独在手机上抓到的是没问题的）

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/41848070/bd11431d-29ee-4329-9883-39025d3b1c6e)

**Information**
 - Platform: Windows
 - OS: 11 23H2
 - Arch: x86-64
 - App Version: 2.6.3

**Comment by MUKAPP** [comment]
今天又用手机vpn抓包看了下，发现手机上也是错误的
![image](https://github.com/reqable/reqable-app/assets/41848070/f8f0f0cc-968e-4480-ba46-03c8bca81d3a)
又看了下之前手机上抓的也是错的，是我之前看错了，应该是手机上的问题（）
手机上抓到的请求头里也是错误的
![1708231837414_d](https://github.com/reqable/reqable-app/assets/41848070/c4615c24-d2ba-4269-b6b9-af981324cfa2)
![1708231883927_d](https://github.com/reqable/reqable-app/assets/41848070/2714548a-4c47-4840-988c-b95692542a8e)
看样子是都跟着第一个访问的二级域名走了

**Comment by MegatronKing** [comment]
@MUKAPP 请求头里面是实际的域名，所以没有任何问题。

**Comment by MUKAPP** [comment]
但是抓到的跟请求的不一样呢

**Comment by MegatronKing** [comment]
> 但是抓到的跟请求的不一样呢

那么你认为的正确标准是怎么来的呢？代码中使用的域名和实际抓到的不一样？

**Comment by MUKAPP** [comment]
> 那么你认为的正确标准是怎么来的呢？代码中使用的域名和实际抓到的不一样？

是的

**Comment by MegatronKing** [comment]
> > 那么你认为的正确标准是怎么来的呢？代码中使用的域名和实际抓到的不一样？
> 
> 是的

可以提供代码片段吗？

**Comment by MUKAPP** [comment]
我的代码就是使用okhttp同时请求了以下三个链接的header
```
https://lanzou.mukapp.top/?url=https://www.lanzv.com/iW3hends5hg&type=down
https://pan.mukapp.top/OneDrive/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81_1.3.apk
https://htool.mukapp.top/download/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81_1.1.5.apk
```

**Comment by MegatronKing** [comment]
> 我的代码就是使用okhttp同时请求了以下三个链接的header
> 
> ```
> https://lanzou.mukapp.top/?url=https://www.lanzv.com/iW3hends5hg&type=down
> https://pan.mukapp.top/OneDrive/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81_1.3.apk
> https://htool.mukapp.top/download/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81_1.1.5.apk
> ```

好的，非常感谢，我确认下。

**Comment by MegatronKing** [comment]
@MUKAPP 很抱歉，复现不了你的问题。下面是请求代码：

```kotlin
val request1 = Request.Builder().head().url("https://lanzou.mukapp.top/?url=https://www.lanzv.com/iW3hends5hg&type=down").build()
val request2 = Request.Builder().head().url("https://pan.mukapp.top/OneDrive/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81_1.3.apk").build()
val request3 = Request.Builder().head().url("https://htool.mukapp.top/download/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81_1.1.5.apk").build()

val callback = object : Callback {

    override fun onFailure(call: Call, e: IOException) {
    }

    override fun onResponse(call: Call, response: Response) {
    }

}
client.newCall(request1).enqueue(callback)
client.newCall(request2).enqueue(callback)
client.newCall(request3).enqueue(callback)
```

**Comment by MUKAPP** [comment]
那就奇怪了，我用这段代码还是会有问题
![1708250071649_d](https://github.com/reqable/reqable-app/assets/41848070/e78496fc-352e-41d1-ad13-f257eeb05d60)
![image](https://github.com/reqable/reqable-app/assets/41848070/3d55846f-8fda-4355-b932-a33e86ed528b)
难道有什么因素可能影响吗

**Comment by MegatronKing** [comment]
[app-debug.zip](https://github.com/reqable/reqable-app/files/14322033/app-debug.zip)
demo我打了个包，后缀改成apk。启动demo应用后会自动发送这三个请求。

**Comment by MUKAPP** [comment]
没问题，奇怪了，但是我软件请求是正常的啊
![5d6dc1b5f9266075d2eab24450469b2f](https://github.com/reqable/reqable-app/assets/41848070/5541ee00-e60e-476b-ab05-0652eabaad4f)

![1708251293955_d](https://github.com/reqable/reqable-app/assets/41848070/a39c5ed0-5d0a-415b-af58-7902cc542d82)

**Comment by MUKAPP** [comment]
先这样吧，莫名其妙的（）
之后看看有没有其他人遇到（）

**Comment by MegatronKing** [comment]
也许是okhttp版本的问题？

这是demo的依赖：
```
implementation("com.squareup.okhttp3:okhttp")
implementation("com.squareup.okhttp3:logging-interceptor")
```

完整代码：
```
package com.example.myapplication

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import com.example.myapplication.ui.theme.MyApplicationTheme
import okhttp3.Call
import okhttp3.Callback
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.Response
import java.io.IOException


class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContentView(R.layout.activity_main)

        MyThread().start()
    }

}

class MyThread : Thread() {
    override fun run() {
        super.run()
        val client = OkHttpClient()
        val request1 = Request.Builder().head().url("https://lanzou.mukapp.top/?url=https://www.lanzv.com/iW3hends5hg&type=down").build()
        val request2 = Request.Builder().head().url("https://pan.mukapp.top/OneDrive/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81_1.3.apk").build()
        val request3 = Request.Builder().head().url("https://htool.mukapp.top/download/%E5%BA%94%E6%80%A5%E9%A3%9F%E5%93%81_1.1.5.apk").build()
        val callback = object : Callback {

            override fun onFailure(call: Call, e: IOException) {
            }

            override fun onResponse(call: Call, response: Response) {
            }

        }
        client.newCall(request1).enqueue(callback)
        client.newCall(request2).enqueue(callback)
        client.newCall(request3).enqueue(callback)
        Thread.sleep(1000000)
    }
}

@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
    Text(
        text = "Hello $name!",
        modifier = modifier
    )
}

@Preview(showBackground = true)
@Composable
fun GreetingPreview() {
    MyApplicationTheme {
        Greeting("Android")
    }
}
```

**Comment by MUKAPP** [comment]
我这是4.12.0
