### ISSUE TITLE
[bug] android request summary cannot get full path url

### ISSUE THREAD

**Issue by s1sw4nto** [reqable/reqable-app#450]
**Describe the bug**
On android devices Request > Summary cannot get full path url

**Information**
 - Platform: android (samsung a54)
 - OS: android 14
 - Arch: arm-v8
 - App Version: 2.6.3
 - 
![Screenshot_20240216_230758](https://github.com/reqable/reqable-app/assets/45629638/f16f8cae-bba1-412d-a510-87c89b842d96)

**Comment by MegatronKing** [comment]
@s1sw4nto Have you installed the CA certificate?

**Comment by MegatronKing** [comment]
I will close this issue due to no user response.
