### ISSUE TITLE
重写之后会请求两次

### ISSUE THREAD

**Issue by WuWL-98** [reqable/reqable-app#455]
重写功能启动后，重写至本地，但是服务器上还是会收到请求，本地也会收到请求。
![image](https://github.com/reqable/reqable-app/assets/78076012/4f5f33f1-4312-4fc5-be74-dc6e83e5d88c)

**Comment by MegatronKing** [comment]
@WuWL-98 感谢反馈，同 #267 。重复问题我先关闭了。
