### ISSUE TITLE
[bug] Linux Mint font display abnormality

### ISSUE THREAD

**Issue by dbit-xia** [reqable/reqable-app#457]
**Describe the bug**
Linux Mint font display abnormality, suggesting customizable fonts?

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/19259623/3f765212-ffbb-41ae-9b26-7e9d6a081257)

**Information**
 - Platform: linux
 - OS: NAME= Linux Mint 21.3 (Virginia)
 - Arch: amd, x86-64
 - App Version: 2.6.3

**Comment by MegatronKing** [comment]
@dbit-xia 感谢反馈，同 #401

**Comment by MegatronKing** [comment]
看起来像是系统字体调了缩放？

**Comment by dbit-xia** [comment]
> 看起来像是系统字体调了缩放？不知道系统设置里面是否有这个选项？

对的, 分辨率太高, 字体显示很小, 所以在系统的字体设置里我调了1.7倍

**Comment by MegatronKing** [comment]
@dbit-xia 试试最新2.7.1版本，已修复！

**Comment by dbit-xia** [comment]
效果好很多了, 发现这里还有一点点显示不协调, 已经不影响使用
![image](https://github.com/reqable/reqable-app/assets/19259623/e517c2bf-dea4-4548-a1d3-859d6d02cc2f)

**Comment by MegatronKing** [comment]
> 效果好很多了, 发现这里还有一点点显示不协调, 已经不影响使用 ![image](https://private-user-images.githubusercontent.com/19259623/307742566-d58ba4b0-072c-4927-9cfc-5c37e754da2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDIyMDQsIm5iZiI6MTcwODk0MTkwNCwicGF0aCI6Ii8xOTI1OTYyMy8zMDc3NDI1NjYtZDU4YmE0YjAtMDcyYy00OTI3LTljZmMtNWMzN2U3NTRkYTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDEwMDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZDVjNzdkZDA4MTA1YzcwZDNjODkwNWY2MWIyZWRiN2MyYTAwZGU2YjdhYzRkOGMwMjcyMGJkMjJiYWM2MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nnixRZmYztS6dRH7vbBpDuNOL6kmmDQ6yj1rtiDh1yc)

是标题颜色还是什么不协调？

**Comment by dbit-xia** [comment]
主菜单被挡住了一半 
![image](https://github.com/reqable/reqable-app/assets/19259623/30af4fab-0418-40ba-8ff2-8f0916cd8e51)
