### ISSUE TITLE
[bug] 对比页面最大化的情况下,添加请求到对比池,会把对比页面的窗体尺寸重置.

### ISSUE THREAD

**Issue by xiuluoshendaren** [reqable/reqable-app#460]
[bug] 对比页面最大化的情况下,添加请求到对比池,会把对比页面的窗体尺寸重置.

**Comment by MegatronKing** [comment]
@xiuluoshendaren 感谢反馈，已经确认问题，将在下个版本修复。

**Comment by MegatronKing** [comment]
@xiuluoshendaren 试试最新2.7.1版本，已修复！
