### ISSUE TITLE
安卓14根证书无法安装

### ISSUE THREAD

**Issue by Become-ILLUSORY** [reqable/reqable-app#462]
**Describe the bug**
我无法在安卓14上成功安装根证书

**To Reproduce**
     1.官方magisk，模块/system/etc/security/cacerts/xxx.0
可以在该目录下正确找到证书，但是reqable显示证书未安装
     2.模块/apex/com.android.conscrypt/cacerts/xxx.0，和1一样

**期望:**
     能否提供一个于安卓14可用的magisk模版模块，仅需用户将自己的证书导入并刷入即可实现安装。或给个详细教程在安卓14上如何安装根证书😭😭

**Comment by Become-ILLUSORY** [comment]
救命，我真的看了一晚上酷安试了好多次了😭😭

**Comment by MegatronKing** [comment]
@Become-ILLUSORY 试试这个 #344

**Comment by Become-ILLUSORY** [comment]
> @Become-ILLUSORY 试试这个 #344

success
