### ISSUE TITLE
[bug] 转换chls文件错误

### ISSUE THREAD

**Issue by xiuluoshendaren** [reqable/reqable-app#463]
![图片](https://github.com/reqable/reqable-app/assets/160598517/6f226445-8802-43aa-86cc-df2b3f20ab1a)
转换chls文件时存在post请求无法完整读取的情况.

**Comment by MegatronKing** [comment]
@xiuluoshendaren 您好，感谢反馈。但是我未能复现这个问题，请问能否将chls文件发我测试下？

**Comment by xiuluoshendaren** [comment]
[转换测试.zip](https://github.com/reqable/reqable-app/files/14357209/default.zip)

**Comment by xiuluoshendaren** [comment]
> @xiuluoshendaren 您好，感谢反馈。但是我未能复现这个问题，请问能否将chls文件发我测试下？

[转换测试.zip](https://github.com/reqable/reqable-app/files/14357212/default.zip)

**Comment by MegatronKing** [comment]
@xiuluoshendaren 试试最新2.7.1版本，已修复！
