### ISSUE TITLE
[feature] 会话保存之后没有更新会话名称

### ISSUE THREAD

**Issue by xiuluoshendaren** [reqable/reqable-app#466]
新建Session x,保存,tab页的标题还是Session x,可不可以改成文件名?

**Comment by MegatronKing** [comment]
@xiuluoshendaren 感谢建议，但是可能做不到。保存的格式是HAR，数据结构还是不一样的。而且，Session x是临时会话，是不同的类型。

**Comment by xiuluoshendaren** [comment]
> @xiuluoshendaren 感谢建议，但是可能做不到。保存的格式是HAR，数据结构还是不一样的。而且，Session x是临时会话，是不同的类型。
保存之后系统不会返回文件名吗?

**Comment by MegatronKing** [comment]
> 保存之后系统不会返回文件名吗?

从设计上来说，临时会话和文件是两种tab类型。
