### ISSUE TITLE
[bug] 版本0.1.7 (13) 当请求过多时会闪退，系统版本mac 13.3.1

### ISSUE THREAD

**Issue by ver1109** [reqable/reqable-app#47]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@ver1109 感谢反馈，有系统bug report日志吗

**Comment by ver1109** [comment]
> @ver1109 感谢反馈，有系统bug report日志吗

macos 版本13.3.1（版号22E261） 0.1.7(13) x86_64
05-18 19:12:33.1247 [I][Dart]: App logger is ready now.
05-18 19:12:33.1247 [V][Dart]: Pre-initing app...
05-18 19:12:33.1249 [V][Dart]: App pre-init done.
05-18 19:12:33.1252 [V][Dart]: Post-initing app...
05-18 19:12:33.1308 [V][Dart]: Initing netbare engine...
05-18 19:12:33.1369 [V][Dart]: Loading CA certificate...
05-18 19:12:33.1372 [V][Dart]: CA certificate is found from cache.
05-18 19:12:33.1386 [V][Dart]: Starting netbare engine on port 8887
05-18 19:12:33.1391 [I][Dart]: Netbare engine is ready!
05-18 19:12:33.1395 [V][Dart]: App post-init done.
05-18 19:12:34.2351 [V][Dart]: Event: app_start
05-18 19:12:34.4699 [V][Dart]: Local IP detected: 192.168.133.156
05-18 19:12:34.4699 [I][Dart]: Use local IP: 192.168.133.156
05-18 19:12:34.4737 [I][Dart]: Check update ok, has update: false
05-18 19:12:35.2908 [V][Dart]: Event: capture_engine_start

重新复现了一下，只有这些日志

**Comment by MegatronKing** [comment]
1.0.1版本修复了一个指针内存失效的bug，不确定是不是和这个闪退有关。我目前没有办法复现这个问题，issue我先挂起。

**Comment by MegatronKing** [comment]
目前没有收到相关crash的反馈，这个issue我先关闭了。
