### ISSUE TITLE
[bug] 二级代理认证无效

### ISSUE THREAD

**Issue by xiuluoshendaren** [reqable/reqable-app#471]
配置了二级代理,填了用户名和密码,但是无法正常使用.

**Comment by MegatronKing** [comment]
@xiuluoshendaren 试试最新2.7.1版本，已修复！

**Comment by xiuluoshendaren** [comment]
> @xiuluoshendaren 试试最新2.7.1版本，已修复！

nice,作者很勤奋啊.

**Comment by MegatronKing** [comment]
> > @xiuluoshendaren 试试最新2.7.1版本，已修复！
> 
> nice,作者很勤奋啊.

Reqable是全职项目，每天的工作日常，不是在写bug就是在修bug😊。

**Comment by Blankeer** [comment]
最新版  2.8.2 (76)，遇到此问题，代理地址和用户名密码没错，curl 请求可以，reqable显示无法连接服务器 httpbin.org

**Comment by triangle959** [comment]
同样的问题在2.18.1出现，打开日志看不到报错信息。显示是无法连接服务器，怀疑是reqable没有连接上代理，而本地Charles可以连接上前置代理。感觉这个二级代理是不是只能写局域网地址？ @MegatronKing

**Comment by MegatronKing** [comment]
> 同样的问题在2.18.1出现，打开日志看不到报错信息。显示是无法连接服务器，怀疑是reqable没有连接上代理，而本地Charles可以连接上前置代理。感觉这个二级代理是不是只能写局域网地址？ @MegatronKing

可以写服务器地址。我没有实际可以测试的认证服务器，只是按照规范实现了。如果你方便的话，可以官网右下角微信加下我，提供下可以测试的地址。
