### ISSUE TITLE
[bug] 保存会话报错

### ISSUE THREAD

**Issue by xiuluoshendaren** [reqable/reqable-app#474]
![图片](https://github.com/reqable/reqable-app/assets/160598517/612d65c9-1d8f-4c69-b52a-e7d9f09a5dfd)
保存会话报错了.

**Comment by Yricky** [comment]
同样问题

**Comment by MegatronKing** [comment]
@Yricky @xiuluoshendaren 感谢反馈，能找到是哪个请求导致的吗？复制个curl给我试试呢

**Comment by xiuluoshendaren** [comment]
> @Yricky @xiuluoshendaren 感谢反馈，能找到是哪个请求导致的吗？复制个curl给我试试呢

请求太多,等我下次遇到吧.

**Comment by MegatronKing** [comment]
同 #508 ，已解决！
