### ISSUE TITLE
[feature] [mobile] 在分享选项中添加"Response&Request"

### ISSUE THREAD

**Issue by MessageForwarding** [reqable/reqable-app#477]
分享"请求与响应"
![IMG_20240223_180120](https://github.com/reqable/reqable-app/assets/161020129/ac78f97c-4269-44f7-9458-1cd6a9e266e3)

[转发消息, 附原文]
Why Not here(Request, Response) Both Share Option.

**Comment by MegatronKing** [comment]
@MessageForwarding HAR格式就同时包含请求和响应数据

**Comment by MessageForwarding** [comment]
在手机端他也许是想要分享简单的纯文本信息, 不过HAR也确实是适用的.
