### ISSUE TITLE
App hides itself after starting capture and all SSL traffic fails

### ISSUE THREAD

**Issue by e-ave** [reqable/reqable-app#479]
1. I install CA cert
2. I install Magic Service app
3. I run the app I want to capture packets from 
4. I select the app I want to capture packets from in Traffic part of Reqable app
5. I Add links to SSL bypass
6. I press button to start capture
7. I leave reqable
8. Now Reqable cant be opened again without reboot OS

**Comment by e-ave** [comment]
All headers and responses are empty.
All connections fail / abort if SSL is not bypassed

**Comment by MegatronKing** [comment]
@e-ave Hello, I'm very sorry, I didn't understand the problem you encountered. Do you have a screen recording or screenshot? I would be very grateful if you could provide it.

**Comment by MegatronKing** [comment]
No user response, I will close this issue. If you still have the issue, please provide more information and reopen it.
