### ISSUE TITLE
[feature] 添加自定义证书功能

### ISSUE THREAD

**Issue by devcxm** [reqable/reqable-app#48]
使用过Charles&Proxyman&mitmproxy，这三代理我的设备使用同一个自定义的证书。

不知作者是否有计划像Proxyman一样添加自定义证书功能？

**Comment by MegatronKing** [comment]
您好，感谢建议，需求已收到。相对来说，需求偏小众，排的优先级会比较低。

**Comment by MegatronKing** [comment]
由于移动端和PC端需要相互导入导出证书，此功能优先级提到最高。

**Comment by MegatronKing** [comment]
@devcxm 2.0.0版本支持导入和导出p12证书，可以试试看：https://github.com/reqable/reqable-app/releases/tag/2.0.0-preview5

**Comment by MegatronKing** [comment]
2.0.0版本已实现。
