### ISSUE TITLE
[bug] [linux] gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)

### ISSUE THREAD

**Issue by Kgym-Hina** [reqable/reqable-app#480]
**Describe the bug**
直接启动后窗口未显示，使用命令行启动发现应用报错
```
./reqable-app-linux-x86_64.AppImage
libpng warning: iCCP: unexpected zlib return code
libpng error: unexpected zlib return code
libpng warning: iCCP: unexpected zlib return code
libpng error: unexpected zlib return code

(reqable:6064): Gdk-CRITICAL **: 13:54:20.274: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
```

**Information**
 - Platform:  EndeavourOS Linux
 - DE: KDE Plasma
 - Window Server: Wayland
 - Arch:  x86-64
 - App Version: 2.7.1

**Comment by MegatronKing** [comment]
感谢反馈，看起来是flutter框架的问题 #137262，需要等待后续更新框架解决。

**Comment by Kgym-Hina** [comment]
在给出的 Issues 下发现已经修复，刚刚使用 snap 安装了最新的 flutter, 发现在同样的环境下可以正常显示
![image](https://github.com/reqable/reqable-app/assets/22652631/75454ff5-8a06-4a57-8c67-afee9c8f1133)

**Comment by MegatronKing** [comment]
确定是 #440 的bug
