### ISSUE TITLE
为什么手机抓包，服务器IP 是 127.0.0.1

### ISSUE THREAD

**Issue by exp0l0zzz** [reqable/reqable-app#481]
<img width="783" alt="image" src="https://github.com/reqable/reqable-app/assets/95993081/0c76de8f-9aba-467d-a7b9-b0ead56bbdfb">

我手机 没有 root

**Comment by MegatronKing** [comment]
@exp0l0zzz 你配置了二级代理吗？

**Comment by exp0l0zzz** [comment]
@MegatronKing 哦哦，我把二级关了就好了，但是还是要root才能抓https，唉苦恼
