### ISSUE TITLE
[bug] Windows 快捷键bug 影响正常使用

### ISSUE THREAD

**Issue by xx299x** [reqable/reqable-app#489]
**Describe the bug**
1. Ctrl + V 失效
2. Del 失效
3. 快捷键逻辑错误

**To Reproduce**
![recording](https://github.com/reqable/reqable-app/assets/23482348/deb40a8c-4753-41a8-9538-d034fdc661ce)

**Information**
 - Platform: windows10
 - Arch: x86-64
 - App Version: 2.8.0

**Comment by MegatronKing** [comment]
@xx299x 感谢反馈，我测试没有能复现。可能是我们的运行环境没有对齐，请问是否有使用一些快捷键相关的辅助软件呢？

从录屏来看，像是`Alt`按键一直被检测到按下了，所以导致其他快捷键都失效了，你可以试试按一下`Alt`再松开能不能恢复到正常。我猜测可能是这个问题：https://github.com/flutter/flutter/issues/95634

**Comment by xx299x** [comment]
应该是我快捷键问题
