### ISSUE TITLE
[bug] 已经root小米9重启手机要重新安装证书reqable安卓版

### ISSUE THREAD

**Issue by Acheng97** [reqable/reqable-app#494]
已经root小米9第一次已经安装好证书，重启手机再抓包，再次提示安装证书，每次重启都是这样

**Comment by xx299x** [comment]
这个似乎不是reqable解决问题的范畴

**Comment by kkopmm** [comment]
刷模块解决问题

**Comment by Acheng97** [comment]
> 这个不是reqable解决问题的首要，建议先解除系统分区然后恢复副本

System已经解锁，我是用mt移动过去的

**Comment by Acheng97** [comment]
> 刷模块解决问题

有现成的模块推荐吗

**Comment by MegatronKing** [comment]
这个不是Reqable应用本身的问题，我先关闭了。

**Comment by kitUIN** [comment]
> > 刷模块解决问题
> 
> 有现成的模块推荐吗

我也被这个问题困扰,所以我手写了一个magic模块解决这个问题

- https://github.com/kitUIN/Reqable-Magic-Crt/releases/tag/0.1.0

**Comment by Acheng97** [comment]
> > > 刷模块解决问题
> > 
> > 
> > 有现成的模块推荐吗
> 
> 我也被这个问题困扰,所以我手写了一个magic模块解决这个问题
> 
> * https://github.com/kitUIN/Reqable-Magic-Crt/releases/

好的，谢谢，我也解决了这个问题，需要从浏览器下载并安装证书才可以
