### ISSUE TITLE
[bug] 未知错误 NetBareCode.errorUnknown

### ISSUE THREAD

**Issue by xx299x** [reqable/reqable-app#495]
**Describe the bug**
不知道如何复现, 我现在这个软件是不可用的状态. 重装和删除数据目录都无法解决

**To Reproduce**
![image](https://github.com/reqable/reqable-app/assets/23482348/da742493-4ea6-426d-a6c0-f8cc3eac5778)

**Expected behavior**

**Screenshots**

**Information**
 - Platform: windows
 - Arch:  x86-64
 - App Version: 2.8.0

**Comment by MegatronKing** [comment]
@xx299x 看起来是和其他软件或者进程端口冲突了，你将默认的端口号9000修改下。

**Comment by xx299x** [comment]
> @xx299x 看起来是和其他软件或者进程端口冲突了，你将默认的端口号9000修改下。

OK, 应该只有这个软件使用9000, 我重启了一下软件, 可能存在残余进程

**Comment by LightToDo** [comment]
windows，2.33.12也会出现这个问题，端口没有被占用。
