### ISSUE TITLE
[feature] 自动删除不关心的连接

### ISSUE THREAD

**Issue by Acytoo** [reqable/reqable-app#496]
**Is your feature request related to a problem? Please describe.**
添加自动删除某些连接记录的功能

**Describe the solution you'd like**
添加一条规则，符合某种规则可以自动删除

**Additional context**
要长期跑着requable 抓包，reqable 记录了几万到十几万的连接，这时候搜索/filter都很慢，能不能添加一个功能，自动抛弃符合某些条件的包，比如所有 icloud.com 的包，所有 googleapi 的包，等。

**Comment by MegatronKing** [comment]
@Acytoo 建议配置SSL Bypass（SSL旁路），盾牌图标右键菜单或者证书菜单进入。配置域名并勾选静默开关，这些流量就不会出现在列表了。
