### ISSUE TITLE
[bug] 脚本运行时报错Failed to deserialize script exec resul

### ISSUE THREAD

**Issue by yuhao7370** [reqable/reqable-app#497]
**Describe the bug**
使用脚本时出现的错误，第一次使用脚本就出现了不清楚原因。

**To Reproduce**
点击发送就会出现bug
脚本是默认给的没有进行修改
![bug](https://github.com/reqable/reqable-app/assets/53969724/b66ff7c9-d0fe-4e75-93d9-2e41ec803dd7)

**Information**
 - Platform: windows
 - OS: 11
 - App Version: 2.3.2

**Comment by MegatronKing** [comment]
@yuhao7370 感谢反馈，看起来像是URL不正确导致的，为什么出现了两个`//`？

**Comment by MegatronKing** [comment]
v2.8.2版本已解决。

**Comment by yuhao7370** [comment]
> @yuhao7370 感谢反馈，看起来像是URL不正确导致的，为什么出现了两个`//`？

这个两个/是游戏开发者的问题，在游戏里写的就是两个/
