### ISSUE TITLE
[bug] shows request body in response tab

### ISSUE THREAD

**Issue by lol-1-afk** [reqable/reqable-app#498]
**Describe the bug**
Reqable shows request body in post request when watching response body

**To Reproduce**
1. Just make some post request
2. Click on request in list, open raw response
3. See error: it shows response headers, but request body

**Expected behavior**
It should show response headers and response body, but shows response headers and request body

**Screenshots**
Here raw response shows request body:
![image](https://github.com/reqable/reqable-app/assets/58441229/b4163b04-1a30-46b7-8138-dacd7418b217)

And here body tab shows real responsew body:
![image](https://github.com/reqable/reqable-app/assets/58441229/e804a68c-63a8-4d8c-b5c9-39e35e4c2ef7)

**Information**
 - Platform: Windows
 - OS: Win11  23H2
 - Arch: 64
 - App Version: 2.8.0 (74)

**Comment by MegatronKing** [comment]
@lol-1-afk Thanks, I will fix this in the next version.

**Comment by MegatronKing** [comment]
Please update v2.8.2, I have fixed this.
