### ISSUE TITLE
[bug] reqable安卓版分享curl无法转换为requests代码

### ISSUE THREAD

**Issue by Acheng97** [reqable/reqable-app#499]
![bbfe65912473e8c7e49a83bd0564d727](https://github.com/reqable/reqable-app/assets/65265814/6d8e7dc5-ca84-4d53-8ca5-f13f5423e1d9)
reqable安卓版分享curl无法转换为requests代码，好像只复制出了url
<img width="1231" alt="image" src="https://github.com/reqable/reqable-app/assets/65265814/d7f0ada4-0441-4c64-91a8-9a93491a8e02">

**Comment by MegatronKing** [comment]
@Acheng97  感谢反馈，请问可以提供有问题的curl吗？可以将敏感信息替换或者删除掉再发我看看
