### ISSUE TITLE
1台Mac/Windows/Linux同时使用,指的是啥?

### ISSUE THREAD

**Issue by Gavin0210** [reqable/reqable-app#50]
是一个账号只能在一台设备使用吗?
换设备登陆的话,  保存的历史会同步吗? 
原来的设备会退登陆吗? 
会限制能登陆的设备数目吗?
专业版能用于企业开发吗?
谢谢

**Comment by MegatronKing** [comment]
您好，可以同时在1台Mac+1台Windows+1台Linux，共3台设备上同时激活使用，但是不能在2+台Mac上同时使用，Windows和Linux同理。历史数据不会同步，考虑到个人隐私和数据安全，目前都是采用离线存储的方式，没有云服务支持。

**Comment by MegatronKing** [comment]
没有问题的话，这个issue我先关闭了
