### ISSUE TITLE
[bug] Python环境无法更换

### ISSUE THREAD

**Issue by yinsel** [reqable/reqable-app#500]
**Describe the bug**
 曾经安装过pyenv但已卸载，确保环境变量中已不存在任何pyenv的相关环境变量，且python环境正常可用版本为3.10，下面是问题录制视频（重启应用/系统依旧如此）

**To Reproduce**
录制视频

**Expected behavior**
正常更换Python环境

**Screenshots**

https://github.com/reqable/reqable-app/assets/91541985/5e936381-5fa6-456e-a14d-389a2f2142de

**Information**
 - Platform: windows
 - OS: windows11
 - Arch: x86-64
 - App Version: 最新便携版

**Comment by MegatronKing** [comment]
@yinsel 感谢反馈。我确认下你的问题，你的路径下的python版本是3.10.0但是识别成了3.10.11？

**Comment by yinsel** [comment]
> @yinsel 感谢反馈。我确认下你的问题，你的路径下的python版本是3.10.0但是识别成了3.10.11？

不是的，是reqable似乎有bug不能换，一直显示未找到python，视频中我尝试指定显示识别成功，但是再次点击依旧未识别，可能是点击"完成"没有保存，看样子应该识别成功了

**Comment by MegatronKing** [comment]
@yinsel 已确认问题，感谢

**Comment by DeemoASCII** [comment]
遇到了同样的问题，使用conda环境之后，无法切换python环境，永远使用系统自带的python，输入python路径之后显示能找到，但是点击保存之后无法保存，仍然使用系统的

**Comment by MegatronKing** [comment]
@DeemoASCII @DeemoASCII 这个问题已经在2.9版本修复，麻烦更新下试试，谢谢。

**Comment by yinsel** [comment]
> @DeemoASCII @DeemoASCII 这个问题已经在2.9版本修复，麻烦更新下试试，谢谢。

问题已修复，感谢！
