### ISSUE TITLE
[bug] reqable导出的har文档其它抓包软件无法打开

### ISSUE THREAD

**Issue by devcxm** [reqable/reqable-app#503]
应该是`startedDateTime`的时间格式不对，少了时区

参考 [http://www.softwareishard.com/blog/har-12-spec/#pages](http://www.softwareishard.com/blog/har-12-spec/#pages)

**Comment by MegatronKing** [comment]
@devcxm 感谢反馈，试试2.8.2版本，`startedDateTime`已改成utc。
