### ISSUE TITLE
导出数据失败[bug] 

### ISSUE THREAD

**Issue by zxerqw** [reqable/reqable-app#508]
**Describe the bug**
今天刚升级到最新版，调试后右键点击调试tab，保存，默认名字点保存报错，在历史记录点导出也是一样的错误，尝试重命名了一下记录，还是报错的。

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/16666177/550e4d92-930b-4527-9339-f608165e7d3b)

**Information**
 - Platform: windows
 - OS: win11
 - Arch: x86_64
 - App Version: 2.8.2(76)

**Comment by zxerqw** [comment]
@MegatronKing 
看到其他也有反馈，我尝试了两个，你看下这个保存出错的，在这个url上，我无法复制成curl，生成代码之类的，都会爆粗，貌似是edge自动请求的东西

![image](https://github.com/reqable/reqable-app/assets/16666177/275dd496-161b-4167-b955-c5373794d27f)

**Comment by zxerqw** [comment]
删了微软的这些请求能保存

**Comment by MegatronKing** [comment]
可能是某些破损的数据无法解码导致的，最新版本已经自动过忽略这些破损数据。所以，这个问题应该不存在了，我先关闭issue，如果有发现请再打开。
