### ISSUE TITLE
[feature] 有没有app筛选功能，通过wifi设置代理后，抓包是整个手机的流量，太多了

### ISSUE THREAD

**Issue by huanghe-1** [reqable/reqable-app#51]
原来的httpcanary可以指定目标应用，现在wifi代理不能指定目标应用了，全部手机流量都抓包，有没有刷选抓包功能

**Comment by MegatronKing** [comment]
这个实现不了，电脑端获取不到移动端的进程信息，所以没有办法区分app。

**Comment by huanghe-1** [comment]
这么说来，httpcanary还是有不可替代的功能啊，期待手机端reqable的上线

**Comment by MegatronKing** [comment]
@SeeFlowerX 很多问题有具体的吗？可以开个issue描述下问题详情，我debug下。
