### ISSUE TITLE
[bug] 请求头中带有content-encoding=deflate的话请求体默认解压,并且使用重发功能重发的请求体是未压缩的

### ISSUE THREAD

**Issue by kongbai141** [reqable/reqable-app#511]
请求头中带有content-encoding=deflate的话请求体默认解压,并且使用重发功能重发的请求体是未压缩的

**Comment by MegatronKing** [comment]
@kongbai141 感谢反馈，我测试无法复现这个问题。请问能否提供有问题的测试用例、截图、录屏等有助于定位问题的信息？

**Comment by MegatronKing** [comment]
没有进一步的信息，这个问题我先关闭了。如果仍然有问题，请提供更多的信息重新打开这个问题，谢谢！
