### ISSUE TITLE
IOS端使用扫码协同无法同步根证书

### ISSUE THREAD

**Issue by yd-coder** [reqable/reqable-app#512]
本人平时需要在三台设备上使用reqable，一台工作台式，一个笔记本，一部iPhone。当我在IOS端的reqable使用扫码协同时，同步根证书的功能好像没有用，每次我扫码台式或者笔记本切换设备时，需要先手动移除一台设备的根证书再信任新的根证书，多个pc的根证书是无法共存的，也没法通过app的同步功能直接同步。
想请问这是我个人的使用方法有问题还是reqable的功能缺陷？

**Comment by MegatronKing** [comment]
@yd-coder 我记得是可以共存的，每个证书的名称不一样。另外，你可以将所有设备都导入同一个证书（p12格式），会更加方便点。

**Comment by yd-coder** [comment]
> @yd-coder 我记得是可以共存的，每个证书的名称不一样。另外，你可以将所有设备都导入同一个证书（p12格式），会更加方便点。

台式和笔记本在ios上的证书都是Reqable Proxy CA不能共存，ios端本身安装的证书是Reqable CA（时间）可以和前者共存，你提到的导入p12格式方法，我在ios上导入后没有在描述文件里看到。

**Comment by yd-coder** [comment]
> @yd-coder `Reqable Proxy CA`这个是最早版本的证书名称，后面改了，你在证书菜单 -> 证书管理 -> 重新生成 就是带时间戳的了。iOS App导入p12格式之后，还需要将证书保存（下载）到本地，点击安装，才能看到描述文件。

感谢！解决了，原来是两台设备的Reqable从老版本更新之后没有重新生成证书，导致ios上下载的一直是Reqable Proxy CA，所以不能共存
