### ISSUE TITLE
系统代理是默认每次打开程序都开启的吗？

### ISSUE THREAD

**Issue by jiechen257** [reqable/reqable-app#513]
<img width="721" alt="image" src="https://github.com/reqable/reqable-app/assets/73946940/3c51956f-1a28-4df4-a9c8-89efc157302d">

希望出一个 setting 能够关闭，作为只调试移动端的场景，每次看到一堆pc端的代理都要手动去关闭一次

**Comment by MegatronKing** [comment]
@jiechen257 你的图红框下面，不是有“自动启用”开关吗

**Comment by jiechen257** [comment]
> @jiechen257 你的图红框下面，不是有“自动启用”开关吗

😂好的
