### ISSUE TITLE
可否支持win7

### ISSUE THREAD

**Issue by 123456789zws** [reqable/reqable-app#515]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
@123456789zws 最新版本是支持win7的，你是否有遇到什么问题？

**Comment by 123456789zws** [comment]
没有，安装报错后一直没试过了，我安装试试
                       
原始邮件
                       
                     

发件人："Megatron King"< ***@***.*** &gt;;

发件时间：2024/3/21 12:22

收件人："reqable/reqable-app"< ***@***.*** &gt;;

抄送人："123456789zws"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [reqable/reqable-app] 可否支持win7 (Issue #515)




 
@123456789zws 最新版本是支持win7的，你是否有遇到什么问题？
