### ISSUE TITLE
[feature] 能不能在重写列表增加一个分组功能

### ISSUE THREAD

**Issue by gwhcn** [reqable/reqable-app#518]
需求：重写列表数据多的时候找起来费劲，希望可以加一个分组和分组勾选功能，方便收纳管理。使用场景如下

#### 场景1，同一个页面多种样式，直接勾选样式分组切换整个页面的mock数据，实现有难度的话只提供分组功能也行
**1. A样式详情页面**
- 接口a http://xxx/xxx/a
- 接口b http://xxx/xxx/b
- 接口c http://xxx/xxx/c

**2. B样式详情页面**
- 接口a http://xxx/xxx/a
- 接口b http://xxx/xxx/b
- 接口c http://xxx/xxx/c

#### 场景2，一个页面多种状态
**1. 订单详情**
- 发货状态详情  http://xxx/xxx/detail
- 签收状态详情  http://xxx/xxx/detail
- 退货状态详情  http://xxx/xxx/detail
- 申述状态详情  http://xxx/xxx/detail

#### 场景3，多应用开发
**1. 应用A**
- 订单详情
    - 发货状态详情  http://xxx/xxx/detail
    - 签收状态详情  http://xxx/xxx/detail
- A样式详情页面
    - 接口a http://xxx/xxx/a
    - 接口b http://xxx/xxx/b
    - 接口c http://xxx/xxx/c
- B样式详情页面
    - 接口a http://xxx/xxx/a
    - 接口b http://xxx/xxx/b
    - 接口c http://xxx/xxx/c

**2. 应用B**
- 直播列表 http://xxx/xxx/xxx
- 评论接口 http://xxx/xxx/xxx

**Comment by MegatronKing** [comment]
@gwhcn 感谢建议，分组功能在规划中，见 #7

**Comment by MegatronKing** [comment]
重复issue我先关闭了。
