### ISSUE TITLE
[feature] 关于调试列表中列选项“大小”的含义解释

### ISSUE THREAD

**Issue by delic10us** [reqable/reqable-app#521]
**Is your feature request related to a problem? Please describe.**
我将数据包的响应导出后发现与调试列表显示的数据大小不一致，比它要大，这让我感到困惑。查阅了官方文档发现缺少对列选项“大小”的解释，自己琢磨了一下，猜测调试列表中的大小指的是实际传输时经过压缩的数据的大小，查看响应体时和导出的数据是经过解压缩后的，因此不一致。

**Describe the solution you'd like**
在官方文档中加上对列选项“大小”的定义和解释。

**Comment by MegatronKing** [comment]
好的，感谢建议。`大小`指的是总大小，请求行 + 请求头 + 请求体 + 状态行 + 响应头 + 响应体的总计大小，请求体和响应体计算的是实际网络传输的大小。
