### ISSUE TITLE
[bug] 请求体hex view导出整型转换错误

### ISSUE THREAD

**Issue by rxbit** [reqable/reqable-app#522]
**Describe the bug**
hex view选择导出时，对>0x7F(-128 ~ -1)的字节转换错误，可能是dart的singed int表示不同？

**To Reproduce**
curl -X GET 'https://httpbin.org/bytes/10?seed=1'

导出
![image](https://github.com/reqable/reqable-app/assets/1555218/696b4313-3f26-44f4-a31a-6aa70a70488a)
查看导出hex
![image](https://github.com/reqable/reqable-app/assets/1555218/f89975df-8986-47b6-9eac-ed8ab4064895)

**Information**
 - Platform:macos
 - OS: 14.4
 - Arch: arm
 - App Version: 2.9.0

**Comment by MegatronKing** [comment]
@rxbit 不好意思，确认是个bug，将在下个版本修复。感谢您的反馈！
