### ISSUE TITLE
导出的json文件是否遵循某种规则能够导入postman？

### ISSUE THREAD

**Issue by morecup** [reqable/reqable-app#523]
再团队协同的时候，可能有的人是用的postmen或者其他软件，是否支持以某种方式共享给别人使用，比如，支持openapi标准导出？

**Comment by MegatronKing** [comment]
@morecup 我调研了下目前市面上所有的类似软件都是自己特定的格式，只能靠别的应用兼容。对于单个请求，我的建议是通过curl导入postman等其他软件。
