### ISSUE TITLE
pc客户端无法抓包，而httpdebugger却可以

### ISSUE THREAD

**Issue by 123456789zws** [reqable/reqable-app#524]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
@123456789zws 您好，感谢反馈。能否提供更多的问题细节，例如操作步骤、录屏、截图等。

**Comment by FKVV** [comment]
两款软件使用的不是同样的代理模式；

httpdebugger 是hook win 网络协议

**Comment by 123456789zws** [comment]
那请问如果用咱们得软件有办法抓pc客户端的包吗，具体我该如何做呢







                       
原始邮件
                       
                     

发件人："FKVV"< ***@***.*** &gt;;

发件时间：2024/4/1 22:39

收件人："reqable/reqable-app"< ***@***.*** &gt;;

抄送人："123456789zws"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [reqable/reqable-app] pc客户端无法抓包，而httpdebugger却可以 (Issue #524)




 
两款软件使用的不是同样的代理模式；
 
httpdebugger 是hook win 网络协议

**Comment by MegatronKing** [comment]
检查客户端是否走系统代理，或者指定他走Reqable的代理地址。

**Comment by 123456789zws** [comment]
请问具体如何操作呢







                       
原始邮件
                       
                     

发件人："Megatron King"< ***@***.*** &gt;;

发件时间：2024/4/9 16:04

收件人："reqable/reqable-app"< ***@***.*** &gt;;

抄送人："123456789zws"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [reqable/reqable-app] pc客户端无法抓包，而httpdebugger却可以 (Issue #524)




 
检查客户端是否走系统代理，或者指定他走Reqable的代理地址。

**Comment by MegatronKing** [comment]
这个只能你自己根据具体情况处理了，不在Reqable的服务范围之内。
