### ISSUE TITLE
[bug] 编辑请求参数时光标位置异动

### ISSUE THREAD

**Issue by chengcct** [reqable/reqable-app#53]
**Describe the bug**
编辑请求的参数时，在任意位置输入参数或产生动作后，光标位置会强制跳转到尾部

**To Reproduce**
1. 新建api
2. 编辑参数
3. 修改任意参数，光标位置移动到尾部

**Information**
 - Platform: win 11
 - App Version: 1.0.1

**Comment by MegatronKing** [comment]
v1.0.2版本已修复。
