### ISSUE TITLE
[bug] 关于Android14安装根证书识别问题，与格式改动

### ISSUE THREAD

**Issue by ElicitZero** [reqable/reqable-app#530]
**Describe the bug**
由于格式改动，Android14不认根证书

**Expected behavior**
需要更改根证书以适配Android14请改为以下截图格式以适配Android14.

**Screenshots**
![Screenshot_2024-03-31-02-41-46-43_9e8df3d0c7c1f50248b6ee043a653d26](https://github.com/reqable/reqable-app/assets/156153737/e333e680-6a8f-4384-98c6-c4e050e344f0)

**Information**
 - Platform: Android
 - OS: RealmeUI 5(Android14)
 - Arch: arm64
 - App Version: 2.10.0

**Comment by MegatronKing** [comment]
@ElicitZero 你好，非常抱歉，我没能get到你的意思？

**Comment by J6451** [comment]
@MegatronKing 我觉得他说的意思是Android14不认这个证书，需要更改证书里面的格式。我这边也有这个问题，导入成功，但是证书并没有生效。

**Comment by MegatronKing** [comment]
@J6451 没有识别出来，基本上是没安装成功或者安装错了。
