### ISSUE TITLE
[bug] 安卓总览中URL过长，显示不正常，不能滑动

### ISSUE THREAD

**Issue by biqiguhexuenai** [reqable/reqable-app#531]
**Describe the bug**
[bug] 安卓总览中URL过长，显示不正常，不能滑动

**To Reproduce**
1. Go to '某个抓到的条目，含有过长的URL'
2. Click on '总览中的URL'
3. See error

**Expected behavior**
能够显示在外框范围内，可以滑动显示
**Screenshots**
![Screenshot_2024-03-31-22-35-12-12_7fac49e5329bfa70bf0c1257a1a51d55](https://github.com/reqable/reqable-app/assets/63104635/d7102041-eb53-4244-a5dd-5add77eddd3b)

**Information**
 - Platform: [Android]
 - OS: [14]
 - Arch: [64]
 - App Version: [2.10.0]

**Comment by MegatronKing** [comment]
感谢反馈，这个问题将在下个版本修复。

**Comment by MegatronKing** [comment]
v2.10.1已修复。
