### ISSUE TITLE
[bug] 卸载一个已加入特定应用列表的应用后，数字显示异常

### ISSUE THREAD

**Issue by biqiguhexuenai** [reqable/reqable-app#533]
**Describe the bug**
卸载一个已加入特定应用列表（分流列表）的应用后，数字显示异常，即使杀后台重进也不行，需要在列表删去某个软件重新计算个数
**To Reproduce**
1. Go to '在reqable的分流列表加入一个软件x'
2. Click on '卸载x'
3. 打开reqable，看应用列表标识数字

**Expected behavior**
起码杀掉后台后再重进能正常显示
**Screenshots**
![IMG_20240331_225011](https://github.com/reqable/reqable-app/assets/63104635/51dcfb23-2af1-40e8-9c9a-0942bee10186)
![Screenshot_2024-03-31-22-49-05-23_7fac49e5329bfa70bf0c1257a1a51d55](https://github.com/reqable/reqable-app/assets/63104635/993100f3-82b9-4cd0-b993-c6465349cc15)]
**Information**
 - Platform: Android
 - OS: [14]
 - Arch: [arm, 64]
 - App Version: [2.10.0]

**Comment by MegatronKing** [comment]
感谢反馈，确实是个问题。

**Comment by MegatronKing** [comment]
v2.11.0应该已经修复了。
