### ISSUE TITLE
[feature] 二级代理支持socks5

### ISSUE THREAD

**Issue by biqiguhexuenai** [reqable/reqable-app#534]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
安卓版reqable二级代理加上socks5
**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
感谢建议。目前Reqable在各个平台的二级代理均不支持socks5，大部份情况下http是代理够用的，所以这个优先级不会很高，请见谅。

**Comment by MegatronKing** [comment]
同 #41

**Comment by MegatronKing** [comment]
重复issue，我先关闭了，请关注上面的已有issue。
