### ISSUE TITLE
建议支持集合内API拖放的功能。目前相当于只有收纳功能，完全无法管理。

### ISSUE THREAD

**Issue by leihenshang** [reqable/reqable-app#536]
![image](https://github.com/reqable/reqable-app/assets/26454042/7ad669fb-89a8-41b5-8483-9cc16f176d5d)

**Comment by MegatronKing** [comment]
同 #473

**Comment by MegatronKing** [comment]
@leihenshang 感谢建议。这个功能是p0优先级，会在最近的几个版本内更新。作为重复的issue，我先关闭了。
