### ISSUE TITLE
[feature] 希望增加gzip压缩插件

### ISSUE THREAD

**Issue by sapoiuyt** [reqable/reqable-app#537]
gzip的返回希望增加一个开关直接解压。

**Comment by MegatronKing** [comment]
@sapoiuyt 目前gzip是自动解压的，请问是有问题吗？

**Comment by sapoiuyt** [comment]
@MegatronKing  有问题  我看见header 附带 Content-Encoding:gzip 没有自动解压。 而且我这边使用的环境是 这个返回的数据 有3M的大小。

**Comment by MegatronKing** [comment]
@sapoiuyt 能提供个case吗？har或者curl都可以，我测试下。

**Comment by MegatronKing** [comment]
没有任何进一步的沟通，我关系了哈

**Comment by anylayer** [comment]
随便测试一个app都是
