### ISSUE TITLE
证书无法安装[bug] 

### ISSUE THREAD

**Issue by Everaine0** [reqable/reqable-app#540]
设备:redmi K50
系统:HyperOS
Android版本:14
root方式:Magisk delta
软件版本:最新
1.MT复制后重启:未安装
2使用澎湃OS A14证书模块，重启:未安装
3.Reqable证书模块，重启:未安装
注:模块已按照大佬的要求进行替换

**Comment by MegatronKing** [comment]
你好，证书的问题，Reqable不负责解决。
