### ISSUE TITLE
[feature] 手机版本增加root自动安装证书或者调用magisk安装

### ISSUE THREAD

**Issue by Zy143L** [reqable/reqable-app#541]
之前HTTPCanary也具备这个功能 在手机reqable上反倒看不到了...希望针对有root权限的可以直接加入证书

**Comment by MegatronKing** [comment]
抱歉，证书的问题reqable最多只能提供一些指引，没法帮用户解决。

**Comment by Zy143L** [comment]
我看作者加了magisk这部分 感谢作者 买了永久 感谢
![image](https://github.com/reqable/reqable-app/assets/21352718/2b7b4525-9b53-4b60-aa7f-7f4b45767c87)
