### ISSUE TITLE
[feature] 希望可以有 Websocket 的 message 支持保存全部功能

### ISSUE THREAD

**Issue by cooper1x** [reqable/reqable-app#542]
<img width="747" alt="image" src="https://github.com/reqable/reqable-app/assets/9080789/9372ca7f-3c1d-4772-af2d-7a2ec3107fb4">

消息特别多，想要过滤很不方便，于是想下载下来，找特定的消息是否存在。

**Comment by MegatronKing** [comment]
问题合并到 #539
