### ISSUE TITLE
[feature] 建议增加一个可以一键开启所有SSL旁路的功能，有时候为了抓包需要让网络不断，但是却要一个个加很麻烦

### ISSUE THREAD

**Issue by wh2526422** [reqable/reqable-app#543]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
支持通配符的，全部SSL旁路，配置一个`*`就行了

**Comment by wh2526422** [comment]
你好，我已收到你的邮件，尽快给你回复。

**Comment by wh2526422** [comment]
但是Android 版本的貌似没办法手动编辑

**Comment by MegatronKing** [comment]
> 但是Android 版本的貌似没办法手动编辑

无法编辑？输入不进去吗？请问能录个屏我看看吗？

**Comment by wh2526422** [comment]
可以了，刚刚试了一下谢谢

**Comment by wh2526422** [comment]
不是加不了通配符而是很难进入编辑状态
