### ISSUE TITLE
[bug] win10端开断点进行编辑就卡死，尽快处理

### ISSUE THREAD

**Issue by feng555588** [reqable/reqable-app#544]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@feng555588 更新到2.21.2试试？
