### ISSUE TITLE
[feature] 提供IPv6支持

### ISSUE THREAD

**Issue by 18183883296** [reqable/reqable-app#547]
应用基于IPv6协议的通信越来越广泛，希望对IPv6地址的流量提供支持。

**Comment by MegatronKing** [comment]
@18183883296 支持IPv6的，不知道你遇到了什么问题？

**Comment by 18183883296** [comment]
> @18183883296 支持IPv6的，不知道你遇到了什么问题？

抱歉，我刚开始了解这个软件，似乎这并不是关于IPv6的问题，应该和网络请求应用没有经过Reqable有关。
我遇到的问题是，Reqable仅能捕获浏览器等少数软件的网络请求，我在使用curl，ApiPost，甚至Reqable本身发起的请求都捕获不到。
我的代理设置如下，没有其他代理软件同时运行
![QQ截图20240402222224](https://github.com/reqable/reqable-app/assets/89304297/5ac1cca6-713a-4eca-8ef5-fbc2c5f0aa2c)

使用Win11系统，Reqable版本2.10.1

**Comment by MegatronKing** [comment]
> 我在使用curl，ApiPost，甚至Reqable本身发起的请求都捕获不到。

因为他们都没有走系统网络代理。例如curl你可以用-x参数手动指定代理地址，ApiPost应用设置应该有代理的选项你找找看，至于Reqable的请求你需要打开url输入框末尾的跟随调试图标。

**Comment by 18183883296** [comment]
> > 我在使用curl，ApiPost，甚至Reqable本身发起的请求都捕获不到。
> 
> 因为他们都没有走系统网络代理。例如curl你可以用-x参数手动指定代理地址，ApiPost应用设置应该有代理的选项你找找看，至于Reqable的请求你需要打开url输入框末尾的跟随调试图标。

好的，谢谢
