### ISSUE TITLE
[bug] Windows上响应体解析为空，生成代码功能失效

### ISSUE THREAD

**Issue by 18183883296** [reqable/reqable-app#549]
**Describe the bug**
任何记录的响应体Json和Raw标签下都是空白，生成代码也是空白。

**Screenshots**
![Hex](https://github.com/reqable/reqable-app/assets/89304297/efd02520-5a42-4b1b-b6e6-48e2c684b1b0)
![json](https://github.com/reqable/reqable-app/assets/89304297/70f26737-d142-4c4b-a3b1-906c074c11ca)
![Raw](https://github.com/reqable/reqable-app/assets/89304297/1eecab6c-18b9-4fb1-bb57-593783d8c52d)
![QQ截图20240402213418](https://github.com/reqable/reqable-app/assets/89304297/574fcac1-60b3-4e43-a310-98c39f9874c2)

**Information**
 - Platform: Windows
 - App Version: 2.10.1

**Comment by MegatronKing** [comment]
感谢反馈。试试这个版本：https://github.com/reqable/reqable-app/releases/tag/2.10.1

**Comment by MegatronKing** [comment]
@18183883296 刚刚部署了2.10.2，麻烦再看看

**Comment by 18183883296** [comment]
> @18183883296 刚刚部署了2.10.2，麻烦再看看

问题已解决
