### ISSUE TITLE
[feature] form请求的body部分，urlencode时，显示表格，可否鼠标移动列的宽度？

### ISSUE THREAD

**Issue by chenying99** [reqable/reqable-app#55]
form请求的body部分，urlencode时，显示表格，可否鼠标移动列的宽度？

（怎么没找到上传图片的地方）

**Comment by MegatronKing** [comment]
调整两列中间的分割线吗？

**Comment by chenying99** [comment]
是的，因为有时左边key的比较短，右边的value比较长，显示不全，不方便可视化查看

**Comment by chenying99** [comment]
如果鼠标可以移动中间的分割线就好了

**Comment by MegatronKing** [comment]
好的，感谢反馈，我会尽快支持

**Comment by chenying99** [comment]
> 好的，感谢反馈，我会尽快支持

接口测试，form提交时的urlencode的表格，也可以调整一下

**Comment by chenying99** [comment]
好的 我试试

**Comment by MegatronKing** [comment]
如果没有问题，这个issue我先关闭了。
