### ISSUE TITLE
[bug] 脚本功能在写脚本代码时，代码不可见，脚本窗口没有显示为空

### ISSUE THREAD

**Issue by DGxg9420** [reqable/reqable-app#550]
这是截图
![QQ截图20240402221459](https://github.com/reqable/reqable-app/assets/71811502/0aa5bc7d-f4f1-4fd1-a2e8-805071743f15)

我是win11，版本是最新的
![QQ截图20240402221712](https://github.com/reqable/reqable-app/assets/71811502/85a05a6e-343e-4fa4-b5c1-d458c1eb78c2)

软件目录下也没有日志文件生成，不知道啥原因，如果需要更多信息的话，我可以继续提供，也不知道是不是只有我这样。
![QQ截图20240402221754](https://github.com/reqable/reqable-app/assets/71811502/a826c30f-3fd2-4636-9e18-6d28dddd9fc1)

**Comment by MegatronKing** [comment]
@DGxg9420 部署了一个2.10.2版本，麻烦再试试！

**Comment by MegatronKing** [comment]
同 #594 问题已解决。

**Comment by DGxg9420** [comment]
辛苦了，感谢！！！
