### ISSUE TITLE
[bug] 菜单栏和光标在如果在中央会冲突

### ISSUE THREAD

**Issue by biqiguhexuenai** [reqable/reqable-app#553]
**Describe the bug**
菜单栏和光标在如果在中央会冲突
**To Reproduce**
1. Go to '响应体或者请求体'
2. Click on '双击打开菜单'
3. See error

**Expected behavior**
分离两者

**Screenshots**
![Screenshot_2024-04-03-15-45-12-53_7fac49e5329bfa70bf0c1257a1a51d55](https://github.com/reqable/reqable-app/assets/63104635/9ebbb529-531f-4014-a732-ea2951957cf6)
**Information**
 - Platform: [Android]
 - OS: [14]
 - Arch: [64]
 - App Version: [2.10.1]

**Comment by biqiguhexuenai** [comment]
另外，复制粘贴会失效，菜单和光标分离过度
![Screenshot_2024-04-04-12-47-35-66_7fac49e5329bfa70bf0c1257a1a51d55](https://github.com/reqable/reqable-app/assets/63104635/16cae03a-2058-4555-b8ff-fb23e27d6da9)


> **Describe the bug** A clear and concise description of what the bug is. 菜单栏和光标在如果在中央会冲突 **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to '响应体或者请求体'
> 
>     2. Click on '双击打开菜单'
> 
>     3. See error
> 
> 
> **Expected behavior** A clear and concise description of what you expected to happen. 分离两者
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. ![Screenshot_2024-04-03-15-45-12-53_7fac49e5329bfa70bf0c1257a1a51d55](https://private-user-images.githubusercontent.com/63104635/319090270-9ebbb529-531f-4014-a732-ea2951957cf6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDYzOTcsIm5iZiI6MTcxMjIwNjA5NywicGF0aCI6Ii82MzEwNDYzNS8zMTkwOTAyNzAtOWViYmI1MjktNTMxZi00MDE0LWE3MzItZWEyOTUxOTU3Y2Y2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA0NDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZTk4NDkwMmUzZjU2ZGE5MDU5MDk5M2E0MzczNmQ1MzQ5NjVmNGIwOGM5ODFlNWU4ZDM1NjI2ZmMwODdlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oi6uYeROy93VS1VL7JSzGrEAXKEIecxdnSrUqhYX0Nw) **Information**
> 
>     * Platform: [Android]
> 
>     * OS: [14]
> 
>     * Arch: [64]
> 
>     * App Version: [2.10.1]

另外，复制粘贴会失效，菜单和光标分离过度
![Screenshot_2024-04-04-12-47-35-66_7fac49e5329bfa70bf0c1257a1a51d55](https://github.com/reqable/reqable-app/assets/63104635/16cae03a-2058-4555-b8ff-fb23e27d6da9)

**Comment by biqiguhexuenai** [comment]
另外，复制粘贴会失效，菜单和光标分离过度
![Screenshot_2024-04-04-12-47-35-66_7fac49e5329bfa70bf0c1257a1a51d55](https://github.com/reqable/reqable-app/assets/63104635/16cae03a-2058-4555-b8ff-fb23e27d6da9)

**Comment by MegatronKing** [comment]
感谢反馈，这个问题将在下个版本修复。

**Comment by MegatronKing** [comment]
v2.11.0已修复。
