### ISSUE TITLE
add domain filiter in search-box

### ISSUE THREAD

**Issue by Cthousand** [reqable/reqable-app#554]
I'm always frustrated when i want to filiter the domian, it is unconvinent to press F1 and choose the right domain when the domian list is long. 
Another situation is that domin-filiter, such as .badu which  contains www.baidu.com, xxx.baidu.com, I think it's useful, but In currency version, it has no way to realize this need.

so, i suggest that we can add domain-filiter function in search-box.

just like this:

<img width="276" alt="iShot_2024-04-03_22 48 11_副本" src="https://github.com/reqable/reqable-app/assets/102720782/a80f829a-b305-41a0-9154-04eff2d23c49">

**Comment by MegatronKing** [comment]
你好，感谢建议。关于域名筛选的问题，我目前的建议是使用书签功能，会更加方便，将指定域名添加到书签，通过书签筛选。右键一个请求记录 -> 书签 -> 添加域名。

**Comment by Cthousand** [comment]
> 你好，感谢建议。关于域名筛选的问题，我目前的建议是使用书签功能，会更加方便，将指定域名添加到书签，通过书签筛选。右键一个请求记录 -> 书签 -> 添加域名。

那么可否让域名支持通配符表达,例如*.baidu.*, 这种场景是:是当我们分析一个网站时,希望只看到目标相关url, 因为一个网站往往有很多子域名,如果使用将指定域名添加到书签里, 这可能并不方便, 因为这需要先找到指定域名

以百度为例:
![image](https://github.com/reqable/reqable-app/assets/102720782/95d271b4-8b8b-47ba-9139-107fdae27874)
我希望能够找到所有.baidu.com的域名, 包括子域名.

我的建议是:让自定义书签支持通配符表达
![image](https://github.com/reqable/reqable-app/assets/102720782/88d6c352-88af-4b56-9ba2-90f560435f39)

**Comment by Cthousand** [comment]
作者大大, 求你加上给你功能, 我原地再续费一年

**Comment by MegatronKing** [comment]
v2.21.0已支持。
