### ISSUE TITLE
[feature] 提供一个GUI选项纠正不正确的Content-Type值

### ISSUE THREAD

**Issue by TopMaps** [reqable/reqable-app#555]
1.响应包：原始预览正常(含有中文字符)
![1](https://github.com/reqable/reqable-app/assets/163238823/15fad79d-d159-46cc-b689-89f0c897388a)

2.但是查看响应体，乱码；而且只显示hex，无中文字符的json字符串也只是显示hex
![2](https://github.com/reqable/reqable-app/assets/163238823/d4e03ef1-4284-4afa-be9f-0c8fe9e13a3e)

3.之前正常，貌似就是2.10.1导致的bug?目前版本以最新2.10.2

**Comment by MegatronKing** [comment]
因为你的Content-Type值是`application/octet-stream`，不是`application/json`，所以body会按照hex显示。如果你需要显示成json，可以通过脚本功能纠正下这个Content-Type的值。

**Comment by MegatronKing** [comment]
另一种方式是提供一个GUI选项，让用户选择数据类型，目前还没有做。

**Comment by MegatronKing** [comment]
同 #383
