### ISSUE TITLE
[bug] android版没有重写功能吗

### ISSUE THREAD

**Issue by wh2526422** [reqable/reqable-app#558]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
没有。同 #368
