### ISSUE TITLE
[bug] mac打开关闭reqable时，会修改系统代理设置

### ISSUE THREAD

**Issue by Fangg3** [reqable/reqable-app#56]
打开时 设置的是reqable服务地址
关闭时 设置为无

**Comment by MegatronKing** [comment]
如果你启用了“自动开启代理”功能或者手动设置代理，reqable会修改并启用系统代理设置。当reqable程序退出的时候，会自动关闭代理（但不会清空系统代理）。详情请阅读文档：https://reqable.com/docs/capture/proxy

**Comment by MegatronKing** [comment]
我看到的大部分代理软件的逻辑基本都是如此，退出程序会自动关闭代理（但不会清空系统代理）。
