### ISSUE TITLE
请问这上传下载的流量是正常的么？

### ISSUE THREAD

**Issue by aigo888** [reqable/reqable-app#560]
![QQ截图20240406155139](https://github.com/reqable/reqable-app/assets/50495954/c00e1037-094c-4e9b-abc2-0e50ff3fc56b)
我并没有使用太长时间，基本上就是用的时候启动拦截，拦截完了就停止了。

**Comment by aigo888** [comment]
我发现拦截的时候，莫名的有很多访问国外的请求，关了reqable请求就停止了，不知道是什么原因。

**Comment by MegatronKing** [comment]
@aigo888 

> 第一个流量的问题。

如果你只是点了停止按钮，没有关闭系统代理，这个量是正常的。停止只是表示流量不记录到列表，系统代理仍然开着的话，流量仍然会经过Reqable。停止后，关闭系统代理（右上角按钮左边的网络图标）就好了。

> 莫名的有很多访问国外的请求。

请求没法凭空生成，只能说明你的设备后台就是有很多这些请求在发送。你可通过Reqable看看是哪个应用程序发送的，发送的什么数据，也许说不定是恶意软件在偷偷传输你的用户数据。

**Comment by aigo888** [comment]
@威震天王
![QQ截图20240406200138](https://github.com/reqable/reqable-app/assets/50495954/4b26477c-afe2-433b-9751-0f49ae1c3dce)

这个图能分析出这个是什么问题么，就是每次有新版本，然后我就点更新，完了在启动后，拦截数据的时候，就有这些请求，等我关了reqable之后，过会打开又正常了。

**Comment by aigo888** [comment]
@威震天王
![QQ截图20240406200138](https://github.com/reqable/reqable-app/assets/50495954/4b26477c-afe2-433b-9751-0f49ae1c3dce)

这个图能分析出这个是什么问题么，就是每次有新版本，然后我就点更新，完了在启动后，拦截数据的时候，就有这些请求，等我关了reqable之后，过会打开又正常了。

**Comment by MegatronKing** [comment]
看不出来，竟然这么多不一样的IP？

**Comment by MegatronKing** [comment]
目前没有看到有与Reqable相关的问题，如果没有进一步的信息，这个issue我将关闭了。
