### ISSUE TITLE
[bug] 打开har文件会重置窗口状态

### ISSUE THREAD

**Issue by Haocen2004** [reqable/reqable-app#564]
**Describe the bug**
如果将reqable窗口最大化后，使用文件关联功能打开har文件，会使得窗口状态重置

**To Reproduce**
1. 将reqable窗口最大化
2. 双击打开任何一个har文件
3. reqable不再是最大化状态

**Expected behavior**
保持原有窗体状态不变

**Screenshots**
无

**Information**
 - Platform: Windows
 - OS: Windows 11 专业版 24H2 26090.112
 - Arch: x86-64
 - App Version: 2.10.2 (80)

**Comment by MegatronKing** [comment]
v2.11.0已修复！
