### ISSUE TITLE
[需求] 增加DNS修改功能 

### ISSUE THREAD

**Issue by reckeyliao** [reqable/reqable-app#565]
在API调试过程中，随时会切换api域名指向的内外网地址，api多了，难免修改起来有困难，能否增加个指定DNS功能，这样可以借助公司的DNS服务器将域名导向到需求的地方。

**Comment by MegatronKing** [comment]
@reckeyliao 试试环境变量功能？

**Comment by reckeyliao** [comment]
试过了，可行。
