### ISSUE TITLE
[建议]TCP、UDP、Websocket等数据包的显示问题 

### ISSUE THREAD

**Issue by reckeyliao** [reqable/reqable-app#566]
**问题一：如题，目前所有TCP、Websocket等数据包在列表界面显示的是VPN://开头的**
建议：显示修改成对应的数据包类型

**问题二：长连接TCP数据包在Reqable中是被当做HTTP请求显示**
建议：如果不支持TCP具体数据包的解析，可以不显示到列表中

**Comment by CMJNB** [comment]
希望手机端可以抓udp的包，类似Vnet的功能

**Comment by MegatronKing** [comment]
v2.17.0已经移除vpn开头的标记。另外，tcp/udp不在reqable的支持范围内，这个issue我关闭了。
