### ISSUE TITLE
[feature] 终于回归了

### ISSUE THREAD

**Issue by superen7527** [reqable/reqable-app#57]
最开始就支持了，没想到后来下架解散群，可惜了好久。刚刚收到邮件才知道这个，希望这次不会再这样了。

对于安卓版，希望后续可以以root或者xp模块形式执行插件，而不是只能用vpn形式，之前还有很多想法，忘的差不多了。没地方反馈。以后想起来再来提意见吧。加油

**Comment by MegatronKing** [comment]
您好，感谢支持。如果您有详细的需求，可以新开一个feature issue，描述具体的需求，这个issue我就先关闭了。
