### ISSUE TITLE
[feature] 数据多次重发 每个数据间隔的延迟可以缩短吗？

### ISSUE THREAD

**Issue by hyt65098631** [reqable/reqable-app#571]
开发者你好，请问该软件的重发功能，在同时选择十个数据重发时不设置间隔时间，它们之间会有一定的间隔时间，这个间隔时间是根据什么来定的，可以缩短其中的间隔时间吗？期待回复
![{65752884-4E08-4b69-BE6B-21C95F4F9F12}](https://github.com/reqable/reqable-app/assets/83172030/41849a64-e920-4df4-a2fc-ebcff86e5ac2)
![{A3833427-67CA-4fdb-9F04-2CAFE4091573}](https://github.com/reqable/reqable-app/assets/83172030/c1fd5e71-3ef5-4952-8109-75cf64f3c9b1)

**Comment by hyt65098631** [comment]
官网说是并发的  但是这个延时好像还是有的   可以改进吗

**Comment by MegatronKing** [comment]
目前来讲，没有可以改进的空间。这个并发只是只是逻辑是并发，实际受限于计算机程序和硬件的性能。
