### ISSUE TITLE
[feature] 支持窗口尺寸调得更小一些

### ISSUE THREAD

**Issue by SugarFatFree** [reqable/reqable-app#576]
**Describe the bug**
窗口太大了，我的笔记本只有14寸，并使用了150%缩放，导致窗口模式下显示过大，无法缩小

**Comment by MegatronKing** [comment]
@SugarFatFree 感谢反馈，能截个图或者拍个照看看吗？另外，缩小可以用快捷键 `control + -`控制。

**Comment by SugarFatFree** [comment]
> @SugarFatFree 感谢反馈，能截个图或者拍个照看看吗？另外，缩小可以用快捷键 `control + -`控制。

![CEPF-PBJ3-4C00-SPE4.jpg](https://github.com/reqable/reqable-app/assets/30424828/bf77501e-853b-4d7c-bc1b-4c2741ebf0ca)

无法再继续缩小窗口了，程序内的缩放只能对内部元素进行缩放，而无法缩放窗口。

**Comment by SugarFatFree** [comment]
@MegatronKing

**Comment by MegatronKing** [comment]
收到，你的分辨率是多少？

**Comment by SugarFatFree** [comment]
> 收到，你的分辨率是多少？

1920*1080的，缩放150%

**Comment by MegatronKing** [comment]
@SugarFatFree 看起来是窗口大小未计算任务栏的高度，我处理了下，你试试v2.12.0版本？

**Comment by SugarFatFree** [comment]
> @SugarFatFree 看起来是窗口大小未计算任务栏的高度，我处理了下，你试试v2.12.0版本？

可以了，但是窗口不能再缩小了吗？我只能拉到无法再拉小窗口了

**Comment by SugarFatFree** [comment]
> @SugarFatFree 看起来是窗口大小未计算任务栏的高度，我处理了下，你试试v2.12.0版本？

这个问题在最新版本：V2.21.4 又出现了，高度超出了任务栏。
