### ISSUE TITLE
重定向目标地址包括匹配子目录，规则就会失效[bug] 

### ISSUE THREAD

**Issue by abpanxianhui** [reqable/reqable-app#580]
![image](https://github.com/reqable/reqable-app/assets/40539467/2fdea158-5612-4e92-abe2-72c392caa827)
这样规则会失效

如果去掉 /*，重定向到 127.0.0.1:3333 规则就会生效

**Comment by MegatronKing** [comment]
@abpanxianhui 感谢反馈。请告诉我下，你的原始请求URL是什么？希望重定向的URL是什么？

**Comment by MegatronKing** [comment]
没有进一步的信息，这个issue我关闭了。
