### ISSUE TITLE
自动换行

### ISSUE THREAD

**Issue by hkyyi** [reqable/reqable-app#581]
**Is your feature request related to a problem? Please describe.**
查看某个报文时点击取消自动换行，在查看另一个报文时自动换行又出现了

**Describe the solution you'd like**
希望可以设置查看报文时是否自动换行，并且永久保存设置，不要查看另一个报文时自动换行又出现了

**Comment by MegatronKing** [comment]
@hkyyi 感谢建议。是否需要保存换行配置，这个问题我曾经考虑过。我的看法是，自动换行不是和个人习惯相关而是和具体内容相关，所以我没有记录这个。如果你有不同的看法，也欢迎提出，一起讨论。
