### ISSUE TITLE
[bug] Please help function Rewrite

### ISSUE THREAD

**Issue by tht010792** [reqable/reqable-app#584]
I have use Reqable 
![1](https://github.com/reqable/reqable-app/assets/97270259/f9064ca2-814f-468c-accd-a0a31434395e)
but when I use reqable on pc capture packet then I rewrited, response dont change on mobile ? please help

**Comment by MegatronKing** [comment]
It seems that the URL does not match, please check.

**Comment by tht010792** [comment]
I have url have many parameter ? but with httpcanany it just have main url , dont need match parameter, I can rewrite ! But with reqable i dont, so my url have many parameters, and parameter is dynamic, how to rewrite it ? Can you add option for that ? use for dynamic parameter and static parameter

**Comment by tht010792** [comment]
Can you example for me ? this is my url 
`https://api.fptplay.net/api/v7.1_a/payment/get_v3_user_vips?serial_number=&drm_id=&drm=1&fhd=1&st=mweN5VbkV4rtbdT6wztgfw&e=1713264215&version=7.13.4&version_code=1345&source=mobile_normal&uSKBC=true&cachedByUrls=true&nettype=wifi&device=FPT%20Play%20Mobile%20%28version:13%2Cmodel:2107113SG%29&mac_address=&mac_addr=2179522f1a752b9a`
