### ISSUE TITLE
[feature] 辅助服务合并到主程序

### ISSUE THREAD

**Issue by reckeyliao** [reqable/reqable-app#586]
如题，每次调试前都需要开启辅助服务，很不方便，让程序也显得臃肿，程序切后台时，也有一定几率被系统暂停掉或者杀掉。可以借鉴此前的xxxx Canary那种就挺好。

**Comment by MegatronKing** [comment]
虽然技术上可以实现，但是工作量比较大，需要推翻目前的技术方案。Reqable虽然复用了HttpCanary的代码，但是两种的技术方案完全不一样，沿用HttpCanary的方案会导致API请求测试部分无法正常工作。

**Comment by MegatronKing** [comment]
v2.17.0已经合并。
