### ISSUE TITLE
[feature] 自定义移动请求信息列位置

### ISSUE THREAD

**Issue by cxplay** [reqable/reqable-app#587]
目前请求信息列是固定的, 无法移动分列的位置(有点像 Chromium 的 DevTools 一样), 经常打开请求详细信息二级窗口后就把最后的几列遮挡住了(当然也可以新窗口打开二级窗口). 不过一旦开启显示的信息列变多, 就更希望本次调试重要的信息能按照希望分布在希望的位置.
![image](https://github.com/reqable/reqable-app/assets/62034099/11c8fcae-bd31-4e74-adef-fd5f12348fef)

**Comment by MegatronKing** [comment]
@cxplay 长按左右拖动试试

**Comment by cxplay** [comment]
> @cxplay 长按左右拖动试试

我去, 隐藏功能! 谢谢解答!
