### ISSUE TITLE
[feature] 已root安卓手机，安装过多次reqable的证书，现在想全部清除，如何清除手机中来源于reqable的所有证书

### ISSUE THREAD

**Issue by akito4** [reqable/reqable-app#590]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
这个可能没有办法，文件名都是hash值，没法辨别。

**Comment by akito4** [comment]
> 这个可能没有办法，文件名都是hash值，没法辨别。

那我直接清掉手机里的所有证书有影响吗？

**Comment by cesaryuan** [comment]
> > 这个可能没有办法，文件名都是hash值，没法辨别。
> 
> 那我直接清掉手机里的所有证书有影响吗？

肯定有影响呀，系统可能直接无法访问所有https网站了

**Comment by MegatronKing** [comment]
其实可以不用删除，手机设置证书列表里面禁用掉就行了。这个不属于reqable的问题，我先关闭了。
