### ISSUE TITLE
[bug] 请求内网自签名证书的Https请求时报错：net::ERR_CERT_AUTHORITY_INVALID 

### ISSUE THREAD

**Issue by leihenshang** [reqable/reqable-app#592]
**Describe the bug**
请求内网自签名证书的Https请求时报错：net::ERR_CERT_AUTHORITY_INVALID 
https://172.0.0.53/apis/xxx.com/node/v1/leafs?from=2024-04-18&to=2024-04-18
使用的是从浏览器中导出的curl，使用命令行可以直接请求到结果。我注意到在命令行中有一个 " --insecure"。
使用apipost可以正常请求。

**Information**
 - Platform: windows
 - OS:  win10 64bit home basic
 - Arch:  x86-64
 - App Version: 2.12.0

**Comment by MegatronKing** [comment]
Reqable现在是强制校验SSL证书，你都ip直连了就不要用https用http。

**Comment by leihenshang** [comment]
> Reqable现在是强制校验SSL证书，你都ip直连了就不要用https用http。

我的场景是这样的，现在我们的服务是一个微服务架构，服务前有个网关验证权限，到指定的服务的API只能通过网关转发。
而这个网关就直接使用了自签名的证书，建议加个开关控制一下或者支持导入自签名证书？

**Comment by MegatronKing** [comment]
> > Reqable现在是强制校验SSL证书，你都ip直连了就不要用https用http。
> 
> 我的场景是这样的，现在我们的服务是一个微服务架构，服务前有个网关验证权限，到指定的服务的API只能通过网关转发。 而这个网关就直接使用了自签名的证书，建议加个开关控制一下或者支持导入自签名证书？

自签名证书是没有问题的。比如你这个地址域名部分是IP，只有服务器返回的证书是签发证书是`127.0.0.1`这个CN才能验证通过，但是你自签名证书肯定不是`127.0.0.1`这个CN吧，所以导入自签名证书也解决不了这个问题。

这个问题有两种方式解决：
1. Reqable不强制校验SSL，目前还没有实现，在后面版本会上线。
2. 使用Reqable的镜像功能映射，参考文档：https://reqable.com/zh-CN/docs/capture/mirror

你这个问题，用镜像功能的操作方式如下：
第一步：点亮URL输入框末尾的跟随调试图标。
第二步：找到你自签证书签发的域名，例如是`abc.com`。
第三步：新建一个镜像规则，将 `abc.com` 映射到镜像地址 `127.0.0.53`。
第四步：将URL输入框里面的本地域名地址`127.0.0.53`改成`abc.com`。
简单来说，就是让Reqable的镜像功能帮你做个了DNS解析。

**Comment by leihenshang** [comment]
> > > Reqable现在是强制校验SSL证书，你都ip直连了就不要用https用http。
> > 
> > 
> > 我的场景是这样的，现在我们的服务是一个微服务架构，服务前有个网关验证权限，到指定的服务的API只能通过网关转发。 而这个网关就直接使用了自签名的证书，建议加个开关控制一下或者支持导入自签名证书？
> 
> 自签名证书是没有问题的。比如你这个地址域名部分是IP，只有服务器返回的证书是签发证书是`127.0.0.1`这个CN才能验证通过，但是你自签名证书肯定不是`127.0.0.1`这个CN吧，所以导入自签名证书也解决不了这个问题。
> 
> 这个问题有两种方式解决：
> 
> 1. Reqable不强制校验SSL，目前还没有实现，在后面版本会上线。
> 2. 使用Reqable的镜像功能映射，参考文档：https://reqable.com/zh-CN/docs/capture/mirror
> 
> 你这个问题，用镜像功能的操作方式如下： 第一步：点亮URL输入框末尾的跟随调试图标。 第二步：找到你自签证书签发的域名，例如是`abc.com`。 第三步：新建一个镜像规则，将 `abc.com` 映射到镜像地址 `127.0.0.53`。 第四步：将URL输入框里面的本地域名地址`127.0.0.53`改成`abc.com`。 简单来说，就是让Reqable的镜像功能帮你做个了DNS解析。

很棒的变通解决方式，但是还是期待加个开关控制是否强制校验SSL。我先用这个方法试试，加油！期待reqable越来越好！
