### ISSUE TITLE
[bug] 系统代理开关关闭后，aws-cli仍然无法使用

### ISSUE THREAD

**Issue by guoxianru** [reqable/reqable-app#593]
**Describe the bug**
软件开启系统代理会添加注册表项（计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ProxyServer），退出软件后并没有删除注册表项，导致部分软件无法正常使用（Windows平台的aws-cli：Failed to connect to proxy URL: "https://127.0.0.1:9000"）

**Information**
 - Platform: Windows
 - OS: Windows 10 企业版
 - Arch: x86-64
 - App Version: 2.11.1

**Comment by MegatronKing** [comment]
@guoxianru 感谢反馈，按照设计退出程序的时候会自动关闭系统代理开关的，没起作用吗？

**Comment by guoxianru** [comment]
网络和Internet>代理>系统代理开关，软件关闭后是会被关闭的，但是注册表项没有被删除，aws-cli无法使用，手动删除注册表，aws-cli恢复正常

**Comment by MegatronKing** [comment]
这个注册表项是应该一直存在的，windows系统代理是通过这个进行设置。我检查了下其他的涉及网络代理的软件，也会保留这个注册表项，只是把注册表里面代理的开关的值修改为关闭。
