### ISSUE TITLE
[feature] android14+ 并不能以（文档标注的） ADB/Root 方式安装 CA，请妥善标注

### ISSUE THREAD

**Issue by MicroCBer** [reqable/reqable-app#594]
由于安卓14将系统信任证书列表移动至/apex内，adb/root方式不再可用，仅可通过在启动时overlay apex来添加证书，请妥善标注

**Comment by MegatronKing** [comment]
非常感谢，我测试下。

**Comment by MicroCBer** [comment]
> 非常感谢，我测试下。

直接执行 Magisk 模块中的脚本应当可以达到在重启前临时加入证书的效果，我觉得可以做个这个按钮，会方便很多

**Comment by terminatortor** [comment]
excuse me,how can I do this wihtout magisk

**Comment by MegatronKing** [comment]
感谢建议，引导文案已经标注。
