### ISSUE TITLE
控件字体显示有问题[bug] 

### ISSUE THREAD

**Issue by luming8** [reqable/reqable-app#595]
控件有些按钮的字体显示有问题，这怎么解决呀
![搜狗截图20240419003419](https://github.com/reqable/reqable-app/assets/101869183/23550def-ccd4-4e3f-80fb-32d7d8d86d5c)

**Comment by MegatronKing** [comment]
@luming8 感谢反馈，试试新版本2.12.1。

**Comment by MegatronKing** [comment]
@luming8 请问有验证过新版本ok吗？
