### ISSUE TITLE
[抓包逻辑]参考圈X抓包逻辑

### ISSUE THREAD

**Issue by DYS7516461** [reqable/reqable-app#597]
作者有没有了解过圈X的代理抓包逻辑 ，reqable app开启抓包后会影响到手机中的其他应用，特别是银行类会提示VPN，但是圈X就没有这个问题

**Comment by MegatronKing** [comment]
不了解，你为什么想搞银行，不去抢呢

**Comment by DYS7516461** [comment]
不是搞银行，只是举个例子，开启reqable会导致我的多个app的后台闪退，相反圈x一直挂代理就没有这个问题，如果我的目的是搞银行的的话，直接用圈x了，只是反馈下问题而已，或者是reqable能不能开启的时候单独指定app（可能是我没找到设置方法，之前黄鸟可以），这样就不会误伤其他app了
