### ISSUE TITLE
[feature] TUN 与网卡模式支持

### ISSUE THREAD

**Issue by cxplay** [reqable/reqable-app#598]
仅在 Windows, 有很多软件并不遵守系统代理设置, 有的也不提供代理设置. 通过 TUN 模式或者网卡模式可以真正全局捕获流量, 是比系统代理更全面的办法.

**Comment by justmd5** [comment]
需要这个功能，类似surge的增强模式

**Comment by dnslin** [comment]
需要这个功能 强行让软件走代理

**Comment by MegatronKing** [comment]
这个功能之前讨论过，见 #337
