### ISSUE TITLE
[bug] 无法抓包HSTS网站

### ISSUE THREAD

**Issue by echo-bytes** [reqable/reqable-app#60]
qianchuan.jinritemai.com 通常会使用加密技术来保护您的信息。Chrome 此次尝试连接到 qianchuan.jinritemai.com 时，该网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 qianchuan.jinritemai.com，或者 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 qianchuan.jinritemai.com，因为此网站使用了 HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by MegatronKing** [comment]
请确保正确安装了Reqable的CA证书。

**Comment by echo-bytes** [comment]
> 请确保正确安装了Reqable的CA证书。

装了，https的网站正常抓包，有的网站是提示这个 hsts 不能抓包  qianchuan.jinritemai.com  你打开看看

**Comment by MegatronKing** [comment]
> > > > 请确保正确安装了Reqable的CA证书。
> > > 
> > > 
> > > 装了，https的网站正常抓包，有的网站是提示这个 hsts 不能抓包 qianchuan.jinritemai.com 你打开看看
> > 
> > 
> > 我电脑打开这个域名是正常的，巨量什么什么
> 
> 解决了，你安装证书教程不对，，，误导了，建议改一下教程

好的，请问是哪里的问题？
