### ISSUE TITLE
连接手机时总是显示连接失败

### ISSUE THREAD

**Issue by TFboy1** [reqable/reqable-app#601]
我按照教程描述的方法进行了尝试：
 手机与电脑都连接到同一个局域网。
这个肯定是满足的
 手机Wifi代理已设置Reqable的IP地址和端口号（见Reqable窗口顶部），或者使用SocksDroid进行转发。
![Screenshot_2024-04-21-10-15-07-605-edit_com android settings](https://github.com/reqable/reqable-app/assets/119146578/555e113f-d740-450e-801f-c06ed7939760)

 手机上已正确安装CA证书（针对只有CONNECT请求的情况）。
因为正在同步电脑和手机，可以自动同步证书，因此并没有给手机安装证书
 电脑网络防火墙已开放Reqable的端口地址。
![capture_20240421101858469](https://github.com/reqable/reqable-app/assets/119146578/4abe9389-f6f9-4bea-a8f7-7c313cac5562)
![capture_20240421101836808](https://github.com/reqable/reqable-app/assets/119146578/e5ade50b-17ff-4bb1-9fd8-b87d46761429)

**Comment by MegatronKing** [comment]
@TFboy1 感谢反馈。请问有试过更换端口吗？或者使用Reqable移动端版本进行连接？

**Comment by TFboy1** [comment]
谢谢你的回答，但我尝试把9000端口换成8888，并没有能连接成功，同时我使用了手机里的Reqable移动端扫码连接，并没有成功连上，我不清楚问题出在电脑还是手机

**Comment by MegatronKing** [comment]
连不上的话，要么不在一个局域网，要么被防火墙拦了。

**Comment by TFboy1** [comment]
和证书啥的有没有关系

**Comment by TFboy1** [comment]
好的，我这就试试

**Comment by Arcticlyc** [comment]
> 好的，我这就试试

电脑进入 wifi 属性，点击查看防火墙安全设置，进入安全中心后点击允许应用通过防火墙，查看是否放行 reqable

**Comment by MegatronKing** [comment]
这个判断基本不是reqable的问题，issue我先关闭了。

**Comment by wastelandEmperor** [comment]
看看是不是，防火墙那边被阻止了。

**Comment by wastelandEmperor** [comment]
<img width="467" alt="Snipaste_2024-06-23_08-26-48" src="https://github.com/reqable/reqable-app/assets/96726103/73d69b7f-a87b-4f35-b9af-11f637598db9">
看看是不是被防火墙阻止了。

**Comment by jachin113** [comment]
网络环境：有线
监听设备：同个电脑上的手机模拟器
问题描述：被reqable监听后，reqable有数据显示，但是一旦开启WiFi代理进行监听，模拟器就无网络，断开WiFi代理不进行监听就模拟器正常
