### ISSUE TITLE
[feature] 希望抓包显示能增加类似于 charles 的结构化展示与接口触发时的高亮显示

### ISSUE THREAD

**Issue by stlomib** [reqable/reqable-app#607]
Describe the solution you'd like
类似于 charles，聚合显示 api 层级，结构化展示 api 请求，并且在 api 触发时高亮下。此功能对于接口多的 app 抓包很方便，api 结构也一目了然。
![Uploading image.png…]()

**Comment by MegatronKing** [comment]
结构树在侧边栏，高亮闪烁暂时还没有。

**Comment by ddkwork** [comment]
我猜你需要一个树形表格



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月24日(周三) 上午9:33
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reqable/reqable-app] [feature] 希望抓包显示能增加类似于 charles 的结构化展示与接口触发时的高亮显示 (Issue #607)




 
Describe the solution you'd like
 类似于 charles，聚合显示 api 层级，结构化展示 api 请求，并且在 api 触发时高亮下。此功能对于接口多的 app 抓包很方便，api 结构也一目了然。

**Comment by MegatronKing** [comment]
高亮的需求见 #174

**Comment by MegatronKing** [comment]
重复issue我关闭了。
