### ISSUE TITLE
[bug] 抓包工具无法通过options接口请求

### ISSUE THREAD

**Issue by abc2520** [reqable/reqable-app#608]
**Describe the bug**
在访问网站页面时，接口会先使用options请求方式访问接口以判断接口是否可用，但是抓包工具无法正常转发options请求，导致网站误判请求接口不存在，进而导致后续的资源无法访问，使用其它抓包工具可以正常转发这个options请求，请帮忙检查一下原因。样本示例网站地址为https://www.chanelink.com/community

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/76686221/379453f3-6f72-4141-9122-48115a9ab96e)

**Information**
 - Platform: [windows]
 - Arch: [win10x64_cn]
 - App Version: [版本 2.12.1 (84) (x86_64)]

**Comment by MegatronKing** [comment]
感谢反馈，确实排查到一个bug，下个版本修复。

**Comment by MegatronKing** [comment]
@abc2520  v2.13.0版本已经修复，可以验证看看。

**Comment by MegatronKing** [comment]
如果没有问题，这个issue我先关闭了。
