### ISSUE TITLE
[feature] 搜索能否增加历史搜索功能

### ISSUE THREAD

**Issue by GlamoroGG** [reqable/reqable-app#610]
我不清楚是否还有更高效的过滤方式,但是目前来说,搜索功能和过滤得配合着使用,我并没有找到搜索历史的功能,希望大佬能增加这个功能。

**Comment by MegatronKing** [comment]
@GlamoroGG 请问是手机端还是电脑端？

**Comment by GlamoroGG** [comment]
> @GlamoroGG 请问是手机端还是电脑端？

电脑端  顶部的搜索框

**Comment by MegatronKing** [comment]
v2.14.0已经修复历史记录搜索无结果的bug。
