### ISSUE TITLE
[feature] 在不开启SSL解密的情况下解出域名

### ISSUE THREAD

**Issue by SeeFlowerX** [reqable/reqable-app#611]
在Charles中有这样一个功能，那就是block list，可以通过域名阻断请求

但根据reqable文档所描述，在没有开启SSL解密时，不会处理任何https的数据，这样一来那些https的请求都会显示为ip+443的样子

但是在Charles中，这些请求会有域名的信息，于是可以通过域名快捷方便的去做阻断

写到这里才发现reqable也暂时没有阻断功能...

不过更重要的是，解出域名信息，肯定是更加直观的。

希望可以增加不开启SSL解密的情况下解出域名这个特效

**Comment by SeeFlowerX** [comment]
更详细使用之后，发现是这样的：

必须安装证书到电脑的系统上，SSL解密的功能才会正常生效，但是如果是只对移动端转发来的数据抓包，实际上是不需要这一步的？因为Charles没有要求证书一定要到电脑上，只要手机安装了，也是能正常解的

不知道有没有办法不安装证书到电脑上仍然可以开启SSL解密功能，提供一个这样的设置

---

另外还是主贴提到的那个，尝试把域名解出来

虽然安装了证书到电脑之后，SSL解密是会把域名解出来，但是一旦把域名加入了SSL旁路，后面又显示成ip+443了

**Comment by MegatronKing** [comment]
v2.17.0已经修复此问题。
