### ISSUE TITLE
[feature] 增加对指定域名或者链接进行阻断/丢弃的功能

### ISSUE THREAD

**Issue by SeeFlowerX** [reqable/reqable-app#612]
![image](https://github.com/reqable/reqable-app/assets/70688581/b4fee294-7616-4ea1-a659-7a825a77a249)

也就是Charles中block list功能，用来模拟弱网或者网络异常等情况

**Comment by MegatronKing** [comment]
@SeeFlowerX 用网关功能

**Comment by SeeFlowerX** [comment]
感谢
