### ISSUE TITLE
[feature] 似乎只能为域添加Cookie，可以增加一个通过IP+端口号的方式添加Cookie的功能吗？谢谢。

### ISSUE THREAD

**Issue by yhsw** [reqable/reqable-app#617]
因为我的工作基本都是调试局域网内webapi，而且我自己的网站也没有域名。
![QQ图片20240426214848](https://github.com/reqable/reqable-app/assets/30999456/64d8227d-443a-4968-9a20-35d4143cba52)
下面这样设置并没有效果...

**Comment by MegatronKing** [comment]
可以用IP，请求的时候用IP请求不要用域名。

**Comment by MegatronKing** [comment]
@yhsw 你好，请问是否还有问题？如果没有问题这个issue我关闭了。
