### ISSUE TITLE
[bug] iOS端按域名分组后，数据不会实时更新

### ISSUE THREAD

**Issue by kybetter** [reqable/reqable-app#619]
**Describe the bug**
 iOS端按域名分组后，数据不会实时更新，需要退回到上一层再进入，才会更新。

**Information**
 - Platform: iPhone
 - OS: 17

**Comment by MegatronKing** [comment]
感谢反馈。这个问题是存在的，确实没有做刷新。

**Comment by MegatronKing** [comment]
v2.16.1版本已经修复。
