### ISSUE TITLE
安卓证书一直下载失败[bug] 

### ISSUE THREAD

**Issue by Gavin0210** [reqable/reqable-app#62]
**Describe the bug**
安卓证书一直下载失败
**To Reproduce**
1.设置wifi代理, 然后浏览器扫码下载证书,一直下载失败

**Information**
手机红米note12 turbo

**Comment by Gavin0210** [comment]
访问网页可以看到很多connect的请求,说明代理是连上的了,但是下载证书失败

**Comment by MegatronKing** [comment]
@Gavin0210 点下右上角`启动`按钮，然后再试下下载证书，看看调试列表们能不能看到下载证书的请求。

**Comment by Gavin0210** [comment]
@MegatronKing 没有看到下载证书的请求.能看到很多miui的请求

**Comment by Gavin0210** [comment]
能不能直接像mitmproxy一样 把各种类型的证书都存电脑上 @MegatronKing

**Comment by MegatronKing** [comment]
你可以导出crt/pem格式的证书
