### ISSUE TITLE
[feature] 支持导入swagger格式api集合

### ISSUE THREAD

**Issue by YujiaCheng1996** [reqable/reqable-app#625]
**Describe the solution you'd like**
good old swagger json格式api文档直接导入为一个集合。

**Describe alternatives you've considered**
导入支持swagger json，最好还能支持url导入，甚至是定时或启动时自动同步。

**Additional context**
Postman导入后再导出再在Reqable导入太麻烦。

**Comment by MegatronKing** [comment]
不知道swagger能不能导出curl，然后通过curl导入reqable集合。

**Comment by MegatronKing** [comment]
v2.29.0版本已实现，请更新版本。
