### ISSUE TITLE
Bug in curl copy with non-standard content-type header

### ISSUE THREAD

**Issue by xshadow0x** [reqable/reqable-app#626]
**Describe the bug**

I found a bug where, when sniffing a request that contains a non-standard content-type header (e.g., application/vnd.api+json or others), copying it as a curl command results in the program not adding any content-type header at all, instead of adding the one that was originally in the request. This can cause the server to refuse to accept the request with an unsupported content-type.

**To Reproduce**
1. sniff request with non-standard content-type 
2. Click copy as curl

**Information**
 - Platform: windows
 - OS: 11
 - App Version: 2.14.1 (87) (x86_64)

**Comment by MegatronKing** [comment]
@xshadow0x Thanks, I can reproduce this bug. I will fix this in the next version.

**Comment by MegatronKing** [comment]
Fixed on v2.15.0
