### ISSUE TITLE
[feature] 规则合集支持搜索规则

### ISSUE THREAD

**Issue by cxplay** [reqable/reqable-app#628]
目前 reqable 的很多核心功能够支持多条规则, 但是规则一多起来要检查某个规则是否已经存在, 比如检查网关中是否已经处理了某路径的 URL, 就会因为规则太多难以实现. 希望能够更灵活地管理已经有的规则, 比如搜索已有规则.

**Comment by MegatronKing** [comment]
v2.17.0已经支持搜索规则。
