### ISSUE TITLE
[feature] 添加类似 mitmproxy 中 contentviews 的 Python API

### ISSUE THREAD

**Issue by cesaryuan** [reqable/reqable-app#630]
**Is your feature request related to a problem? Please describe.**

存在这样一种情况，有一个网站的API，他的请求body和相应body都是加密的，然而，我们已经通过逆向工程得到了解密算法，也就是说对于每一个请求，我们都可以通过自己编写的程序来解密他。

然而这是十分不方便的，这种情况下如果需要总览这个网站的请求都是些什么内容的话，就需要点开请求1，复制到我的程序，运行解密；点开请求2，一直到请求n；十分复杂的过程。

**Describe the solution you'd like**

因此，可以提供类似于[Mitmproxy的contentviews API](https://docs.mitmproxy.org/stable/addons-examples/#contentview)，该API实现了这样的功能，向响应体栏添加一个自定义view，该view的内容由python脚本定义，这样就可以完全解决上面的问题：通过编写python脚本，对每一个请求都进行解密然后放在custom content view中方便自己浏览。

![image](https://github.com/reqable/reqable-app/assets/35998162/1421ec8b-caa7-4221-810d-cbc6c73371a9)

**Describe alternatives you've considered**
None

**Additional context**

**Comment by MegatronKing** [comment]
print输出就行，内容会在控制台Tab视图上显示出来的。
