### ISSUE TITLE
[feature] 自动合并cookie

### ISSUE THREAD

**Issue by Soujer** [reqable/reqable-app#631]
![image](https://github.com/reqable/reqable-app/assets/43666892/8c0c8e4d-df20-44cd-aa79-ee26d01b1710)
无论是浏览器控制台 还是fd等抓包工具 cookie 都是合并的，方便直接复制到某些发包工具中直接使用！谢谢！

**Comment by MegatronKing** [comment]
请更新2.15.0版本，在Cookies标签页中可以复制合并的cookie内容。
