### ISSUE TITLE
[bug] 某些Windows程序无法被抓包

### ISSUE THREAD

**Issue by biqiguhexuenai** [reqable/reqable-app#636]
**Describe the bug**

**To Reproduce**
1. Go to 'reqable'
2. Click on '某些程序'
3. See error

**Expected behavior**
希望Windows可以抓包，浏览器啥的可以正常抓，改成socks代理也抓不到，截图是github项目catvodopen，另外希望加上像手机一样的分流机制，每次都抓一堆地址，还要按筛选很杂乱麻烦
**Screenshots**
![IMG_20240506_212644](https://github.com/reqable/reqable-app/assets/63104635/a307872d-c6d1-41c2-bd8f-d07f5f087496)

**Information**
 - Platform: [windows]
 - OS: [win10]
 - Arch: [x64]
 - App Version: [2.14.1]

**Comment by MegatronKing** [comment]
@biqiguhexuenai Reqable使用非侵入的技术方案，如果应用程序不走系统代理，那么肯定无法捕获流量。

**Comment by biqiguhexuenai** [comment]
有啥办法解决，这种的我不太熟



---原始邮件---
发件人: "Megatron ***@***.***&gt;
发送时间: 2024年5月7日(周二) 下午4:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [reqable/reqable-app] [bug] 某些Windows程序无法被抓包 (Issue #636)




 
@biqiguhexuenai Reqable使用非侵入的技术方案，如果应用程序不走系统代理，那么肯定无法捕获流量。

**Comment by MegatronKing** [comment]
发送网络请求的时候指定Reqable代理地址或者读取系统代理配置。
