### ISSUE TITLE
[bug] Windows访问google超时

### ISSUE THREAD

**Issue by qilinxinan** [reqable/reqable-app#637]
**Describe the bug**
Windows环境下安装好证书，访问大部分Https都没问题，唯独google.com不行，提示超时

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/107522343/b112c964-f863-4c5b-a5db-fe1497de94dc)

**Information**
 - Platform: windows
 - OS: 11
 - Arch: x86
 - App Version: 2.14.1.87

**Comment by MegatronKing** [comment]
肯定的啊，reqable不具备翻墙功能。

**Comment by qilinxinan** [comment]
> 肯定的啊，reqable不具备翻墙功能。

我开了clash，有影响吗？并且启动reqable后，显示证书有问题。
![image](https://github.com/reqable/reqable-app/assets/107522343/4725e7be-98d4-42d2-8703-c3995b04c9c7)

**Comment by MegatronKing** [comment]
你用二级代理，让Reqable的流量经过clash，具体方式请查看官网文档。

**Comment by qilinxinan** [comment]
> 你用二级代理，让Reqable的流量经过clash，具体方式请查看官网文档。

确实可行，nice！
