### ISSUE TITLE
[bug] cef的请求无法拦截到（嵌入浏览器的请求）

### ISSUE THREAD

**Issue by qilinxinan** [reqable/reqable-app#638]
我在wpf里使用了cef嵌入web，在web里的请求，无法在reqable里拦截到

**Comment by MegatronKing** [comment]
@qilinxinan 检查下网络请求是否会走系统代理。如果不走系统代理，需要指定到Reqable的代理服务器地址。

**Comment by qilinxinan** [comment]
明白了，cef可以设置是否走系统代理。
