### ISSUE TITLE
[bug] 生成的curl命令在许多常用的在线转代码的网站会无法转换

### ISSUE THREAD

**Issue by fyfyfy982** [reqable/reqable-app#64]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@fyfyfy982 您好，感谢反馈！请问有具体的例子吗？

**Comment by fyfyfy982** [comment]
第一个包
http://gateway.changyou.com/gateway/cyou/payment/query.json?phone_no=&amp;imei=


小熠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reqable/reqable-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月12日(星期一) 晚上9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [reqable/reqable-app] [bug] 生成的curl命令在许多常用的在线转代码的网站会无法转换 (Issue #64)





 
@fyfyfy982 您好，感谢反馈！请问有具体的例子吗？

**Comment by MegatronKing** [comment]
能否提供一个现成的无法转化的curl呢？这样更容易帮助我复现问题。

**Comment by fyfyfy982** [comment]
curl -X GET http://gateway.changyou.com/gateway/cyou/payment/query.json?phone_no=&amp;imei= -H 'User-Agent: android-async-http/1.4.4 (http://loopj.com/android-async-http)' -H 'Cookie: tgw_l7_route=63207bf00b3d53905ae331a6d8d78874' -H 'Cookie2: $Version=1' -H 'Accept-Encoding: gzip' -H 'debug: false' -H 'device_id: 28:16:7F:EE:BB:EF' -H 'user-id: 524001761304421' -H 'sign: d5b094d2bc3f5839' -H 'app-key: 1400140930701' -H 'access-sn: 19' -H 'clientVersion: 2.0' -H 'channel-id: 4001' -H 'device-id: 28:16:7F:EE:BB:EF' -H 'app_key: 1400140930701' -H 'user_id: 524001761304421' -H 'media_channel_id: 2010752002' -H 'media-channel-id: 2010752002' -H 'access_sn: 19' -H 'tag: 123123' -H 'channel_id: 4001' --http1.1
&nbsp;


小熠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月12日(星期一) 晚上10:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [reqable/reqable-app] [bug] 生成的curl命令在许多常用的在线转代码的网站会无法转换 (Issue #64)





 
能否提供一个现成的无法转化的curl呢？这样更容易帮助我复现问题。

**Comment by MegatronKing** [comment]
@fyfyfy982  v1.0.3版本去掉了--http1.1这一类的版本信息，麻烦试试是否还有问题？

**Comment by MegatronKing** [comment]
如果没有问题的话，这个issue我先关闭了
