### ISSUE TITLE
Windows 11 stopped connecting to the internet [bug] 

### ISSUE THREAD

**Issue by Aristta** [reqable/reqable-app#643]
As soon as I close Reqable, applications (almost all) stop connecting to the internet, but as soon as I reopen Reqable the connection returns. How can I fix this?

**Comment by MegatronKing** [comment]
It may be that the system proxy settings have not been reset. Although it will automatically reset when you exit Reqable, it may fail in some cases and require you to reset it manually. May I ask, which os do you have?

**Comment by Aristta** [comment]
I apologize for the long absence, I completely forgot about the open request. Yes, you were right, the issue was with the proxy settings, which did not reset automatically after exiting the program. The operating system is Windows 11 Pro, using the latest version.

**Comment by MegatronKing** [comment]
Logically, the system proxy settings will be automatically turned off when exiting the app. From the description, I can't figure out what the issue is. 

If you can provide the log file, I think it will be helpful. 

Log file was stored on `C:\Users\xxx\AppData\Roaming\Reqable\log`.

**Comment by MegatronKing** [comment]
If no log provided, I can not debug this issue.

**Comment by rutagoat** [comment]
Hello 
I am having the same issue. 

When i close the reqable my internet stop working in browser and other apps.
But when i reopen the app it still not work first i have to enable system proxy then the internet start working and then i stop the system proxy. 

I have attached the logs with issue

logs - https://gist.github.com/rutagoat/9ce9011e88295c3b9b135ce4a603e982

Please help with me this. @MegatronKing 


OS - Windows 11
Requable version - 3.0.38 (191)

**Comment by MegatronKing** [comment]
> Hello I am having the same issue.
> 
> When i close the reqable my internet stop working in browser and other apps. But when i reopen the app it still not work first i have to enable system proxy then the internet start working and then i stop the system proxy.
> 
> I have attached the logs with issue
> 
> logs - https://gist.github.com/rutagoat/9ce9011e88295c3b9b135ce4a603e982
> 
> Please help with me this. [@MegatronKing](https://github.com/MegatronKing)
> 
> OS - Windows 11 Requable version - 3.0.38 (191)

After you close Reqable app, open system settings and check whether network proxy was on or not.

**Comment by rutagoat** [comment]
> After you close Reqable app, open system settings and check whether network proxy was on or not.

Hello Thanks for the reply
To try to fix the issue with the proxy, I uninstalled the reqable. Then I reinstalled it, and now everything is working fine. After stopping the recording and closing the application, the system’s internet still works.
Thanks again for the tool.
