### ISSUE TITLE
[bug] 二级代理的一些奇怪问题

### ISSUE THREAD

**Issue by qilinxinan** [reqable/reqable-app#644]
**Describe the bug**
因为电脑安装了clash，所以使用了二级代理。
![image](https://github.com/reqable/reqable-app/assets/107522343/24eb7aeb-b007-4364-93b8-02d338d3d039)
在开启二级代理时，如果reqable是启动状态，则一切正常使用，能抓包，也能正常科学上网。

![image](https://github.com/reqable/reqable-app/assets/107522343/5ecef859-dfe9-483c-a974-722cefb79ab3)
但是如果reqable是停止状态，则部分网站无法使用。
![image](https://github.com/reqable/reqable-app/assets/107522343/50f357c3-b4d7-45f7-8da9-ed1a3bcdf7a4)

我分析了下，这部分网站的特征是局域网网站，是我在局域网另一台电脑上部署的测试网站。现在这样的效果就很繁琐，如果我停止抓包，我停止reqable还不行，必须得关闭reqable软件才行。要用时再继续打开，太繁琐。

**Information**
 - Platform: windows
 - OS: 11
 - Arch: x86-64
 - App Version: 2.14.1.87

**Comment by MegatronKing** [comment]
您好，感谢反馈。可能是二级代理服务器无法连接到测试网站部署的设备，比如二级代理服务器和测试网站部署的设备不在一个局域网内。试试下面两种方式：
- 方式1: 配置二级代理的时候，使用禁用模式，配置本地局域网请求不走二级代理。
- 方式2: 代理菜单里面把`配置回环`选项关闭。

**Comment by qilinxinan** [comment]
> 您好，感谢反馈。可能是二级代理服务器无法连接到测试网站部署的设备，比如二级代理服务器和测试网站部署的设备不在一个局域网内。试试下面两种方式：
> 
> * 方式1: 配置二级代理的时候，使用禁用模式，配置本地局域网请求不走二级代理。
> * 方式2: 代理菜单里面把`配置回环`选项关闭。

尝试
方法1，导致启动和停止状态均无法使用局域网请求。
方法2，当前配置回环选项就是未开启的（尝试了下开启，也无影响）

**Comment by qilinxinan** [comment]
目前最好的解决方法就是点极速模式，极速模式开启=关闭抓包，只能这样了

**Comment by MegatronKing** [comment]
看起来有可能是bug，能否提供下日志呢？
1. 打开Reqable设置，开启`调试日志`。
2. 复现下问题。
3. 点击Reqable底部栏5下，打开日志窗口，（复制）保存日志内容。
4. 日志内容脱敏（如果有必要的话）。
5. 关闭设置中`调试日志`开关。

**Comment by qilinxinan** [comment]
> 看起来有可能是bug，能否提供下日志呢？
> 
> 1. 打开Reqable设置，开启`调试日志`。
> 2. 复现下问题。
> 3. 点击Reqable底部栏5下，打开日志窗口，（复制）保存日志内容。
> 4. 日志内容脱敏（如果有必要的话）。
> 5. 关闭设置中`调试日志`开关。

这是复现的GIF和日志

![GIF 2024-5-11 10-27-40](https://github.com/reqable/reqable-app/assets/107522343/5b1b785f-79e0-4c83-887c-0b093ca9568e)

[reqable.log](https://github.com/reqable/reqable-app/files/15281383/reqable.log)

**Comment by MegatronKing** [comment]
感谢🙏，非常有帮助，我先定位下问题。

**Comment by C-racker** [comment]
我是退出软件也不管用，然后必须重新开关代理软件才行。

**Comment by MegatronKing** [comment]
@qilinxinan 请试试2.15.1版本，应该修复了。

**Comment by qilinxinan** [comment]
> @qilinxinan 请试试2.15.1版本，应该修复了。

可以了，nice！
