### ISSUE TITLE
[bug] 更换字体后首字符会出现方块

### ISSUE THREAD

**Issue by vesugier** [reqable/reqable-app#645]
条件:
1.非写死的字符串（会被改变的）的首个字符，且此处不能被用户修改（可编辑状态就会恢复正常显示）
2.字体非原始字体

![图片](https://github.com/reqable/reqable-app/assets/66554786/6b625e5b-bad2-46d3-aab4-a1cb73ab12a2)

**Comment by MegatronKing** [comment]
2.15.1已经修复。
