### ISSUE TITLE
[bug] 只读？脚本无法更改

### ISSUE THREAD

**Issue by fuckgithubh** [reqable/reqable-app#647]
![image](https://github.com/reqable/reqable-app/assets/31642056/6205d5ce-fb4e-4fdb-80f2-6a80248eff12)

**Comment by MegatronKing** [comment]
context里面这些都是只读的，可以在`request`类里面修改请求path和query。

**Comment by fuckgithubh** [comment]
我想更改host @MegatronKing

**Comment by MegatronKing** [comment]
通过镜像功能修改host。脚本运行的时候表示已经和服务器开始数据通信了，host已经确定。

**Comment by fuckgithubh** [comment]
重定向先还是脚本先发生 @MegatronKing

**Comment by MegatronKing** [comment]
302这种重定向？还是功能重写重定向？

**Comment by fuckgithubh** [comment]
功能重写@ @MegatronKing

**Comment by MegatronKing** [comment]
重写、断点、脚本，先后是这个顺序
