### ISSUE TITLE
[bug] windows 10 配置了配置回环 还是监听不到本地的127.0.0.1的服务信息

### ISSUE THREAD

**Issue by starsBugs** [reqable/reqable-app#651]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: windows
 - OS: [e.g. 12.1]
 - Arch: x86-64
 - App Version: 2.15.1

**Comment by starsBugs** [comment]
![image](https://github.com/reqable/reqable-app/assets/57882716/d444897e-35e4-4c4e-8a99-22740b2e2094)

**Comment by MegatronKing** [comment]
@starsBugs 你好，能打开系统网络代理设置截个图看看吗？

**Comment by starsBugs** [comment]
![image](https://github.com/reqable/reqable-app/assets/57882716/60733187-2dbb-4e0d-a436-137138bf1ca9)

**Comment by starsBugs** [comment]
抱歉，是我切换了软件代理的地址导致的

**Comment by starsBugs** [comment]
![image](https://github.com/reqable/reqable-app/assets/57882716/e061ecb2-6537-4b24-bf07-6996ff7ca532)
切换127.0.0.1就可以了
