### ISSUE TITLE
[bug] MAC M2 关闭一个API就闪退

### ISSUE THREAD

**Issue by Tlaeld** [reqable/reqable-app#652]
只要对一个未保存的API进行操作就闪退，无论是保存，取消还是不保存
[Reqable-2024-05-16-175152.ips.zip](https://github.com/reqable/reqable-app/files/15333016/Reqable-2024-05-16-175152.ips.zip)

**Comment by MegatronKing** [comment]
感谢反馈，同 #622 ，目前几例反馈都是Mac M系列14.4.1版本。

**Comment by MegatronKing** [comment]
@Tlaeld 有开着类似keyboardholder的输入辅助工具吗？目前有反馈类似软件会导致Reqable闪退。

**Comment by Tlaeld** [comment]
有使用Input Source Pro，经检查确实是该软件导致的闪退
