### ISSUE TITLE
[bug] 请求头字符导致编辑问题

### ISSUE THREAD

**Issue by HdShare** [reqable/reqable-app#654]
**Describe the bug**
创建请求失败: FormatException: 
Invalid HTTP header value: "language=中文（广西，简体）"(at character 10)
language=中文（广西，简体）

**To Reproduce**
1. 抓包后的调试列表
2. 右键菜单-编辑

**Expected behavior**
正常转到Api界面进行发送

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/49312623/edef4d88-3aa2-4eba-a372-c67497687abb)
![image](https://github.com/reqable/reqable-app/assets/49312623/08385ec5-0f5f-4b25-bf80-dbf54dcf79fb)

**Information**
 - Platform: windows
 - OS: 10
 - Arch: x86-64
 - App Version: 2.15.1

**Comment by MegatronKing** [comment]
2.16.0版本创建API请求时已不再校验是否包含非ASCII字符。
