### ISSUE TITLE
[bug] ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by zdzym** [reqable/reqable-app#656]
**Describe the bug**
开启代理访问某些网站提示 ERR_HTTP2_PROTOCOL_ERROR

**To Reproduce**
1. 开始监听，配置系统代理
2. 访问 https://[www.minecraft.net](https://www.minecraft.net/zh-hans/15th-anniversary?mcRef=redeemCape)/zh-hans/15th-anniversary?mcRef=redeemCape
3. 无法打开网页，提示 ERR_HTTP2_PROTOCOL_ERROR
4. 关闭系统代理，一切正常

**Expected behavior**
正常抓包

**Screenshots**

**Information**
 - Platform: Windows 10
 - Arch: x86-64
 - App Version: 2.16.0

**Comment by MegatronKing** [comment]
感谢反馈，能够复现这个问题，下个版本修复。

**Comment by MegatronKing** [comment]
v2.17.0已经修复此问题。

**Comment by jsrcode** [comment]
> 感谢反馈，能够复现这个问题，下个版本修复。

再次出现这个问题 且具有随机性 net::ERR_HTTP2_PROTOCOL_ERROR
