### ISSUE TITLE
[bug] 提供合并cookie的选项

### ISSUE THREAD

**Issue by ZH-RR** [reqable/reqable-app#658]
cookie: _octo=GH
cookie: _device_id=73a
cookie: saved_user_sessions=9236
cookie: user_session=O5Zq
cookie: __Host-user_session_same_site=O5Zq
cookie: logged_in=yes
cookie: dotcom_user=ZH-RR

**Comment by ZH-RR** [comment]
> cookie: _octo=GH1 cookie: _device_id=73a cookie: saved_user_sessions=92368510%3VBl cookie: user_session=O cookie: __Host-user_session_same_site=O5Zq cookie: logged_in=yes cookie: dotcom_user=ZH-RR

**Comment by ZH-RR** [comment]
![Uploading M11FWA]6{JR(N%EU8R44L%H.png…]()

**Comment by MegatronKing** [comment]
这不是bug，多个cookie是正常的。

**Comment by KeepEcho** [comment]
不是bug ，但是希望是合并到一个字段里面去，这样 在其他程序调用很方便。目前的这样的形式，不方便使用。

**Comment by MegatronKing** [comment]
v2.18.1版本Cookie视图已支持合并或拆分。
