### ISSUE TITLE
[bug] 严重性能问题。

### ISSUE THREAD

**Issue by lsdlh** [reqable/reqable-app#66]
**Describe the bug**
cup满载

**To Reproduce**
抓了一会包，使用了脚本，重写，重放，cup占用就满了，停止抓包也是cpu满的。并且这个时候退出CPU不占用了，但无法再次启动，Reqable.exe文件还是被占用，文件解锁后才能启动

**Expected behavior**
正常占用，正常启动

**Screenshots**
https://pic.ziyuan.wang/2023/06/13/90b6036e60b47.png

**Information**
 - Platform: [windows]
 - OS: [e.g. 10]
 - Arch: [e.g. x86-64]
 - App Version: [e.g. 1.0.2（18）（x86_64）]

**Comment by MegatronKing** [comment]
v1.0.3版本做了性能优化，可以试一下是否还有问题。

**Comment by MegatronKing** [comment]
如果没有问题了，这个issue我先关闭了。
