### ISSUE TITLE
Add rewrite request/response feature!

### ISSUE THREAD

**Issue by IamLoot** [reqable/reqable-app#660]
I know your previous app (HttpCanary) faced many troubles because of this rewrite functionality. I'm suggesting you release a separate build for this that supports rewrite functionality for standalone Android apps. It would be great if you could release a clone build that supports the rewrite functionality standalone and it should be released only in GitHub as this again may be against Google Play policy.

**Comment by MegatronKing** [comment]
Thanks for the suggestion, but there are no plans for this at the moment.
