### ISSUE TITLE
capture on android14

### ISSUE THREAD

**Issue by terminatortor** [reqable/reqable-app#664]
How does the program solve the problem of packet capture on Android 14? The certificate always fails to install, and the method of installing the certificate under the Android 13 system no longer works.

**Comment by MegatronKing** [comment]
@terminatortor Hi, system certificate and user certificate, which you mean?

**Comment by terminatortor** [comment]
system certificate
I push the certificate in system/etc/security/cacerts directory and granted 777 permission, but the Android 14 phone can not recognize it, so the app always prompts that the certificate is not recognized, and the traffic can be caught, but there is no data, and the traffic is always connect type

**Comment by MegatronKing** [comment]
Same as #594,  Android 14 have moved cacerts to /apex. Maybe you should try magisk module to install system ca cert.
