### ISSUE TITLE
android版app 开启抓包后微信小程序点击后显示运行环境加载失败(2,101)

### ISSUE THREAD

**Issue by lppyyy** [reqable/reqable-app#665]
android版app 开启抓包后微信小程序点击后显示运行环境加载失败(2,101)
师傅 这个需要怎么解决呀

**Comment by MegatronKing** [comment]
抱歉，这个我也不懂，但是这应该不是Reqable的问题。

**Comment by yanecc** [comment]
应该还是Reqable的问题，使用其他抓包软件（如ProxyPin）代理安卓设备，能正常访问微信小程序并捕获http请求

**Comment by MegatronKing** [comment]
@yanecc @lppyyy 

更新到最新2.17.0试试，如果觉得自己环境没有问题，按照下面的操作提供下日志我看看。

1. 点击侧边栏 + 打开Reqable设置，开启调试日志。
2. 复现下问题。
3. 侧边栏长按logo，打开日志窗口，导出日志内容贴到这里。
4. 日志内容脱敏（如果有必要的话）。
5. 关闭设置中调试日志开关（打开日志会影响App性能）。
