### ISSUE TITLE
[feature] 如何用脚本修改body响应

### ISSUE THREAD

**Issue by lsdlh** [reqable/reqable-app#67]
响应是一个json,我想修改json某些字段的值，我直接这样修改response.body["data"]="222"会报错'CaptureHttpBody' object is not subscriptable

**Comment by MegatronKing** [comment]
你需要用json解析response.body.payload成dict，然后把新的json转成字符串使用response.body.text()设置回去

**Comment by lsdlh** [comment]
response.body.payload报错了
16:49:02.219: Traceback (most recent call last):
16:49:02.220:   File "main.py", line 43, in <module>
16:49:02.220:     main()
  File "main.py", line 14, in main
16:49:02.220:     onResponse(argv[1])
  File "main.py", line 32, in onResponse
    dictionary = json.load(content)
  File "D:\ProgramData\Anaconda3\lib\json\__init__.py", line 293, in load
16:49:02.220:     return loads(fp.read(),
16:49:02.221: UnicodeDecodeError: 'gbk' codec can't decode byte 0x90 in position 4979: illegal multibyte sequence

**Comment by MegatronKing** [comment]
response.body.payload确定是字符串吗

**Comment by MegatronKing** [comment]
下个版本Reqable会提供直接操作json数据的api，这样可以方便进行json数据的处理

**Comment by lsdlh** [comment]
> response.body.payload确定是字符串吗，另外编码默认都是utf-8

是字符串，里面有中文

**Comment by MegatronKing** [comment]
我刚刚测试即使有中文也没问题，能提供下具体的脚本代码吗

**Comment by MegatronKing** [comment]
下个新版本提供的json相关的api是这样的：
```
response.body.jsonify()
response.body['data'] = '123'
response.body['headers']['accept'] = {
   'a': '123'
}
```
不知道是否能够满足你的需要

**Comment by lsdlh** [comment]
> 我刚刚测试即使有中文也没问题，能提供下具体的脚本代码吗
又测了一下不是response.body.payload问题，我脚本里什么都没写都会有这个不错，但别的请求用脚本就没问题，我用的anaconda创建的环境，换了个py3.8也这样

**Comment by MegatronKing** [comment]
v1.0.3版本已实现对json的支持。
