### ISSUE TITLE
windows无法识别出python环境，自定义python环境无效

### ISSUE THREAD

**Issue by guodf** [reqable/reqable-app#672]
**Describe the bug**
设置自定义python3目录，不能发现python

**To Reproduce**
1. 启用脚本功能
2. 输入自定义python环境

**Expected behavior**

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/7540349/88b2addb-c5a3-4313-9cbc-6cbf9b795735)

**Information**
 - Platform: Windows11
 - OS: Windows11 23H2
 - Arch: x86-64
 - App Version: 2.16.0

**Comment by MegatronKing** [comment]
你好，感谢反馈。
1. 提供下日志我看看，目录在：`C:\Users\xxx\AppData\Roaming\Reqable\log`。
2. 试试这个脚本输出什么：
```python3
import subprocess

# 使用subprocess运行命令，并捕获输出
output = subprocess.check_output(['python', '-V'], stderr=subprocess.STDOUT)

# 解码输出并提取版本号
output = output.decode()


print("Python版本号:", output)
```

**Comment by guodf** [comment]
@MegatronKing 
[20240523113716-bffa3dd0-18b5-11ef-9d74-f70815a70c04.log](https://github.com/reqable/reqable-app/files/15428161/20240523113716-bffa3dd0-18b5-11ef-9d74-f70815a70c04.log)
![image](https://github.com/reqable/reqable-app/assets/7540349/e0faa11b-afac-4b39-9f63-cb1b53298ccb)

**Comment by MegatronKing** [comment]
感谢提供信息，这个问题将在下个版本修复。

**Comment by MegatronKing** [comment]
v2.17.0版本已经修复。
