### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by CAI5201314** [reqable/reqable-app#674]
最新win电脑版，搞不懂为什么老是自动变成系统代理未设置，自动启用我没开启，抓几个数据就变黄色了

**Comment by CAI5201314** [comment]
必须关掉ClashVerge才行

**Comment by MegatronKing** [comment]
clash在抢系统代理，所以这个问题不是reqable的问题。

**Comment by MarkLily** [comment]
两者不可兼得吗？必须开一个关一个？
