### ISSUE TITLE
[bug] 工作台，应用程序固定后没有置顶

### ISSUE THREAD

**Issue by freedomfly666** [reqable/reqable-app#675]
**Describe the bug**
操作：工作台 -> 应用程序 -> 右键 -> 固定 
bug：应用程序没有置顶。但是域名固定后，可以置顶

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/16679590/42084889-ddb6-40df-839e-3da0815e8578)

**Information**
 - Platform: windows
 - OS: windows 10
 - Arch: x86-64
 - App Version: lastest

**Comment by MegatronKing** [comment]
@freedomfly666  感谢反馈，v2.17.0已经修复。
