### ISSUE TITLE
[bug] 逍遥模拟器，安装了证书为什么还提示“不是私密连接”

### ISSUE THREAD

**Issue by fangao888** [reqable/reqable-app#679]
俺是新手，都配置完了为啥打开https网页还提示不是私密连接
![QQ截图20240525234424](https://github.com/reqable/reqable-app/assets/57599569/703fc7f3-8e9f-4f07-805d-0adea06157a9)
![QQ截图20240525234443](https://github.com/reqable/reqable-app/assets/57599569/44ec4fa7-45be-4699-8658-81f1b5a45fe5)
![QQ截图20240525234516](https://github.com/reqable/reqable-app/assets/57599569/883391c1-44fa-4c1e-80f3-1a840bc1e7a1)

**Comment by MegatronKing** [comment]
使用电脑抓包请安装电脑的证书。
