### ISSUE TITLE
[bug] Internet connection is lost when reqable is activated. (game)

### ISSUE THREAD

**Issue by IlluminatiWave** [reqable/reqable-app#682]
**Describe the bug**
When I activate the app, the application loses access. This does not happen with other apps (like youtube).

**To Reproduce**
1. Activate packet capture
2. Open the game
3. The game rejects the connection to the server (when the direct connection to the server appears, the game has 2 stages, the login and the direct connection to the server, you can pass the login, but not the connection to the game servers (it says error 4001:110).

When using other apps (Pcapdroid) this does not happen, but unfortunately, having ssl connections, the only thing I get are encrypted packets.

**Expected behavior**
The game starts normally (when disabling traffic capture, the game starts normally, but inside the game, when trying to access any content, the game starts dialing as if it needs an internet connection).

**Screenshots**

**Information**
 - Platform: Android
 - OS: 13.0
 - Arch: arm64
 - App Version: 2.16.1

**Comment by MegatronKing** [comment]
Thanks for feedback. I need logs to troubleshot, please follow the steps and upload log file here.
- Turn on 'Netbare Log' in app settings.
- Reproduce the bug.
- Long press logo icon in the side menu.
- Export the log and attach to here.

**Comment by MegatronKing** [comment]
@IlluminatiWave Hello, if no log file is provided, I will close this issue.
