### ISSUE TITLE
[feature] 在安卓版本增加IPv6支持

### ISSUE THREAD

**Issue by XiaoTong6666** [reqable/reqable-app#684]
您好作者

我的设备是基于Android11的LineageOS18.1

使用的Reqable版本是2.16.1

当我使用Magisk刷入证书模块并且配置好证书后使用VPN记录模式进行启动（应用程序仅via浏览器，换成firefox，termux问题也一样）并且可以正常抓取ipv4的数据包，当我在浏览器尝试访问ipv6网站的时候出现net::ERR_INTERNET_DISCONNECTED错误，但是关掉Reqable后又可以正常访问。

在错误期间Reqable并没有记录我对ipv6站的请求，我也尝试使用termux的curl -x 127.0.0.1:9000 6.ipw.cn之类的通过reqable提供的http-proxy可以正常对数据包的抓取

其他的VPN软件比如我最常用的V2rayNG是可以正常代理IPv6的，而reqable的VPN似乎不能代理

下图为termux的curl的输出，包含问题所在
![2236d1e81f58207b](https://github.com/reqable/reqable-app/assets/110387028/6e61330d-d596-431d-a2ef-9419e7276243)

**Comment by MegatronKing** [comment]
v2.17.0已经支持IPv6。
