### ISSUE TITLE
[bug] 抓包和发请求的Cookie功能太割裂，无法通用

### ISSUE THREAD

**Issue by LarkinZero** [reqable/reqable-app#686]
**Describe the bug**
1. 抓包的cookie，不是以合并的方式展示的。想整个复制太麻烦，在Cookie页整个复制，没有用`;`连起来。还得自己手动加
2. 发请求的时候，是不是也能加个Cookie页？

**Comment by MegatronKing** [comment]
@LarkinZero 感谢反馈。

> 在Cookie页整个复制，没有用;连起来

不知道你用的是哪个版本，新版本cookie页复制是自动连起来的，不需要手动修改。


> 发请求的时候，是不是也能加个Cookie页？

发请求Cookie是自动从CookieJar中带入的，没有单独的Cookie页。

**Comment by LarkinZero** [comment]
升级最新版后可以了
