### ISSUE TITLE
默认不要开启全局代理，被坑了好几次了，关了软件还是会存在全局代理[bug] 

### ISSUE THREAD

**Issue by 23-RunWang** [reqable/reqable-app#687]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
你可以在`代理`菜单中关闭`自动启用`。首次启动App时候，如果选择了流量分析场景模式，默认自动开启系统代理。
