### ISSUE TITLE
安卓14版本 没root的话真的不能抓到ssl协议的流量吗

### ISSUE THREAD

**Issue by haohaode11** [reqable/reqable-app#688]
现有安卓14版本  小米14手机 （未ROOT）  reqable版本2.16.1  已经将CA证书安装至用户目录  但是抓取某些APP的时候直接就是没网络 应该是ssl握手失败导致

**Comment by MegatronKing** [comment]
正常的，android 7.0之后不信任用户目录下的证书。

**Comment by haohaode11** [comment]
> 正常的，android 7.0之后不信任用户目录下的证书。

那这种情况不root就没办法抓了吗
