### ISSUE TITLE
[feature] 有没有办法支持底层 TCP 协议 ( 非HTTP ) 流量包

### ISSUE THREAD

**Issue by biggerstar** [reqable/reqable-app#689]
我发现有部分没有使用 `HTTP[S]` 协议的软件似乎是抓不到包的， 但是 `wireshark` 能抓到，
看了下似乎走的是更底层的 TCP 协议

因为不喜欢鲨鱼的界面，并且对 reqable 的未来发展很期待，希望作者能研究下 TCP 流量截取的可行性

**Comment by biggerstar** [comment]
忘记说了， 上面提到有关 TCP 的问题是指的 PC版本

另外在使用过程中觉得还有一个优化的点( PC端 )
当请求加载的图片很多时， 很影响接口的筛选
我这边有个想法， 比如在请求类型筛选时
1. (软件已实现) 单击鼠标左键可以选择例如 json http1 可以筛选
2. ( 新特性 )  单击鼠标右键时可以排除某种类型， 比如在 image选项卡 单击右键排除图片的请求

**Comment by MegatronKing** [comment]
- Reqable目前主要就是处理HTTP协议，其他TCP/UDP协议都是不处理的。
- 筛选这个功能后面会优化的。

**Comment by MegatronKing** [comment]
TCP不在reqable的支持范围内，所以这个问题我先关闭了。

**Comment by ArtificialIdoit** [comment]
现在支持了吗

**Comment by hoey94** [comment]
用wireshark吧
