### ISSUE TITLE
[bug] url域名和请求报文中的Host域名可能出现不一致的情况

### ISSUE THREAD

**Issue by gwhcn** [reqable/reqable-app#691]
**Describe the bug**
应用启动后假设同时请求m.baidu.com和app.baidu.com域名接口。m.baidu.com优先请求，之后app.baidu.com请求在抓包软件中url可能被替换成m.baidu.com，请求报文Host域名仍然是app.baidu.com，请求结果404。

这个情况在Requble和Proxyman都有，在Charlis没有任何问题。

**To Reproduce**
1. 鸿蒙Next系统，为了抓包方便在拦截器中全部切换成http请求，config.url = config.url?.replace('https', 'http')，写了就会出现url域名和Host域名不一致的情况。应用中日志和断点排查请求正常，应用中没有替换url的域名，并且使用Charlis没有问题。

**Screenshots**
![screenshot-20240531-162945](https://github.com/reqable/reqable-app/assets/20394691/5f32d16d-d90b-44d6-ae19-1e144971cf53)

**Comment by MegatronKing** [comment]
@gwhcn 感谢建议，这个问题将在下个版本修复。

**Comment by MegatronKing** [comment]
Fixed on v2.17.0.
