### ISSUE TITLE
[bug] Failed to save file, please manually delete Reqable directory

### ISSUE THREAD

**Issue by remixer-dec** [reqable/reqable-app#693]
**Describe the bug**
Certificate export does not work

**To Reproduce**
1. Go to Certificate setup
2. Click on the arrow or the filename
3. See error "Failed to save file, please manually delete ..."
4. Manually deleting the directory does not help. All other export options also do not work. Storage permission is granted (but only with access to media files, it is the only option in settings, maybe requesting access to all files can avoid this)

**Expected behavior**
File should be saved and exported correctly. 

**Information**
 - Platform: Android
 - OS: 11
 - Arch: arm64
 - App Version: 2.16.1

**Comment by remixer-dec** [comment]
Downgraded to [2.11.1](https://github.com/reqable/reqable-app/releases/tag/2.11.1) it has an option to download certificate via browser which works fine.

**Comment by MegatronKing** [comment]
Access to all files violates Google Play's policy. This issue because reqable is uninstalled and reinstalled, and reqable cannot overwrite the previous files. You can manually delete the previous files.

Btw, I have added the browser option on the latest v2.17.0 app.

**Comment by remixer-dec** [comment]
Thanks for an alternative solution! No, the issue is not caused by prev. version, I never had previous version on this device, the directory was completely empty when I tried it after all the clicks, removing it did not help. It is probably [restrictions](https://developer.android.com/about/versions/11/privacy/storage) of specific Android version. 
> Starting in Android 11, apps cannot create their own app-specific directory on external storage. 

Usually to access specific directories apps call ACTION_OPEN_DOCUMENT_TREE first.
