### ISSUE TITLE
[feature] 期望请求header中 cookie能够合并为一个字段

### ISSUE THREAD

**Issue by KeepEcho** [reqable/reqable-app#695]
目前在http请求种 cookie被分解成了N个字段，在导入python处理就很麻烦。要写个专门的函数来处理合并为一个。
希望能改善下这块。跟正常的类似 Fiddler 一样，cookie的值就是一个合并好的字符串，用 ; 来分割的。

**Comment by MegatronKing** [comment]
@KeepEcho `cookie被分解成了N个字段` 原始数据就是多个Cookie分离的，不是Reqable自己分离的。如果你需要合并的Cookie值，可以点击复制图标获取。

**Comment by MegatronKing** [comment]
同 #658
