### ISSUE TITLE
[question] 请问 Reqable 的多窗口是怎么实现的？

### ISSUE THREAD

**Issue by Ferry-200** [reqable/reqable-app#696]
如题。是类似于社区的 [desktop_multi_window](https://pub.dev/packages/desktop_multi_window)  另外启动一个 Flutter 实例的方案，还是别的方案呢？

Windows 下打开设置窗口就多增加 40 多MB 的内存，感觉应该是第一种🤔

**Comment by MegatronKing** [comment]
就是[desktop_multi_window](https://pub.dev/packages/desktop_multi_window)这个方案，定制了下

**Comment by Ferry-200** [comment]
好的，谢谢😘
