### ISSUE TITLE
[bug] 在pixel5 redfin 13 系统下，证书识别不到，证书已经在系统目录里还是不行。

### ISSUE THREAD

**Issue by xgj1988** [reqable/reqable-app#697]
**Describe the bug**
在pixel5 redfin 13 系统下，证书识别不到，证书已经在系统目录里还是不行。

**To Reproduce**
在pixel5 redfin 13 系统下，证书识别不到，证书已经在系统目录里还是不行。

**Expected behavior**
应该可以抓包才对，不知道哪里的问题

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/8272614/b9990bc1-ec4d-4f40-9198-e7a9947dbe97)
![image](https://github.com/reqable/reqable-app/assets/8272614/4a77577c-fdb6-402c-8846-9db8ef24bc1c)
![image](https://github.com/reqable/reqable-app/assets/8272614/fa0932a3-743a-4af1-bc20-d4c0b7eccf62)
![image](https://github.com/reqable/reqable-app/assets/8272614/d822faf6-3566-4129-96d1-57e0214853e8)

**Information**
 - Platform: android
 - OS:  13
 - Arch:arm64
 - App Version: 3.0.10

**Comment by MegatronKing** [comment]
证书问题需要你自己去排错，这个和reqable其实没什么关系的。

**Comment by MegatronKing** [comment]
补充一下，手机Chrome内核浏览器抓包请将证书安装到用户目录，安装到系统目录证书CT验证会失败。

Chrome (and subsequently many other Chromium-based browsers) has recently started requiring Certificate Transparency logs for CA certs found in the system certificate store.
