### ISSUE TITLE
[feature] 如何让 reqable 只抓去 手机的包，把windows 的关掉，类似charles的 windows proxy选项

### ISSUE THREAD

**Issue by xgj1988** [reqable/reqable-app#701]
![image](https://github.com/reqable/reqable-app/assets/8272614/bc2465a3-2d82-4c64-94d6-a1e9fe6c9c9c)

参考 charles 的这个设置。。因为有时候包太多了。
还有就是；
是否增加根据应用程序，服务器IP进行过滤吗？

**Comment by MegatronKing** [comment]
你好，感谢反馈。

> 是否增加根据应用程序，服务器IP进行过滤吗？

请打开侧边栏。

**Comment by MegatronKing** [comment]
> 类似charles的 windows proxy选项

你把Reqable顶部的盾牌图标点掉就行，或者在`代理`菜单中操作。

**Comment by xgj1988** [comment]
![image](https://github.com/reqable/reqable-app/assets/8272614/f31db7d7-d7f9-43a2-b3a4-88cb83d32dc4)
这个吗？
