### ISSUE TITLE
[bug] 复制cURL单引号未转义

### ISSUE THREAD

**Issue by rex-chang** [reqable/reqable-app#702]
**Describe the bug**
gen curl request error.

**To Reproduce**
1. Go to ' 集合'
2. Click on '请求Tab'
3. 当请求Method 为 POST, ContentType 为 json, json 内容中有 `'` 时, 复制为 curl 请求, 字符未转义.

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@rex-chang 感谢反馈，v2.18.0已经修复。
