### ISSUE TITLE
[feature] 一些使用体验改进的建议

### ISSUE THREAD

**Issue by gyunlyun** [reqable/reqable-app#703]
## 环境
应用版本：2.17.0
操作系统：Windows 11

*** 
### 现有情况
当布局一致的情况下，调试页面的请求/响应布局为水平。
![image](https://github.com/reqable/reqable-app/assets/111403418/36132209-8f44-467c-9f6b-71de5d596661)
编辑页面为垂直。
![image](https://github.com/reqable/reqable-app/assets/111403418/238f0f51-7d60-4d54-a8fd-92a6a22c2721)
### 期望情况
当布局一致的情况下请求/响应布局始终与全局布局一致，均为垂直/水平。

***
### 现有情况
当光标焦点在请求/响应详情上时，不能通过快捷键进入编辑此条流量记录。
![image](https://github.com/reqable/reqable-app/assets/111403418/707a3ef3-b85d-4476-9a23-ed0e35fb265d)
### 期望情况
光标在流量记录/流量详情上时，能够通过快捷键进入编辑。

***
### 现有情况
快捷键固定，不符合个人习惯。
### 期望情况
常用功能快捷键支持自定义，比如编辑、 重发等。

***
### 现有情况
右击调试关闭其他，需要单个确认所有API是否保存。
![image](https://github.com/reqable/reqable-app/assets/111403418/b815b8e5-3882-4610-9183-6dbd7621dddf)
### 期望情况
允许直接保存或不保存。

**Comment by MegatronKing** [comment]
@gyunlyun 忘记回复了，非常抱歉。

首先，感谢您的建议，我依次回复下。

> 保持调试和编辑页面的请求/响应布局一致。

水平和垂直，看的是整体布局，不是请求和响应布局。这个需求见仁见智，暂时不会做变化。

> 当光标焦点在请求/响应详情上时，不能通过快捷键进入编辑此条流量记录。

我测试是可以通过快捷键创建API编辑的，你可以更新到最新版本再试试。

> 支持自定义快捷键。

这个尚不支持，后面有空会实现的，优先级不高。

> 关闭API时支持一次性（不）保存所有API。

右键Tab可以强制关闭所有/其他Tab的，如果没看到请更新到最新版本。

**Comment by gyunlyun** [comment]
> @gyunlyun 忘记回复了，非常抱歉。
> 
> 首先，感谢您的建议，我依次回复下。
> 
> > 保持调试和编辑页面的请求/响应布局一致。
> 
> 水平和垂直，看的是整体布局，不是请求和响应布局。这个需求见仁见智，暂时不会做变化。
> 
> > 当光标焦点在请求/响应详情上时，不能通过快捷键进入编辑此条流量记录。
> 
> 我测试是可以通过快捷键创建API编辑的，你可以更新到最新版本再试试。
> 
> > 支持自定义快捷键。
> 
> 这个尚不支持，后面有空会实现的，优先级不高。
> 
> > 关闭API时支持一次性（不）保存所有API。
> 
> 右键Tab可以强制关闭所有/其他Tab的，如果没看到请更新到最新版本。

好的，部分需求是个人习惯现在已经适应了；提到的需求功能也都已经实现了，目前使用的最新版已经没有这些问题。
很棒的产品，加油💪。
