### ISSUE TITLE
[bug] 在 `2.17.0` 版本后 MuMu模拟器12 无法正常抓包

### ISSUE THREAD

**Issue by GuangChen2333** [reqable/reqable-app#707]
**Describe the bug**
在 Reqable `2.17.0` 版本后 MuMu模拟器12 无法正常抓包。

在确认证书安装完成后，在 `VPN` 模式下，目标应用无法正常联网 且 调试面板内仅有 `DNS` 数据包。

在确认该问题后，我尝试了不同架构下的安装包，该问题均出现。

在回滚到 `2.16.1` 版本且安装了 `magic service` 后，该问题解决。

**To Reproduce**
1. 安装 [MuMu 模拟器12](https://adl.netease.com/d/g/mumu/c/gw_mumu12?type=pc&direct=1)
2. 安装 [云·星穹铁道](https://autopatchcn.bhsr.com/client/cn/20240425223601_Mh1fhzqWdL6e11cp/gw/StarRail_2.2.0.apk)
3. 安装 Reqable `v2.17.0`
4. 按照正常步骤抓包
5. 该问题出现

**Expected behavior**

**Screenshots**

**Information**
 - Platform: Android
 - OS: Android 12
 - Arch: aarch64
 - App Version: 2.17.0

**Comment by MegatronKing** [comment]
@GuangChen2333 试试最新的2.19.0版本？

**Comment by GuangChen2333** [comment]
OK，修复了大抵是。
