### ISSUE TITLE
[bug] 开启脚本后，会自动对原请求参数值进行URL解码处理，导致出错

### ISSUE THREAD

**Issue by KeepEcho** [reqable/reqable-app#709]
**Describe the bug**
在开启脚本后，再次请求中。
软件对原请求URL中的参数值会自动进行URL解码，参数中包含已经被编码的内容会还原，
导致请求出错。

**To Reproduce**
1. IOS手机与WIN客户端交互
2. 抓包App 小红书
3. 未开启脚本前，一切都正常，手机端刷新等返回200。可以刷新首页feed流
4. 开启脚本后，一直返回406错误。
5. 反复对比发现是2次请求的一个固定参数，在开启脚本后，里面的值被URL解码处理了。
![image](https://github.com/reqable/reqable-app/assets/171533549/95d0535d-a6ad-4f87-9403-b61922558001)
导致每次请求出错。

eg：
原始请求为：
/api/sns/v6/homefeed?client_volume=0.2&geo=eyJsYXRpdHVkZSI6MjIuOTM3MDMyNjE3MjkwMjUsImxvbmdpdHVkZSI6MTEzLjM0MTk5MDExMzQyMn0%3D
开启脚本后变为：
/api/sns/v6/homefeed?client_volume=0.2&geo=eyJsYXRpdHVkZSI6MjIuOTM3MDMyNjE3MjkwMjUsImxvbmdpdHVkZSI6MTEzLjM0MTk5MDExMzQyMn0=

不开启脚本，一切正常，只要开启脚本就出错。

**Expected behavior**

**Screenshots**
![image](https://github.com/reqable/reqable-app/assets/171533549/95d0535d-a6ad-4f87-9403-b61922558001)

**Information**
 - Platform: windows & ios 
 - OS: 11 
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@KeepEcho 感谢反馈，v2.18.0已经修复。
