### ISSUE TITLE
[feature] Support mobile platforms

### ISSUE THREAD

**Issue by kios123** [reqable/reqable-app#71]
挺期待安卓版本的，什么时候可以下载？

**Comment by MegatronKing** [comment]
目前重心在桌面端，移动端排期仍然待定。

**Comment by JiaLeDe** [comment]
> 目前重心在桌面端，移动端排期仍然待定。

我可以提供资金支持

**Comment by MegatronKing** [comment]
> > 目前重心在桌面端，移动端排期仍然待定。
> 
> 我可以提供资金支持

非常感谢，按照公布的计划，移动端App将作为桌面端的赠品，如果您订阅了就是对我们项目的支持。

**Comment by JiaLeDe** [comment]
> > > 目前重心在桌面端，移动端排期仍然待定。
> > 
> > 
> > 我可以提供资金支持
> 
> 非常感谢，按照公布的计划，移动端App将作为桌面端的赠品，如果您订阅了就是对我们项目的支持。

嘿嘿，可以给个优惠券嘛？370263995@qq.com

**Comment by MegatronKing** [comment]
已完成。
