### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by hashinami46** [reqable/reqable-app#712]
**Describe the bug**
Installed system cert using kernelsu, but the app couldn't recognized it.

**To Reproduce**
1. Install cert installer using kernelsu.
2. Open Reqable.
3. Cert is not installed.

**Screenshots**
![Screenshot_2024-06-12-09-41-54-978_com.android.settings-edit.jpg](https://github.com/reqable/reqable-app/assets/127002966/b239932a-33e0-4ad2-b8e9-913192a30c5f)
![Screenshot_2024-06-12-09-42-12-445_com.reqable.android-edit.jpg](https://github.com/reqable/reqable-app/assets/127002966/1a8b524b-cb16-43d1-8086-14ede3a35398)

**Information**
 - Platform: Android (Redmi note 11)
 - OS: Android 13
 - Arch: aarch64
 - App Version: 2.18.0

**Comment by MegatronKing** [comment]
If the certificate is not installed successfully, please check below.
- The correct certificates are installed.
- Magsik module usage is correct.
- Root permissions granted.
- The device has rebooted.

I will close this as it is not a reqable issue.
