### ISSUE TITLE
无法设置系统代理

### ISSUE THREAD

**Issue by GoldenTag** [reqable/reqable-app#713]
系统代理那个按钮点击后过一两秒就变黄色，一直不生效。
Mac m1pro   2.18.0版本

**Comment by MegatronKing** [comment]
@GoldenTag `代理`菜单里面有个`代理辅助工具`安装了吗？

**Comment by MegatronKing** [comment]
@GoldenTag 请问还有问题吗？

**Comment by MegatronKing** [comment]
如果没有问题，这个issue我关闭了。

**Comment by itzhoujun** [comment]
我也相同的问题。安装代理辅助工具之后重启应用就ok了。不过这个操作太隐蔽了。
