### ISSUE TITLE
[feature] 调试列表搜索添加支持`非`逻辑

### ISSUE THREAD

**Issue by yuehun** [reqable/reqable-app#715]
过滤掉指定类型的，过滤掉指定进程的，
比如过滤掉jpg类型的，过滤掉包含xxx文本的

**Comment by MegatronKing** [comment]
已有过滤功能

**Comment by yuehun** [comment]
![微信截图_20240616154545](https://github.com/reqable/reqable-app/assets/24507941/90ec585a-cb01-45c9-b5c6-d88278ee0ae3)
是指的这个搜索吗

**Comment by MegatronKing** [comment]
对

**Comment by WankkoRee** [comment]
但是现在的搜索功能不支持排除规则，无法满足 *过滤掉jpg类型的，过滤掉包含xxx文本* 的需求

**Comment by WankkoRee** [comment]
比如说我想排除掉 `OPTIONS` 方法请求，但是只能正向选择除了 `OPTIONS` 之外的所有方法，而不能直接选择 `OPTIONS` 并设置这条规则是排除规则。

**Comment by yuehun** [comment]
> 对

我说的意思也是楼下说的，永久性过滤某种类型的，是排除，不是筛选

**Comment by MegatronKing** [comment]
v2.21.0已支持条件匹配。
