### ISSUE TITLE
[bug] 使用搜索功能时候,刷新浏览器,界面不更新

### ISSUE THREAD

**Issue by Gavin0210** [reqable/reqable-app#72]
如果搜索的内容在body里面, 搜索完以后, 刷新浏览器,搜索结果界面不会更新新的出来.

如果搜索的内容在url里面, 搜索完以后, 刷新浏览器,搜索结果界面会更新新的出来.

**Comment by MegatronKing** [comment]
@Gavin0210 我没有能复现这个bug

**Comment by Gavin0210** [comment]
我试了一下确实是稳定复现.
打开软件.
chrome设置代理到软件 ,然后打开百度首页. 首页下面热搜随便找个关键词.假设是 "尚未".
在调试界面ctrl +F, 能搜到一个结果.
然后回到chrome 刷新 调试界面还是一个结果.
这个时候增加关键词的长度 "尚未结案"
回车
会发现有两个结果.
也就是不会自动更新出来

**Comment by Gavin0210** [comment]
@MegatronKing

**Comment by MegatronKing** [comment]
@Gavin0210 v1.0.6版本已修复，可以试下。
