### ISSUE TITLE
关于改进建议

### ISSUE THREAD

**Issue by 86523553** [reqable/reqable-app#721]
建议在返回的数据区域原始里边把数据显示一下 把<br binary body>这种压缩的格式显示出来  在返回的功能栏哪里加一个用记事本打开原始或者响应头或者响应体 都可以用记事本查看 然后在提交数据哪里显示的 GET /aichat/api/prompts?from=pc_plugin HTTP/1.1这种URL建议补全全部链接   另外还有一个建议 就是能不能在设置里边加一个功能就是翻译功能 官方可以提供一个默认翻译 例如微软翻译什么的 可以自己配置key 例如百度的有道的  然后全局都可以使用 选中单词之后右键 翻译 绘制一个翻译结果弹出式显示  然后能不能出一个活动什么的 例如有人发布B站或和抖音教程 可以奖励多少天的授权 这样大家也会积极的去发布使用教程 也可以起到推广效果

**Comment by MegatronKing** [comment]
你好，感谢反馈。

> 建议在返回的数据区域原始里边把数据显示一下，把这种压缩的格式显示出来

压缩的数据显示出来也是乱码，所以这个意义是什么呢？

> 在返回的功能栏哪里加一个用记事本打开原始或者响应头或者响应体 都可以用记事本查看

这个我研究下

> GET /aichat/api/prompts?from=pc_plugin HTTP/1.1这种URL建议补全全部链接

HTTP原始报文就是这样。

> 能不能在设置里边加一个功能就是翻译功能

抱歉，这个暂时没有计划。

> 能不能出一个活动什么的 例如有人发布B站或和抖音教程 可以奖励多少天的授权 这样大家也会积极的去发布使用教程 也可以起到推广效果

一直是支持的。有发布合法合规高质量的教程，都可以联系我们获取许可证奖励。

**Comment by dai-bao-hua** [comment]
不错不错
