### ISSUE TITLE
同时保存请求和响应到书签之类的地方用于分析和版本差异对比

### ISSUE THREAD

**Issue by o2e** [reqable/reqable-app#723]
比如我分析一个软件数据包，他有很多很多的请求。我想新建一个【书签栏目】叫 xxxAPP  然后把想要的请求和响应同时保存过去用来后续统一分析请求和响应。

现在似乎只能保存请求，没有保存响应，或者只能导出响应的文件用其他软件打开，不太方便使用。

保存的请求和响应可以重发，但不会替换保存的响应 都是打开新的选卡去操作这样子。

有些APP更新之后 数据结构改变了，我会重新保存一份，这样方便看每个版本的请求和响应。

历史请求这个还是不太满足需求，因为请求很多很多，要挨个筛选寻找，也可能是我不太会用吧。

大佬看看这个功能可行吗，期待更新，或者有一种替代方案~

**Comment by MegatronKing** [comment]
@o2e 你说的是收藏功能吧：#314
