### ISSUE TITLE
[feature] 增加自定义请求体/响应体格式tab

### ISSUE THREAD

**Issue by waldenana** [reqable/reqable-app#724]
<img width="289" alt="8c" src="https://github.com/reqable/reqable-app/assets/5113227/7668b856-1780-46a7-b839-e0f46a2fe98b">
这里是否可以增加一个扩展能力，用于展示自定义格式的数据

**Comment by MegatronKing** [comment]
@waldenana 用python脚本，print你想要的格式，会出通过`控制台tab`展示出来。
