### ISSUE TITLE
脚本代码出现异常时，匹配到的网页无法打开

### ISSUE THREAD

**Issue by 18353284786** [reqable/reqable-app#725]
当我的脚本内部出现异常，打开网页或者访问接口时就会无法访问。一直以为是网络或者代理问题排查时浪费了一些时间。
但是呢表面上看起来Reqable 除了脚本控制台没有任何提示。获取可以来一些异常的提醒，让我们更快的发现问题。

**Comment by MegatronKing** [comment]
感谢反馈，我们会考虑尽快优化的。

**Comment by MegatronKing** [comment]
这个问题已经优化，新版本会提示脚本阻断了请求并可以直接点击打开相关脚本。

**Comment by fahedhalawi-wq** [comment]
原来需要经过下面的操作，才能是软件恢复正常：然后鼠标右键单击开始菜单→ “Windows PowerShell (管理员)”→输入：
（WIndows11中可能显示Windows 终端（管理员））
netsh winsock reset
（按下Enter键）
netsh int ip reset
（按下Enter键）
ipconfig /release
（按下Enter键）
ipconfig /renew
（按下Enter键）
ipconfig /flushdns
（按下Enter键）
ipconfig /registerdns
（按下Enter键）
inetcpl.cpl
▲（按下Enter键）（将打开Internet属性界面）▲
ncpa.cpl
◆（按下Enter键）（将打开网络链接面板）◆
▲在“Internet属性界面”点击“高级”，
点击“还原高级设置”，然后再点击“重置”（Windows11中没有“重置”按钮，请忽略此步骤）。
然后在上述选择框中找到：使用TLS1.0→→使用TLS1.1→→使用TLS1.2→→使用TLS1.3（实验），这4个打上勾，点击确定。▲
