### ISSUE TITLE
[bug] 脚本保存不了

### ISSUE THREAD

**Issue by wy12345678901** [reqable/reqable-app#726]
**Describe the bug**
新建脚本后无法保存

**To Reproduce**
1 脚本，新建脚本，新建脚本后无法保存
自己解决方法，重启软件，升级软件都不行
**Expected behavior**
<img width="1008" alt="image" src="https://github.com/reqable/reqable-app/assets/94431733/46c5c9e9-40f4-44b5-a672-0ac7594b5f36">

<img width="219" alt="image" src="https://github.com/reqable/reqable-app/assets/94431733/25648d7c-2ef2-4377-a9e3-c9b80fd6a5e6">
**Information**
 - Platform: [macos,]
 - OS: [e.g. 12.4]
 - Arch: [ x86-64]
 - App Version: [2.18.1（94）]

**Comment by MegatronKing** [comment]
@wy12345678901 你好，感谢反馈。我们按照步骤无法复现问题，请问能否录制下你的操作步骤？

**Comment by wy12345678901** [comment]
> @wy12345678901 你好，感谢反馈。我们按照步骤无法复现问题，请问能否录制下你的操作步骤？
我发现是这个URL*   必须填写值才行， 
以为有默认.*,   结果是不填写不会保存文件，我这边录制的视频发现了，解决了
感谢
