### ISSUE TITLE
[feature]  能够添加个支持抓包监听本地127.0.0.1

### ISSUE THREAD

**Issue by ubadly** [reqable/reqable-app#727]
我的场景是开启reqable的抓包 ，配合电脑上的proxifer代理指定软件进行抓包，但现在出现的问题就是 我链接不同的网络，监听地址也会不一样 导致我每次都需要重新修改proxifer上面的ip地址 有啥设置为监听本地地址的方案或者能否加上对这个需求的支持

**Comment by MegatronKing** [comment]
proxifer你应该用127.0.0.1而不是本机局域网IP

**Comment by ubadly** [comment]
> proxifer你应该用127.0.0.1而不是本机局域网IP

之前我试过127.0.0.1当时不知道为啥么成功，我还以为不支持呢。
刚又试了一下发现可以正常使用，是我的操作问题！
