### ISSUE TITLE
[bug] 内存泄漏

### ISSUE THREAD

**Issue by lsdlh** [reqable/reqable-app#733]
**Describe the bug**
Windows Server 2022 开启了无痕模式和极速模式，长时间运行一两天，内存占用暴涨，可以达到1g以上

**To Reproduce**
长时间运行一两天

**Expected behavior**
保持较低内存占用

**Screenshots**
![Snipaste_2024-06-25_10-48-39](https://github.com/reqable/reqable-app/assets/45959509/e78708d1-51da-48a7-b540-92dfd152fb6a)

**Information**
 - Platform: Windows Server 2022
 - OS: 21H2
 - Arch: x86-64
 - App Version: 2.18.1

**Comment by lsdlh** [comment]
![Snipaste_2024-06-25_11-00-55](https://github.com/reqable/reqable-app/assets/45959509/69a8e087-4b58-49a7-900d-fad1269a21ab)

**Comment by lsdlh** [comment]
并且会代理失效，需要重启软件

**Comment by MegatronKing** [comment]
应该是脚本导致的内存问题，同#546。dart框架问题。部分设备存在，目前无法解决。

**Comment by lsdlh** [comment]
> 应该是脚本导致的内存问题，同#546。dart框架问题。部分设备存在，目前无法解决。

重写也算吗

**Comment by MegatronKing** [comment]
> 重写也算吗

不会。目前已知的bug就是部分windows设备上脚本会导致内存泄露。

**Comment by lsdlh** [comment]
> > 重写也算吗
> 
> 不会。目前已知的bug就是部分windows设备上脚本会导致内存泄露。

那我这里没有开启脚本，也有这个情况

**Comment by MegatronKing** [comment]
> 那我这里没有开启脚本，也有这个情况

有没有可能重写匹配上了一个几百M上G的接口？重写的数据会全部加载到内存的。

**Comment by lsdlh** [comment]
> > 那我这里没有开启脚本，也有这个情况
> 
> 有没有可能重写匹配上了一个几百M上G的接口？重写的数据会全部加载到内存的。

响应是18kb,也不是很频繁的匹配到，一天也就几十次

**Comment by lsdlh** [comment]
抓包地址和请求地址相同，loop了
