### ISSUE TITLE
右上角添加接口时，可以提示是否黏贴复制的url跟参数

### ISSUE THREAD

**Issue by joranbo** [reqable/reqable-app#734]
![image](https://github.com/reqable/reqable-app/assets/29445870/0b4b1d03-90ab-467e-a384-59bbbb892604)

**Comment by MegatronKing** [comment]
@joranbo 你好，很棒的建议，非常感谢。下个版本我们会做两个优化：
- 右键`+`可以直接从粘贴板curl/url创建API测试。
- URL输入下拉框会展示粘贴板的url，点击一下即可输入。

**Comment by MegatronKing** [comment]
2.19.0已支持。
