### ISSUE TITLE
[bug] 无法设置脚本环境

### ISSUE THREAD

**Issue by sun-1009** [reqable/reqable-app#735]
无法自动检测到系统环境变量的python，手动添加，完成按钮灰显，也无法完成
![image](https://github.com/reqable/reqable-app/assets/173806914/572a2762-444e-44aa-9c33-e4283f389240)

**Comment by MegatronKing** [comment]
@sun-1009 感谢反馈。点击reqable应用底部栏5下，打开日志控制台，把日志发给我看看。

**Comment by Dylan-Li8** [comment]
08-19 11:17:47.3388 [V][Dart]: Detecting python env version: python3.exe
08-19 11:17:47.5040 [I][Dart]: Python env detect output: 
D:\Program Files (x86)\Reqable>"D:\SoftData\scoop\apps\clink\current\clink.bat" inject --autorun 
Python 3.12.3
08-19 11:17:47.5040 [E][Dart]: Failed to detect Python env version: 
D:\Program Files (x86)\Reqable>"D:\SoftData\scoop\apps\clink\current\clink.bat" inject --autorun 
Python 3.12.3
08-19 11:17:47.5040 [V][Dart]: Detecting python env version: python.exe
08-19 11:17:47.6609 [I][Dart]: Python env detect output: 
D:\Program Files (x86)\Reqable>"D:\SoftData\scoop\apps\clink\current\clink.bat" inject --autorun 
Python 3.12.3
08-19 11:17:47.6609 [E][Dart]: Failed to detect Python env version: 
D:\Program Files (x86)\Reqable>"D:\SoftData\scoop\apps\clink\current\clink.bat" inject --autorun 
Python 3.12.3

我的是因为clink.bat的输出导致的无法正确识别版本
