### ISSUE TITLE
增加右键浏览器打开功能

### ISSUE THREAD

**Issue by jinshuqishi2019** [reqable/reqable-app#736]
提一个小功能，在链接上可以右键浏览器打开，适用于打开视频图片链接，json也可以使用浏览器插件处理。

**Comment by MegatronKing** [comment]
感谢建议。小功能，下个版本顺手办了。

**Comment by MegatronKing** [comment]
@jinshuqishi2019 突然想起来，这里的url右键菜单是有这个选项的。
<img width="1080" alt="截屏2024-06-27 18 23 09" src="https://github.com/reqable/reqable-app/assets/15059084/1234713c-a41c-46f8-aee5-4b3646847a1f">

**Comment by jinshuqishi2019** [comment]
原来这里有，谢谢你说明

**Comment by MegatronKing** [comment]
2.19.1列表右键也添加了这个选项。
