### ISSUE TITLE
[HONOR 20s(非root) 已根据步骤安装证书并信任仍然无法进行联调ssl抓包] 

### ISSUE THREAD

**Issue by 986823307** [reqable/reqable-app#737]
**Describe the bug**
已经根据文档将证书下载到手机并信任安装，通过apktool解析apk包编辑配置发现原本下载的apk已经配置network_security_config.xml，通过手机协同抓包后https的请求显示“客户端SSL握手失败”

**To Reproduce**
1.下载并信任证书
2.app扫码进行协同抓包
3.软件中显示ssl握手失败

**Expected behavior**
-

**Screenshots**
<img width="1049" alt="屏幕截图 2024-06-27 153231" src="https://github.com/reqable/reqable-app/assets/56620683/4c51a9bb-da7f-49ee-ab93-49b58360b0f2">

**Information**
 - Platform: [windows&android]
 - OS: [鸿蒙OS]
 - Arch: [arm64]
 - App Version: [2.19.0]

**Comment by MegatronKing** [comment]
只有native开发的配置network_security_config.xml才有用，flutter等框架无效的。

**Comment by 986823307** [comment]
> 只有native开发的配置network_security_config.xml才有用，flutter等框架无效的。

那这个要在哪里改勒？望告知，谢谢

**Comment by MegatronKing** [comment]
> > 只有native开发的配置network_security_config.xml才有用，flutter等框架无效的。
> 
> 那这个要在哪里改勒？望告知，谢谢

如果你是flutter框架，看看这个，刚刚写的：https://juejin.cn/post/7384791103445417996

**Comment by MegatronKing** [comment]
> 你的意思是文档中的配置要改需要抓包的APP，而不是Reqable的APP？

证书安装到用户目录对flutter应用无效的，只有系统目录才有效。要么去改项目代码。

**Comment by 986823307** [comment]
> > 你的意思是文档中的配置要改需要抓包的APP，而不是Reqable的APP？
> 
> 证书安装到用户目录对flutter应用无效的，只有系统目录才有效。要么去改项目代码。

懂你意思了，感谢

**Comment by snila** [comment]
> > 你的意思是文档中的配置要改需要抓包的APP，而不是Reqable的APP？
> 
> 证书安装到用户目录对flutter应用无效的，只有系统目录才有效。要么去改项目代码。

您好，我的手机已经root，且证书也已安装到系统里，抓flutter应用还是显示客户端SSL握手失败，是什么原因呢？
![5f30c3288b622d663d4cf9babe32d9c7](https://github.com/user-attachments/assets/151a7a00-54f4-4839-9d4b-a67e08014939)
![be0e2682136a93cc7b012b12b4c8af03](https://github.com/user-attachments/assets/cb4f3246-216e-4d07-bba8-34f329d0947d)
