### ISSUE TITLE
[feature] 请求头与参数增加json模式编辑

### ISSUE THREAD

**Issue by Menusyes** [reqable/reqable-app#738]
参数或请求头数据相互分享或打印在控制台中时，基本都是拿json丢来丢去，这时候想在Reqable上调试下，得一个个参数手动加，就算用文本模式也要调整格式。不如加个json模式，直接粘进去了事。

**Comment by MegatronKing** [comment]
有道理，文本模式粘进我直接帮你json转成键值对，就不用手动修改了。

**Comment by MegatronKing** [comment]
2.19.1已实现。
