### ISSUE TITLE
[feature] 直接IP请求时使用自定义Host作为SNI

### ISSUE THREAD

**Issue by ejfkdev** [reqable/reqable-app#739]
域名dns解析可以按地区返回就近的服务器IP，还有灰度测试也可能切部分流量解析到某个测试IP，需要请求发送到特定的服务器IP

比如增加一个输入框，指定连接某个IP
或者URL支持 https://ip 的格式，把host头当做sni域名

**Comment by MegatronKing** [comment]
URL支持`https://ip`的格式进行测试，要把请求设置里面SSL证书校验选项关闭，但是SNI是不支持host头当做sni域名。如果你对SNI有需求，可以试试镜像这个功能，把域名映射到指定IP：https://reqable.com/zh-CN/docs/capture/mirror，启用这个功能后，记得还要把url输入框后面的图标点亮。

举个例子，你请求的域名是`example.com`，默认解析的IP是`120.0.0.1`，你希望请求的IP是`120.0.0.2`，SNI也用`example.com`。镜像配置`example.com` -> `120.0.0.2`并选择保留SNI。你在请求的URL里面可以直接输入`https://example.com/`，点亮后面的跟随调试图标，你发送请求的时候就是请求的`120.0.0.2`并且SNI是`example.com`。

**Comment by ejfkdev** [comment]
> URL支持`https://ip`的格式进行测试，要把请求设置里面SSL证书校验选项关闭，但是SNI是不支持host头当做sni域名。如果你对SNI有需求，可以试试镜像这个功能，把域名映射到指定IP：https://reqable.com/zh-CN/docs/capture/mirror ，启用这个功能后，记得还要把url输入框后面的图标点亮。
> 
> 举个例子，你请求的域名是`example.com`，默认解析的IP是`120.0.0.1`，你希望请求的IP是`120.0.0.2`，SNI也用`example.com`。镜像配置`example.com` -> `120.0.0.2`并选择保留SNI。你在请求的URL里面可以直接输入`https://example.com/`，点亮后面的跟随调试图标，你发送请求的时候就是请求的`120.0.0.2`并且SNI是`example.com`。

curl命令本身支持指定解析ip
`curl --resolve 'www.example.org:443:127.0.0.1' https://www.example.org`
镜像功能确实可以满足需求，不过修改规则再发请求略繁琐，目前不支持上面resolve参数导入导出curl

---

还有一个小问题，curl的-k或者-insecure与设置里的SSL校验，在导入导出curl里没有同步

**Comment by MegatronKing** [comment]
直接IP请求时使用自定义Host作为SNI，这个功能已经实现了，下个版本就可以用了。

> 还有一个小问题，curl的-k或者-insecure与设置里的SSL校验，在导入导出curl里没有同步

 感谢提醒，确实忘记同步insecure这个选项了。

您反馈的问题很重要，有空的话可以在我们官网右下角扫码加个微信。如果你有意购买reqable永久许可证，可以获得半价的资格；如果只用社区版或者已有许可证，也可以获取一个额外免费的许可证兑换码。

**Comment by MegatronKing** [comment]
2.19.1已实现。
