### ISSUE TITLE
[bug] 无法正常高亮base64数据

### ISSUE THREAD

**Issue by 46ef882ff3a47d** [reqable/reqable-app#742]
**Describe the bug**
在请求和响应俩个框中, 对于base64数据的json高亮都是有问题的

**To Reproduce**
请求任意返回base64数据的接口, 或者你可以写一个包含base64数据的json到请求框中, 记得切换json数据类型

**Expected behavior**
修复高亮显示, 因为错误的高亮导致我在请求框中输入json的时候发生了错误的缩进

**Screenshots**
<img width="1012" alt="截屏2024-07-01 16 41 12" src="https://github.com/reqable/reqable-app/assets/132568160/1b8b78a7-b70c-4153-82e9-0e6096f92bd3">

**Information**
 - Platform: macos
 - OS: 14.5
 - Arch: m2
 - App Version: 2.19.0

**Comment by MegatronKing** [comment]
已知问题，同 #195 。dart栈空间太小，正则匹配回溯爆栈了，除非更换高亮算法优化或者不用正则。
