### ISSUE TITLE
[feature] 断点弹窗功能体验不好

### ISSUE THREAD

**Issue by OwnerCM** [reqable/reqable-app#745]
断点功能能否直接在主窗口的列表进行操作，现在的弹窗体验不好，如果使用正则匹配多个地址会反复跳弹窗，不方便使用。
建议可以参考fiddler的断点功能。

**Comment by MegatronKing** [comment]
你好，感谢反馈。目前来说，我没有感受到使用独立窗口体验不好的点，能否提供一些你的操作录屏？

**Comment by OwnerCM** [comment]
> 你好，感谢反馈。目前来说，我没有感受到使用独立窗口体验不好的点，能否提供一些你的操作录屏？

单独抓一个请求时新弹窗没什么影响，大佬可以试试在某个域名下使用*通配符，刚执行完一个请求准备回主窗体看数据或者回软件界面看结果时，立马又断点一个请求弹出窗口，需要频繁的切换窗口。

**Comment by MegatronKing** [comment]
> 某个域名下使用*通配符

但是你的意图不就是对所有通配符*匹配请求进行断点吗？如果是单个请求，你直接对单个请求断点就可以了。
