### ISSUE TITLE
[bug] 关闭Reqable后，正常上网出现异常

### ISSUE THREAD

**Issue by qilinxinan** [reqable/reqable-app#746]
配置如下：
![image](https://github.com/reqable/reqable-app/assets/107522343/e520b478-f045-4936-9034-ac1395f71b11)

问题如下：
开启Reqable（不管有没有启动），网络正常。只要关闭Reqable，部分需要翻墙的网站无法访问，不需要翻墙的部分也有出现异常无法访问的情况。
![image](https://github.com/reqable/reqable-app/assets/107522343/5f60304f-8d8f-41de-b3fa-ae538fa2e432)

看到你的更新日志有这个，之前是好的，应该是这个版本更新后出现的问题。
![image](https://github.com/reqable/reqable-app/assets/107522343/27fc8747-decf-4f07-97fd-8c21743e05f2)

**Information**
 - Platform: windows
 - OS: win11
 - Arch:  x86-64
 - App Version: 2.19.0.95

**Comment by qilinxinan** [comment]
我往上试了下，好多个版本都是这样的问题。退回到2.18.0正常了。

**Comment by MegatronKing** [comment]
@qilinxinan 截图看起来不像是reqable的问题，而是dns污染的问题。

打不开网页的时候，你检查下系统网络代理是否开着。如果开着并且配置着reqable的端口，那说明是reqable退出时没有清理代理配置；如果已经关闭了，那说明就和Reqble没关系。

另外，打不开的时候，你检查下网站上面的SSL证书，如果签发者不是reqable，那和reqable也没什么关系的。

**Comment by MegatronKing** [comment]
我现在也经常遇到dns污染的问题。比如说，reqable.com的ip是192.168.1.1，但是dns解析返回的是192.168.1.2，网站就会去访问192.168.1.2这台服务器，返回了不正确的ssl证书，就会出现你上面那个错误。

**Comment by qilinxinan** [comment]
好像是，现在重现不了了，先关闭
