### ISSUE TITLE
[feature] zstd codec support

### ISSUE THREAD

**Issue by tas33n** [reqable/reqable-app#747]
**Describe the bug**
when capturing networks form facebook/messenger networks, the response are always Hex data , theres no option to show as utf-8 or readble text. The devtool form chrome show the data as readble json or script data. i've also cheked in burp suite that also shows as json data but reqable always shows hex..

**To Reproduce**
3. See error

**Expected behavior**
It should show the data same as chrome dev tools shows, or at least have option to show hex and utf8 data.

**Screenshots**
Reqable:
![image](https://github.com/reqable/reqable-app/assets/55633040/c7eaef3c-8697-4f7c-8bec-c3ff5cf2c7cf)

Chrome dev tool:
![image](https://github.com/reqable/reqable-app/assets/55633040/0e117366-0b4a-44e0-8cfa-838f4a7e5167)

Burp Suite ((different api but same type data))
![image](https://github.com/reqable/reqable-app/assets/55633040/9ad09edc-6975-4221-bc1f-61a38d90e747)

**Information**
 - Platform: Windows
 - OS: 11
 - Arch: 64
 - App Version: 2.19.0

**Comment by MegatronKing** [comment]
@tas33n Please attach the response headers here.

**Comment by MegatronKing** [comment]
> response header from reqable :
> 
> ```
> :status: 200
> vary: Accept-Encoding
> content-encoding: zstd
> content-type: text/javascript; charset=utf-8
> reporting-endpoints: coop_report="https://www.facebook.com/browser_reporting/coop/?minimize=0", coep_report="https://www.facebook.com/browser_reporting/coep/?minimize=0", default="https://www.facebook.com/ajax/comet_error_reports/?device_level=mod-low&brsid=7387264710118225710", permissions_policy="https://www.facebook.com/ajax/browser_error_reports/"
> report-to: {"max_age":2592000,"endpoints":[{"url":"https:\/\/www.facebook.com\/browser_reporting\/coop\/?minimize=0"}],"group":"coop_report","include_subdomains":true}, {"max_age":86400,"endpoints":[{"url":"https:\/\/www.facebook.com\/browser_reporting\/coep\/?minimize=0"}],"group":"coep_report"}, {"max_age":259200,"endpoints":[{"url":"https:\/\/www.facebook.com\/ajax\/comet_error_reports\/?device_level=mod-low&brsid=7387264710118225710"}]}, {"max_age":21600,"endpoints":[{"url":"https:\/\/www.facebook.com\/ajax\/browser_error_reports\/"}],"group":"permissions_policy"}
> content-security-policy: default-src data: blob: 'self' https://*.fbsbx.com 'unsafe-inline' *.facebook.com *.fbcdn.net 'unsafe-eval';script-src *.facebook.com *.fbcdn.net *.facebook.net 127.0.0.1:* 'unsafe-inline' blob: data: 'self' connect.facebook.net 'unsafe-eval' https://*.google-analytics.com *.google.com;style-src *.fbcdn.net data: *.facebook.com 'unsafe-inline' https://fonts.googleapis.com;connect-src *.facebook.com facebook.com *.fbcdn.net *.facebook.net wss://*.facebook.com:* wss://*.whatsapp.com:* wss://*.fbcdn.net attachment.fbsbx.com ws://localhost:* blob: *.cdninstagram.com 'self' http://localhost:3103 wss://gateway.facebook.com wss://edge-chat.facebook.com wss://snaptu-d.facebook.com wss://kaios-d.facebook.com/ v.whatsapp.net *.fbsbx.com *.fb.com https://*.google-analytics.com;font-src data: *.facebook.com *.fbcdn.net *.fbsbx.com https://fonts.gstatic.com;img-src *.fbcdn.net *.facebook.com data: https://*.fbsbx.com facebook.com *.cdninstagram.com fbsbx.com fbcdn.net connect.facebook.net *.carriersignal.info blob: android-webview-video-poster: *.whatsapp.net *.fb.com *.oculuscdn.com *.tenor.co *.tenor.com *.giphy.com https://paywithmybank.com/ https://*.paywithmybank.com/ https://www.googleadservices.com https://googleads.g.doubleclick.net https://*.google-analytics.com;media-src *.cdninstagram.com blob: *.fbcdn.net *.fbsbx.com www.facebook.com *.facebook.com data: *.tenor.co *.tenor.com https://*.giphy.com;frame-src *.facebook.com *.fbsbx.com fbsbx.com data: www.instagram.com *.fbcdn.net https://paywithmybank.com/ https://*.paywithmybank.com/ https://www.googleadservices.com https://googleads.g.doubleclick.net https://www.google.com https://td.doubleclick.net *.google.com *.doubleclick.net;worker-src blob: *.facebook.com data:;block-all-mixed-content;upgrade-insecure-requests;
> document-policy: force-load-at-top
> permissions-policy: accelerometer=(), attribution-reporting=(self), autoplay=(), battery=(self), bluetooth=(), camera=(self), ch-device-memory=(), ch-downlink=(), ch-dpr=(), ch-ect=(), ch-rtt=(), ch-save-data=(), ch-ua-arch=(), ch-ua-bitness=(), ch-viewport-height=(), ch-viewport-width=(), ch-width=(), clipboard-read=(self), clipboard-write=(self), compute-pressure=(), display-capture=(self), encrypted-media=(self), fullscreen=(self), gamepad=*, geolocation=(self), gyroscope=(), hid=(), idle-detection=(), interest-cohort=(), keyboard-map=(), local-fonts=(), magnetometer=(), microphone=(self), midi=(), otp-credentials=(), payment=(), picture-in-picture=(self), private-state-token-issuance=(), publickey-credentials-get=(self), screen-wake-lock=(), serial=(), shared-storage=(), shared-storage-select-url=(), private-state-token-redemption=(), usb=(), usb-unrestricted=(), unload=(self), window-management=(), xr-spatial-tracking=(self);report-to="permissions_policy"
> cross-origin-resource-policy: same-origin
> cross-origin-embedder-policy-report-only: require-corp;report-to="coep_report"
> cross-origin-opener-policy: same-origin-allow-popups;report-to="coop_report"
> pragma: no-cache
> cache-control: private, no-cache, no-store, must-revalidate
> expires: Sat, 01 Jan 2000 00:00:00 GMT
> x-content-type-options: nosniff
> x-xss-protection: 0
> x-frame-options: DENY
> origin-agent-cluster: ?0
> strict-transport-security: max-age=15552000; preload
> x-fb-debug: /3JEfxMr+S6AOFf+2tPZwVf3Czv/h7geW+L36Y4808X5Lr9YtTQYFx+qeg7FjTkEjHgmq2Cpc0csDIlEE8ovZA==
> date: Wed, 03 Jul 2024 04:39:57 GMT
> x-fb-connection-quality: EXCELLENT; q=0.9, rtt=27, rtx=0, c=10, mss=1392, tbw=3577, tp=-1, tpl=-1, uplat=272, ullat=0
> alt-svc: h3=":443"; ma=86400
> ```

Thanks, not support `content-encoding: zstd` currently, would you like to share me the url, I can have a test.

**Comment by MegatronKing** [comment]
> when i used this curl in postman, it returned 'br' encoding instead of 'zstd'
> 
> Postman: ![image](https://private-user-images.githubusercontent.com/55633040/345310357-64fb4483-e0e2-4025-a4ed-40add0ec3e6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTE4MDYsIm5iZiI6MTcxOTk5MTUwNiwicGF0aCI6Ii81NTYzMzA0MC8zNDUzMTAzNTctNjRmYjQ0ODMtZTBlMi00MDI1LWE0ZWQtNDBhZGQwZWMzZTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA3MjUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMjQxZmJiYTBlYjM2M2ZhNDgyNmRiZGRiZDdlNGFlMTE3NDQyMWM0YmM3YjE2MDU0OGIxODBiMjIwOWViZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tshG0qEkrGgaoBD8pdK5KL86dAscjO2myzBrGf6094M)
> 
> Chrome: ![image](https://private-user-images.githubusercontent.com/55633040/345310614-e58aca95-1fd6-4ad6-8d00-c7d6268940a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTE4MDYsIm5iZiI6MTcxOTk5MTUwNiwicGF0aCI6Ii81NTYzMzA0MC8zNDUzMTA2MTQtZTU4YWNhOTUtMWZkNi00YWQ2LThkMDAtYzdkNjI2ODk0MGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA3MjUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNTVkYTNmMDliODk2NTFhOWVjYTcwNmU3NGZlZjhkY2VhNWRhNzQ0MTM1NDg2MmRjNjYwZTNjMmUyMDM1NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uUM72Z3TS49WLVFuMB9oi6SKPEnzh34OS3CsLSM-MBQ)

Please check `Accept-Encoding` in request headers.

**Comment by MegatronKing** [comment]
We will support `zstd` compression in the next version.

**Comment by MegatronKing** [comment]
Done! Please update to 2.20.0.
