### ISSUE TITLE
[feature] 希望调试时可以用脚本修改最终展示的reqbody 和 response

### ISSUE THREAD

**Issue by AnxysUaen** [reqable/reqable-app#749]
一些常见场景下，发送和接收的报文都是加密过的数据，目前的脚本可以做到修改响应数据进行解密，但是修改请求数据为明文后，请求就会失败，是否可以单纯修改用于展示的请求数据而不修改实际发送的数据

**Comment by MegatronKing** [comment]
直接print，然后在控制台tab里面看

**Comment by AnxysUaen** [comment]
好吧，不过实在是不太优雅
