### ISSUE TITLE
[bug] 希望重写功能，能增加一个请求发起前重定向，有时候并不希望将请求发送给对方之后，再重写请求，我希望在请求发送给对方之前重定向

### ISSUE THREAD

**Issue by 17683772549** [reqable/reqable-app#750]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
同 #267
