### ISSUE TITLE
[feature] 搜索条件能增加包含多个url片段的的功能，现在的搜索似乎通配符似乎只能实现一类url的搜索。

### ISSUE THREAD

**Issue by LeToNode** [reqable/reqable-app#752]
某些情况下可能几种不同的url返回的结果会是类似的或者相同，比如第一页和后续的请求的区分。

**Comment by MegatronKing** [comment]
@LeToNode 感谢提交反馈，能举个具体的例子吗？

**Comment by LeToNode** [comment]
比如www.abc.com/goods.html?ssodid= 和api.abc.com/goods/list/****

这是因为我们系统第一页用了后端渲染。

**Comment by MegatronKing** [comment]
其实就是希望搜索支持`或`逻辑对吧

**Comment by LeToNode** [comment]
对。这样我可以通过一次搜索看到这些结果，不用看两次来区分问题源头。

**Comment by MegatronKing** [comment]
v2.20.2已支持`或`逻辑关系。
