### ISSUE TITLE
会话保存后，所有get类型的请求参数全部丢失.[bug] 

### ISSUE THREAD

**Issue by ouguochong** [reqable/reqable-app#754]
**Describe the bug**
保存会话后，再次打开保存的会话。会发现所有get类型的请求，url后面的？参数都丢失了。

**Information**
 - Platform: [ windows]
 - OS: win11
 - Arch: [x86-64]
 - App Version: [2.19.1(96)]

**Comment by MegatronKing** [comment]
@ouguochong 你好，保存会话是怎么操作的？能否提供下操作步骤？

**Comment by ouguochong** [comment]
> @ouguochong 你好，保存会话是怎么操作的？能否提供下操作步骤？

直接右键单击当前会话tab页->保存，然后“文件”->“打开”之前保存的文件。

**Comment by MegatronKing** [comment]
> > @ouguochong 你好，保存会话是怎么操作的？能否提供下操作步骤？
> 
> 直接右键单击当前会话tab页->保存，然后“文件”->“打开”之前保存的文件。

感谢回复，我测试并没有复现问题。你说的参数是什么？Query Parameters吗？

**Comment by ouguochong** [comment]
> > @ouguochong 你好，保存会话是怎么操作的？能否提供下操作步骤？
> 
> 直接右键单击当前会话tab页->保存，然后“文件”->“打开”之前保存的文件。
安卓8手机，抓取google message,rcs聊天开关测试
保存前：
![image](https://github.com/reqable/reqable-app/assets/28273030/7c609da2-a33b-4e25-b6a3-e280a5ac863e)
保存后
![image](https://github.com/reqable/reqable-app/assets/28273030/1bba21b4-ac78-43e9-b39a-65452e164a15)

**Comment by ouguochong** [comment]
> > > @ouguochong 你好，保存会话是怎么操作的？能否提供下操作步骤？
> > 
> > 
> > 直接右键单击当前会话tab页->保存，然后“文件”->“打开”之前保存的文件。
> 
> 感谢回复，我测试并没有复现问题。你说的参数是什么？Query Parameters吗？

安卓8手机，抓取google message,rcs聊天开关测试
保存前：
![image](https://github.com/reqable/reqable-app/assets/28273030/7c609da2-a33b-4e25-b6a3-e280a5ac863e)
保存后
![image](https://github.com/reqable/reqable-app/assets/28273030/1bba21b4-ac78-43e9-b39a-65452e164a15)

**Comment by MegatronKing** [comment]
@ouguochong 看起来像和特定的请求有关，能否将选中的这个请求复制个curl给我测试下？或者把har文件贴在这里也行。

**Comment by ouguochong** [comment]
curl -X GET '
https://rcs-acs-mcc234.jibe.google.com?vers=0&rcs_state=0&IMSI=234100116677428&IMEI=867686023886748&terminal_model=Nexus%206P&terminal_vendor=Huaw&terminal_sw_version=8.1.0&client_vendor=Goog&client_version=20240603-01.01&rcs_profile=UP_T&rcs_version=5.1B&token&SMS_port=0'
-H 'User-Agent: IM-client/OMA1.0 Huawei/Nexus_6P-8.1.0
Goog/messages.android_20240603_01_rc01' -H 'Connection: Keep-Alive' -H
'Accept-Encoding: gzip' -H 'client_channel: PUBLIC' -H 'Accept-Language:
zh-Hans-CN' -H 'tachyon_identity_key:
CAESIQUopu4fjhwYMSDjKcSIb3svyCAu8LSuaAN8pl5tPI45Og==' -H
'rcs_engine_session_id: 7e655214-ef98-495f-91b6-398b96db912e' -H
'rcs-pe-version: 3' -H 'rcs-pe-location: 3' -H 'gmscore_instance_id_token:
cQx41rHbZR4:APA91bELyLrcRMwsl-PoqL9CgtjpTXrtF-icxUqh7-BvXBKADEqWRhJ4-t2iVeli1ShGT_CbCFlbW54OmJeKw-WUFp1nUeNQV_l-N8x0Hhk5ZXO4YJ-UCZfX1w0AlQSG9BHf_OpOTC10'
-H 'Droid-Guard:
CgYjsMeqc4IStTQKBhChiAxH8tIQWwAACju1grMqibgAF4temRTZqDoAR7aCu18zHyAAkTFspexpJBcAe7sEtihRS2wBCEjpxOXOEbEAaHYKiHD-8y4DYcqNUGmec_4BEvASo2MjxbgDjY0NjzO1oN_aB4kYAOuhCBJEw8AjNCibPq9E2sV-hkaQSrFE9Q1JvHjMPpMmFKdpY8VqQNLy0Vwfc5dMzggIlnBsu32tuzVyAlxk7wqx-1xfLubye2yempOGv7EcYhqNNmfDO0dkRh_rkKNQS36eU3hQfR__tDNSQG57wJhaUk4CMPY87yOukpIuI324qBA74Bf-yLEwcFkEnjvlYYhII-QQDXwMf0KVlU-2kfldXNEAYytgA2377Rr6bhHgKSpiVoZAXoP8no5yA60otWT5x7tosynbN5CjQP3U77POnSmV3G9-om-gFIN1intLVyv7PFkdmWKqfBK7VsIQ-6a-BM3biQeoWTbRIvIK6Hu8uBaSPadHLxm--57miXDRs_OKIiuzl8Zw5gQuv2UA4b9qxC497PCW-7yJ5F86ukP22CijF3QXBloKxr2ppokRu9bajDgEBdU0AVkv8Cqw2PSNE0NK5v_tfy2pVIIxzsG2rhB63doGjfWIE3WefxtsK32AR6R10qI8elqZEpNOnNwJgaxZZYKmqFhhrqW_PtlQnPzisGdwdLMXerc375xfmb657ftsVBYm8r7DpqHZ9crsf_28TAcLEzf8BeZHxfj4u285fFXeFpGfmLJwChe1jHsfm_oEOk5VOZlkMEym5YIkkOfMNCi-6iYpdCMayXFO6tpoxc0K3QhS9KoT0dRH1riTuyO6Qsl_qiNMwf2hGtHUV9dnz4kJEJVmvlWArrQZ26CxcjOm9_GHxKck8gYAIUj9FoEU4q9VpKv5WNT53AohCVVRI33Zm7_PE0kKgsqHHhgFqVUgvAvTopBhaodcdufy2c60fBeRuMkkIi1X0mKJFyzWowk6c3pKQK-sM9snGg2xOq_8ayEmWQ6_4aOLlN3rgKFvC6_Kb69MA1vV43NqN4e5FYfH-QM0gfNeZPo78Ub9VRqrzo-prPSnI8RbvfSyytMDnpdBysmxYdRBvEm4qgB95GvVvhBfSkAZY6-oIKvj3fns_NFIeBiVVTg7XHAn7XYJVrgK7zU_m3hm4Dkm2FsekXgnAR8ThXKqhwmelj4XChkNaGsWC9rbW5bbe3mzdjkqyHyjXDeQ6laKAqqvBD3RK4UzMKzw1MeZLPn5cJ5uLUjZQr3ga3gxrjaCqg4SJ68gIOgaAqFOgduGOQ7NdZYCrxSMQ0gJONB9zT4CGlIbQ2j7vzvosLnYJDfwMnjTEP0xDaT2p_L0jNnuQG10ZX0mJKr5efgLHpmD4mr0n756Jg0MvXW_SWA_a-69ZYxgFvre9-_FXM6N0QCAKs5DZQ62AJDapx04aNN-Lq6qNYM9LODZy5yCMv2pK0OuP2cINpRagg6meRWkmZiwIW7Wo07zUxtMI2j6quAX0cVwzW_EK57o_NQ3KtO--9mhrlFGKqfIcSA6jkGmZ0orkl1CfVnwfAWeQU2vxoBFB5-rUDTdwYg4C8OtOCMLMZLFRNxEPZaz6kD5dr2thgxNlwzHVtWihFiyBhbi-KUGVXdafDVU_KvSJjTQO6LJPpiwOWFT4DFj9RcKriENb1ZgROSJtQ_f-98YrbEN6_uF1_0NyzQEFNkUl8ixy4T64gPhHa_v7mC27na2vkKHUqdLPh2llCUGsJkuo2jlDeTgoF0s0Fq6uTaxN4e45LhiN6piYAmnpDAsEYCMT3hzkCyQ1C5kTZi5JdGQkp0QnuIFOFMS6xkvtorK-cmcxmLXTX0U-J3ypwS7fJipaNYXkuJhp9_oxjERNaCv0FhCqXWlW4sRDiWb7f8cDG3fyyzGQPitEl38P9q_ZwQ-WR1-Zi5rhv_HWLQlkL57voWSGdcNLh1J9SESYiww6eRPpEav8MSDw1S07Zyia3B5MxLwq0Ltp12voSv_VpaAwKzAjvzHkn6aKiRDup1uCZ1e7K2I_jFXCc90wOQrd-6vKo14lrvj1SE6FErsInknu09GZP3EMhNLS_0JGcIH9LZgQE_FL7qZot2uFBu5bzYAV6RcVtQNQZ4gpD3IYHdECItWsnPeVpUEkRv7JCG2kOXDfljdIrFazD_NEEPgUccs5r5MlvSE6_cl9K2mlLsWx5j5kz-ZteVaIuVP_y0-B7hMgcoTpkwacUNQWXnQe68LXRAhCssbEgoFqhry3bxyWEc-L27exnkPR49bA-pZWCYvs2iIpRYXZo1YFsbdMrHMFKbOHCsbO5V1Sb625HSnupuKoO_0gQdIB1QVwzxawPo_CajTAlXbokaxxgjEE5QHIO1_lX2hI4vV4S3-dr0VO64rlrNmL01dLYHF3ikcMyWkcN-Bhvx5_GQhNlZTyps0gZ-wC4VvZH878bndkjLN4YQcnUO3AcIHShZjOvYmG4hb3lTsGuOrHZEZQ75XPjCTrvMqADIDLBOcGmVlzX-s_pBAxOcSW2vVcJBHnlVb-Rwfs2nFlK6QWlZggFYXhex_qgGWLR8dFijqqkrBrnDpt81DRyHcgUTeygRpsMN8eZ63q_rU4bRxsg1-NzGiMnku2cbfYu-L_FrS49AAbjniTQJrEkAqBPKsqWbYDXYcTWphNGAupuFbTMbCzJ3UWuFIi4n3xmr08NdAeadbJy2_lEpbEz9ikjKILZBDMnrEE_-t0Q-Bpe9vjhfxshUGymdcXxxsnoACAScpy9tZ9jWggaPo-LlRJH2lb3gKvOZ32nWZr_7fFxJ69dL4lW6vAFnrW6DUDdFvLoHumeeIpn0OQAAtd_wrvWn9cKt0cCiYe8oG0weF_qmkHtGCfhLk26NFOAuR1TdoebAjWshKD3eoRlRaxY_Yh-okv3tiuYcHf5eoFB-P_qlM639dmaP4-7Zwg12kqQRVTP_LzzGfZgm80e37mGi6-jaS9ycNWl2kCB8LoSG5wpQPy9iEJ5PW0IHjESn2kudZy_kWEeu41VmkL0PmZSLLemgRSeBBcym6vHnVPiBqgaVi4vQjw_8vYiAnt4YTyEFsU6gIEbPFJwucqo-wdJEBLToomELI3h-ulOseorn3mmOlXUMuzvPA9hZ3P4HFu33CdfYZUwCUog9TsTzFt2eQI6HMduIfheu5amsrTwAN0Sbo8xdOdbzsqPXQpWGqftGGHcFXV621JLPR4gWnP5xZntzquAHhkuePKNWQm3cgIRtaq_SFCS3Uki8K0euOTmw0emLoV_w7DXzMoEnbaVUN8nBtNY8LXW9e5q3ubNdYK367hBcK6hl4edyPVeOK5ciIw99qshGTPzmE35EOeBO6tNM51re_zeyec7bjtBHQ56lNLmok4VL6JTwla8JmJsGnIl3pfKCGHlRTUmCmEqgNZ2z4ZOXrn_iDoaLeaMQkbHWQ2fG-Ylp9KV5g7WamiZXrCRYIidzlqgCyZgCV85TrIVO793f9ktwe2jgOiNBy6V7HeOSNMx-DvFqDjvtuRHKKY7UN9QtwLPCQqKAB92MDRRDW1jz31dgNytXQGAyiCojEPDd-VlVnfPnwrZQu72CNH4PaU2C7JtQCLcXAMjLdrSWfIpZXXdFB8tVRqyzN2Kohwg4uc7oyBGE0bd4RuvTe9dzwnK-1Z2aqKB_-IHmaX4lF6JNf9c1u21Sc_qv4g_G5BgZV_bPkbSMhxR2xDa4CpGVoMQWikzA6FGkAZv1OSGJHZFSX79ScudoSX2uJ0pYHdB6Raw3zPgODNHKFjd4d4rCAjp_KJUa16NSgoxm_NTHs9CUe5jjqdS6CQuHMCxPi23z0C-lugNNyLrSCHKVh9_H0qKG2gXtsqOM12AQmWTpXAu9ZRihPWrU1BOdT1vxUmdnFemzaL-a1BJiuL9wB7inTujUuJa5wCYPuB1mmVDYUTtwrUt7ppWgiau0yPV_UevX9iOpOUr_ieQKPncpiv8InDhywvYtKv8zfgTz0quXEgQcDczYDKQrqyng-S4eQ1yx_SQGdhFabueBiLscA26dx07hIPi7rbjNmLVPhjwBTLqLGbmbU-LCYtznDLTGJh4cY7yAmxhI1M0CtcyVhDEruL5z4Aq9hHbQM7faO25UasgVSpQnRqtr46peX5EpFwRkKBAuQrWZ3KJVuk_wuBwDt5yIkGEA06booFevuWW6I3GpTfq4HkzJYUdBjRICwXRXi3oCrciWjtInGB64KHYaE-VJ-QIuzOGHQD6r42Kajg5TQBDhrOEuYEsrgrYi4gaDjmAGYEujm5J_HvbvM8wES8xpaqPiqN6dlrA_ySaUBk3xhKwcVuPv-klfwumMFfaazQh3LquP-ES8lNub1iEt9Poeeg3Bjpzr9YIqkibvBispc7qQRK41EsfnHycrh1CF7NnZJjT-_MkVukv-XBHsCSmD9JUI8nX78erYkyhLi-elU-RSKiU7UQmCUbWGNSb17JEST5Sae37UqlVmly0v3SN5B_jwOvNgcIcQ1cz_iJuUl48K5hfO_ZbCyAZGXr6Rl_wWpW9E8pnLNU0zdzk9-RNr5DncQ7VtfysS1tJBJaGbAAjPz2HItxVgJjdE3o6wUHew-wy_LDyBy6iq16cBWAyWavgjkkmqx5g-3I3poasnm7-C-QC4l_qLRX636DQHKeiMqv234Dm5V9gNlAbhzu39I7S9Mnq1sUBxtFqy0KqmCzIVCK1ME7M2RHkYdDaPU49a_xQWdrWTfqKMY_vY2wyOV9e6pM8e_OGMwCfAmRKtgqyxqVaHGkSkmdSl5rXe7eVQCfy-5Gz6b8DI_xsaNn-nPK_L04sAZX-kcaHX98JmsviGmgmFGwVi6Fi2c1XOKbOyrqm4nZa4l9FHh7Mwo0rvuPpSF--0vft0rfAqc_NHiOHawsI7G8OKX_qhbYLZK62dPwaPiUjorYBZs7zDYp4BYbyuZf4UoyMc10vmKwIU1H-rltDaaq98r4f0JSQ5-MRuZzXWOCEiacDnEr-VxZi32Lc1HjJ2l4vJ87hf2JIdf48tBfRO7aK4113mKXbxel0OIcj3xhvFmNUeJ2Pbl9Eu-0mdt8xKL9foOYM6nftj-veZ_hQLUyePhFybXa-J7exhJyReoLXIOWYrjccrvbmZ6KbG4VoGr5KK8FYglGrpnmcYa5SY3MCpguvFNJqcmrM6ue6RtTaWUAHPNPjnDHeFuCyrecLZA-TNU6en9w0EKOG0XEc_uHOE5GQC14dUMkFifLAAlvrGWHyvXll1xCi60sdeQivpTON4lOMyXW1UqEU7wYazvlRfC6UTJlwQZA7qQCxKI8Zfm8FL6G8fApNaubV4nV7qpQz3XZRWhcmZTlQBtGFx0HdsMW0aJh8VTVGbP83UzV5Wr0LwnkzMeWIFfAtj-v2jwfPjfQ3DLsAI13CyTb0DojIdcdgVsJraJjzx76deGOq32Yww809ogaSeFu5UZ-yQvDNc8suXDwUgNGoD821wBdMXvl95LZr5JOVzt6vgSgzT3QPF9jDZHtR3YT6WZCokHpJugq_yLEAK-G4P02Rn7T3y9IYRgzgfa5hoYSu27Q_crqzIT2lOzdqH9KOxlUZS7KDGXRNaSeChuvNf2042OWBrq0E70jbNhu2zjtt6vFDDVsWH5zzaDkHuzQfZCTtT5EcrZ-gknHxQLnPSVMCwQgAu8CCYO0wJozBh_z8cVLL3ugf211vT9e3DFgt_pZz5hn2TzguIK_hQtML__br9bdZ4J5HvremQW9lCW6oM53G5JBxujmSZbzgOctXmFve6xwqJmYiMRu_WTgFNniJCjrR_JOjnBO2bTjsUoh7BetDQnQ6q4zjN5gK8-Y5vhrud4FT7ve7m5mjR5_2LW5T_qwJIRhgQ8a3KkmJXrBVXIiNCHesGKZ4agUK9Hy4tfP99HCHDRmOI81dfeP3SJSsV2X8YWLA7Am3x2AUxoYazOdv2FzH44NjEjpSxusrOH3fOJuJtaJEysXioIYRHHdSwpFnWyzufz_ApPkr7iZqGLGUQ0gKWoauF0DSMlECZSn7TjIp6BubrpfLrlNMt99tMIzJjhAJXQkpkwY5yneXBOKkxMJv8wco5pgAn3tFombRMj3g6T6TCSraZoaJS-54L2FOldQgbAv1Jeg1KOrDWqzKZZzDysyIef9Q-Fd-riIdSd_hbsEz06PpjCO1fvy9AXxp-20tHGE05ORkCvh6-BoqzvvXcBSPQ8TMalEC65EYYK9umfsHGIbwAZfHRBhiEianaC3bUxjkI9urZL--APN5OxJDFuyrQNWNI5zY33tZoiCJfwAGrt7WhonH-5Bom-m8fz4Hv-Q8-9VUJPmBmpKDB-ahHP6zr2vtE8xvGveJeDTu3NUYp45zD5gurHFGIpYeB-EU-SEIk2_iJnskXsBWOlw_fxK_NLrSL3Rd-XWbAoWKWBlm8GhLR_2ZhEVcUMvB4-ODHVnY2jp73FZP5fJ_eq2fajHg_o0_y1iYfg9cIhaP7-ZIpbzRG-VhkxhdDg0RgqmhpYEW3o9rl54rPNeQ_z_TK6OlmbejXUBomdJsvASzk5shRvi_hhfshpDCiqR7P1kdIgZKwmCVahUxQX7DuFOsJnMxOmrInso2oW4caIVP1N-iuQJVSOAxHYGXCg5G3eYYkjKAsRL2L2mSEPaxnNVFlv3WR3702-VuJ7RgOzd2RIvRxBSeey3HLoqyPiizU1ZJhd1cS3AmuqbLGAM1oKvAaHKULezp7xYtV1BqhdQHWIZzbOC4Ne-RTw2BINAX90E1SgWBJy8JdNbRzxWKWMPaWu2JeZ2oCVTKWzgaUDzHIZXo0x3P0Nzci3jmC4vJ049KAoKLmFewwNOjH6byfqn3AD7T_X7OMKf161LVw7qQI-uvI5SCu9PtpVoCOIhuI-jkDUhBB1vB4FeNxQVSYGAWaBB1zPpPe_IQnA2veemY-VTkD0UFfK36NzUEY2vRy1bVh_AZjc9sXS6Ep7eCXLfORf0TDZdU5G9n57qTUyX-PcdE-DVL3Ih3OPD6A4GmLlh_0PCAllRYDCtQ1hXUm-3pdH3sdo_qNLiW7cohs426U_l5fYVZ9rQJrT365T0eSWj_6BumqZT62C8oFuajucKjmHCaOCBt_4rh2LKJuegvPDWWaKx8PU8hv3h3IMeGFPgHqMXLTGbJ1UtjU2LYMDHFMeNGW9_CaBFCR-lpLW8J_COxhDWdf9MDLCOBExNX9ddCEdkntL_LzoKTznZlZzoMMgAwMewGdGGkLhmUOGI8xWIVq44p1vXshRO6eze2hlL8xwx1iU9jYTd4W230eeGkNJU-Uezs6Itjvxbb_LR-mdZcSMIIMzdBcrgRP4JJcx5fFhJvsKevoD3AQ8jDNFu3JfXgjnDlwtY8axvPdh3y8Zf_TSxveB91GFj46YD8iX52Yr0rpkYPiKniILpAhIMOZVL0VQuAGWdZnfK2bkUcxlaK49VxM8m8V-JaA9-hu_uTjzO1btpT73cljYnzqwTsheERHeElitR8T9TzLV3z9t60TkIjjYwFF2y3dxSm5VbyA_vWj4CKXLH_nelisszrN796wTBs_XkamHN8ItZByAWu7tMNPg8rUlQstZzpnzGfsJsH239ieF11QsWraAcFJS1wRU4UmFjTUqiwi_ZMtLMwH8nq723_6jK0BIH4PrDN5kmX0-e6ObQyVd1oDXz1s_r0gHnXKofd_uwe8ISwPiPtMNTF5m6AuxRiVrXHC4PfpsLcrq-iar-OVUfl94ovFZ8IoP7KAFuxVR4oiKgUqnn5ScDLcfy18EmyirhnrJms0Zfr-sjlMFYcE6I1oSneheCBXNasDtG_kq63G_GWqzbIE9z-5u95qONN1anrF6KzxOPIGAkpHvubvl51IPNJm4xoOa2zuldDa14A_x-T6UwZ-jVQhJlrYXPOvw6W9Z6-xVbIfhb5c5Umc6qYQ2zvOdD9qAnDr37-ZgJ0PMS-5_oIpLnuXZUE5VJIdx0fhZjSOJs4HzSqvjWRD_B5r5_JXMGb4j6BM9XyFr2qb688dQEx2clOoVahEHp3XIhC46yJdbd8KgfHSPa1AvlS6gcMrLcb4XAB9z2hjesANce5k1KX6uD95SqqH9xMrEQPxaZ_kh3S8smzxWey_0hl8bTzDch_KLbUQBemoBjaN3P2R4uVi1_gVwNhQ9C8sA492-plYfdAwlo-bXS6IhB07t7I52MyvNYdcutC5kqWfJD3mew8DTR2OT4LfYw03pMkP9m3bdOJAf3zNoejWPt4gpFe6FOyxilP2ysmyvjA7bQgYMf9FcAJxtOzOOa9Ww8JzOL87xZANYaDHVdxODIQ2N468CMz97arngNM_7Dzv05-TaspuwPBQQ1OBNyqYE7JsuxKKoZYnrKKuKU3KB9ELiTAT_rzOFqIG0u27gkq7Sh25n1YZ9qrUyiZ7Og2uXSsd-W1hM5b7H68LTo6tFJPb8LoXcLCK7C3bzAR7qB8kbUVsYXYNyrjdglzCFdO0OzVhs_TXJf6PC4A6DdTJFaFc_NJkIjF4QkMt7YBk-erlmePvpJcz1YsxN0wV7aHD7D2hPauukHBa-OTRlrdp-AkJQ5_PHGcwxeRDM-5xd7oB9Jk-GBBMfWGxyYy9MopyS-QLzGN2KCfZxRuywAdRX15yYWEn6wCnU3RL0WT5DNm-oFAvNtoRl36Zvmr4nDMWIhrWnFECNdMRk4jTHMQlRcaySVMGvub7delVTICvVzVOu2RiwngbECDmJbC-TAH6CsDcaJTPSi0HG6eofTlBNBlYXawGIHqQP-Bf8jgAWuxF0wgs_mugiKI8i459sTDq1eIigi7CVs1FxdNrgbK1Mp8S85jRBRITcU1eMU5MFRW_MeNuLVgscu_D8JvUWE5TMtQ5VYEd9Gd_nVPAdhqoQIFdY9KuZomFC7nZoXwS-iPCRkjphybMtI3dLgTts1WtNGhcKAggBCgUIDBDCAQoECA0QAAoECA4QAyIAKhC7Z61tbadDUJknSuvChw5-'
-H 'Droid-Guard-Salt: caf1cc51-2499-4a3a-8a7b-a0eb93534d7f'

Megatron King ***@***.***> 于2024年7月7日周日 22:43写道：

**Comment by MegatronKing** [comment]
非常感谢，成功复现问题，我先排查下原因。

**Comment by ouguochong** [comment]
> 非常感谢，成功复现问题，我先排查下原因。

好的，辛苦开发大佬了！

**Comment by MegatronKing** [comment]
v2.20.0版本已修复。
