### ISSUE TITLE
[bug] 部分域名无法抓包，连接失败

### ISSUE THREAD

**Issue by ynlczf** [reqable/reqable-app#755]
比如：必应正常抓包 百度就不行 ，之前都能正常抓包的，不知道是不是系统升级后的问题

操作系统信息
![image](https://github.com/reqable/reqable-app/assets/31738162/92268014-ada5-4b06-80d5-e51b165832c2)

reqable调试日志

07-08 14:34:11.8650 [V][Netbare]: [503] [TCP] Connecting to www.baidu.com(240e:ff:e020:9ae:0:ff:b014:8e8b):443
07-08 14:34:11.8654 [V][Netbare]: [504] [TCP] Connecting to www.baidu.com(240e:ff:e020:9ae:0:ff:b014:8e8b):443
07-08 14:34:13.8840 [V][Netbare]: [499] [TCP] Connecting to h2tcbox.baidu.com(14.215.182.183):443
07-08 14:34:13.8841 [V][Netbare]: [497] [TCP] Connecting to h2tcbox.baidu.com(14.215.182.183):443
07-08 14:34:13.8841 [V][Netbare]: [498] [TCP] Connecting to h2tcbox.baidu.com(14.215.182.183):443
07-08 14:34:13.8841 [E][Netbare]: [499] Failed to connect: h2tcbox.baidu.com
07-08 14:34:13.8841 [E][Netbare]: [497] Failed to connect: h2tcbox.baidu.com
07-08 14:34:13.8841 [E][Netbare]: [498] Failed to connect: h2tcbox.baidu.com
07-08 14:34:13.8843 [I][Netbare]: [499] TCP proxy session closed!
07-08 14:34:13.8843 [I][Netbare]: [497] TCP proxy session closed!
07-08 14:34:13.8843 [I][Netbare]: [498] TCP proxy session closed!
07-08 14:34:13.8852 [I][Netbare]: [505] TCP proxy session created!
07-08 14:34:13.8852 [I][Netbare]: [505] TCP proxy session started!
07-08 14:34:13.8855 [I][Netbare]: [506] TCP proxy session created!
07-08 14:34:13.8855 [I][Netbare]: [506] TCP proxy session started!
07-08 14:34:13.8858 [I][Netbare]: [507] TCP proxy session created!
07-08 14:34:13.8858 [I][Netbare]: [507] TCP proxy session started!
07-08 14:34:13.8859 [V][Netbare]: [505] Using https proxy protocol.
07-08 14:34:13.8860 [V][Netbare]: [506] Using https proxy protocol.
07-08 14:34:13.8860 [V][Netbare]: [507] Using https proxy protocol.

**Comment by MegatronKing** [comment]
`h2tcbox.baidu.com`这个域名解析失败，是你电脑dns解析有问题？

**Comment by ynlczf** [comment]
解析正常，尝试换过DNS服务器地址，开启代理就访问不了，关了就正常
