### ISSUE TITLE
[feature] Save websocket frames in HAR

### ISSUE THREAD

**Issue by armm29393** [reqable/reqable-app#757]
export har from android and open in reqable on macos can't see tab websocket in response section

![image](https://github.com/reqable/reqable-app/assets/22807984/d9801376-eb20-42ab-84bf-0de7fd607d27)

**Comment by MegatronKing** [comment]
We don't support websocket for HAR yet.

**Comment by MegatronKing** [comment]
v2.22.1 has done.
