### ISSUE TITLE
[bug] http://reqable.proxy/ssl无法访问

### ISSUE THREAD

**Issue by sqyww** [reqable/reqable-app#758]
![image](https://github.com/reqable/reqable-app/assets/22743174/4c8e99dd-b08f-4d83-a3b0-f991f741703c)

**Comment by MegatronKing** [comment]
@sqyww 你是最新版本吗？Reqable里面已经配置了系统代理（网络图标是绿的）吗？

**Comment by sqyww** [comment]
@MegatronKing 是的，这个连接是下载证书的链接，昨天还能打开，今天打不开了

**Comment by MegatronKing** [comment]
> @MegatronKing 是的，这个连接是下载证书的链接，昨天还能打开，今天打不开了

试试吧域名换成 `localhost:端口`看看
