### ISSUE TITLE
脚本报错 [TypeError: unsupported operand type(s) for |: 'type' and 'type'] 

### ISSUE THREAD

**Issue by lsq665** [reqable/reqable-app#76]
抓包时右键生成的脚本，加个回车就报错，
![image](https://github.com/reqable/reqable-app/assets/80682634/5fb086ff-c192-45a0-81fb-0f4534fa8377)
使用文档中的测试脚本也都是这个错误

**Comment by lsdlh** [comment]
> 看样子是用了python 3.9不支持的语法，你试试3.10或者3.11 python版本

![1687231924102.png](https://pic.ziyuan.wang/2023/06/20/f212912de4943.png)
py3.11,输出里中文乱码

**Comment by MegatronKing** [comment]
> > 看样子是用了python 3.9不支持的语法，你试试3.10或者3.11 python版本
> 
> ![1687231924102.png](https://camo.githubusercontent.com/0316c1d812f09fc2f63fa1d44896df974cf8f16c24e907b7b3111ff529a2d2de/68747470733a2f2f7069632e7a697975616e2e77616e672f323032332f30362f32302f663231323931326465343934332e706e67) py3.11,输出里中文乱码

并不能复现这个乱码问题
