### ISSUE TITLE
[feature] 如何重定向的同时rewrite path

### ISSUE THREAD

**Issue by gaoyuanbj05** [reqable/reqable-app#760]
例如：将 https://foo.com/a/b/index.html 转发到 http://localhost:3000/index.html
请问该如何实现呢？

**Comment by MegatronKing** [comment]
参考这个文档：https://reqable.com/zh-CN/docs/capture/rewrite#redirect

**Comment by gaoyuanbj05** [comment]
> 参考这个文档：https://reqable.com/zh-CN/docs/capture/rewrite#redirect

感谢回复，我看过文档了，但是重定向貌似只支持 /* 匹配全部子路径，也就是转发到 http://localhost:3000/a/b/index.html 但我想实现的是局部路径，即 http://localhost:3000/index.html ，这个有办法吗？

**Comment by MegatronKing** [comment]
@gaoyuanbj05 

啊抱歉，我竟然忘记回复这个issue了。可以用通配符`*`匹配全部子路径，也可以直接写固定路径，你提的肯定是支持的。刚刚发布了2.24.0版本，优化了一些重定向问题，可以用最新版本试试。

另外，Issue我先关闭了。
