### ISSUE TITLE
[feature] 希望增加 TCP UDP 的流量解析

### ISSUE THREAD

**Issue by Kn0wns** [reqable/reqable-app#761]
可以参考 sunny 相关的软件, sunny 这个项目经常容易崩溃 鲨鱼用起来又不是很便携

<img width="1510" alt="Snipaste_2024-07-10_17-57-04" src="https://github.com/reqable/reqable-app/assets/76414050/7f8caf43-546e-4bf9-b27a-c95fdc8e10c8">

**Comment by MegatronKing** [comment]
同 #59
