### ISSUE TITLE
websocket message解析显示错误

### ISSUE THREAD

**Issue by oopses** [reqable/reqable-app#762]
版本2.2.0  win10免安装

对同一个websocket抓包，fiddler显示正常reqable 显示有截断
![IMG_export_20240711_131136214](https://github.com/reqable/reqable-app/assets/17480732/6a2cedfe-dbb6-4d60-813e-21d36f1f0075)
![IMG_export_20240711_131131641](https://github.com/reqable/reqable-app/assets/17480732/0cf609eb-e871-423a-9234-fe1d691211c4)

**Comment by MegatronKing** [comment]
感谢反馈，请问websocket地址可以提供下用来测试验证吗？

**Comment by oopses** [comment]
> 感谢反馈，请问websocket地址可以提供下用来测试验证吗？

内网服务，你那边应该无法直接访问，所以我搞了个demo可以复现，

ws.py  本地起一个ws，利用postman或者hoppscotch直连这个ws， Proxiffier全局代理，发送一个字符串信息即可， 比如  ping ，我观察到一般发送第二个ping，reqable那边显示就异常了
```
import asyncio
import websockets
import json



async def echo(websocket, path):
    async for message in websocket:
        data = {'type': 'pong',"data": "pong"}
        await websocket.send(json.dumps(data))


asyncio.get_event_loop().run_until_complete(websockets.serve(echo, 'localhost', 18765))
asyncio.get_event_loop().run_forever()
```

**Comment by MegatronKing** [comment]
非常感谢， 我测试下看看

**Comment by MegatronKing** [comment]
在windows设备上复现了，也许是内存问题，需要进一步排查。

**Comment by MegatronKing** [comment]
我的现象和你有点不一样，我排查下来是因为没支持数据解压。我这边如果server配置成这种就没有问题了，你可以试试看。
```
asyncio.get_event_loop().run_until_complete(websockets.serve(echo, 'localhost', 18765, compression=None))
```

**Comment by MegatronKing** [comment]
@oopses 不确定你那边是不是也是compression的问题？

**Comment by oopses** [comment]
> @oopses 不确定你那边是不是也是compression的问题？

后端是java的，我没去排查，之前使用Fiddler抓包，所以我对比了一下

**Comment by MegatronKing** [comment]
@oopses 发布了2.20.1版本，我测试问题已经修复了，你有空可以确认下。

**Comment by oopses** [comment]
@MegatronKing 下载更新，验证已正常  👍
