### ISSUE TITLE
[bug] post请求数据类型为multipart,一个参数为file,发送请求一直等待返回

### ISSUE THREAD

**Issue by veincheng** [reqable/reqable-app#764]
**Describe the bug**
post请求数据类型为multipart,一个参数为file,发送请求一直等待返回,没有立即显示结果

**To Reproduce**
1. POST请求,请求体数据类型选择multipart,参数设定几个,其中一个为file,选择本地图片,其他随意
2. 点击发送,响应体这边是显示等待状态,没有立即返回数据
3. 等待状态

**Expected behavior**
返回打印的数据

**Screenshots**
![issue111](https://github.com/user-attachments/assets/562c1063-1862-470c-a163-44d034c1085f)

**Information**
 - Platform: windows
 - OS: 11
 - Arch: x86-64
 - App Version: 2.20.0

**Comment by veincheng** [comment]
经过本人测试,问题应该是出在app给出默认的响应头,计算内容长度（Content-Length) 没有运行,导致无法出结果。只要设定Content-Length为确定的值,覆盖默认的值，可以立即返回数据。

**Comment by MegatronKing** [comment]
不知道是否和服务端的实现有关，我用`https://httpbin.org/post`测试正常。

<img width="1080" alt="截屏2024-07-12 13 26 33" src="https://github.com/user-attachments/assets/1054d886-cc27-43b4-981b-e3e0fb92ac35">

**Comment by MegatronKing** [comment]
你试试`https://httpbin.org/post`是否正常？

**Comment by veincheng** [comment]
我用httpbin测试了下确实没什么问题，但是我后端是简单的php自带server启动的处理图片返回请求信息而已。也许是php 自带的server 处理content-length 有点问题。你有php的话你也可以看看能不能重现

**Comment by MegatronKing** [comment]
@veincheng 你说的默认content-length是整体的还是分部的？

**Comment by veincheng** [comment]
![issue22222](https://github.com/user-attachments/assets/bd81f4cc-b55c-446e-82b1-c091de11b82d)
根据本人观察，应该是请求已经成功了，并且已经返回200，但是结果渲染这块一直说等待计算。估计是App处理结果的渲染逻辑有些问题。跟后端关系不大。默认的content-length是自动计算

**Comment by MegatronKing** [comment]
话说你server返回的是什么数据格式？有没有可能server返回的content-length不对，或者缺少content-length？

**Comment by veincheng** [comment]
我检查了下软件的配置，检查了代理，正常了。
