### ISSUE TITLE
全局搜索的逻辑和在响应体搜索的逻辑不一[feature] 

### ISSUE THREAD

**Issue by LiuZ0814** [reqable/reqable-app#765]
**Is your feature request related to a problem? Please describe.**
比如我的响应体是这个

            "registerDay": 389,
            "avatarUrl": null
![image](https://github.com/user-attachments/assets/ea1c99ee-50b6-4962-a84b-48e1609c3c87)

那我用全局搜索的时候就得是这样才搜得到registerDay":389(注意去掉了空格)
![image](https://github.com/user-attachments/assets/d8c12596-7866-4927-9974-bcaac6f41402)

而在响应体搜索的时候就得改成registerDay": 389(加上了空格)
![image](https://github.com/user-attachments/assets/b700a574-7298-4dd3-9b91-52014d2abf73)

**Describe the solution you'd like**
我觉得全局搜索的逻辑应该改成在响应体里搜索那样

**Comment by MegatronKing** [comment]
@LiuZ0814 抱歉，回复晚了。因为你原始请求体应该就是不带空格的，响应体Tab下默认展示的是格式化之后的数据，你切换到raw下面看看原始响应体是不是不带空格呢？

**Comment by MegatronKing** [comment]
这是正常现象不是Bug，关闭此Issue。
