### ISSUE TITLE
[bug] [严重]不能获取http请求

### ISSUE THREAD

**Issue by ed6896** [reqable/reqable-app#766]
**Describe the bug**
局域网服务器部署的web项目，有独立的http://ip:port, 不是localhost访问的请求。
在个人电脑上打开reqable并开启代理后，reqable抓不到http请求，但是能抓取如百度等https请求

个人电脑：
谷歌浏览器
最新版本reqable

**Comment by MegatronKing** [comment]
@ed6896 代理菜单里面把配置回环开关开启，或者你更新最新版本v2.20.2试试。

**Comment by MegatronKing** [comment]
@ed6896 你好，问题解决了吗？

**Comment by MegatronKing** [comment]
没有进一步的用户回复，问题关闭。

**Comment by Mo-life** [comment]
我今天下载这个这个工具，也发现了这个问题。下载的Windows中最新的社区版，我在本地PC启动了一个web项目，是http://localhost:port/ 访问本地系统。但是把reqable并开启代理后进无法访问了，关掉配置回环开关就可以正常访问。我有抓本地包的需求，fiddler代理就不会有任何影响。
