### ISSUE TITLE
[feature] 希望新增data转json功能

### ISSUE THREAD

**Issue by Dawnnnnnn** [reqable/reqable-app#769]
![QQ_1721109332388](https://github.com/user-attachments/assets/202eb632-4d9f-4f88-802f-132be29d51a9)

希望针对这种 application/x-www-form-urlencoded 格式的数据，能够选中data后右键复制为json字符串，用于粘贴到IDE中快速编辑，现在只能手动造一个json体出来

期望：
    
      原数据：a=1&b=2&c=3
      复制数据: {"a":1,"b":2,"c":3}

**Comment by MegatronKing** [comment]
v2.20.2已支持。
