### ISSUE TITLE
高亮规则是不是有问题

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#77]
![image](https://github.com/reqable/reqable-app/assets/1797392/e4bb9a4b-c776-4c4f-be0d-f10b7b8464dd)
![image](https://github.com/reqable/reqable-app/assets/1797392/c5f92bdb-8b84-4529-bbe1-d48e1aa4969b)

同样的规则有的灰色有的不是灰色

**Comment by MegatronKing** [comment]
有可能是多次调整高亮规则导致的。比如你先设置了GET灰色，然后又把GET改成了其他，之前的GET仍然是灰色，新出现的就不是灰色了。你看看是不是这样的？

**Comment by RonaldinhoL** [comment]
> 

不是，我只设置了 connect/options 的灰色规则和 4xx/5xx的红色规则

**Comment by RonaldinhoL** [comment]
中途没有修改过

**Comment by MegatronKing** [comment]
ok，感谢反馈，我知道原因了。

**Comment by MegatronKing** [comment]
@RonaldinhoL v1.0.5版本已修复。
