### ISSUE TITLE
[feature] API调试数据类型Multipart支持文本模式编辑，参考postman的form-data数据格式的Bulk Edit功能

### ISSUE THREAD

**Issue by cry980285208** [reqable/reqable-app#772]
reqable的Multipart数据类型编辑很不方便，API调试数据类型Multipart支持文本模式编辑，参考postman的form-data数据格式的Bulk Edit功能，或者参考reqable的urlencode数据类型的编辑功能

postman
![image](https://github.com/user-attachments/assets/2b58e2a2-3a0f-4377-84c0-7bf2754c1547)
![image](https://github.com/user-attachments/assets/2bbe4a90-8466-463c-836e-078f848e4c2f)

reqable
![image](https://github.com/user-attachments/assets/9c1b44a9-ec6b-4006-902a-bb38977bcc5a)
![image](https://github.com/user-attachments/assets/fd282176-ca14-4daa-ad69-3450d959612a)

**Comment by MegatronKing** [comment]
感谢反馈，form确实漏了文本编辑模式。

**Comment by MegatronKing** [comment]
忘记回复了，这个需求已经实现，更新版本即可。
