### ISSUE TITLE
[bug] 指定 host 时会发送到错误的地址

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#773]
![image](https://github.com/user-attachments/assets/1540dd63-50d2-4994-a308-9fbce300a634)
当指定了host时会发送到 host 指定的地址而不是 url 中的地址

**Comment by ljq8896** [comment]
http协议规则就是如此

**Comment by ljq8896** [comment]
带host的url在解析成http(s)请求时会把host:port解析到head中的host字段，鉴于你已经指定了host，就不会解析url中的host

**Comment by RonaldinhoL** [comment]
> http协议规则就是如此

curl -k -H "host:xxx.com" https://x.x.x.x/xxx 

curl可以使用这种方式，host并不会影响ip地址

**Comment by ljq8896** [comment]
> > http协议规则就是如此
> 
> curl -k -H "host:xxx.com" https://x.x.x.x/xxx 
> 
> curl可以使用这种方式，host并不会影响ip地址

curl 违反了rfc规范 最新的规范是如果以绝对形式uri发送请求，对header中的host进行解析并发送，但服务商收到请求后忽略header中的host值，使用uri重新生成host。
上一版规范中，去过绝对形式uri中的uri-host与header中的host不同，返回400错误。
