### ISSUE TITLE
[bug] 返回值为<gzip binary body>时，响应体解析中包含多余数据

### ISSUE THREAD

**Issue by Dawnnnnnn** [reqable/reqable-app#774]
![QQ_1721197267677](https://github.com/user-attachments/assets/e2f6b084-d0b2-49a4-869e-6fc5e24d964f)
![QQ_1721197284506](https://github.com/user-attachments/assets/d57ac0b8-b69a-469e-a65a-da2f7b110116)
![QQ_1721197328404](https://github.com/user-attachments/assets/f6c6418c-c0bc-40cf-9777-9a4d2770a06f)

虽然这个可能是原数据，但用户大概并不需要看到这种数据。如果一定要加，建议将这种带有多余数据的放到原始响应tab里，响应体tab里放优化后的数据，原始响应tab里的<gzip binary body>感觉也没有什么意义

**Comment by Dawnnnnnn** [comment]
这种数据还影响了响应体tab中的json解析，实在是难以阅读

**Comment by MegatronKing** [comment]
因为这个就是gzip解压后的数据，看起来像是chunked编码，但不是原始数据。

**Comment by Dawnnnnnn** [comment]
我手动删掉第一行和最后一行尝试在网页里json解析看，没想到第三行还有。。现在这太难用了
![QQ_1721199377875](https://github.com/user-attachments/assets/e5eb1a39-5208-4f9f-a2f5-b06b4d256a5a)

**Comment by MegatronKing** [comment]
但是，这和reqable一点关系都没有。数据就是这样，你不能怪别人。

**Comment by Dawnnnnnn** [comment]
我懂了，这就是接口返回的结果....看来只能手动解析处理这类数据了
