### ISSUE TITLE
[feature] 建议优化调试页面操作

### ISSUE THREAD

**Issue by SebaSs007** [reqable/reqable-app#776]
问题：
1、应用角度存在多应用混杂一起，无法在抓包结束后快速清除无用流量、一些不需要的图片、视频也无法快速清理。
2、抓包流量在选中时可以通过划动方式批量操作，但是如果需要选择其中不连续的几段流量 划动时会取消前面选中的内容。
3、reqable可以查看导出的har文件，但是无法进行编辑操作，比如我想对har文件里的一些无用流量进行清理，然后再重新导出为新的版本，结合第2点 就很费事，这部分我只能借用  fiddler来处理。

优化建议：1、参考fiddler 增加Content-Type 列 划分流量类型，并且可以针对选中的行列的值，批量选中页面中相同的流量
![image](https://github.com/user-attachments/assets/0ab6057b-f20c-41b8-ae1b-f9e8f291e1d9)
2、按住ctrl键 可以划动选中不连续的部分。
3、增加对har文件的更多编辑操作。

**Comment by MegatronKing** [comment]
你好，感谢反馈。

> 1、参考fiddler 增加Content-Type 列 划分流量类型，并且可以针对选中的行列的值，批量选中页面中相同的流量
`Content-Type`列是有的，默认不显示，你右键菜单里面勾选上。可以排序，但是批量选择功能是没有的。

> 2、按住ctrl键 可以划动选中不连续的部分。
这个细节确实忽略了，我补上。

> 3、增加对har文件的更多编辑操作。
这个功能已经在下个版本计划中了。

**Comment by MegatronKing** [comment]
@SebaSs007 2和3已经实现，更新版本即可。
