### ISSUE TITLE
[bug] 堆栈跟踪没作用

### ISSUE THREAD

**Issue by Mrqqeat** [reqable/reqable-app#777]
这个功能听说是和算法助手Pro一起使用的，re最新版本20.2, + 算法助手pro，LSPosed和算法助手均勾选了reqable和对应APP，且算法助手开起来堆栈跟踪，reqable中也启用了堆栈跟踪选项卡，抓完包后并没有该选项卡，官网文档也没发现对此功能的介绍

**Comment by abigmiu** [comment]
我虚拟机运行算法助手， 然后真机抓虚拟机的包也不会出现堆栈
