### ISSUE TITLE
[bug] windows安装后无法启动netbare engine

### ISSUE THREAD

**Issue by hlj1350** [reqable/reqable-app#78]
**Describe the bug**
错误日志文件
windows "Windows 10 Pro" 10.0 (Build 22621) 1.0.5(21) x86_64
06-20 18:23:28.1460 [I][Dart]: App logger is ready now.
06-20 18:23:28.1460 [V][Dart]: Pre-initing app...
06-20 18:23:28.1460 [V][Dart]: App pre-init done.
06-20 18:23:28.1460 [V][Dart]: Post-initing app...
06-20 18:23:28.1517 [V][Dart]: Initing netbare engine...
06-20 18:23:28.1537 [V][Dart]: Loading CA certificate...
06-20 18:23:28.1537 [V][Dart]: CA certificate is found from cache.
06-20 18:23:28.1547 [V][Dart]: Starting netbare engine on port 9000
06-20 18:23:28.1547 [E][Dart]: Unable to start netbare engine: errorUnknown!
06-20 18:23:28.1568 [V][Dart]: App post-init done.
06-20 18:23:29.1482 [V][Dart]: Event: app_start
06-20 18:23:29.1977 [V][Dart]: Detecting python env version: python3.exe
06-20 18:23:29.3403 [I][Dart]: Python env detect output: Python 3.10.7

06-20 18:23:29.7157 [V][Dart]: Local IP detected: 192.168.31.45
06-20 18:23:29.7157 [I][Dart]: Use local IP: 192.168.31.45
06-20 18:23:29.9924 [I][Dart]: Check update ok, has update: false
06-20 18:23:32.5839 [V][Dart]: Event: capture_proxy_off
06-20 18:23:44.3295 [V][Dart]: Event: capture_engine_start
06-20 18:23:44.3295 [E][Dart]: Failed to start netbare engine, code NetBareCode.errorUnknown
06-20 18:23:48.5888 [V][Dart]: Event: menu_file_open_file
06-20 18:23:48.5888 [V][Dart]: Event: work_shortcut_open_har
06-20 18:23:58.4596 [V][Dart]: Event: menu_help_goto_documentation
06-20 18:25:20.4495 [V][Dart]: Event: menu_help_check_update
06-20 18:25:20.8408 [I][Dart]: Check update ok, has update: false
06-20 18:27:41.3758 [V][Dart]: Event: menu_help_goto_feedback
06-20 18:28:50.5937 [V][Dart]: Showing window settings
06-20 18:28:50.5937 [V][Dart]: Popuping window settings
06-20 18:28:50.5937 [V][Dart]: Event: window_popup_settings

**To Reproduce**
1.官网下载windwos安装包
2. 安装到D盘
3. 自动运行软件后点击启动

**Expected behavior**
应该启动调试

**Screenshots**
![QQ截图20230620183140](https://github.com/reqable/reqable-app/assets/46241289/9b8f7bf6-6351-4de0-ba5d-85bf6784eb32)

**Information**
弹窗提示NetBareCode.errorUnknown

**Comment by MegatronKing** [comment]
@hlj1350 试试切换个端口，或者看看是不是被火绒等防火墙类软件拦截了禁止网络访问。实在不行，重启下机器试试。

**Comment by hlj1350** [comment]
更换端口后解决问题
