### ISSUE TITLE
历史记录保存在什么位置

### ISSUE THREAD

**Issue by z3c3c** [reqable/reqable-app#780]
我正在使用 Android 的 Reqable 客户端，**我想知道历史记录保存在什么位置**，方便我批量地针对性地管理历史流量，而不是全部删除或者只能删除某条记录。

**Comment by MegatronKing** [comment]
在box数据库里面

**Comment by z3c3c** [comment]
感谢回复，能否再具体一点，我并没有找到相关的 db 文件。
<img width="712" alt="image" src="https://github.com/user-attachments/assets/4ed25bb6-b106-4c48-aec6-1f25fbd62527">
