### ISSUE TITLE
[bug] 二级代理无法使用带验证的HTTP PROXY

### ISSUE THREAD

**Issue by beck-8** [reqable/reqable-app#782]
**Describe the bug**
二级代理无法使用带验证的http proxy

**To Reproduce**
1. 使用GOST 起一个不带验证的http代理
2. reqable启用二级代理，一切正常
3. GOST加上验证用户名/密码都是 1
4. 给reqable二级代理增加密码
5. 所有的请求都是CONNECT状态

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [macos]
 - OS: [14.5]
 - Arch: [M1]
 - App Version: [2.20.2]

**Comment by MegatronKing** [comment]
v2.21.0已修复此问题。
