### ISSUE TITLE
MagiskModule 安装报证书不安全

### ISSUE THREAD

**Issue by zhiyu-zeng** [reqable/reqable-app#785]
自带的MagiskModule 安装后报证书不安全

证书安装至系统目录后，手动移入系统证书目录或者使用其他移动证书的模块不报，使用过的设备都是这样的情况

**Comment by MegatronKing** [comment]
系统安全提示和reqable完全关系。

**Comment by zhiyu-zeng** [comment]
是用自带的Magisk模块报的，卸载后使用第三方证书移动模块，或者手动移入，不会报
