### ISSUE TITLE
[feature] 许可证激活验证支持用户配置代理

### ISSUE THREAD

**Issue by Xarriors** [reqable/reqable-app#786]
所在的开发环境处于内网，访问外部网络需要经由系统代理，当前激活流程应该是走直连了，导致软件激活失败

需要激活流程也支持走代理服务器

![image](https://github.com/user-attachments/assets/c80b4876-dd9a-4ecf-8e44-d5ce52e2217c)

![image](https://github.com/user-attachments/assets/07f6230a-412c-4059-b5f5-65685a3c9523)

**Comment by Xarriors** [comment]
或者支持离线注册

**Comment by MegatronKing** [comment]
v2.21.0已支持配置代理。
