### ISSUE TITLE
[feature] 关于 `Ctrl`+`Enter` 快捷键

### ISSUE THREAD

**Issue by xuanzhi33** [reqable/reqable-app#787]
## 现状
我在编辑请求Headers字段的时候按下`Ctrl`+`Enter`，发送的请求是编辑前的请求头。只有当我按下回车或鼠标点击其他区域后，再按下按下`Ctrl`+`Enter`，发送的内容才是修改后的。

## 建议
按下`Ctrl`+`Enter`时应该直接使用新的内容进行发送，更符合直觉。

**Comment by MegatronKing** [comment]
编辑的时候不会直接更新，只有输入完成（焦点丢失）才会实际更新数据，不然性能就太拉了。下个版本，`Ctrl`+`Enter`按下之后，强行关闭编辑模式，更新完数据再发送请求。

**Comment by MegatronKing** [comment]
v2.21.0已解决。
