### ISSUE TITLE
[bug] 桌面端Win10专业版 证书安装上依旧提示未安装证书

### ISSUE THREAD

**Issue by Arui66** [reqable/reqable-app#788]
![image](https://github.com/user-attachments/assets/93e6ffb2-d15f-40db-a57c-787dc9cd0a33)
reqable版本是最新版的2.20.2
reqable安装版跟免安装版本都尝试过
![image](https://github.com/user-attachments/assets/ed761e67-cf2e-419e-9ffa-d5c164afa1fb)
证书自动安装  跟手动导入也操作过
手动导入时候的存储位置   当前用户 和 本地计算机 也都选择过  
安装完重启电脑还是不行  
不知道是我哪里操作不对
希望开发者看到帮忙看一下

**Comment by MegatronKing** [comment]
1. 检测下证书信息，对比指纹，确保安装的证书和reqable当前证书是同一个。
2. 排除360等安全软件的影响。

**Comment by Arui66** [comment]
> 1. 检测下证书信息，对比指纹，确保安装的证书和reqable当前证书是同一个。
> 2. 排除360等安全软件的影响。

![image](https://github.com/user-attachments/assets/fed0104b-cb56-4903-b9a6-6715ab93c4cb)
左边的是已安装的信息   右边的是导出来的证书信息 我看着都是一样的（其实我不懂...），并没有安装360等杀毒软件

**Comment by Arui66** [comment]
我手动删除了证书  重新安装又好了（不知道是为什么）打扰了
