### ISSUE TITLE
[bug] 网关筛选静默不生效

### ISSUE THREAD

**Issue by fyfyfy982** [reqable/reqable-app#79]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@fyfyfy982 我没有能复现这个问题，是不是忘记开启右上角调试了？

**Comment by fyfyfy982** [comment]
不是啊，我是想过滤掉一个包
![image](https://github.com/reqable/reqable-app/assets/70060630/91f20eba-c542-453f-bb3b-a8e762894682)
我不知到是不是我用法不对

**Comment by MegatronKing** [comment]
需要使用wildcard匹配path子目录

**Comment by fyfyfy982** [comment]
不能直接通过地址过滤吗
