### ISSUE TITLE
如何从 box 数据库中恢复历史记录数据

### ISSUE THREAD

**Issue by z3c3c** [reqable/reqable-app#791]
如题，由于我有批量处理历史记录的需求，但是工具中仅支持单条转换成 har，所以有两问题：
1. 如何从 box 数据库（data.mdb  lock.mdb恢复历史记录）
2. 如何将.reqable 文件转换成 .har 文件

**Comment by MegatronKing** [comment]
1. box数据库记录格式应该是二进制的，类似protobuf。没有原始数据格式，可能不太好处理，但是这个我也没法提供。
2. .reqable是json格式，写个脚本解析转换即可。

**Comment by z3c3c** [comment]
多个 reqable 文件和一条历史记录的对应关系是怎样的呢

**Comment by MegatronKing** [comment]
> 多个 reqable 文件和一条历史记录的对应关系是怎样的呢

这个很难讲清楚的。话说你这个需求是什么，要读历史数据？

**Comment by z3c3c** [comment]
是的，我需要从历史数据里面读取所有的 url、生成的时间戳以及对应的应用等信息

**Comment by z3c3c** [comment]
如果很难对应的话，能够获取时间戳感觉也可以

**Comment by MegatronKing** [comment]
> 如果很难对应的话，能够获取时间戳感觉也可以

和前面一样的，没有原型文件，很难解析。运行时处理数据不行吗，一定要结束之后读历史记录处理？

**Comment by z3c3c** [comment]
因为要处理的数据量会很大数百GB甚至 TB，所以通过服务器批量并行处理性能会比在运行时处理更好，而且就算是运行时处理，处理后的数据还是需要导出到服务器上的。如果运行时处理的话，你的方案是啥样的呢？

**Comment by MegatronKing** [comment]
> 因为要处理的数据量会很大数百GB甚至 TB，所以通过服务器批量并行处理性能会比在运行时处理更好，而且就算是运行时处理，处理后的数据还是需要导出到服务器上的。如果运行时处理的话，你的方案是啥样的呢？

看看这个：https://reqable.com/zh-CN/docs/capture/report-server

**Comment by z3c3c** [comment]
但安卓客户端上貌似没有上报功能~

**Comment by MegatronKing** [comment]
> 但安卓客户端上貌似没有上报功能~

这功能全平台都有。

**Comment by z3c3c** [comment]
我刚刚看了一下，并没有在安卓客户端中找到 [使用方法](https://reqable.com/zh-CN/docs/capture/report-server#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F) 中提到的 工具 -> 报告服务器

**Comment by MegatronKing** [comment]
> 我刚刚看了一下，并没有在安卓客户端中找到 [使用方法](https://reqable.com/zh-CN/docs/capture/report-server#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F) 中提到的 工具 -> 报告服务器

移动端目前没有专门的文档，在右上角更多菜单中打开。
