### ISSUE TITLE
[bug] 在遇到编码非 UTF-8 时无法显示文字预览

### ISSUE THREAD

**Issue by 01101sam** [reqable/reqable-app#793]
**Describe the bug**
使用 API 调试工具时，有些网站并非 `UTF-8` (如 `BIG5`, `BGK`, `Windows-31J` 等)

例如: `Content-Type: text/html; charset=Windows-31J`

这导致 HTML 预览选项消失，只有 HEX

**To Reproduce**
1. Go to [This URL](https://www2.mufgcard.com/inet/life/ninsyou/entry/kitei2.html?pacd=1&lid=register_mufg)
2. Click on 'Send'
3. See error

**Expected behavior**
> 取自 POSTMAN

![image](https://github.com/user-attachments/assets/27d9f5d7-bbc2-4e95-b453-7dc3f766281e)

正常预览
![image](https://github.com/user-attachments/assets/3a7d67d8-f7ef-400f-ab46-b69f8fcfcc1b)

**Screenshots**
![image](https://github.com/user-attachments/assets/a46a640b-da3e-462a-b8b7-e80acb58c68c)
![image](https://github.com/user-attachments/assets/90a1e888-10d3-4b18-a7f2-ebd4ab5270bb)

**Information**
 - Platform: Windows
 - OS: 10 LTSC
 - Arch: AMD x86_64
 - App Version: 2.20.2 (99)

**Comment by MegatronKing** [comment]
你好，感谢反馈。这个编码好像确实不支持。

**Comment by MegatronKing** [comment]
版本2.21.2已支持`Windows-31J`编码。
