### ISSUE TITLE
文本对比工具建议

### ISSUE THREAD

**Issue by wuewill** [reqable/reqable-app#795]
![image](https://github.com/user-attachments/assets/54b93158-7d6f-45ac-a5fd-3c2f4b1d2e94)
![image](https://github.com/user-attachments/assets/fc0d48ba-4fa3-44b0-8b98-7d01ae0267cb)

能否把对比工具改成这样的，原版的很难分辨出到底哪里不一样，改成这样可以更直观的看出分别

**Comment by MegatronKing** [comment]
你好，感谢建议，同 #5
