### ISSUE TITLE
[feature] 证书安装模块支持apatch

### ISSUE THREAD

**Issue by karhow** [reqable/reqable-app#798]
现在的证书模块安装只支持magisk和ksu，在apatch的root环境安装不了证书模块，虽然apatch支持部分magisk模块的，作者可以顺便适配一下apatch的证书安装模块吗？

**Comment by MegatronKing** [comment]
你好，非常抱歉，我不懂apatch这个，magisk模块还是社区小伙伴提供的。

**Comment by Kn0wns** [comment]
我测试机就是apatch 可以正常使用这个模块

**Comment by karhow** [comment]
> 我测试机就是apatch 可以正常使用这个模块

我这边好像不可以，我的环境是这样的![IMG_20240724_104252.jpg](https://github.com/user-attachments/assets/3e3195f0-5cf8-4306-8ed0-486f36e8a38f)

![Screenshot_2024-07-24-10-42-28-15_7fac49e5329bfa70bf0c1257a1a51d55.jpg](https://github.com/user-attachments/assets/c31026c3-6b3c-4742-9927-2eb2dd0aa14d)

![Screenshot_2024-07-24-10-42-18-51_26ccd656f4ada08d09da6514b90ed2c0.jpg](https://github.com/user-attachments/assets/f71c9171-29e6-49e3-9569-3b5af151dbc4)

**Comment by MegatronKing** [comment]
@karhow 可能是和其他证书模块冲突？或者没安装错了模块？既然前面有小伙伴说可以，只能你自己检查下操作步骤了。

**Comment by karhow** [comment]
> @karhow 可能是和其他证书模块冲突？或者没安装错了模块？既然前面有小伙伴说可以，只能你自己检查下操作步骤了。

我检查过，真的没找到原因，安装日志也是正常的，可以帮忙咨询一下模块的作者吗？![Screenshot_2024-07-25-22-49-39-26_26ccd656f4ada08d09da6514b90ed2c0.jpg](https://github.com/user-attachments/assets/3e5c23c8-f7c1-4ed7-8627-aa4acfeb45dd)

![Screenshot_2024-07-25-22-49-21-46_26ccd656f4ada08d09da6514b90ed2c0.jpg](https://github.com/user-attachments/assets/39d91b68-acde-4465-abeb-58407976a08e)

![Screenshot_2024-07-25-22-49-13-66_26ccd656f4ada08d09da6514b90ed2c0.jpg](https://github.com/user-attachments/assets/bb82e8f5-5cee-4019-8f28-d7d8194fa8ce)

**Comment by MegatronKing** [comment]
这个问题我无法帮你，既然有说可以，那issue先关闭了。
