### ISSUE TITLE
[feature] 希望json格式数据能显示字段的数量

### ISSUE THREAD

**Issue by leeyiding** [reqable/reqable-app#800]
类似图示的功能

![image](https://github.com/user-attachments/assets/c1ea632e-bc24-4185-b9ed-58c17f0b2588)
![image](https://github.com/user-attachments/assets/d7b23660-c227-49d4-b4d5-a50abc4afa06)

**Comment by MegatronKing** [comment]
你好，感谢建议。这个需求同 #185 。
