### ISSUE TITLE
[feature] 保存常用的过滤设置

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#804]
比如我加了 url不包含 .css .png .svg 等，希望可以保存并在其他地方一键应用，不然切换搜索很麻烦

**Comment by MegatronKing** [comment]
v2.28.0已实现。

**Comment by RonaldinhoL** [comment]
![image](https://github.com/user-attachments/assets/8cdbb58b-ee31-4493-87d5-18b1e04ec8f5)

能同时应用就更好了
