### ISSUE TITLE
[feature] 复制curl以及编辑API时的编码问题

### ISSUE THREAD

**Issue by KingFuRong** [reqable/reqable-app#806]
当我复制curl或者编辑API时，请求会因为URL编码问题被服务器拒绝响应
<img width="843" alt="截屏2024-07-25 14 29 37" src="https://github.com/user-attachments/assets/a6a65d30-5ea7-4ffe-902a-ef6ebf4d7e80">

**Comment by MegatronKing** [comment]
你好，感谢反馈。问题是期望编码实际没有编码，还是期望不编码实际编码了？还有curl能发下看看吗？

**Comment by KingFuRong** [comment]
感谢你的回复，我期望的是编码的，使用编辑API或者复制curl得到的是未编码的
<img width="898" alt="截屏2024-07-25 14 49 26" src="https://github.com/user-attachments/assets/60bc4092-75db-4604-9248-0c0ba11f1f9d">
这张图片中，红色标识出来的是原始的请求，绿色标识出来的是通过编辑API发出的请求

curl如下
curl -X GET 'https://api.m.jd.com/client.action?t=1721890065469&loginType=11&loginWQBiz=golden-trade&client=android&clientVersion=8.0.47&osVersion=Android%2014&screen=407*904&networkType=wifi&d_brand=Redmi&d_model=23078RKD5C&lang=zh_CN&sdkVersion=3.3.5&openudid=oA1P50NgALLs0hjTmoL2shpdA7Ns&uuid=10244140987371708491131090&functionId=getCommentListAppletForJd&appid=wx_item_new&body=%7B%22source%22:%22wxaitem%22,%22deviceUUId%22:%22%22,%22platform%22:2,%22uuid%22:%2210244140987371708491131090%22,%22deviceType%22:%2223078RKD5C%22,%22referer%22:%22http%3A%2F%2Fwq.jd.com%2Fwxapp%2Fpages%2Findex%2Findex%22,%22detailVersion%22:%222%22,%22fVersion%22:%221.4.9%22,%22version%22:%22v2%22,%22sku%22:%2210098322758683%22,%22page%22:1,%22pagesize%22:10,%22sorttype%22:5,%22tenantCode%22:%22jgminise%22,%22bizModeClientType%22:%22WxMiniProgram%22,%22callback%22:%22getCommentList%22,%22score%22:4%7D&scval=undefined&xAPIScval2=wx&h5st=20240725144745477;5m5yim566i9zgnt0;565d6;tk03ac9c71c6e18pMngzeDJ4MiszOEhVbrxTzaJ0kGxHiU03vZ1ZLQIl6ojriXCFr5kh2U0LnE_rvqxIVbcUK-_D7XA5;46266e7655a32860ef0142c7f86978d21cb9171d1250af40593a9286ecf0ac6b;4.7;1721890065477;VSXGJZkYq4ErsLhBbPB74wZ2qj57Ki30vI1cxmoDKtciUq_sQp-0fMi-dY5gWOg_lMww5No9XXtUKoG_zM8C9lskDZ_6meLNc05SUqlLwGqp' -H 'User-Agent: Mozilla/5.0 (Linux; Android 14; 23078RKD5C Build/UP1A.230905.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.186 Mobile Safari/537.36 XWEB/1260065 MMWEBSDK/20231202 MMWEBID/4640 MicroMessenger/8.0.47.2560(0x28002F51) WeChat/arm64 Weixin NetType/WIFI Language/zh_CN ABI/arm64 MiniProgramEnv/android' -H 'Accept-Encoding: gzip,compress,br,deflate' -H 'x-rp-client: mini_2.1.0' -H 'charset: utf-8' -H 'x-referer-package: wx91d27dbf599dff74' -H 'content-type: application/json;charset=UTF-8' -H 'x-referer-page: /pages/gold/item/pages/detail/index' -H 'Referer: https://servicewechat.com/wx91d27dbf599dff74/755/page-frame.html' -H 'Cookie: buildtime=20240710;wxapp_type=1;wxapp_version=9.19.100;wxapp_scene=1089;cid=5;visitkey=10244140987371708491131090;gender=1;province=Guangdong;city=Shenzhen;country=China;nickName=%E4%BA%AC%E4%B8%9C%E7%94%A8%E6%88%B7;avatarUrl=https%3A%2F%2Fimg11.360buyimg.com%2Fjdphoto%2Fs120x120_jfs%2Ft1%2F82031%2F9%2F5133%2F19337%2F5d36bcadE9cdb240c%2Fccc58f73b721ec2d.png;wxNickName=%E4%BA%AC%E4%B8%9C%E7%94%A8%E6%88%B7;wxAvatarUrl=https%3A%2F%2Fimg11.360buyimg.com%2Fjdphoto%2Fs120x120_jfs%2Ft1%2F82031%2F9%2F5133%2F19337%2F5d36bcadE9cdb240c%2Fccc58f73b721ec2d.png;shshshfp=e6b331f967434077b21817d265a72bc2;equipmentId=jdd01w49SZRBEPAPKNGH2DJZZ4SAYIFDE437QCTNX3PWH3ZRPFLPZNQVV6XRIU7Q64U3QCDB5YZYPSQNUQ4ARTRO32M5COX32YU5DNLZ7XVYGKSFK5WI4JZHHRQKROKPZGXB7JHS;fingerprint=c68b3c68639ae2d76f00dfb51e463e08f251bf09;deviceName=23078RKD5C;deviceVersion=3.3.5;deviceOS=Android;deviceOSVersion=14;unionid=oCwKwuP6NE9Zf1vEOlA4J_wo-HZA;jdpin=jd_6fd51dc25a242;wxapp_openid=oA1P50NgALLs0hjTmoL2shpdA7Ns;pinStatus=0;mcossmd=33341b8b6382782bb53b0e078fc3f954;wid=5353903934;pin=jd_6fd51dc25a242;wq_uin=5353903934;wq_unionid=oCwKwuP6NE9Zf1vEOlA4J_wo-HZA;skey=zw30E663C4D1560487BFCDB82CEA03AE2598734452C899EDF67790F1751342D3D99B4348C1096670310A0DF8A5B2C5CD322F3123570F04617565021DEDC8C6B3D947B5D0E983E6AD401CA031B7169D15ADB914AC91873C146618344996E805C123;ou=20883D101825D23C9F28122F55E029CBE397021816C8048CA26F6681BCEBA2EB50C7310CC2786CDF607CC7219779D9453DC42B08A07FCEF287C4948C70286D73ADD651368F0595712FFE23B58280B74A;wq_addr=6097554977%7C9_639_38632_38682%7C%E5%90%89%E6%9E%97_%E9%95%BF%E6%98%A5%E5%B8%82_%E5%AE%BD%E5%9F%8E%E5%8C%BA_%E5%A5%8B%E8%BF%9B%E4%B9%A1%7C%E5%90%89%E6%9E%97%E9%95%BF%E6%98%A5%E5%B8%82%E5%AE%BD%E5%9F%8E%E5%8C%BA%E5%A5%8B%E8%BF%9B%E4%B9%A1%E5%90%89%E6%9E%97%E7%9C%81%E9%95%BF%E6%98%A5%E5%B8%82%E5%AE%BD%E5%9F%8E%E5%8C%BA%E5%A5%8B%E8%BF%9B%E4%B9%A1%E5%8C%97%E8%BF%9C%E8%BE%BE%E5%A4%A7%E8%A1%973000%E5%8F%B7%E9%95%BF%E6%98%A5%E5%B7%A5%E4%B8%9A%E5%A4%A7%E5%AD%A6%E5%8C%97%E6%B9%96%E8%A5%BF%E6%A0%A1%E5%8C%BA%7C125.391307%2C43.993308;PPRD_P=EA.17078.49.1-LOGID.1721890054986.1805408830-CT.138567.93.1;cartLastOpTime=1721876789;cd_eid=jdd01w49ZMQTRBPP5NCR4XFVSDJ7XMFPGEC6CL6UUQUAP75L7XL5INEUORLP7GWDSY5OM5W2CSFRWZO2P4G7UUDA4KP55VY2VCHN2RIPF3ERPPWKGPEQPQJKHHIGOZOCXJFLR63E;nickname=%E6%B2%BD%E9%85%92%E6%84%BF%E5%90%9B%E9%85%8C;CV=wxportal_vx.shtml;IndexVersionCookie=0;IndexCommonReport=%5Bobject%20Object%5D;cartNum=2;__jda=122270672.3dd7959eb96ce2da3ae9d10572e4ce89.1721875552672.1721875552672.1721875552672.1;__wga=1721890054926.1721890048961.1721875552780.1721875552780.2.2;__jdv=122270672%7Cweixin-search%7Ct_262767352_weixinsearch%7Ccpc%7C2219650310_0_953f5e3a6a3a4af0bc4220317%7C1721875559801;shshshfpa=f867ca34-c98b-0264-cc60-f61448427cc9-1721875552;shshshfpb=BApXclE3P5PVBkWQkO8zs0H6pn2PzhM0TBmPGUn1o9xJ1Mt2HvIC2;hf_time=1721875553814;wq_skey=zw30E663C4D1560487BFCDB82CEA03AE2598734452C899EDF67790F1751342D3D99B4348C1096670310A0DF8A5B2C5CD322F3123570F04617565021DEDC8C6B3D947B5D0E983E6AD401CA031B7169D15ADB914AC91873C146618344996E805C123;wq_auth_token=379D2A230D15B7F75E1C3214E194141ED6B785405192F9C6E5DFCD2F4E643243B83F28FC0FCEF83361F49105C838CD66;shshshsID=90e17ca3eef1d6d49586143f136fd294_2_1721890054184;network=wifi'

**Comment by MegatronKing** [comment]
@KingFuRong 原始请求是怎么来的？调试列表抓到的？

**Comment by KingFuRong** [comment]
原始的请求是正常抓包抓到的

**Comment by MegatronKing** [comment]
这个没办法支持，看起来原始请求的URL编码没有按照RFC规范来，但是Reqable行为是严格按照RFC规范定义来的。

**Comment by KingFuRong** [comment]
但是直接重发会按照原始请求的格式重发，Charles复制出来的curl同时是可用的
无论如何，感谢你的回复

**Comment by MegatronKing** [comment]
> 但是直接重发会按照原始请求的格式重发，Charles复制出来的curl同时是可用的 无论如何，感谢你的回复

按照你这个说法，我觉得可能不是url编码的问题。上面复制的curl，我直接运行也是返回403。Charles复制出来的curl是什么样的，能否提供下看看？

**Comment by KingFuRong** [comment]
> > 不过直接重发会按照原始请求的格式重发，Charles复制的curl同时出来是可用的无论如何，谢谢你的回复
> 
> 按照你这个说法，我觉得可能不是url编码的问题。上面复制的curl，我直接运行也是返回403。Charles复制出来的curl思考的，能否提供下看看？

很抱歉现在才看到你的消息，Charles的curl如下

curl -H "Host: api.m.jd.com" -H "x-rp-client: mini_2.1.0" -H "charset: utf-8" -H "x-referer-package: wx91d27dbf599dff74" -H "User-Agent: Mozilla/5.0 (Linux; Android 14; 23078RKD5C Build/UP1A.230905.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.188 Mobile Safari/537.36 XWEB/1260117 MMWEBSDK/20231202 MMWEBID/4640 MicroMessenger/8.0.47.2560(0x28002F51) WeChat/arm64 Weixin NetType/WIFI Language/zh_CN ABI/arm64 MiniProgramEnv/android" -H "content-type: application/json;charset=UTF-8" -H "x-referer-page: /pages/gold/item/pages/detail/index" -H "Referer: https://servicewechat.com/wx91d27dbf599dff74/763/page-frame.html" --compressed "https://api.m.jd.com/client.action?t=1726727761310&loginType=11&loginWQBiz=golden-trade&client=android&clientVersion=8.0.47&osVersion=Android%2014&screen=407*904&networkType=wifi&d_brand=Redmi&d_model=23078RKD5C&lang=zh_CN&sdkVersion=3.3.5&openudid=oA1P50NgALLs0hjTmoL2shpdA7Ns&uuid=10244140987371708491131090&functionId=getCommentListAppletForJd&appid=wx_item_new&body=%7B%22source%22%3A%22wxaitem%22%2C%22deviceUUId%22%3A%22%22%2C%22platform%22%3A2%2C%22uuid%22%3A%2210244140987371708491131090%22%2C%22deviceType%22%3A%2223078RKD5C%22%2C%22referer%22%3A%22http%253A%252F%252Fwq.jd.com%252Fwxapp%252Fpages%252Fmini%252Fmini%22%2C%22detailVersion%22%3A%222%22%2C%22fVersion%22%3A%221.5.4%22%2C%22version%22%3A%22v2%22%2C%22fold%22%3A1%2C%22sku%22%3A%2210079579995880%22%2C%22page%22%3A1%2C%22pagesize%22%3A10%2C%22score%22%3A0%2C%22tenantCode%22%3A%22jgminise%22%2C%22bizModeClientType%22%3A%22WxMiniProgram%22%2C%22callback%22%3A%22getFoldCommentList%22%7D&scval=undefined&xAPIScval2=wx&h5st=20240919143601315%3B5m5yim566i9zgnt0%3B565d6%3Btk03a8c071b1718pMyszKzJuQ3ZYA66IhnbYr6O58sY5iLEkDBgT1xA-7TVDKMx5RkVq4LHn6nFsH1wBfn2G7Y4g3Fez%3B5c0275598fad53a7a20f33f94bf9d3a8409f0482a0af5272d0d27572239fcf07%3B4.7%3B1726727761315%3BVOpztgWt2AT-SnS1fuYt1EkWvKaAeKtjpNT3nb330AvXgnN-dcgsKqgfj0S5fXTSNoG0OmhmB8xX2lv91w7Ry0xXAe8ahOgr56IPKgV5tIAk"
