### ISSUE TITLE
[feature] API测试请求头列表支持移动和批量操作

### ISSUE THREAD

**Issue by jinshuqishi2019** [reqable/reqable-app#807]
目前API测试请求头列表的元素增加上下移动按钮，这个功能我的两款api工具一般都有，希望加上。

有的请求头元素很多，判断元素是否必须，就需要一个个取消，有时候明显不需要对还一个个取消就有点麻烦，如果可以增加框选或者shift选择+右键，批量取消就更好。不过这个功能我现在用的api工具没有，可能其他方面的考量，仅希望作者考虑下。

**Comment by MegatronKing** [comment]
@jinshuqishi2019 你好，感谢建议。批量操作请求头可以切换到文本模式，编辑器支持Alt + 上下箭头移动顺序，或者注释取消选择。

**Comment by jinshuqishi2019** [comment]
谢谢，学会了
