### ISSUE TITLE
[bug] 启用重写时发现存在重复请求

### ISSUE THREAD

**Issue by yissyoo** [reqable/reqable-app#808]
**Describe the bug**
- 启用重写时发现存在重复请求

**To Reproduce**
1. 安装 Fiddler Classic、启动、使用 8888 端口、停止 Capturing
2. 启动 Reqable、停止调试、灭掉所有图标（SSL除外）
3. 设置并启用二级代理 127.0.0.1:8888、确保系统代理是关闭状态
4. 添加并启用重写：将 http://www.baidu.com/debug 重定向到 http://localhost:8888/debug
5. 新建 api：GET http://www.baidu.com/debug 跟随调试、发送

**Expected behavior**
- 请求已被重写，fiddler 不应该收到 baidu.com 的原始请求
- 疑似在未启用二级代理的情况下，Reqable 也会向已被重写的**原始地址**发送请求

**Screenshots**
![image](https://github.com/user-attachments/assets/834118c5-6e4b-4fd5-9fc6-3c72b70a8e52)

**Information**
 - Platform: windows 
 - OS: win10 LTSC 21H2
 - Arch: x86-64
 - App Version: 2.21.0(100)(x86_64)

**Comment by yissyoo** [comment]
**版本 2.21.1(101)(x86_64) win10 在不启用二级代理的情况下一样有这个问题**

**重写规则**
![image](https://github.com/user-attachments/assets/4ee3bc34-78fb-4fde-9a25-4c21f0302b77)

**调试结果看起来没有问题**
![image](https://github.com/user-attachments/assets/1cee0db1-2d6c-47ea-bfb5-d7e5e926f521)

**但是后端收到了两次请求**
![image](https://github.com/user-attachments/assets/dbfa960b-54c1-42b0-b989-683227b3c89a)

**Comment by beck-8** [comment]
你说的应该是原请求不应该请求到server吧？
我在使用同类工具mitmproxy也发现类似的问题，重写后，原请求竟然还请求到过server

**Comment by yissyoo** [comment]
> 你说的应该是原请求不应该请求到server吧？ 我在使用同类工具mitmproxy也发现类似的问题，重写后，原请求竟然还请求到过server

是的，用 Charles 无此问题。

**Comment by beck-8** [comment]
![image](https://github.com/user-attachments/assets/366963e9-b7e2-4758-83c5-332f57b71848)
发现文档中讲过了

**Comment by MegatronKing** [comment]
同 #267
