### ISSUE TITLE
[bug] MacBook Pro M1 11.2.3 (20D91) 打开闪退 

### ISSUE THREAD

**Issue by yanghongfeng1998** [reqable/reqable-app#809]
[bug] MacBook Pro M1 11.2.3 (20D91) 打开闪退 
![image](https://github.com/user-attachments/assets/37cec167-69e2-4e77-ad5d-0e8785ebc272)

**Comment by MegatronKing** [comment]
@yanghongfeng1998 你好，感谢反馈。

1. Reqable是最新版本吗？
2. 是否有复现步骤？
3. 能否提供下crash报告？

**Comment by MegatronKing** [comment]
可能类似#919
