### ISSUE TITLE
[bug] reqable抓安卓APP时相比Charles有部分https请求无法正常解密

### ISSUE THREAD

**Issue by SeeFlowerX** [reqable/reqable-app#81]
**Describe the bug**
也许是reqable对socks5类型的转发兼容性？不够完善导致的，通过[socksdroid](https://github.com/bndeff/socksdroid)转发流量给reqable，Charles能解出来的https在reqable显示为socks5://[ip]:443

**To Reproduce**

手机均安装好Charles和reqable的证书，并使用magisk插件将证书移动到系统证书目录

1. 通过酷安安装**探探**
2. 安装[socksdroid](https://github.com/bndeff/socksdroid)
3. 配置socksdroid，设置好抓包软件的socks监听ip和端口，选择`Per-app Proxy`，在APP List中填写探探的包名，`com.p1.mobile.putong`
4. 打开探探APP进行抓包

![image](https://github.com/reqable/reqable-app/assets/70688581/b8e71d90-3f55-45c9-afd9-c8ca9850bc7d)
![image](https://github.com/reqable/reqable-app/assets/70688581/92eb5003-7673-4be1-8ae3-e7df5a103523)
![image](https://github.com/reqable/reqable-app/assets/70688581/09c35871-2cde-4140-87ad-db9ecda650d8)

**Expected behavior**
正常解密`i.tantanapp.com`域名下的https解密内容

**Screenshots**

对比图如下，同样的操作Charles可以抓到`i.tantanapp.com`域名下的内容，完整url被解密了

而reqable则全部是`socks5://120.133.43.34:443`，可以发现这个ip就是`i.tantanapp.com`的解析地址

![image](https://github.com/reqable/reqable-app/assets/70688581/2ef93d4d-a577-433b-b667-b750826e1bed)
![image](https://github.com/reqable/reqable-app/assets/70688581/497825f6-041e-413d-962c-43179037ba14)
![image](https://github.com/reqable/reqable-app/assets/70688581/bc3f3739-01ff-4ef4-bad6-d99f56bc1494)

**Information**
 - Platform: windows
 - OS: win10
 - Arch: x86-64
 - App Version: 1.0.5

**Comment by SeeFlowerX** [comment]
我用自己的设备测试了下，似乎又是可以的了，只有少数的socks5://[ip]:443

回想起来可能是下午操作的时候，是覆盖安装了新版本的reqable？没有重新安装证书，证书应该是放到系统目录下去了的，节后会确认一下。

感谢回复。

![image](https://github.com/reqable/reqable-app/assets/70688581/456511be-9616-4e5c-99e2-6fb460a46c3c)

**Comment by SeeFlowerX** [comment]
看来是每次更新之后都需要重新安装一次证书？我重新导出安装证书之后，大部分https都可以解密了，不过还是有相当多的 `socks5://[ip]:443` 
![image](https://github.com/reqable/reqable-app/assets/70688581/998fa4ed-10c4-4b42-8710-c709d415cb96)
![image](https://github.com/reqable/reqable-app/assets/70688581/2481a3b7-25ba-4f4c-b0c6-fbb15525147f)

**Comment by SeeFlowerX** [comment]
reqable可以增加一个字体大小、粗细调整的功能吗，用习惯了Charles再用reqable发现很不习惯，才反应过来reqable的字体偏细小

**Comment by MegatronKing** [comment]
> reqable可以增加一个字体大小、粗细调整的功能吗，用习惯了Charles再用reqable发现很不习惯，才反应过来reqable的字体偏细小

麻烦新开一个issue，这个issue的问题我先关闭了。
