### ISSUE TITLE
[bug] 调试界面 添加自定义响应头列之后，出现同名请求头列且无法删除

### ISSUE THREAD

**Issue by yissyoo** [reqable/reqable-app#812]
**Describe the bug**  
如标题所述，添加响应头列后，会自动出现一个同名的请求头列（自动显示出来），且在请求头管理中看不到，无法隐藏或删除。  

目前我是通过手动修改 shared_preferences.json 来修复这个问题的。

**To Reproduce**
1. 调试界面，右击列表头部，添加响应头，例如 X-ABC
2. 列表出现一个请求头列 X-ABC
3. 右击列表头部，请求头管理，看不到该列

**Expected behavior**
你懂的

**Screenshots**
![image](https://github.com/user-attachments/assets/70b0790e-e0d6-447a-9c21-87e9a1efca68)

**Information**
 - App Version: 2.21.0(100)(x86_64)

**Comment by MegatronKing** [comment]
感谢反馈，发现一些问题，我尽快修复。

**Comment by yissyoo** [comment]
更新 101 后这个问题已经解决了
