### ISSUE TITLE
[bug] 脚本功能在处理特殊path时转换错误

### ISSUE THREAD

**Issue by Dawnnnnnn** [reqable/reqable-app#813]
脚本为空脚本，未对请求做任何处理，url为*

实际需要访问的网址：https://xxxx.com/api/v1/338806;l=c?zonest=2
在Reqable中抓到的访问网址：https://xxxx.com/api/v1/338806?zonest=2

关闭脚本功能时，请求恢复正常，在Reqable中抓到的网址为 https://xxxx.com/api/v1/338806;l=c?zonest=2

**Comment by MegatronKing** [comment]
@Dawnnnnnn 感谢反馈，将在下个版本修复。

**Comment by MegatronKing** [comment]
@Dawnnnnnn 2.21.2已解决，试试看。

**Comment by Dawnnnnnn** [comment]
测试已修复
