### ISSUE TITLE
在响应体中搜索，点击下一个不会跳转到目的位置

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#82]
只会跳转一次，然后鼠标滚动过后就不会再跳转了

**Comment by MegatronKing** [comment]
这个问题是wordwrap模式下吗

**Comment by MegatronKing** [comment]
我没能复现这个问题，能否提供一个操作录屏？

**Comment by RonaldinhoL** [comment]
![image](https://github.com/reqable/reqable-app/assets/1797392/a6e928e8-6c75-48cf-bd88-104d0655e50f)
![image](https://github.com/reqable/reqable-app/assets/1797392/90f62bae-3770-429a-9254-5cd292c617e6)

随便找个例子，第一张图，输入搜索字符串，会自动跳转到匹配的位置处，第二张图，鼠标滚过那个区域以后，无论怎么点击都不会回到匹配的位置处

**Comment by RonaldinhoL** [comment]
也许是只有一个匹配的情况下会出现这个问题，程序以为已经搜索到位置处了，但是没有判断当前的行，不知道我需要再次跳转到
那里

**Comment by MegatronKing** [comment]
确实单结果的时候有问题，已复现，感谢反馈。

**Comment by MegatronKing** [comment]
@RonaldinhoL v1.0.6版本已修复，可以试下。
