### ISSUE TITLE
[feature] Websocket数据包显示优化

### ISSUE THREAD

**Issue by reckeyliao** [reqable/reqable-app#822]
**建议1：增加数据包编号**
没有一个编号标注的前提下，数据收发量大起来，看了前一个包的数据再退回去找前面的某个数据包，就不知道刚刚看的是哪条数据了

**建议2：增加列表界面收发数据的颜色标记**
收发的包都采用的是灰色图标形式，不是很清晰，建议发出的数据和收到的数据用颜色加以区分

**建议3：增加Websocket数据包删除功能**
收到的数据多了，有些不需要用到了，可以一次性清除掉旧数据，新收到的包可以继续在列表显示（如果点启动按钮旁的清除会把ws连接整个包都清空，自然都看不到后面收到的ws数据了）

**Comment by MegatronKing** [comment]
@reckeyliao 感谢建议，这个会做优化的。

**Comment by MegatronKing** [comment]
建议2已实现。

**Comment by MegatronKing** [comment]
v2.22.2已完成优化。
