### ISSUE TITLE
[bug] 无法添加需要认证的二级代理

### ISSUE THREAD

**Issue by lichangg** [reqable/reqable-app#824]
<img width="819" alt="image" src="https://github.com/user-attachments/assets/1a5674b7-9a38-439d-999c-13ac39e1eee9">
和文档中展示的二级代理界面不一样，没有添加认证的地方
<img width="796" alt="image" src="https://github.com/user-attachments/assets/00de6072-fc06-49d4-9ab7-089f66f1cbe7">

**Information**
 - Platform: [macos]
 - OS: [12.1]
 - Arch: [arm]
 - App Version: [1.4.0]

**Comment by MegatronKing** [comment]
@lichangg 更新版本吧，你这个版本看起来也太老了，最新已经2.21.2了。
