### ISSUE TITLE
[feature] 增加一个HOSTS功能，可以直接在软件中，随时调整域名对应的IP

### ISSUE THREAD

**Issue by hhs66317** [reqable/reqable-app#828]
测试过程中，调整hosts时，通常都是调整系统的hosts，但是调整系统的 hosts 之后，对于已经打开的软件，不能很快应用，通常都需要重启才可以。

可以在代理工具中增加一个自定义hosts功能，可以添加、编辑、勾选生效的 hosts绑定

**Comment by MegatronKing** [comment]
@hhs66317 感觉建议。已经有这个功能了，叫`镜像`，看看官网文档。

**Comment by hhs66317** [comment]
> @hhs66317 感觉建议。已经有这个功能了，叫`镜像`，看看官网文档。

我看过官方文档中的镜像功能了，它主要能做域名替换，我需要的是访问指定域名时，访问指定IP，而不是DNS返回的线上IP，测试环境的域名与线上环境一致，不是独立的测试域名

**Comment by MegatronKing** [comment]
> > @hhs66317 感觉建议。已经有这个功能了，叫`镜像`，看看官网文档。
> 
> 我看过官方文档中的镜像功能了，它主要能做域名替换，我需要的是访问指定域名时，访问指定IP，而不是DNS返回的线上IP，测试环境的域名与线上环境一致，不是独立的测试域名

抱歉，忘记回复了。你可以配置映射到新域名，也可以配置映射到指定IP。

**Comment by hhs66317** [comment]
> > > @hhs66317 感觉建议。已经有这个功能了，叫`镜像`，看看官网文档。
> > 
> > 
> > 我看过官方文档中的镜像功能了，它主要能做域名替换，我需要的是访问指定域名时，访问指定IP，而不是DNS返回的线上IP，测试环境的域名与线上环境一致，不是独立的测试域名
> 
> 抱歉，忘记回复了。你可以配置映射到新域名，也可以配置映射到指定IP。

客气了，你说的对，我想当然了，确实可以通过镜像来映射到指定的IP，实现类似hosts的效果

可否考虑对镜像功能增加一个备注属性，如果可以希望能支持分组管理，可以切换到不同的分组中，并根据需要调整分组中启用的规则，一旦规则比较多，每次勾选不同的规则会很麻烦

**Comment by MegatronKing** [comment]
> 如果可以希望能支持分组管理，可以切换到不同的分组中。

应该早就已经有了分组功能（文件夹）了呀。

**Comment by hhs66317** [comment]
Orz，太尴尬了，软件我摸索的还不够

**Comment by bbaobelief** [comment]
我也需要自定义hosts功能，试过镜像不好用

**Comment by MegatronKing** [comment]
> 我也需要自定义hosts功能，试过镜像不好用

请说出你的理由，方便我们进行改进。

**Comment by defnngj** [comment]
添加三个就要求付费了，所以，所以又用回了 SwitchHosts 更方便。
