### ISSUE TITLE
[feature] 导入自定义证书&sslping 

### ISSUE THREAD

**Issue by junknet** [reqable/reqable-app#83]
需求,按照优先级排列
1. 导入自定义证书
2. sslpin双向锁定，添加对指定网站主动发送客户端证书的功能
3. 4k屏分辨率自适应
4. Archlinux 打包

我司考虑采购这个软件，对咱是刚需，主要看中跨平台一致性，以及脚本调试功能，希望取得进一步联系

**Comment by MegatronKing** [comment]
@junknet 加我微信 ![](https://license.reqable.com/assets/assets/images/chat_qrcode.jpg)
