### ISSUE TITLE
[feature] 

### ISSUE THREAD

**Issue by liulbaofeng** [reqable/reqable-app#830]
Oh! The editing feature is actually not free! I want it to be completely free

**Comment by MegatronKing** [comment]
Sorry, I can't understand what you mean?

**Comment by liulbaofeng** [comment]
捕捉到数据包后，右上角更多中有个编辑功能，使用了几次后发现需要许可证。这才发现这个功能并不是完全免费的，这是个非常棒的功能，我希望它完全免费
如果可以的话，我希望购买许可证时，可以出一个永久购买的选项

问一句题外话，我希望知道您的国籍，看到了您的名字，我一直以您说英语


![Screenshot_20240812_085724_com reqable android_edit_1042766667148202](https://github.com/user-attachments/assets/a3ecb2db-5ddb-4985-92b4-effbf03113a8)

**Comment by MegatronKing** [comment]
[官网](https://reqable.com/pricing)可以购买。
