### ISSUE TITLE
[bug] 脚本不生效

### ISSUE THREAD

**Issue by hackdoors** [reqable/reqable-app#832]
![image](https://github.com/user-attachments/assets/5b0184a2-f36b-47fd-8c9a-12ae38e627f9)
版本：
版本2.21.4 (104)
日志一直不打印

**Comment by hackdoors** [comment]
电脑环境为：
<img width="586" alt="image" src="https://github.com/user-attachments/assets/beca70b6-5ff8-4ea7-b2e3-e3457198b562">

**Comment by MegatronKing** [comment]
@hackdoors url匹配规则没写对

**Comment by hackdoors** [comment]
谢谢大佬，确实是末尾少了个*号
