### ISSUE TITLE
[feature] 以 Alt + 鼠标左键点击调试标签页关闭按钮时默认直接关闭不进行保存

### ISSUE THREAD

**Issue by cxplay** [reqable/reqable-app#833]
目前的状态下，关闭调试标签页都会弹出一个窗口询问是否保存，但有一些临时调试的接口并不需要长期保存，当这类临时调试的标签很多的时候并且混在一般接口调试的标签中（不能一概 <kbd>Ctrl</kbd> + <kbd>Shit</kbd> + <kbd>W</kbd> 全部关闭），带有快捷键的点击直接关闭会提高不少整理工作区的效率。

**Comment by MegatronKing** [comment]
@cxplay 你好，感谢建议。我觉得这是个不错的思路，请问Alt + 鼠标左键有相关实践的产品例子吗？

**Comment by cxplay** [comment]
> @cxplay 你好，感谢建议。我觉得这是个不错的思路，请问Alt + 鼠标左键有相关实践的产品例子吗？

还真没有遇到过，这个想法只是在使用 Reqable 的过程里冒出来的。

**Comment by MegatronKing** [comment]
我在下个版本加上，多多益善

**Comment by MegatronKing** [comment]
v2.22.0已实现此功能。
