### ISSUE TITLE
提出几个修改新加功能的建议  

### ISSUE THREAD

**Issue by TSW1133** [reqable/reqable-app#836]
1. 修改在JSON 格式返回的响应数据中 可以 使用  树状组件  把JSON 每一级都解析出来 更好的展示JSON的节点属性和值  Raw再展示JSON原文
2. 新增 可以增加关于TCP抓包的部分   更好的体现 小黄鸟YYDS
3. 新增  直接禁用TCP/UDP 默认端口 可以试APP 强制转为HTTP/S协议进行请求抓包
4. 总体 小黄鸟 YYDS 值得冲

**Comment by MegatronKing** [comment]
你好，感谢建议。这几个问题已有相关issue，#185 #59
