### ISSUE TITLE
[bug] 数据包编辑存在编码问题

### ISSUE THREAD

**Issue by TopMaps** [reqable/reqable-app#837]
POST表单提交数据，token经过base64编码，在urlencode或者文本显示模式下，/+被解码为空格，导致鉴权失败
![1](https://github.com/user-attachments/assets/744d2a48-74e5-41b9-ac48-4ca49f3dcb75)
![2](https://github.com/user-attachments/assets/5e8bf256-8346-4ca8-9f69-820b0fa046bc)

**Comment by MegatronKing** [comment]
感谢反馈，下个版本修复。

**Comment by Dawnnnnnn** [comment]
@MegatronKing 拓展一种bug场景：

抓包中请求为正常请求，右键请求选择重发也是正常请求，但右键编辑再发送接口就会报错，我查了查是post data中的+被转换为空格了，感觉和这个issue差不多

**Comment by Dawnnnnnn** [comment]
@MegatronKing 同时右键请求复制的curl也是同样的问题

**Comment by MegatronKing** [comment]
感谢反馈，v2.22.0已修复此Bug。
