### ISSUE TITLE
[bug] 这个问题如何处理

### ISSUE THREAD

**Issue by 419310** [reqable/reqable-app#838]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: 
 - 很多https安卓包不能看到

**Comment by MegatronKing** [comment]
无效问题 ，关闭。
