### ISSUE TITLE
[bug] API编辑器没有跟随自定义证书的设置

### ISSUE THREAD

**Issue by yinsel** [reqable/reqable-app#839]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
默认是不会的，需要启用跟随调试。

**Comment by yinsel** [comment]
> 默认是不会的，需要启用跟随调试。

是这吗？

![image](https://github.com/user-attachments/assets/e9fada87-69d5-4dfd-b93e-c64af44904e3)

**Comment by MegatronKing** [comment]
是的

**Comment by yinsel** [comment]
ok
