### ISSUE TITLE
[bug] 关于应用捕捉

### ISSUE THREAD

**Issue by liulbaofeng** [reqable/reqable-app#840]
我想对分身应用进行捕捉时，发现无法捕捉到
我询问了我的系统专员，他们告知分身应用和主应用使用的应用包名是同一个。
在捕捉只能捕捉到主应用

HUAWEI
Harmony OS 4.2
arm64-v8a(64bit)

 App Version: 2.21.4(104)arm64

**Comment by MegatronKing** [comment]
你好，不理解你具体遇到的问题是什么？或者你是否具备这方面的技术知识？

**Comment by liulbaofeng** [comment]
我开启了QQ的分身应用，我想抓取QQ分身，但却捕捉不到，只能捕捉到主应用。在选择应用程序时，也只能选取QQ主应用

主应用和分身应用的包名相同，我觉得程序似乎分不清主应用和分身应用，抓取的数据包也只有主应用的数据

虽然包名相同，  但是进程不同。我觉得可以加入基于进程控制符ID-PID来过滤进程
![Screenshot_20240812_104649_com reqable android_edit_1049354627969387](https://github.com/user-attachments/assets/999ee39b-c296-482d-b730-7e9e8e630bfd)

**Comment by MegatronKing** [comment]
这个和reqable有关系吗？
