### ISSUE TITLE
建议加入新功能

### ISSUE THREAD

**Issue by TSW1133** [reqable/reqable-app#841]
1. TCP抓包的支持
2. 可以灵活禁用手机UDP TCP 端口 使目标APP 强转为Http/s协议  
3. 工具箱内可以加入关于Protobuf 解码的支持
4. 脚本功能 是否可以单独分配一个UI窗口  可以更方便快捷的更改全局的脚本规则

**Comment by MegatronKing** [comment]
@TSW1133 您好，感谢建议。

1和3已经有相关issue了。2这个需求不是很理解。4可以在vscode窗口里面编辑。
