### ISSUE TITLE
[feature] 目标应用选择

### ISSUE THREAD

**Issue by liulbaofeng** [reqable/reqable-app#842]
在添加目标应用时，会用应用名或者应用包名搜索

建议添加更精细的选择选项，希望可以通过选择进程控制符 (PID) 来添加目标应用

**Comment by MegatronKing** [comment]
你好，感谢建议。应用名或者应用包名搜索还不够用吗，请问pid是什么场景？应用名或者应用包名搜索不出来吗？

**Comment by liulbaofeng** [comment]
多进程环境中，可能存在多个相同的应用同时运行，手机中拥有相同应用名和包名(两个都一样)时，没有办法搜索完整，只能显示一个

每个应用实例都有独立的进程标识符Process Identifier，需要根据PID来精确地控制某个特定的进程，通过PID就可以区分开需要哪一个应用进程

**Comment by MegatronKing** [comment]
我大概理解你的意思了，但是很抱歉技术上无法实现。

**Comment by liulbaofeng** [comment]
好的 理解您的决定
