### ISSUE TITLE
[bug] SSL Pinning issue

### ISSUE THREAD

**Issue by MhmRdd** [reqable/reqable-app#843]
Unable to bypass ssl pinning issue when trying to intercept https requests response, with system certificate installed.

The issue appeared when trying some games such as 'Battle Bay' login api or the demonstration app 'SSL Pinning Demo':https://github.com/httptoolkit/android-ssl-pinning-demo

Generally with system certificate installed, reqable shouldn't have issue with capturing ssl traffic, but unfortunate it happens when trying to, this behaviour happened to prior capture apps such as HttpCanary.

**Note:**I have managed to bypass some of ssl pinning issue by using the [LSPosed Module](https://github.com/Xposed-Modules-Repo/io.github.tehcneko.sslunpinning) on target app selected, but it wasn't enough to bypass all the ssl pinning tests, the screenshots below clears the behaviour.

(Without Bypassing module):
![Screenshot_2024-08-13-22-48-31-19_7fac49e5329bfa70bf0c1257a1a51d55.jpg](https://github.com/user-attachments/assets/b3a7df38-ee7f-4aaf-bc4e-e1f86e994e7b)

![Screenshot_2024-08-13-22-48-42-61_7fac49e5329bfa70bf0c1257a1a51d55.jpg](https://github.com/user-attachments/assets/1d991266-7c97-496f-bb83-18f400d08dcb)

![IMG_20240813_224947.jpg](https://github.com/user-attachments/assets/4a8e2617-27cd-42c0-bc48-e69b1181b907)

![IMG_20240813_225006.jpg](https://github.com/user-attachments/assets/2ab2eb49-b174-4bf3-bb29-e9fe2c8b80ae)

![IMG_20240813_225030.jpg](https://github.com/user-attachments/assets/f3ffc36c-d927-4d5b-97b6-29c7e529e7d9)

![IMG_20240813_225042.jpg](https://github.com/user-attachments/assets/3db7fc7e-ed70-4475-ab63-376c89f7228b)

![IMG_20240813_225101.jpg](https://github.com/user-attachments/assets/bfd0156f-b99c-4726-ba4d-78af0cd0acfb)

(With Bypassing Module):
![Screenshot_2024-08-13-23-02-29-26_7fac49e5329bfa70bf0c1257a1a51d55.jpg](https://github.com/user-attachments/assets/4179074c-d985-478d-8999-3d91a2db73e0)

![IMG_20240813_230311.jpg](https://github.com/user-attachments/assets/34b42c75-03cc-440a-9cc5-00735cda4c9a)

![IMG_20240813_230344.jpg](https://github.com/user-attachments/assets/b97a5397-8cae-4c97-a536-23560d2b6704)

![IMG_20240813_230409.jpg](https://github.com/user-attachments/assets/1ffb0c3a-8cb7-426c-a4ee-1b4376638cca)

![IMG_20240813_230419.jpg](https://github.com/user-attachments/assets/62ff7e1c-96a9-419a-bc1d-579159e7532c)

**Information**
 - Platform: Android
 - OS: 13
 - API/Release: 33
 - Root Certificate: Yes (Installed with KSU Module Reqable, App recognised)
 - Security Patch: 2023-01-03
 - Root Framework: KernelSU 11928
 - Arch: arm, arm64
 - App Version: 2.21.4

**Comment by MegatronKing** [comment]
@MhmRdd Thanks for feedback, would you like to provide me some logs? Long press the logo icon in the side-menu, and export the log here.

**Comment by MhmRdd** [comment]
Sure, here's both of the logs with/without the ssl unpinning module.
(Without bypassing Module):
[20240814033255-82e8ea60-59e5-11ef-902c-47a019d065bb.log](https://github.com/user-attachments/files/16607095/20240814033255-82e8ea60-59e5-11ef-902c-47a019d065bb.log)

(With bypassing Module):
[20240814033645-0c8a11e0-59e6-11ef-862f-51e8ba1425e6.log](https://github.com/user-attachments/files/16607099/20240814033645-0c8a11e0-59e6-11ef-862f-51e8ba1425e6.log)

**Comment by MegatronKing** [comment]
Obviously, ssl bypass didn't work, this is not a reqable issue.

**Comment by MhmRdd** [comment]
Will there be any future update concerning well improved ssl pinning bypass method?

**Comment by MegatronKing** [comment]
> Will there be any future update concerning well improved ssl pinning bypass method?

No that plan, this is not related with Reqable.

**Comment by MhmRdd** [comment]
Oh, okay sorry for bothering with wrong topic.
