### ISSUE TITLE
[bug] 响应体报错FormatException: Filter error, bad data

### ISSUE THREAD

**Issue by Dawnnnnnn** [reqable/reqable-app#844]
![QQ_1723620035287](https://github.com/user-attachments/assets/41e257f0-4961-4b19-b81f-f91618553ec6)
![QQ_1723620064989](https://github.com/user-attachments/assets/a362c307-cd85-4926-affe-da5894cc09de)

但是复制curl到rapidAPI里发包是可以显示出raw返回的

![QQ_1723620137273](https://github.com/user-attachments/assets/394137ff-6cdb-4ab1-856e-b98a8dbdf33b)

**Comment by MegatronKing** [comment]
@Dawnnnnnn 感谢反馈。看起来像是deflate解码的问题，能否将这个请求curl发我测试下？如果不便贴在这里，可以发送到我邮箱 coding@reqable.com

**Comment by Dawnnnnnn** [comment]
> @Dawnnnnnn 感谢反馈。看起来像是deflate解码的问题，能否将这个请求curl发我测试下？如果不便贴在这里，可以发送到我邮箱 [coding@reqable.com](mailto:coding@reqable.com)

已发送，请求自身有有效期，请尽快查看

**Comment by MegatronKing** [comment]
@Dawnnnnnn 收到，感谢，可以复现问题了。

**Comment by MegatronKing** [comment]
感谢反馈，v2.22.0已修复此Bug。
