### ISSUE TITLE
[bug] 按住option键的同时按删除键无法删除整个单词

### ISSUE THREAD

**Issue by yym68686** [reqable/reqable-app#848]
**Describe the bug**
按住option键的同时按删除键无法删除整个单词，只能一个字母一个字母删。

**To Reproduce**
3. See error

**Expected behavior**
按一次删除一整个单词。

**Screenshots**

**Information**
 - Platform:  macos
 - OS: 14.6.1 (23G93)
 - Arch: arm
 - App Version: 2.21.4(104)

**Comment by MegatronKing** [comment]
感谢建议，v2.22.0已添加此功能。
