### ISSUE TITLE
[bug] Can't install certificate CA

### ISSUE THREAD

**Issue by EngineerGlitch** [reqable/reqable-app#856]
**Describe the bug**

For unrooted certificate setup, I can't install a certificate CA, it's crashing in the instant I click on the .crt file. By the way, I tried an other certificate CA (from the app PCAPdroid) 
It's working, there is a problem only with this one.

**To Reproduce**
1. Go to 'Certificate Setup' and 'Unrooted
2. Click on 'Export certificate'
3. Go to the 'Install a certificate' on 'Settings'
4. Install certificate CA by clicking the .crt file
5. Instant crash and returned to settings, tried multiple times
6. You can also see that the certificate CA isn't installed after that

**Expected behavior**
Certificate CA added correctly - X

**Screenshots**
Attached - ✓

![Screenshot_2024-08-19-17-35-48-133_com android settings-edit](https://github.com/user-attachments/assets/874352bd-a5cc-4fe7-bd98-47a12db4a39a)
![Screenshot_2024-08-19-17-36-31-149_com google android documentsui-edit](https://github.com/user-attachments/assets/cb460e85-03fc-454c-98a0-c736241193aa)
![Screenshot_2024-08-19-17-36-58-523_com android settings-edit](https://github.com/user-attachments/assets/f362b06e-63bd-49a7-bbf7-aecbb0de21bc)
![Screenshot_2024-08-19-17-36-02-615_com android settings-edit](https://github.com/user-attachments/assets/c2eb3685-0b91-4acf-985e-f3730c2dcf1f)

**Information**
 - Platform: Smartphone (POCO X4 GT)
 - OS/UI: Xiaomi HyperOS 1.0.x.x (Android 14)
 - Arch: arm64
 - App Version: 2.22.0 (105) (arm64)

**Comment by MegatronKing** [comment]
@EngineerGlitch Thanks for feedback. Can you attach the crash logs here?
<img width="782" alt="shot" src="https://github.com/user-attachments/assets/d9dfbeaf-347d-4e60-94ef-b96f6d311506">

**Comment by EngineerGlitch** [comment]
@MegatronKing Yeah sure, here it is :

![Screenshot_2024-08-19-18-10-51-924_com miui bugreport-edit](https://github.com/user-attachments/assets/59dc972d-77a7-4681-824c-48deecc264e1)
![Screenshot_2024-08-19-18-11-56-265_com miui bugreport-edit](https://github.com/user-attachments/assets/1e7c65f9-9461-4e65-a292-18826ac133ab)

There is 13 more lines I can't click to show, trying to find the file, will put it here. Hope it will help you :)

**Comment by MegatronKing** [comment]
Seems that the installer has no permission to read the certificate file. You can move the file to another public folder and try again.

**Comment by EngineerGlitch** [comment]
Fixed, no needed to move the file.

![Screenshot_2024-08-19-19-47-06-210_com android settings-edit](https://github.com/user-attachments/assets/17eb8a2b-5018-4100-94e1-d422ab2bffab)

**Fix to this issue**
Permission problem on the settings to
'Access for all the files' for a system app (trying to find who it was) but just unmask system app, activate all apps, mask them, then deactivate users app because it's a sensitive permission

![Polish_20240819_200912073](https://github.com/user-attachments/assets/1b399caf-36c6-4416-8c59-2e713d3e335c)

**Advice**
Add on the app, text to check systems app 'Access for all the files' permission

**Comment by MegatronKing** [comment]
Should the Settings app always has the 'Access for all the files' permission? It is not make sense to turn it on manully.

**Comment by EngineerGlitch** [comment]
It's not the settings app, it's one of the system apps if I unmask them
