### ISSUE TITLE
HarmonyOS 证书安装支持

### ISSUE THREAD

**Issue by llm-github** [reqable/reqable-app#858]
HarmonyOS NEXT不支持文件传输同iOS一样，只能本机下载后安装证书，希望能支持Android证书安装时在局域网内下载证书安装（同Charles）

**Comment by MegatronKing** [comment]
> HarmonyOS NEXT不支持文件传输同iOS一样，只能本机下载后安装证书，希望能支持Android证书安装时在局域网内下载证书安装（同Charles）

局域网下载证书这个功能是支持的，参考应用内安装指引。
