### ISSUE TITLE
[bug] 关闭以后后台中还会运行，导致打开的时候无法打开，必须手动结束进程才能打开

### ISSUE THREAD

**Issue by fyfyfy982** [reqable/reqable-app#86]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@fyfyfy982 试试1.1.0版本，已经做了优化，看看是否有效？

**Comment by MegatronKing** [comment]
如果没有问题，这个issue先关闭了。
