### ISSUE TITLE
[优化建议] 调试功能右侧的总览接口弹窗没有光标定位

### ISSUE THREAD

**Issue by southllwind** [reqable/reqable-app#860]
**Describe the bug**
总览TAB的接口弹窗没有光标定位

**To Reproduce**
1、双击已抓取的调试接口
2、定位至总览模块
3、点击接口地址
4、点击弹窗内容的接口地址

**Expected behavior**
根据点击位置，出现光标定位

**Screenshots**
![d17a15077be5ad87c04b27072295f83](https://github.com/user-attachments/assets/989cfed8-bd64-461d-8b8b-496bf590cc84)

**Information**
系统：windows
版本：v2.22.0

**Comment by MegatronKing** [comment]
v2.22.2已修复。
