### ISSUE TITLE
[bug] https://github.com/MegatronKing/HttpCanary/issues/3

### ISSUE THREAD

**Issue by enessmr** [reqable/reqable-app#865]
**Describe the bug**
Chrome: Connection was shutdown.

**Expected behavior**
Connect to internet in turkey without ant auth error.
Check the title link.

**Screenshots**
Title link has.

**Information**
 - Platform: android (CUSTOM ROM)
 - OS: PixelOS (Unofficial PixelOS, Unofficial rom.) 13
 - Arch: armv8a-64
 - App Version: idk

**Comment by cxplay** [comment]
Do you know how to make Android trust your custom certificates by default?

> <https://www.google.com/search?q=Chrome+Android+ERR_CRET_AUTHORITY_INVALID>

**Comment by cxplay** [comment]
Install Certificate | Reqable
> https://reqable.com/en-US/docs/getting-started/installation/#android

**Comment by enessmr** [comment]
Old version of Reqable (HttpCanary, outdated.) worked for me.

**Comment by enessmr** [comment]
SOLUTION FOUND! VPN to proxy. Worked without any issues. Blocked Ads too!

**Comment by enessmr** [comment]
The same error appears in miui
