### ISSUE TITLE
[bug] win11+原生安卓8.1最新版本经常出现连接成功但是抓不到包，也无法通过vpn代理方式上网，多次重启未果

### ISSUE THREAD

**Issue by xs-alpha** [reqable/reqable-app#866]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@xs-alpha 试试Android最新版本2.22.1

**Comment by MegatronKing** [comment]
没有进一步的回复，关闭issue。

**Comment by zxhans** [comment]
vivo x9s plus 使用reqable 能打开vpn 但无法拦截，证书安装不进系统目录
