### ISSUE TITLE
安全连接证书校验无效，无法进入某些页面

### ISSUE THREAD

**Issue by JohnChan1017** [reqable/reqable-app#875]
![微信图片_20240827135716](https://github.com/user-attachments/assets/2ddf3c4b-b4a8-4bf1-aa01-92f38d95ef70)
有些app必须校验证书才能进入某些功能，这时Reqable就无法抓包了，请问有解决方案吗？还是说用Wireshark才行？

**Comment by MegatronKing** [comment]
证书信任问题，和Reqable没什么关系。
