### ISSUE TITLE
[bug] 新建网关无法选择行为,默认为仅允许,无法选中其他

### ISSUE THREAD

**Issue by TopChina** [reqable/reqable-app#879]
**Describe the bug**
新建网关无法选择行为,默认为仅允许,无法选中其他

**Information**
 - Platform: [macos]
 - OS: [macos sequoia 15.0 Beta版(24A5327a)]
 - Arch: [arm]
 - App Version: [2.22.1 (106)]

**Comment by MegatronKing** [comment]
感谢反馈，2.22.2版本已修复。
