### ISSUE TITLE
[bug] 翻墙后如何代理？

### ISSUE THREAD

**Issue by JiaLeDe** [reqable/reqable-app#88]
可不可以加上个配置翻墙代理的功能？我用的windows，V2ray翻墙，他的socket端口是10808，http端口是10809，可以放到如图所示的位置嘛？配置翻墙代理ip和端口。这样手机连reqable的时候也能翻墙，会方便好多
![image](https://github.com/reqable/reqable-app/assets/63954316/63a97fda-9335-47a9-9b97-f91244cecf8b)

**Comment by MegatronKing** [comment]
应该是这个需求 #14
