### ISSUE TITLE
[bug] 重定向 URL 复制功能损坏

### ISSUE THREAD

**Issue by cxplay** [reqable/reqable-app#888]
> - Reqable 版本: v2.22.2
> - 操作系统: Windows 11 23H2 (22631.4037)

在重定向面板使用复制按钮复制重定向目标 URL 失败, 实际复制到剪贴板上的内容都是 `Instance of 'Tgb'`.

演示:
> https://github.com/user-attachments/assets/8eaf7ec9-1780-4b35-a2ee-0d0e237144eb

**Comment by MegatronKing** [comment]
v2.23.0版本已修复。
