### ISSUE TITLE
[bug] 使用脚本中断请求时，在脚本控制台打印可以打印请求体内容，而在请求体的界面上却显示无任何数据

### ISSUE THREAD

**Issue by cry980285208** [reqable/reqable-app#89]
使用脚本中断请求时，在脚本控制台打印可以打印请求体内容，而在请求体的界面上却显示无任何数据
如图：控制台打印的body是有值的，界面上显示无任何数据
![Dingtalk_20230630161859](https://github.com/reqable/reqable-app/assets/46832863/42f84b04-bcd2-44d8-b068-d2b4c5ad71ff)

![Dingtalk_20230630160740](https://github.com/reqable/reqable-app/assets/46832863/3be5a59c-05c8-4e3e-8565-b49551230827)

**Comment by MegatronKing** [comment]
您好，这个是预期的行为。UI显示的内容是断点、重写、脚本等全部执行之后的结果，因为你返回了None表示不向服务器发送数据，所以UI上也不会显示数据。之所以不显示原始数据，因为用户可能会觉得很奇怪，为什么我用了脚本等修改了数据但是UI里面看到数据没有被修改呢？

**Comment by cry980285208** [comment]
> 您好，这个是预期的行为。UI显示的内容是断点、重写、脚本等全部执行之后的结果，因为你返回了None表示不向服务器发送数据，所以UI上也不会显示数据。之所以不显示原始数据，因为用户可能会觉得很奇怪，为什么我用了脚本等修改了数据但是UI里面看到数据没有被修改呢？

我期望的是UI上显示的是我用脚本修改请求参数后的数据，而不是显示原始数据，虽然返回了None，但实际请求参数已经构造好了，只是代理软件拦截了这个请求，所以这里应该显示最终修改后的结果比较合理一点

**Comment by MegatronKing** [comment]
Reqable拦截是基于责任链模式，流量入->网关->重写->断点->脚本->UI显示->流量出，脚本里面返回None表示中断整个责任链路和断点功能里面中断请求是一样的，相当于抛出异常，最终数据都不会经过`UI显示`这一步。

**Comment by cry980285208** [comment]
> Reqable拦截是基于责任链模式，流量入->网关->重写->断点->脚本->UI显示->流量出，脚本里面返回None表示中断整个责任链路和断点功能里面中断请求是一样的，相当于抛出异常，最终数据都不会经过`UI显示`这一步。

那如果我想实现修改请求参数，但不向服务器发送这个请求，是不是只能在控制台打印请求的参数是吗？在def onResponse(context, response):
  return None 这里返回None实际是已经向服务器发送了请求是吧？

**Comment by MegatronKing** [comment]
> 那如果我想实现修改请求参数，但不向服务器发送这个请求
这样的场景我倒是没有想到过。这个确实只能在onRequest里面返回None。
> onResponse函数内部返回None实际是已经向服务器发送了请求是吧
是的。onResponse负责处理即将返回给客户端的响应数据。返回None，表示客户端将无法收到响应数据。
