### ISSUE TITLE
使用一段时间后程序目录占用大问题

### ISSUE THREAD

**Issue by HDY-XXX** [reqable/reqable-app#890]
![reqabl](https://github.com/user-attachments/assets/63e5d360-da05-41a8-858f-c49f988cee08)

![image](https://github.com/user-attachments/assets/0dd8fdc1-24f4-4551-8838-87c206af7646)
程序版本 v2.22.2
使用约三个月

**Comment by MegatronKing** [comment]
@HDY-XXX 是不是改过缓存时间设置？

<img width="1080" alt="截屏2024-09-02 11 34 11" src="https://github.com/user-attachments/assets/00757d38-8483-4608-a1fd-3e9e0c01232e">

**Comment by MegatronKing** [comment]
没有进一步的回复，Issue我关闭了。
