### ISSUE TITLE
[bug] 下载文件请求，文件名乱码

### ISSUE THREAD

**Issue by Jump2nj** [reqable/reqable-app#894]
没有像postman一样发送请求并下载的一键按钮，下载文件需要再单独点一次保存，并且保存的文件名乱码，这个可以优化吗或者哪里可以设置呢？

**Comment by Jump2nj** [comment]
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/0effb7ca-aad9-4a03-bbd4-ce21d456f58b">

**Comment by Jump2nj** [comment]
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/28f85304-1b0d-414f-963c-2a7686147150">

**Comment by MegatronKing** [comment]
保存文件，启用下脚本，文件路径可以自定义:
```python
response.body.writeFile(path)
```

**Comment by Jump2nj** [comment]
<img width="657" alt="image" src="https://github.com/user-attachments/assets/243d92e0-cd0a-4a80-913d-f999c58bec91">
您说的脚本方式每个下载接口都需要单独定义文件名且需要点击两次按钮，postman一步到位自动拉起弹框选择文件保存路径而且文件名也没乱码。提个建议优化下哈哈，毕竟订阅了就不想再用postman了😂

**Comment by MegatronKing** [comment]
@Jump2nj 更新下v2.23.0版本，这个问题已处理。
