### ISSUE TITLE
[feature] 更新更多脚本示例代码

### ISSUE THREAD

**Issue by wuewill** [reqable/reqable-app#90]
请更新多一点脚本的用法，现有的脚本示例用法对新手不友好  比如请求类的示例   ，multipart数据的写法，数据的字典转换

**Comment by MegatronKing** [comment]
1. 脚本的框架代码已全部开源：https://github.com/reqable/python-scripting-api
2. 新建了一个脚本公共模板仓库：https://github.com/reqable/python-scripting-templates
