### ISSUE TITLE
No support for Russian domains

### ISSUE THREAD

**Issue by xshadow0x** [reqable/reqable-app#901]
**Describe the bug**
No support for Russian domains. When attempting to compose a request with a Russian domain (e.g., https://дом.рф/), the program crashes, although it was expected to encode it as https://xn--d1aqf.xn--p1ai/ and send the request. However, when sniffing traffic from an Android device, the Russian domain is represented in URL encoding as %20..., which also hinders the connection.

**Information**
 - Platform:  windows, android
 - OS: win11, android14
 - Arch: win64, android arm64
 - App Version: v2.22.0

**Comment by MegatronKing** [comment]
Fixed on v2.23.0.
