### ISSUE TITLE
[bug] 安卓手机接入代理进行抓包后，网络请求很慢。

### ISSUE THREAD

**Issue by DevinFu** [reqable/reqable-app#903]
安卓手机接入代理进行抓包后，如果历史记录长时间没清理，网络请求会很慢。

**Information**
 - Platform: [macos]
 - OS: [12.7.6]
 - Arch: [x86-64]
 - App Version: [2.20.1]

**Comment by MegatronKing** [comment]
@DevinFu 您好，感谢反馈，请问是调试列表旧数据没清理，还是侧边栏历史Tab里面的历史记录没清理？

**Comment by MegatronKing** [comment]
由于没有进一步的回复，issue关闭。
