### ISSUE TITLE
[bug]+符号被自动添加空格

### ISSUE THREAD

**Issue by ghost-xx** [reqable/reqable-app#906]
![46LD)1N KQQ3$VIYGT`WB27](https://github.com/user-attachments/assets/5bc8ff08-d3f1-45f2-bf20-ad4da6fea94d)
这是刚复制进去的   

然后在点链接就会自动被更改
![39@{NCT8 M4Q@)0 (%85) 9](https://github.com/user-attachments/assets/82d1a373-bc9f-4b00-b01a-4e61b83d4a1f)

**Comment by MegatronKing** [comment]
@ghost-xx 你好，感谢反馈，这个不是bug，是这样设计的。

空格在URL编码之后就是`+`号，我们无法判断用户在URL输入框里面输入的是编码前还是编码后的数据，所以统一按照编码后的进行处理，因为用户复制粘贴编码的URL的情况比较多。`+`号解码之后就变成空格。如果你需要保持`+`号，请在参数tab下面进行编辑。

如果你用postman等工具，你会发现虽然显示的是`+`，但实际发送的数据是空格，这个会造成很大的误导。

**Comment by MegatronKing** [comment]
在设计接口的时候，如果需要传递base64数据，尽量不要通过参数传递。因为Base64里面的`+`和`=`符号会导致很大的歧义。
