### ISSUE TITLE
[bug] 关于导入curl时，请求体无法正常导入的问题

### ISSUE THREAD

**Issue by xvhuan** [reqable/reqable-app#907]
curl 'https://test/test.php' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36' \
  -H 'X-Requested-With: XMLHttpRequest' \
  --data-raw 'requestParamStr={"a":"bbb"}' \
  --insecure

类似于上述的post表单，导入curl无法正常导入。
![image](https://github.com/user-attachments/assets/42b8f106-026f-44dd-9191-61141d727bf9)

![image](https://github.com/user-attachments/assets/3da4407e-9129-4b05-aec5-861c8d1237bd)

**Comment by MegatronKing** [comment]
@xvhuan 您好，感谢反馈，我们在v2.23.0版本已经修复了此问题。
