### ISSUE TITLE
[bug] 更新后抓包闪退

### ISSUE THREAD

**Issue by ms458** [reqable/reqable-app#908]
APP版本：2.23.0
设备：红米k70pro（Android 14）
https://github.com/user-attachments/assets/ebc690c3-0f9b-41df-a874-bf80cc6f5cde

上个版本没有这问题

**Comment by MegatronKing** [comment]
@ms458 您好，感谢反馈，我们无法复现此问题。试过卸载重装或者清除数据吗？

**Comment by ms458** [comment]
> @ms458 您好，感谢反馈，我们无法复现此问题。试过卸载重装或者清除数据吗？

我没有试过，我嫌麻烦，那我现在试试清除数据和重新安装吧

**Comment by MegatronKing** [comment]
已解决。
