### ISSUE TITLE
[bug] Android13安装用户CA时出现问题 - 无法将此文件用于CA证书

### ISSUE THREAD

**Issue by Bro-Xun** [reqable/reqable-app#91]
**Describe the bug**
在Android13设备上安装用户CA时出现问题

**To Reproduce**
1. 在系统安全选项卡-CA证书下安装`reqable-ca.crt`或`reqable-ca.pem`

**Information**
 - Platform: Redmi K50 Ultra
 - OS: MIUI 14 stable (Android 13)
 - Arch: arm64
 - App Version: latest

**Comment by MegatronKing** [comment]
@Bro-Xun 我测试没有这个问题，MIUI 14.0.6。能否再操作下录制个屏幕我看看？

**Comment by MegatronKing** [comment]
没有收到进一步的反馈，这个issue我先关闭了。
