### ISSUE TITLE
重定向不能屏蔽发往原服务器的请求吗

### ISSUE THREAD

**Issue by TimiXiaoFa** [reqable/reqable-app#910]
重定向不能屏蔽发往原服务器的请求吗

**Comment by MegatronKing** [comment]
您好，后面会优化的，同#267

**Comment by TimiXiaoFa** [comment]
我想让开发环境的前端xxx.dev:8090/api/service请求到本机localhost:8080/service
使用重写的话，会重复请求。使用脚本的话，无法修改url。使用镜像的话，不能屏蔽部分url，因为是多应用。
还有什么方法吗？
