### ISSUE TITLE
[bug] iOS最新版的app不能抓包，使用后没有流量通过

### ISSUE THREAD

**Issue by Fly-a-Kite** [reqable/reqable-app#911]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@Fly-a-Kite 您好，能否提供一个录屏？启动Reqable抓包，打开Safari App访问`reqable.com`网站。

**Comment by Fly-a-Kite** [comment]
Uploading a4c9beab66261c09d4a8d1ae7c10b62d.mp4…

**Comment by Fly-a-Kite** [comment]
所有的请求都不行，我根证书也安装上了

**Comment by MegatronKing** [comment]
@Fly-a-Kite 刚刚提交了2.24.0版本的更新，审核过后，更新下再试试。

**Comment by Fly-a-Kite** [comment]
@MegatronKing 最新版本的ios正常了

**Comment by mymine** [comment]
> @Fly-a-Kite 刚刚提交了2.24.0版本的更新，审核过后，更新下再试试。

Linux一样。debian,ubuntu,archlinux都不能抓包。可以链接手机抓包手机

**Comment by abnerxc** [comment]
> > [@Fly-a-Kite](https://github.com/Fly-a-Kite) 刚刚提交了2.24.0版本的更新，审核过后，更新下再试试。
> 
> Linux一样。debian,ubuntu,archlinux都不能抓包。可以链接手机抓包手机

一样的问题 ，我用的LinuxMint22.1 ，安卓和IOS都没有流量
