### ISSUE TITLE
[feature] 网关规则新建时继承上一个网关规则的行为

### ISSUE THREAD

**Issue by cxplay** [reqable/reqable-app#912]
在添加多个同类行为规则的时候将能大大提高效率.

**Comment by MegatronKing** [comment]
有`复制新建`选项。

**Comment by cxplay** [comment]
> 有`复制新建`选项。

忘记这个了, 感谢.

就是 Windows 新建规则的时候 Tab 不能用来切换输入框, Enter 也不能直接确认新建, 这个可以改进一下吗?
