### ISSUE TITLE
[feature] 在退出时保存当前工作区布局，并在下次打开时恢复

### ISSUE THREAD

**Issue by devioa** [reqable/reqable-app#913]
如题，比如请求参数配置区选择的是`请求头`，下次打开应用后应当也停留在这个选项卡，而不是重置到`参数`，还有把远程主机响应区`展开`布局后，下次打开应当保持这个布局，而不是重置为默认一半一半的布局，这样能降低每次启动后恢复布局的交互成本。

**Comment by MegatronKing** [comment]
您好，感谢建议。

**Comment by MegatronKing** [comment]
同 #130
