### ISSUE TITLE
摘取的数据包都只有connect数据包

### ISSUE THREAD

**Issue by dailei20021** [reqable/reqable-app#916]
192.168.31.241:90
![都是connect数据包](https://github.com/user-attachments/assets/00b48b07-4a64-41ec-8b24-3dbc87b30537)

windows11，windows64位版本Reqable
抓取网页数据，怎么调试模式返回的都是 connect数据包，一个get和post都没有。

**Comment by MegatronKing** [comment]
您好，有下面这些可能：
1. 证书未安装。
2. SSL代理设置的绕行模式。
3. 地址无法访问。

**Comment by dailei20021** [comment]
证书安装过的，一周前能正常抓包。网址正常的 绕行怎么设置呢？



---- 回复的原邮件 ----
| 发件人 | Megatron ***@***.***> |
| 日期 | 2024年09月09日 16:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [reqable/reqable-app] 摘取的数据包都只有connect数据包 (Issue #916) |

您好，有下面这些可能：

证书未安装。
SSL代理设置的绕行模式。
地址无法访问。

**Comment by MegatronKing** [comment]
查看官网文档。

**Comment by dailei20021** [comment]
谢谢



---- 回复的原邮件 ----
| 发件人 | Megatron ***@***.***> |
| 日期 | 2024年09月09日 16:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [reqable/reqable-app] 摘取的数据包都只有connect数据包 (Issue #916) |

查看官网文档。
