### ISSUE TITLE
[feature] 请问如何可以直接从浏览器中复制请求，粘贴到reqable在生成请求使用

### ISSUE THREAD

**Issue by jxs1211** [reqable/reqable-app#917]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MegatronKing** [comment]
@jxs1211 关注`Reqable`官方公众号，最新的一篇文章有讲到。

**Comment by jxs1211** [comment]
> @jxs1211 关注`Reqable`官方微信公众号，最新的一篇文章有讲到。

所以公众号是啥?

**Comment by MegatronKing** [comment]
微信公众号：Reqable
