### ISSUE TITLE
[bug] M1 频繁崩溃

### ISSUE THREAD

**Issue by xuergo** [reqable/reqable-app#919]

**Comment by xuergo** [comment]
[log.md](https://github.com/user-attachments/files/16947493/log.md)

**Comment by MegatronKing** [comment]
@xuergo 你之前好像提过一个闪退问题 #871

**Comment by xuergo** [comment]
> @xuergo 你之前好像提过一个闪退问题 #871

是的当时是安装了 x86 的版本，后面我重新安装了arm，但是还是会频繁闪退

**Comment by xuergo** [comment]
我是 m1 pro ，启动就闪退。复现的话，可以频繁启动退出，应该可以触发。我现在基本上奔溃之后要重新启动好几次才能进入。

**Comment by MegatronKing** [comment]
> 频繁启动退出，应该可以触发。

M2设备我测试好像复现不了。

**Comment by xuergo** [comment]
> > 频繁启动退出，应该可以触发。
> 
> M2设备我测试好像复现不了。

好吧，如果是个例，可能是我环境问题。但是这个问题似乎是我用了一段时间后才触发的，我重新安装一下试试吧

**Comment by MegatronKing** [comment]
日志看起来是框架的问题，和这个类似：https://github.com/flutter/flutter/issues/148279

**Comment by xuergo** [comment]
> 日志看起来是框架的问题，和这个类似：[flutter/flutter#148279](https://github.com/flutter/flutter/issues/148279)

好吧，只能等flutter 修复了

**Comment by MegatronKing** [comment]
这个问题可能和MacOS版本有关，看评论说有的版本能复现，有的版本不行。https://github.com/flutter/flutter/issues/148279#issuecomment-2118102510

**Comment by xuergo** [comment]
> 这个问题可能和MacOS版本有关，看评论说有的版本能复现，有的版本不行。[flutter/flutter#148279 (comment)](https://github.com/flutter/flutter/issues/148279#issuecomment-2118102510)

好像是有些关系，我同事的mac一直运行正常。有时间我将尝试更新我的系统。

**Comment by MegatronKing** [comment]
我试试自己修复重新编译下框架，之前也有类似这个问题，issue我还是重新打开。

**Comment by MegatronKing** [comment]
可以试试这个版本：
https://reqable-generic.pkg.coding.net/package/app/apple_m_crash_fix_test.dmg?version=latest

**Comment by xuergo** [comment]
> 可以试试这个版本： https://reqable-generic.pkg.coding.net/package/app/apple_m_crash_fix_test.dmg?version=latest

你好 我频繁退出打开确实不会闪退了，但是我手机抓包不好用了，需要设置什么东西吗

**Comment by MegatronKing** [comment]
> > 可以试试这个版本： https://reqable-generic.pkg.coding.net/package/app/apple_m_crash_fix_test.dmg?version=latest
> 
> 你好 我频繁退出打开确实不会闪退了，但是我手机抓包不好用了，需要设置什么东西吗

应该不是这个fix版本的问题。

**Comment by xuergo** [comment]
> > > 可以试试这个版本： https://reqable-generic.pkg.coding.net/package/app/apple_m_crash_fix_test.dmg?version=latest可以尝试这个版本： https://reqable-generic.pkg.coding.net/package/app/apple_m_crash_fix_test.dmg?version=latest
> > 
> > 
> > 你好 我频繁退出打开确实不会闪退了，但是我手机抓包不好用了，需要设置什么东西吗
> 
> 应该不是这个fix版本的问题。

没有问题，是我的设备许可证激活掉了，重新注册后一切正常。感谢🙏
