### ISSUE TITLE
[feature] 增加显示原始请求/响应内容

### ISSUE THREAD

**Issue by devcxm** [reqable/reqable-app#92]
示例

<img width="533" alt="image" src="https://github.com/reqable/reqable-app/assets/8568955/725b3105-3e08-44aa-8128-6263dd073137">

<br>

<img width="305" alt="image" src="https://github.com/reqable/reqable-app/assets/8568955/38c4ddb1-7d89-44d8-8721-0de245a78183">

**Comment by MegatronKing** [comment]
只有HTTP1.x的报文是以你截图内容的方式组织，而HTTP2/HTTP3等协议版本的报文并不是这种。另外，这种数据显示方式有什么特别的需求场景吗？

**Comment by wuewill** [comment]
我复议   这种方便

**Comment by devcxm** [comment]
> 只有HTTP1.x的报文是以你截图内容的方式组织，而HTTP2/HTTP3等协议版本的报文并不是这种。另外，这种数据显示方式有什么特别的需求场景吗？

为了能直观的看到服务器接收到的内容是什么，比如请求头，有些请求有重复请求头字段，还有些请求头字段是非法`:`开头（浏览器）。

**Comment by MegatronKing** [comment]
1.4.0已支持。

**Comment by fantasy0v0** [comment]
现在原始请求内容在哪里可以看到呢？
