### ISSUE TITLE
[bug] 协同手机抓包；应用程序没根据手机应用分类

### ISSUE THREAD

**Issue by wangyuan0217** [reqable/reqable-app#921]
![image](https://github.com/user-attachments/assets/fdec0ed0-79e6-4a01-af41-cbf4e4a8b6e6)
之前记得手机抓包这边显示的都是手机上app的名字，比如酷安，xxx等；但是现在统一都在电脑ip这个目录下了

**Comment by MegatronKing** [comment]
Android应该是有的，前提是扫码连接并保持在线的设备才有。

**Comment by wangyuan0217** [comment]
单纯手机抓包发现  2.21.几(忘了具体) 的版本抓包能显示具体的软件名称； 但是app升级到最新的2.23.0后，对app抓包，抓到了不显示应用名称，显示未知应用
![image](https://github.com/user-attachments/assets/87359d4d-a2e9-4fb7-890c-5f3a61005c17)

**Comment by wangyuan0217** [comment]
> Android应该是有的，前提是扫码连接并保持在线的设备才有。

都能抓到在电脑上显示了啊  环境是正常的吧；  感觉是老版本可以，新版本不行；

**Comment by MegatronKing** [comment]
你增强模式关掉了吗？

**Comment by wangyuan0217** [comment]
感谢；   应该是关掉了增强模式，  打开就有app名称了

**Comment by wangyuan0217** [comment]
想问下，为啥手机抓包同步到电脑上不需要再手机上设置代理到电脑的ip:9000啊，不设置就能正常抓包
