### ISSUE TITLE
[feature] 焦点没有好的办法从搜索项到列表

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#925]
当有多个搜索项，点击取消启用某个搜索项以后，焦点无法回到列表，这时 ctrl + L 无法响应，焦点要回到列表，只能点击列表，这时候就会失去当前选中的列表项， 因为列表项不会自动滚动到选中的位置，每次刷新都是从第一项开始的

**Comment by MegatronKing** [comment]
有点复杂，能录制个操作视频吗？

**Comment by RonaldinhoL** [comment]
好像又没有这个问题了，先关闭看看
