### ISSUE TITLE
[bug] 使用模块安装证书，软件会显示证书未安装；协同模式无法联网；内网无法进行协同；

### ISSUE THREAD

**Issue by batjoker** [reqable/reqable-app#929]
**Describe the bug**
1.刷入证书模块后，会显示证书未安装。
2.连接一台pc进行协同后，部分手机应用断网。
3.另一台内网网段pc无法进行协同。

**To Reproduce**
1.使用kernelSU刷入了模块并开启，会显示证书未安装，不过只在手机使用应用时可以正常联网和抓包。
2.连接pc1（内网地址192.168.xxx.xxx）协同显示设备已连接，但是手机应用就会断网。同时还会显示和pc的证书不一致问我要不要同步。
现在导致我有些抓取的内容只能在手机端一条一条复制到备忘录再粘给电脑，调试基本上没法调。或者手机点击导出，但是手机导出超过一定条数就会失败，大约100多条，不知道是社区版的限制还是手机性能限制还是有bug。
3.换了一个网络环境，扫描pc2（内网地址150.xxx.xxx.xxx，这个是自定义的，手机地址也在同一网段内）无法进行协同设备连接，一直在转圈。

**Expected behavior**
1.应当显示已安装（如果只是显示bug，不影响应用，也没问题）
2.pc应当能正确识别并抓取手机流量，手机导出不应当失败。
3.只要是一个网段应当都能连接上。我ping过两台设备是互通的。

**Screenshots**
1.证书问题
https://p.sda1.dev/19/0a31e5a223743a0de685ad491d02e281/IMG_20240917_102842.jpg https://p.sda1.dev/19/fadb5b0337515da2532167abdb8c6b6a/IMG_20240917_102927.jpg
 2.断网问题
https://p.sda1.dev/19/9a4016d7ae650fafc7330fac406fdb82/Screenshot_2024-09-17-10-17-01-870_com.ximalaya.ting.lite.jpg https://p.sda1.dev/19/f2c73182c41a537fa6abdeb80d604c6a/IMG_20240917_102958.jpg
3.该问题表现为不停转圈连不上，可以传一个日志
https://p.sda1.dev/19/af424e5a0a231820297d787240b256af/Screenshot_2024-09-17-10-41-28-387_bin.mt.plus.jpg
日志没有写出来，不过我连接wifi的时候是手动设了一个和1.57同段的地址的

**Information**
 - Platform: windows+android
 - OS: win10+MIUI13
 - Arch: x86-64,arm
 - App Version: 2.23.0（109）

**Comment by MegatronKing** [comment]
您好，感谢反馈。

> 1.使用kernelSU刷入了模块并开启，会显示证书未安装，不过只在手机使用应用时可以正常联网和抓包。

证书检测是系统的API调用，Magisk和kernelSU这些方式可能会破坏系统API的实现，这个没有什么办法。

> 2.连接pc1（内网地址192.168.xxx.xxx）协同显示设备已连接，但是手机应用就会断网。同时还会显示和pc的证书不一致问我要不要同步。

你要在电脑上调试，必须要在手机上安装电脑的证书。如果是多台设备，建议所有设备用同一个根证书，导出导入下即可。

> 手机导出超过一定条数就会失败，大约100多条，不知道是社区版的限制还是手机性能限制还是有bug。

应该是bug，如果还能复现录个视频我看看。

3.换了一个网络环境，扫描pc2（内网地址150.xxx.xxx.xxx，这个是自定义的，手机地址也在同一网段内）无法进行协同设备连接，一直在转圈。

同一个网段不代表能互联，可能是路由器或者交换机做了端口隔离等等，建议检查下。

**Comment by MegatronKing** [comment]
没有进一步的回复，issue关闭。
