### ISSUE TITLE
无法保存 har

### ISSUE THREAD

**Issue by RonaldinhoL** [reqable/reqable-app#93]
![image](https://github.com/reqable/reqable-app/assets/1797392/da503ee0-052b-44ee-a7ff-c20d56247581)

不管选哪个目录以什么文件名保存都会失败

**Comment by MegatronKing** [comment]
看起来不像是Reqable的问题，是不是某些软件对Reqable采取了沙盒机制阻止了Reqable进行文件读取和写入。或者，是否有试过其他盘？

**Comment by RonaldinhoL** [comment]
> 

存哪个盘都没用， 1.0.6 (22) (x86_64) 稳定复现

**Comment by MegatronKing** [comment]
> > 
> 
> 存哪个盘都没用， 1.0.6 (22) (x86_64) 稳定复现

本机运行还是模拟器里面运行？还有软件是安装在哪个目录下面？

**Comment by MegatronKing** [comment]
@RonaldinhoL  v1.0.7版本已修复。
