### ISSUE TITLE
Support for Custom Domain Resolutions within the VPN

### ISSUE THREAD

**Issue by johnstef99** [reqable/reqable-app#933]
Hello,

I’ve been using Reqable in conjunction with [Virtual Hosts](https://github.com/x-falcon/Virtual-Hosts) on my Android phone for testing custom hosts. For instance, I need app.test to resolve to my PC’s IP during development.

However, since Reqable creates its own VPN, I’m unable to use both Reqable and Virtual Hosts at the same time, as they conflict with each other.

It would be very useful if Reqable could add a feature to define custom domain resolutions directly within the VPN, allowing for more flexible development setups without the need for additional apps or conflicts with other VPN-based tools.

**Comment by MegatronKing** [comment]
I think you can turn off VPN mode in Reqable.

**Comment by MegatronKing** [comment]
DNS Spoofing would be a better solution for your issue, in that case you can give up the Virtual Hosts. However, we haven't supported this feature on mobile platform.
