### ISSUE TITLE
[bug] couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by linlide** [reqable/reqable-app#934]
**Describe the bug**
I try the version versionName=2.6.3 on Android Emulator OS 8.1 and got the crash time to time when click icon on launcher. And new versions or old one have this issues either.

`
09-17 14:18:28.782  5600  5600 E AndroidRuntime: FATAL EXCEPTION: main
09-17 14:18:28.782  5600  5600 E AndroidRuntime: Process: com.reqable.android, PID: 5600
09-17 14:18:28.782  5600  5600 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.reqable.android/com.reqable.android.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/base.apk"],nativeLibraryDirectories=[/data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/lib/x86, /data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/base.apk"],nativeLibraryDirectories=[/data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/lib/x86, /data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at j3.d.f(Unknown Source:483)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at io.flutter.embedding.engine.b.<init>(Unknown Source:35)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at f3.f.I(Unknown Source:172)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at f3.f.q(Unknown Source:7)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at f3.e.onCreate(Unknown Source:13)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at com.reqable.android.MainActivity.onCreate(Unknown Source:0)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6999)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6990)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	... 10 more
09-17 14:18:28.782  5600  5600 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/base.apk"],nativeLibraryDirectories=[/data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/lib/x86, /data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at j3.d.f(Unknown Source:28)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	... 19 more
09-17 14:18:28.782  5600  5600 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/base.apk"],nativeLibraryDirectories=[/data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/lib/x86, /data/app/com.reqable.android-UqLQw5iXebnfzsRf8rZfRA==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at j3.d$a.b(Unknown Source:18)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at j3.d$a.call(Unknown Source:0)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-17 14:18:28.782  5600  5600 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
`

**To Reproduce**

**Expected behavior**
Crash time to time

**Screenshots**

**Information**
 - Platform: [Android Emulator]
 - OS: [8.1]
 - Arch: [x86]
 - App Version: [ versionCode=71 minSdk=21 targetSdk=33
    versionName=2.6.3
    apkSigningVersion=2
]

**Comment by MegatronKing** [comment]
We not support x86 arch.
