### ISSUE TITLE
[feature] 增加请求头信息过滤不记录的开关

### ISSUE THREAD

**Issue by lzxry** [reqable/reqable-app#935]
**Is your feature request related to a problem? Please describe.**
大部分情况下，抓包时，抓包的日志记录中会出现我的账号的cookies或者token信息，导出har文件也会携带账号的这些重要参数

**Describe the solution you'd like**
增加一个设置过滤不记录请求头参数的开关

**Comment by MegatronKing** [comment]
@lzxry 您好，感谢建议。这个需求恐怕不好实现，重要信息可能是在参数，可能是在头部，可能是在数据体，没有办法做到智能过滤。
