### ISSUE TITLE
[bug] Android 14 上无法正常抓包，证书日期也不一致

### ISSUE THREAD

**Issue by TigerBeanst** [reqable/reqable-app#936]
**Describe the bug**
在证书模块安装，且 Reqable 内部能正常判定模块已安装根证书的情况下，抓包目标选中 Edge Android Canary（便于查看证书，其他应用也无法正常抓包，没网），不开启调试时，网页正常访问，开启后出现证书错误，且日期与安装的 CA 证书不同，显示的是原本网站证书的日期。
（增强模式，记录模式为VPN，本机，未开启二级代理）

未避免其他问题，已尝试先卸载 Reqable，卸载证书模块，重启手机，安装 Reqable，生成新证书模块安装并重启。且不开启二级代理。

**Screenshots**
![Screenshot_2024-09-19-20-16-19-014_com reqable android](https://github.com/user-attachments/assets/61a69c8e-cdd7-46bf-8b2d-f399416f339b)

![Screenshot_2024-09-19-19-51-38-082_com microsoft emmx canary](https://github.com/user-attachments/assets/5afbfc36-4d46-46a1-b933-66464ae1f104)

![Screenshot_2024-09-19-19-53-57-618_me weishu kernelsu](https://github.com/user-attachments/assets/ab9c97a0-4041-438d-b81a-4a491942bbf6)

![Screenshot_2024-09-19-19-53-07-241_com android settings](https://github.com/user-attachments/assets/85a33ea5-89cb-4b1a-812d-14c60588ec82)

录屏参考：https://1drv.ms/v/s!AhWD_ingH5wej7ZqOJe8P10q8H_e0A

**Information**
 - Platform: Android
 - OS: 14
 - Arch: arm64
 - App Version: 2.23.1(110)

**Comment by MegatronKing** [comment]
@TigerBeanst 

1. 试试其他浏览器，比如firefox。
2. 试试重启设备。
3. 试试重装证书。

**Comment by TigerBeanst** [comment]
> @TigerBeanst
> 
> 1. 试试其他浏览器，比如firefox。
> 2. 试试重启设备。
> 3. 试试重装证书。

1. 这一点正文提到过，正常App也会连不上，看Reqable里的提示也是SSL错误
2&3. 试过很多次了，也彻底卸载Reqable重装过

**Comment by MegatronKing** [comment]
> > @TigerBeanst
> > 
> > 1. 试试其他浏览器，比如firefox。
> > 2. 试试重启设备。
> > 3. 试试重装证书。
> 
> 1. 这一点正文提到过，正常App也会连不上，看Reqable里的提示也是SSL错误
> 
> 2&3. 试过很多次了，也彻底卸载Reqable重装过

证书安装的问题还是需要你自己排查，也许是操作问题，也许是系统问题。这里提issue是没有用的，我确实帮不了你。

**Comment by Youlor** [comment]
我也遇到了 一模一样 修一下吧

**Comment by TigerBeanst** [comment]
目前测试下来抓包很随缘，在其他条件不变的情况下，有时候会直接导致对应应用没网，有时候又能抓到请求。。

**Comment by MegatronKing** [comment]
> 目前测试下来抓包很随缘，在其他条件不变的情况下，有时候会直接导致对应应用没网，有时候又能抓到请求。。

更新到最新2.24.0看看。

**Comment by TigerBeanst** [comment]
> > 目前测试下来抓包很随缘，在其他条件不变的情况下，有时候会直接导致对应应用没网，有时候又能抓到请求。。
> 
> 更新到最新2.24.0看看。

依旧。举个例子，我现在打开 https://github.com/Geocld/XStreaming 对它进行抓包成功了，XStreaming 正常有网络，Reqable 能捕获到请求。
但我可能在 Reqable 上停止记录后，清除原本有的记录再打开记录，回到 XStreaming 抓包，就会使得 XStreaming 没有网络，且记录里甚至连请求都没有。
反复杀掉Reqable后指不定某一次就又可以了。

**Comment by deximy** [comment]
我也发现了，有时候会出现之前抓包抓的好好的，断掉capture再打开之后就一个包都抓不到同时应用断网，一个workaround就是疯狂重启，重启若干次之后问题可能会神奇的消失。

**Comment by suyanlin** [comment]
+1，证书都已经安装了，手机端单独使用，还是和PC端协同使用，只有开启抓包了，其它app都无法使用~这个问题一直都存在，今天是2024.09.29~我的是安卓14，未root，客户端是最新的，证书一致（和楼主的不一样）~

**Comment by Youlor** [comment]
这个问题我都解决了，但是很扭曲，希望修一下。@TigerBeanst
根本原因：应该是电脑（我是windows）的证书有问题，通过下载magisk插件刷入Android去抓包就会出现这个issue。
解决方案：从reqable Android app生成magisk插件并刷入，然后把这个Android的p12证书导入电脑，再抓包就不会有问题了。

**Comment by TigerBeanst** [comment]
> 这个问题我都解决了，但是很扭曲，希望修一下。@TigerBeanst 根本原因：应该是电脑（我是windows）的证书有问题，通过下载magisk插件刷入Android去抓包就会出现这个issue。 解决方案：从reqable Android app生成magisk插件并刷入，然后把这个Android的p12证书导入电脑，再抓包就不会有问题了。 再补充一句，以前版本没问题，估计是新版本引入的bug

我这个过程一直用的是手机端产生的CA证书，没有用到协同……

**Comment by llheidgall** [comment]
我也试了，reqable ＋magisk抓一般应用（QQ，微信）可以抓到，但是Edge Chrome Forefox 应该是内置了ssl检测，并且一旦ssl错误，就会中断连接。
应该要改应用内置的ssl功能，如使用JustTrustMe来绕过

![Image](https://github.com/user-attachments/assets/cb676e97-bbdb-48b3-b5a0-b552327e91ff)
