### ISSUE TITLE
[feature] Windows下拉菜单交互优化

### ISSUE THREAD

**Issue by JiaLeDe** [reqable/reqable-app#94]
看到有发放5折优惠券，希望可以参与活动领取一张，还有获取优惠券的途径嘛？(想开通10+年)

**Comment by MegatronKing** [comment]
@JiaLeDe 之前参加内测的同学有首年五折优惠，或者之前购买过HttpCanary的可以免费领取两年，其他优惠没有了。由于已经有用户续期了10年，如果突然新增折扣活动，背刺他们非常不公平，所以目前不考虑优惠活动，望理解。

**Comment by JiaLeDe** [comment]
还有ui界面的一个小优化，就是当点击左上角的一些菜单后，如'文件'，点击后会展示下拉框，此时将鼠标移动到旁边的'工具'上时，'文件'的下拉框依旧存在，可不可以在第一次点击后，下拉框跟随鼠标移动，移动到哪个菜单就展示哪个菜单的下拉框？

**Comment by MegatronKing** [comment]
> 还有ui界面的一个小优化，就是当点击左上角的一些菜单后，如'文件'，点击后会展示下拉框，此时将鼠标移动到旁边的'工具'上时，'文件'的下拉框依旧存在，可不可以在第一次点击后，下拉框跟随鼠标移动，移动到哪个菜单就展示哪个菜单的下拉框？

您提议的这个效果是最理想的。不过我之前初步研究发现这个效果不太容易实现，而且目前需求池中有更多重要的功能，所以目前没有计划去优化这个细节。

**Comment by MegatronKing** [comment]
1.2.0已优化。
