### ISSUE TITLE
[bug] cUrl import problem

### ISSUE THREAD

**Issue by Flikify** [reqable/reqable-app#942]
**Describe the bug**
When importing curl, the data type of the request body will not automatically change to the type corresponding to Content-Type

**To Reproduce**
1. Copy curl from f12 developer tools
2. Import cUrl in Reqable
3. Click on the request body
4. The data type of the request body is always the default Urlencode

**Expected behavior**
I hope it can automatically change with content-type

**Screenshots**
![image](https://github.com/user-attachments/assets/5c6164e6-c3d1-4fc7-8a74-844dceaa167a)

**Information**
 - Platform: windows
 - OS: 23H2
 - Arch:  x86-64
 - App Version: 2.24.0

**Comment by Flikify** [comment]
![image](https://github.com/user-attachments/assets/2ff5a07e-7656-4409-afe0-69469c5f4247)

**Comment by MegatronKing** [comment]
@Flikify Please paste the cURL here, I will have a look.

**Comment by Flikify** [comment]
A Content-type is automatically added，I have hidden my real address

`curl 'https://api.test.cn/staticInfo' \
  -H 'accept: */*' \
  -H 'accept-language: zh-CN,zh;q=0.9' \
  -H 'content-type: application/json;charset:utf-8;' \
  -H 'origin: https://api.test.cn' \
  -H 'priority: u=1, i' \
  -H 'referer: https://api.test.cn/' \
  -H 'sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36' \
  -H 'x-ta-uid: 09031146215707620003' \
  --data-raw '{"locationId":7037463}'`

**Comment by Flikify** [comment]
![image](https://github.com/user-attachments/assets/98a16266-13d5-4212-aa04-fcd029c344d0)

After importing, you can see that there are two Content-types on the image, and the data type of the request body is Urlencode

**Comment by MegatronKing** [comment]
Change `content-type: application/json;charset:utf-8;` to `content-type: application/json` will work.

**Comment by MegatronKing** [comment]
I will fix this in the next hotfix version.

**Comment by MegatronKing** [comment]
`application/json;charset:utf-8;` seems to be a invalid value, `application/json; charset=utf-8` is correct.
