### ISSUE TITLE
[bug] 证书错误

### ISSUE THREAD

**Issue by TopChina** [reqable/reqable-app#944]
<img width="553" alt="image" src="https://github.com/user-attachments/assets/59021854-95bb-44c8-a508-fd9086ec4edb">
<img width="513" alt="image" src="https://github.com/user-attachments/assets/ad696f09-781f-42e1-bce2-a50c380d53a7">
<img width="513" alt="image" src="https://github.com/user-attachments/assets/5ccbed46-c989-41af-99f4-a4f276010141">

这个问题困扰我好几个月了,同样的代理软件,surge,Proxyman,Postman等,都不报这个错误,证书信任配置的一模一样的,唯一区别可能是其他代理软件自动忽略了一些127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,17.0.0.0/8,localhost,*.local,*.crashlytics.com

**Comment by MegatronKing** [comment]
@TopChina 第一张截图是哪里的？

**Comment by MegatronKing** [comment]
@TopChina 

你试试导出证书文件（Reqable - 证书菜单 - 根证书管理 - 导出根公钥证书.crt），然后运行下下面的命令看看：
```bash
security verify-cert -c /Users/megatronking/Downloads/reqable-ca.crt
```

**Comment by MegatronKing** [comment]
@TopChina 说明证书安装是OK的，如果应用提示证书不信任，说明没有使用系统的CA Store，可能是直接内置的独立的CA Store。
