### ISSUE TITLE
[feature] 增加复制应用信息功能

### ISSUE THREAD

**Issue by SebaSs007** [reqable/reqable-app#947]
1、软件在调试页支持 复制url和复制curl两种，希望增加复制应用程序列、应用ID列字段的功能，最好再添加一个保存应用图标的选项，方便用于检索与拓展。
![image](https://github.com/user-attachments/assets/af5f36be-39d9-4dd5-bf71-32941df33e1f)
2、针对流量底噪的问题，软件提供了白名单功能，但每次都要在APP上添加指定的应用会多些步骤，抓包分析量很大时影响节奏，而且有时应用会产生一些 APP之外的流量，这样会有遗漏。
     相比白名单能否在 电脑端添加一个黑名单，把应用ID等作为隐藏字段，这样我只需要维护这个黑名单就行了。

**Comment by MegatronKing** [comment]
@SebaSs007 最新版本实现了黑名单功能。

**Comment by MegatronKing** [comment]
2.27.0版本在详情总览tab下面新增了应用信息显示，长按可以直接复制。

**Comment by NeverMore126** [comment]
@SebaSs007 您好，我也在研究涉诈APP，可否方便交流一下，如果方便可以加我Q 1186422137或者邮件 1186422137@qq.com
