### ISSUE TITLE
[bug] 开发人员证书名称错误，导致安卓设备无法抓取https

### ISSUE THREAD

**Issue by meesii** [reqable/reqable-app#948]
![image](https://github.com/user-attachments/assets/0719c0ed-210a-4a92-b9b6-b19e02695b25)

你们提供的证书名称为“4069bf7.0”，漏掉了前面一位，我对比了系统的证书全是8个字符的。
然后我自己通过openssl计算得出正确名称应该是“04069bf7.0”。
我把正确的名称复制到system/etc/security/cacerts/ 立马就可以抓包了！
希望官网赶紧修改掉这个错误，以免更多人浪费时间。

**Comment by MegatronKing** [comment]
@meesii 非常感谢，我们尽快修复。

**Comment by MegatronKing** [comment]
2.25.0已修复。
