### ISSUE TITLE
[bug] 非root的安卓14系统的手机，无法正常抓包。

### ISSUE THREAD

**Issue by suyanlin** [reqable/reqable-app#950]
非root的安卓14系统的手机，无法正常抓包，使用的是最新版2.25.0。
无论是协同模式，还是独立模式，只要开启了抓包，手机其它app都是无法正常访问网络。
PC端和手机端都已经安装好了证书，重启手机，清理app缓存都试过了。

如果电脑开启v2rayN，再在reqable配置并开启的二级代理的话，部分海外app可以正常访问并抓包，比如TG，但是谷歌应用市场app还是不行。以前的旧手机使用小黄鸟好好，这个reqable的手机端抓包体验实在太差，简直就是没法使用，完全没有购买欲望，虽然PC端体验很优秀，比Fiddler好。

**Comment by MegatronKing** [comment]
已知有一个 #948 的bug，最新版本2.25.0已经修复了。

**Comment by suyanlin** [comment]
> 已知有一个#948的bug，最新版本2.25.0已经修复了。

两个bug看起来一样，实际上是不一样的，他那个是属于已经root的手机，我这个是还没有root的手机~

**Comment by MegatronKing** [comment]
@suyanlin 您好，麻烦提供下具体的能够复现问题的步骤呢。

**Comment by suyanlin** [comment]
> @suyanlin 您好，麻烦提供下具体的能够复现问题的操作步骤呢。

你们找一台非root的安卓14系统的手机正常安装使用测试就知道了呀，很多人都遇到这个问题~

**Comment by MegatronKing** [comment]
非root的设备需要在源码项目里面处理证书的问题。这个issue我现在关闭了，如果发现有明确Reqable的bug再重新打开。
