### ISSUE TITLE
[bug] ios

### ISSUE THREAD

**Issue by miaobukeyan17** [reqable/reqable-app#955]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by miaobukeyan17** [comment]
ios WeChat 无法抓包

**Comment by MegatronKing** [comment]
您好，如果有具体问题请说具体问题，如果某些应用有问题请联系应用开发商。
