### ISSUE TITLE
[bug] 环境变量赋值实际只在当前context生效。没有全局生效。比如在其它请求，还是使用的是默认值。

### ISSUE THREAD

**Issue by zhanlan123** [reqable/reqable-app#961]
![image](https://github.com/user-attachments/assets/c5ff2a91-35f6-423f-9a1a-7e78e971c7f7)
就是此功能没有效果。

**Comment by zhanlan123** [comment]
此功能的写入变量没有效果

**Comment by zhanlan123** [comment]
如果环境变量没有，可以写入，但是如果存在，就不能变更。

**Comment by MegatronKing** [comment]
@zhanlan123 感谢反馈，问题已经确认，我们将在下个版本修复。

**Comment by MegatronKing** [comment]
v2.26.0已经修复
