### ISSUE TITLE
[bug]  复制 cUrl 的时候失败，提示：创建请求失败:FormatException:Filter error,bad data

### ISSUE THREAD

**Issue by KorolZhu** [reqable/reqable-app#963]
mac 上抓包的某个请求，点击复制 cUrl 的时候失败，提示：创建请求失败:FormatException:Filter error,bad data
点击 编辑的时候也会失败，也会提示上面这个信息
还有双击这个请求看请求体的时候也会提示上面这个

版本信息：
Mac 端 版本2.25.1 (114)

**Comment by MegatronKing** [comment]
@KorolZhu 您好，这个请求的原始报文能截个图看看吗？如果不方便贴在这里，可以发送到我们邮箱 coding@reqable.com

**Comment by KorolZhu** [comment]
@MegatronKing 你好，原始报文已经发送到你的邮箱

**Comment by KorolZhu** [comment]
我这个问题作者回复我了，已经解决了，我把我这个问题原因说明下，你看看是不是同样的问题

问题原因：
我这个请求的请求头中有个字段Content-Encoding: gzip，但是呢，我的请求体是明文的 json ，并没有 gzip 压缩
而 reqable 识别到有 gzip 请求头的时候，是认为请求体是 gzip 压缩的，所以也会以 gzip 解压缩去显示这个请求体，因为我请求体是没有压缩的，拿没有压缩的去解压缩，肯定是有异常。所以显示上面那个报错信息

解决方法：
去掉这个请求头就行了
Content-Encoding: gzip

@hnuuhc

**Comment by hnuuhc** [comment]
> 我这个问题作者回复我了，已经解决了，我把我这个问题原因说明下，你看看是不是同样的问题
> 
> 问题原因： 我这个请求的请求头中有个字段Content-Encoding: gzip，但是呢，我的请求体是明文的 json ，并没有 gzip 压缩 而 reqable 识别到有 gzip 请求头的时候，是认为请求体是 gzip 压缩的，所以也会以 gzip 解压缩去显示这个请求体，因为我请求体是没有压缩的，拿没有压缩的去解压缩，肯定是有异常。所以显示上面那个报错信息
> 
> 解决方法： 去掉这个请求头就行了 Content-Encoding: gzip
> 
> @hnuuhc

我想我明白你的意思了,确实有这个请求头,但是请求并不是我发起,而且应用发起的,所以我无法控制不添加这个参数.问题在android中,win中未遇到,但应该会类似.

**Comment by MegatronKing** [comment]
@hnuuhc 如果你的请求头（或者响应头）中包含了`Content-Encoding: gzip`或者类似`gzip`的压缩算法，但是实际body未进行压缩或者压缩不正确，那么reqable进行解码就会报错。可能有些开发者乱传字段，声明了压缩但是实际不压缩。对于这些不符合规范的请求，你用重写或者脚本把这个字段删掉就好了。

**Comment by hnuuhc** [comment]
> @hnuuhc 如果你的请求头（或者响应头）中包含了`Content-Encoding: gzip`或者类似`gzip`的压缩算法，但是实际body未进行压缩或者压缩不正确，那么reqable进行解码就会报错。可能有些开发者乱传字段，声明了压缩但是实际不压缩。对于这些不符合规范的请求，你用重写或者脚本把这个字段删掉就好了。

首先,在app中没有重写的功能,使用编辑和复制选项也都会提示创建请求失败,而且这些也只能在错误之后修改单个请求,无法批量操作,在调试时,几十条都是如此,只能查看原始报文,调试起来将会非常难受.

**Comment by MegatronKing** [comment]
@hnuuhc 请用电脑版本进行操作，app流量可以转发到电脑。
