### ISSUE TITLE
[bug] 新建一个 Api发送到服务端失败，Postman 就没问题

### ISSUE THREAD

**Issue by KorolZhu** [reqable/reqable-app#964]
我新建一个 post api 请求，添加请求头，和 json的请求体，发送到服务端，提示非法请求，服务端告诉我是请求体是乱码，
我用同样的方式用 postmen 构造这个请求，就没问题

版本：
Mac 端 2.25.1 (114)

**Comment by MegatronKing** [comment]
@KorolZhu 您好，能提供下这个API的curl吗，我这边测试下。

**Comment by KorolZhu** [comment]
@MegatronKing 你好，已经发送到你的邮箱

**Comment by KorolZhu** [comment]
我这个问题作者回复我了，已经解决了，我把我这个问题原因说明下

问题原因：
我这个请求的请求头中有个字段Content-Encoding: gzip，但是呢，我的请求体是明文的 json ，并没有 gzip 压缩
在新建一个 api发送的时候，reqable 识别到我有 gzip 字段，会默认对请求体进行压缩，所以发送给服务端的是压缩后的内容，但是服务端不支持 gzip 压缩，直接以明文的方式读取，所以就乱码了

解决方法：
去掉这个请求头就行了
Content-Encoding: gzip
