### ISSUE TITLE
is there any way to unlock it

### ISSUE THREAD

**Issue by menmemdvtka** [reqable/reqable-app#967]
![screenshot_1728550889](https://github.com/user-attachments/assets/3c93de02-5466-4899-b76b-6f3235d2e2e4)

**Comment by MegatronKing** [comment]
SSL handshake error?

**Comment by menmemdvtka** [comment]
> Lỗi bắt tay SSL?

how to fix it admin
any instructions

**Comment by MegatronKing** [comment]
Install `Reqable Proxy CA Certificate` to your device correctly.

https://reqable.com/en-US/docs/getting-started/installation/

**Comment by menmemdvtka** [comment]
> Install `Reqable Proxy CA Certificate` to your device correctly.
> 
> https://reqable.com/en-US/docs/getting-started/installation/

![image](https://github.com/user-attachments/assets/fb945a6b-f7db-436f-8b2b-69b1bc26878f)
Although ssl is all green, why is there still an error? I hope admin can support me.

**Comment by MegatronKing** [comment]
@menmemdvtka If you want to capture mobile traffic, you must install PC CA certificate to mobile. The green icon indicates that you have installed the CA certificate in PC rather than mobile.

**Comment by menmemdvtka** [comment]
https://github.com/user-attachments/assets/f2f24310-4dff-4826-9853-a95ba1ba95ad

I installed everything correctly but still got an error. I'm running on Android 6.

**Comment by MegatronKing** [comment]
@menmemdvtka Tap a request to view the detail error message, give me a screen shot if you could.

**Comment by menmemdvtka** [comment]
> @menmemdvtka Tap a request to view the detail error message, give me a screen shot if you could.

admin accept socket inspection to decode to get the application api?
I want to hire admin to check I will pay admin
I bought the app from admin but can't check the problem

**Comment by MegatronKing** [comment]
Please provide me some useful error message, not the phenomenon.

**Comment by MegatronKing** [comment]
Tap a request to view the detail, it will show the error message.
