### ISSUE TITLE
请问怎么将小程序的请求打到本地呢

### ISSUE THREAD

**Issue by Riven872** [reqable/reqable-app#972]
看到有反向代理的功能，但是我起本地服务器之后好像没有监听选项用来监听我的本地服务器。
现在的想法是将小程序（在 PC 端直接打开的，不在移动端）的请求转发到本地，说白了就是把域名转换成 localhost:port 的形式，请问需要怎么做呢？

**Comment by Riven872** [comment]
或者说就是 Charles 的 Map Remote 功能怎么在 Reqable 上实现呢？

**Comment by MegatronKing** [comment]
@Riven872 用这个：https://reqable.com/zh-CN/docs/capture/rewrite#redirect

**Comment by Riven872** [comment]
可以了，我一开始用反向代理是理解错了。
