### ISSUE TITLE
[bug] websocket的url地址不正确，缺少斜杠

### ISSUE THREAD

**Issue by hualiye** [reqable/reqable-app#975]
websocket的url地址，主机名和路径之间缺少斜杠。
例如
本来是  wss://wsproxy.hpbz.com/?playerId=55309
工具上是 wss://wsproxyhpbz.com?playerId=55309

**Comment by MegatronKing** [comment]
@hualiye 请问是哪个版本，记得曾经修复过类似的bug。

**Comment by MegatronKing** [comment]
@hualiye 您好，请问能否提供下版本信息？

**Comment by MegatronKing** [comment]
没有进一步的信息，此issue关闭。
