### ISSUE TITLE
[bug]  id 号对不上

### ISSUE THREAD

**Issue by geekyouth** [reqable/reqable-app#976]
**Describe the bug**
![image](https://github.com/user-attachments/assets/e3d950bd-7610-4add-9db5-310991a35932)

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Information**
 - Platform: [e.g. windows, macos, linux]
 - OS: [e.g. 12.1]
 - Arch: [e.g. arm, x86-64]
 - App Version: [e.g. 1.0.0]

**Comment by MegatronKing** [comment]
@geekyouth 您好，感谢反馈，这两个ID号是不一样的。

- 列表里面的ID号，是请求的唯一标志符号，方便用户排序或者记住是哪个请求。
- 连接ID是TCP的连接序号，不同请求可能会相同，如果相同表示是复用的同一个TCP连接。
