### ISSUE TITLE
The backend will retain all request information, taking up my space

### ISSUE THREAD

**Issue by zhaoan719** [reqable/reqable-app#977]
When using this software, even if I select the domain name I need, it still crawls other domains, resulting in a lot of request information being saved in addition to the domain name I filtered. Can you provide a feature that, after I select only the domain name I need,other requests for domain names are not retained

**Comment by MegatronKing** [comment]
You can use `SSL Proxying`.

![image](https://github.com/user-attachments/assets/1e18eeea-2ca1-4aef-b0d8-a554274bd4d1)
