### ISSUE TITLE
[bug] 更新過後IOS 無法使用增強模式

### ISSUE THREAD

**Issue by l7123222l7** [reqable/reqable-app#979]
更新過後IOS 無法使用增強模式 會被攔截

**Comment by MegatronKing** [comment]
@l7123222l7 您好，感谢反馈，能否提供更详细的信息，例如操作步骤和截图。

**Comment by l7123222l7** [comment]
在ios 15.8 18.1 18.1-beta5 測試上 已經開啟完整根證書
在協同模式下 開啟增強模式 打開任何網站 都會被攔截不出現抓包數據
都已經安裝最新版本reqable 在電腦及其他設備上

其他IOS版本也是如此 在安卓上完美運作 不過因為工作需要 需要用到IOS 麻煩了感謝

![image](https://github.com/user-attachments/assets/4ae062a5-5767-4495-ab31-95798178f571)
![image](https://github.com/user-attachments/assets/0a6fe716-6889-40c2-9d17-a4e5117c7b33)
![image](https://github.com/user-attachments/assets/53c0f1b2-bbb1-4f3a-86d7-a838d151b1c7)

**Comment by bianzhifeng** [comment]
确实, iOS开了增强模式, 所有网络都不通了, 更别提抓包了

**Comment by MegatronKing** [comment]
这个问题已经解决了，需要等下个版本更新。

**Comment by bianzhifeng** [comment]
太好了! 麻烦问下, 大概多长时间有版本更新呢?

**Comment by MegatronKing** [comment]
> 太好了! 麻烦问下, 大概多长时间有版本更新呢?

下周一二的样子。

**Comment by bianzhifeng** [comment]
牛皮牛皮~

**Comment by MegatronKing** [comment]
2.27.0版本已修复。

**Comment by bianzhifeng** [comment]
再次测试完美运行~ 牛皮~
