### ISSUE TITLE
[bug] 无法抓包

### ISSUE THREAD

**Issue by cocoyamnut** [reqable/reqable-app#980]
环境如下
![IMG_20241016_081526](https://github.com/user-attachments/assets/3695c23a-acb6-4446-bd17-744fb577f7ee)
![IMG_20241016_081618](https://github.com/user-attachments/assets/8fce08f9-b204-4084-a834-a8c816ce1fe6)
![IMG_20241016_082006](https://github.com/user-attachments/assets/e5dd701e-6a54-4c7f-9ebf-4b83048965d7)

**Comment by MegatronKing** [comment]
@cocoyamnut 证书信任问题需要你自己排查和解决，我们无法提供帮助。如果你找到问题原因，确定是我们的问题，欢迎反馈给我们。

**Comment by cocoyamnut** [comment]
> @cocoyamnut 证书信任问题需要你自己排查和解决，我们无法提供帮助。如果你找到问题原因，确定是我们的问题，欢迎反馈给我们。

确实是你们的问题，在安卓14模块并不会有作用。

**Comment by MegatronKing** [comment]
仔细阅读这个：https://reqable.com/zh-CN/docs/getting-started/installation/#%E6%B5%8F%E8%A7%88%E5%99%A8

**Comment by cocoyamnut** [comment]
> 仔细阅读这个：https://reqable.com/zh-CN/docs/getting-started/installation/#%E6%B5%8F%E8%A7%88%E5%99%A8

使用[MoveCertificate](https://github.com/ys1231/MoveCertificate)移动证书可以正常抓包。

**Comment by cocoyamnut** [comment]
并且不会出现不信任证书问题。

**Comment by MegatronKing** [comment]
文档已经讲得很清楚了，这个问题我关闭了。

**Comment by cocoyamnut** [comment]
![image](https://github.com/user-attachments/assets/aa7dabfc-16b6-4a57-935b-b922938accc1)
![image](https://github.com/user-attachments/assets/76682fc7-5491-4fdf-8287-95bc861c0423)
使用的是小米浏览器 抓取的https://baidu.com 浏览器不是chrome、firefox，没有也没固定证书。
