### ISSUE TITLE
[bug] 与安卓APP一起工作时，应用程序筛选栏异常抖动

### ISSUE THREAD

**Issue by cesaryuan** [reqable/reqable-app#982]
**Describe the bug**
与安卓APP一起工作时，应用程序筛选栏异常抖动，见视频

**To Reproduce**
1. 打开 reqable 安卓端
2. 与 PC 端一起使用
3. See error

**Expected behavior**
不要异常抖动

**Screenshots**

https://github.com/user-attachments/assets/21103bb6-c438-4877-b1c0-249ac159c853

**Information**
 - Platform: Windows
 - OS: 11
 - Arch: x86-64
 - App Version: 2.25.1

**Comment by MegatronKing** [comment]
@cesaryuan 获取应用信息是异步的，一开始是显示的IP地址，后面才会显示应用名称，因为排序的原因会跳动。

**Comment by cesaryuan** [comment]
> @cesaryuan 获取应用信息是异步的，一开始是显示的IP地址，后面才会显示应用名称，因为排序的原因会跳动。

现在这种情况导致在域名筛选栏和结构筛选栏中，鼠标无法准确的指向要筛选的内容，以为指到了，结果突然调动，鼠标就点到了别的筛选项

**Comment by MegatronKing** [comment]
这个好解决，下个版本IP那一项一直显示就不会跳动了

**Comment by MegatronKing** [comment]
@cesaryuan 更新下版本试试，已经优化了。
