### ISSUE TITLE
[bug] 新版本抓包界面很卡，特别影响体验，请排查

### ISSUE THREAD

**Issue by tabs** [reqable/reqable-app#983]
不知道从什么时候开始，抓包感觉界面很卡顿，体验极差

**Comment by tabs** [comment]
![image](https://github.com/user-attachments/assets/d3c2d8e2-b6e8-4e93-b3db-cac730b65c2f)

**Comment by tabs** [comment]
特别是请求多，比较快时候，卡，，，之前的版本没有这个现象

**Comment by MegatronKing** [comment]
@tabs 您好，感谢反馈。是不是有请求出现循环回路了，列表里面出现非常多相同的请求？

**Comment by tabs** [comment]
> @tabs 您好，感谢反馈。是不是有请求出现循环回路了，列表里面出现非常多相同的请求？

没有回路
![image](https://github.com/user-attachments/assets/831156f3-e7c3-4164-9175-c7b9adb936ea)

**Comment by tabs** [comment]
> @tabs 您好，感谢反馈。是不是有请求出现循环回路了，列表里面出现非常多相同的请求？

https://www.vvvdj.com/play/244490.html

**Comment by tabs** [comment]
![image](https://github.com/user-attachments/assets/2da27b76-5756-4080-8717-6ab8d396d5e8)

**Comment by tabs** [comment]
你好，我换了台电脑会快很多，不知道我台电脑怎么回事

**Comment by MegatronKing** [comment]
这个不影响性能，目前已知卡到影响体验的有几种情况。

1. 查看了比较大的数据，几十M上百M这种，会一点卡。
2. 请求回路，或者同时有大量请求在不停发，这个肯定会卡。这种能卡到列表里里面有很多完全一样的请求，SSL代理里面设置成绕行模式忽略这个请求的域名可以解决。
3. 历史记录数据过大可能会有影响，侧边栏历史Tab里面清空掉看看。历史记录的保存时间可以设置短一点，这样会自动及时地清理。

**Comment by tabs** [comment]
历史记录数据

> 这个不影响性能，目前已知卡到影响体验的有几种情况。
> 
> 1. 查看了比较大的数据，几十M上百M这种，会一点卡。
> 2. 请求回路，或者同时有大量请求在不停发，这个肯定会卡。这种能卡到列表里里面有很多完全一样的请求，SSL代理里面设置成绕行模式忽略这个请求的域名可以解决。
> 3. 历史记录数据过大可能会有影响，侧边栏历史Tab里面清空掉看看。历史记录的保存时间可以设置短一点，这样会自动及时地清理。

谢谢，我清理了历史记录现在好了。
我是老用户了，开了专业版。平常用的多，平常忘记清理历史数据了
谢谢您做出来这个很棒的抓包分析工具 ，简直是国产骄傲

**Comment by tabs** [comment]
历史记录数据

> 这个不影响性能，目前已知卡到影响体验的有几种情况。
> 
> 1. 查看了比较大的数据，几十M上百M这种，会一点卡。
> 2. 请求回路，或者同时有大量请求在不停发，这个肯定会卡。这种能卡到列表里里面有很多完全一样的请求，SSL代理里面设置成绕行模式忽略这个请求的域名可以解决。
> 3. 历史记录数据过大可能会有影响，侧边栏历史Tab里面清空掉看看。历史记录的保存时间可以设置短一点，这样会自动及时地清理。

谢谢，我清理了历史记录现在好了。
我是老用户了，开了专业版。平常用的多，平常忘记清理历史数据了
谢谢您做出来这个很棒的抓包分析工具 ，简直是国产骄傲

**Comment by MegatronKing** [comment]
关于历史记录时间，你可以检查下。

<img width="1080" alt="Screenshot 2024-10-16 at 15 06 12" src="https://github.com/user-attachments/assets/53b334fb-e842-4d95-9c9e-ce0a3405cb9b">

**Comment by tabs** [comment]
> 关于历史记录时间，你可以检查下。
> 
> <img alt="Screenshot 2024-10-16 at 15 06 12" width="1080" src="https://private-user-images.githubusercontent.com/15059084/376930389-53b334fb-e842-4d95-9c9e-ce0a3405cb9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjI3ODUsIm5iZiI6MTcyOTA2MjQ4NSwicGF0aCI6Ii8xNTA1OTA4NC8zNzY5MzAzODktNTNiMzM0ZmItZTg0Mi00ZDk1LTljOWUtY2UwYTM0MDVjYjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDA3MDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YTE1M2RiZWY2MWViM2U4ODM3MzJlMDE1N2E3OWQzZDIxMGY0NDJlY2Q5NGRhZmEwZGM0YzA4NjVjODgxMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gi_Gnu6LWEmfMifiryt6KquAcOgm5u9eTQbLkyQAVhQ">

已经修改为3天，之前默认是永久。
