### ISSUE TITLE
[bug] Failed to detect Python env: 1 => 'python3.exe' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by czpandy** [reqable/reqable-app#985]
当前版本 2.26.1(116)(x86_64)
![image](https://github.com/user-attachments/assets/8584d56f-54e6-4a69-92ce-3f20181124ee)
Python版本号: Python 3.13.0
识别到了python版本，但是执行报错
调试日志
windows  Windows 10 Home China 10.0 (Build 22631) 2.26.1(116) x86_64 cpu(20)
10-16 13:34:47.6344 [I][Dart]: App logger is ready now.
10-16 13:34:47.6344 [V][Dart]: Pre-initing app...
10-16 13:34:47.6344 [V][Dart]: App pre-init done.
10-16 13:34:47.6364 [V][Dart]: Post-initing app...
10-16 13:34:47.6977 [V][Dart]: Initing netbare engine...
10-16 13:34:47.7016 [V][Dart]: Loading CA certificate...
10-16 13:34:47.7016 [V][Dart]: CA certificate is found from cache.
10-16 13:34:47.7155 [V][Dart]: Starting netbare engine on port 9000
10-16 13:34:47.7165 [I][Dart]: Netbare engine is ready!
10-16 13:34:47.7174 [V][Dart]: Checking netbare engine state...
10-16 13:34:47.7267 [V][Dart]: App post-init done.
10-16 13:34:47.7267 [V][Dart]: Event: app_start
10-16 13:34:47.7184 [I][Netbare]: [0] TCP proxy session created!
10-16 13:34:47.7187 [I][Netbare]: [0] TCP proxy session started!
10-16 13:34:47.7413 [V][Dart]: Detecting python env version: python3.exe
10-16 13:34:47.7581 [V][Dart]: Event: capture_engine_start
10-16 13:34:47.7299 [V][Netbare]: [0] Internal forwarder: 127.0.0.1 => 127.0.0.1:12412
10-16 13:34:47.7305 [V][Netbare]: [0] [TCP] Connecting to 127.0.0.1:12412
10-16 13:34:47.7306 [V][Netbare]: [0] [TCP] Connected 127.0.0.1:12412
10-16 13:34:47.7688 [I][Dart]: [Collaborative] Server is running on port 12312
10-16 13:34:47.7757 [V][Dart]: Receive a internal request: /
10-16 13:34:47.7776 [V][Dart]: Local IP detected: 192.168.0.112
10-16 13:34:47.7776 [I][Dart]: Use local IP: 192.168.0.112
10-16 13:34:47.7873 [I][Dart]: Netbare engine state is ok!
10-16 13:34:47.7880 [E][Netbare]: [0] "Read from server": End of file
10-16 13:34:47.7881 [I][Netbare]: [0] TCP proxy session closed!
10-16 13:34:47.9136 [E][Dart]: Failed to detect Python env: 1 => 'python3.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by czpandy** [comment]
换成Python 3.12.3也是一样的

附上下面日志

10-16 13:34:47.9136 [E][Dart]: Failed to detect Python env: 1 => 'python3.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

10-16 13:34:47.9136 [V][Dart]: Detecting python env version: python.exe
10-16 13:34:47.9492 [I][Dart]: Check update ok, has update: false
10-16 13:34:48.0057 [I][Dart]: Capture SSL enabled: true
10-16 13:34:48.3570 [I][Dart]: Python env detect output: Python 3.12.3

10-16 13:34:50.4345 [I][Dart]: Capture redundancy file clean done!
10-16 13:35:01.1609 [V][Dart]: Showing window capture_script_list
10-16 13:35:01.1609 [V][Dart]: Popuping window capture_script_list

**Comment by MegatronKing** [comment]
@czpandy 您好，这个日志报错不影响，会同时检测`python3.exe`和`python.exe`，有一个成功即可。

**Comment by czpandy** [comment]
> @czpandy 您好，这个日志报错不影响，会同时检测`python3.exe`和`python.exe`，有一个成功即可。

问题是调试脚本，没有任何日志输出，脚本已经启动了
![image](https://github.com/user-attachments/assets/c2e8d874-e4db-4bd6-8f9f-33370b00a478)
![image](https://github.com/user-attachments/assets/c2417b50-48ec-42a7-8d4f-e7fea840ceb9)
`# API Docs: https://reqable.com/docs/capture/addons

from reqable import *

def onRequest(context, request):
  # Print url to console
 print('request url ' + contxt.url)

  # Update or add a query parameter
  # request.queries['foo'] = 'bar'

  # Update or add a http header
  # request.headers['foo'] = 'bar'

  # Replace http body with a text
  # request.body = 'Hello World'

  # Map with a local file
  # request.body.file('~/Desktop/body.json')

  # Convert to dict if the body is a JSON
  # request.body.jsonify()
  # Update the JSON content
  # request.body['foo'] = 'bar'

  # Done
  return request

def onResponse(context, response):
  # Update status code
  # response.code = 404

  # APIs are same as `onRequest`

  # Done
  return response

`

**Comment by MegatronKing** [comment]
url规则没配对上，触发不了脚本
