### ISSUE TITLE
[bug] 通过Burp抓包，拷贝的curl，不能导入到reqable,如图所示

### ISSUE THREAD

**Issue by 0x22E09-8** [reqable/reqable-app#988]
**Describe the bug**
 通过Burp抓包，拷贝的curl，不能导入到reqable,如图所示

**Screenshots**
![image](https://github.com/user-attachments/assets/af689d33-bccd-412f-b82b-835ab65fed85)
![image](https://github.com/user-attachments/assets/7c8d5fe3-8f67-4fe2-b615-c7f4cfff0169)

**Information**
 - Platform: windows
 - App Version:2.26.1
 -

**Comment by MegatronKing** [comment]
同 #978 ，下个版本支持。
