### ISSUE TITLE
[bug] 脚本控制台打印中文乱码

### ISSUE THREAD

**Issue by cry980285208** [reqable/reqable-app#99]
**Describe the bug**
脚本控制台打印中文乱码
![Dingtalk_20230707091602](https://github.com/reqable/reqable-app/assets/46832863/b5ce4b48-0550-412c-8978-4e92ada0e130)

**Comment by MegatronKing** [comment]
@cry980285208  我没有能复现这个问题。Postman Headers里面ContentType有设置charset吗？

**Comment by MegatronKing** [comment]
![image](https://github.com/reqable/reqable-app/assets/15059084/4aec3340-f103-4d4a-bd85-3816fe7abd93)

**Comment by cry980285208** [comment]
> @cry980285208 我没有能复现这个问题。Postman Headers里面ContentType有设置charset吗？

设置了charset也不行，还是乱码，系统是Windows11
![Dingtalk_20230711110418](https://github.com/reqable/reqable-app/assets/46832863/349ca738-3d63-4622-96cb-c8dbbd070399)

**Comment by MegatronKing** [comment]
@cry980285208 在print之前加上这两行代码试试？
```python
import sys
sys.stdout.reconfigure(encoding='utf-8')
```

**Comment by cry980285208** [comment]
> @cry980285208 在print之前加上这两行代码试试？
> 
> ```python
> import sys
> sys.stdout.reconfigure(encoding='utf-8')
> ```

果然可以
![Dingtalk_20230711144501](https://github.com/reqable/reqable-app/assets/46832863/f372b0f6-bfa6-4dc2-97f7-e283c44b0975)

**Comment by MegatronKing** [comment]
@cry980285208 要不你再试试另一种方案，脚本最上面加上这一行注释。
```
# encoding: utf-8
```

**Comment by cry980285208** [comment]
> @cry980285208 要不你再试试另一种方案，脚本最上面加上这一行注释。
> 
> ```
> # encoding: utf-8
> ```

这种方案不行

**Comment by MegatronKing** [comment]
好的，感谢。我考虑下如何处理这个问题。

**Comment by MegatronKing** [comment]
@cry980285208 更新下v1.1.1版本试试，我加了个逻辑，脚本里面不需要做特殊处理。不知道你那边是否能生效，帮忙验证下。

**Comment by cry980285208** [comment]
> @cry980285208 更新下v1.1.1版本试试，我加了个逻辑，脚本里面不需要做特殊处理。不知道你那边是否能生效，帮忙验证下。

可以，感谢
![Dingtalk_20230713172638](https://github.com/reqable/reqable-app/assets/46832863/4c506011-5ca5-4ec5-86fc-d823a9449f7f)
