### ISSUE TITLE
[bug] 重写规则中的文件夹无法使用

### ISSUE THREAD

**Issue by Me-turing** [reqable/reqable-app#990]
**Describe the bug**
在重写规则中创建文件夹 无法将其他规则归档到一起

**To Reproduce**
1. 创建一个重新规则A
2. 创建文件夹B
3. 无法将A添加到B下

**Expected behavior**
应该可以将规则按照文件夹分类？

**Screenshots**
![image](https://github.com/user-attachments/assets/57eab8f6-593d-4904-ab03-b3949445cd4b)

**Information**
 - Windows11

**Comment by MegatronKing** [comment]
@Me-turing 长按然后拖进去
